/* Practice Log book — Chapter 6: Lists.
   Original lesson text following the chapter-by-chapter curriculum of
   "Automate the Boring Stuff with Python" (3rd ed.) by Al Sweigart.
   Read the original chapter free at the src link below.
   Every shown output was captured by executing the code, not written from memory. */
window.BOOK = window.BOOK || { chapters: {} };
window.BOOK.chapters.ch06 = {
n: 6,
title: "Lists",
src: "https://automatetheboringstuff.com/3e/chapter6.html",
blurb: "Ordered values in one place: indexes, slices, in-place methods, tuples, and the reference surprise behind every shared list.",
sections: [
{ t: "The list data type",
  body: [
  ["p","A list holds many values in one place, in a fixed order. You write one as square brackets around comma-separated items — the items can be strings, numbers, other lists, or any mix. The whole list is itself a single value: it can sit in a variable, be printed, or be handed to len(), which reports how many items it holds. An empty pair of brackets is a valid list with nothing in it yet."],
  ["code",">>> pantry = ['rice', 'lentils', 'salt']\n>>> pantry\n['rice', 'lentils', 'salt']\n>>> len(pantry)\n3\n>>> len([])\n0"],
  ["p","Each item sits at a numbered position called an index, and the numbering starts at zero: the first item is at index 0, the second at index 1. Square brackets after the list pick one item out, and the expression evaluates to that item, ready to use anywhere a value can go."],
  ["code",">>> pantry = ['rice', 'lentils', 'salt', 'cumin']\n>>> pantry[0]\n'rice'\n>>> pantry[3]\n'cumin'\n>>> 'I bought ' + pantry[1]\n'I bought lentils'"],
  ["p","A list inside a list is one item with its own indexes inside. Two sets of brackets dig two levels down: the first picks the inner list, the second picks from it."],
  ["code",">>> stacked = [['jar', 'tin'], [10, 20, 30]]\n>>> stacked[0]\n['jar', 'tin']\n>>> stacked[1][2]\n30"],
  ["p","Negative indexes count from the other end: -1 is always the last item, -2 the one before it. They save you from writing pantry[len(pantry) - 1] every time you want the tail of a list."],
  ["code",">>> pantry[-1]\n'cumin'\n>>> pantry[-2]\n'salt'"],
  ["code",">>> pantry = ['rice', 'lentils', 'salt', 'cumin']\n>>> pantry[4]\nIndexError: list index out of range"],
  ["note","The length of a list is never a valid index. Four items means indexes 0 through 3, so pantry[4] is one past the end — the off-by-one mistake behind most IndexErrors. Indexing an empty list at all raises the same error."]
]},
{ t: "Slices, changes, and del",
  body: [
  ["p","A slice pulls several items out at once and evaluates to a new list. It takes two indexes with a colon between them: the slice starts at the first index and stops just before the second, so pantry[1:3] holds two items, not three."],
  ["code",">>> pantry = ['rice', 'lentils', 'salt', 'cumin']\n>>> pantry[1:3]\n['lentils', 'salt']\n>>> pantry[0:2]\n['rice', 'lentils']"],
  ["p","Either side of the colon can be left out. A missing start means from the beginning, a missing end means to the end, and leaving out both copies the whole list — a detail that turns out to matter when copies come up at the end of this chapter."],
  ["code",">>> pantry[:2]\n['rice', 'lentils']\n>>> pantry[2:]\n['salt', 'cumin']\n>>> pantry[:]\n['rice', 'lentils', 'salt', 'cumin']"],
  ["p","Unlike the strings of earlier chapters, a list can be changed after it is made. Assigning to an index replaces the item there — the list keeps its length, but one slot holds a new value."],
  ["code",">>> pantry = ['rice', 'lentils', 'salt', 'cumin']\n>>> pantry[1] = 'beans'\n>>> pantry\n['rice', 'beans', 'salt', 'cumin']"],
  ["p","The + operator joins two lists into a new, longer one, and * repeats a list a whole number of times. Both build new lists rather than changing the old ones."],
  ["code",">>> ['a', 'b'] + ['c']\n['a', 'b', 'c']\n>>> [0, 1] * 3\n[0, 1, 0, 1, 0, 1]"],
  ["p","A del statement removes one item by index. Everything after the removed item slides down one position to close the gap."],
  ["code",">>> pantry = ['rice', 'beans', 'salt', 'cumin']\n>>> del pantry[1]\n>>> pantry\n['rice', 'salt', 'cumin']"],
  ["note","After del pantry[1], the item that used to be at index 2 is at index 1. Deleting index 1 and then index 2 therefore skips a survivor and takes an item you meant to keep — when several items must go, delete from the highest index down, or the shifting positions will pull the wrong ones."]
]},
{ t: "Looping, membership, and unpacking",
  body: [
  ["p","A for loop visits a list item by item: the loop variable takes the first value, the block runs, then the second value, and so on until the list is exhausted. No indexes are involved unless you ask for them."],
  ["code","chores = ['dishes', 'laundry', 'compost']\nfor chore in chores:\n    print('Tonight: ' + chore)"],
  ["code","Tonight: dishes\nTonight: laundry\nTonight: compost"],
  ["p","When the position matters too, one way is to loop over range(len(...)) and index into the list by hand. The index variable then works double duty: it labels the item and fetches it."],
  ["code","supplies = ['tape', 'glue', 'string']\nfor i in range(len(supplies)):\n    print('Slot ' + str(i) + ': ' + supplies[i])"],
  ["code","Slot 0: tape\nSlot 1: glue\nSlot 2: string"],
  ["p","The in and not in operators ask whether a value appears anywhere in a list, and evaluate to a Boolean. They read like English, and they are the standard guard before operations that crash on missing values — the methods section returns to this."],
  ["code",">>> 'glue' in ['tape', 'glue', 'string']\nTrue\n>>> 'nails' in ['tape', 'glue', 'string']\nFalse\n>>> 'nails' not in ['tape', 'glue', 'string']\nTrue"],
  ["code",">>> row = []\n>>> len(row) > 0 and row[0] == 'go'\nFalse"],
  ["note","and and or settle as soon as the answer is known: a False left side of and means the right side never runs at all. That is why the check above is safe — with an empty row, row[0] alone would raise an IndexError, but the len test already answered False and Python never looked. Put the cheap, protective test first."],
  ["p","Multiple assignment unpacks a list into named variables in one line, first item to first name, second to second. The number of names must match the number of items exactly, or the line raises a ValueError."],
  ["code",">>> box = [120, 80, 45]\n>>> width, height, depth = box\n>>> height\n80"],
  ["p","The same trick swaps two variables without a third one to hold the spare: the right side is bundled up before the left side is assigned, so neither value is lost mid-swap."],
  ["code",">>> a, b = 5, 9\n>>> a, b = b, a\n>>> a\n9"],
  ["p","When a loop needs the index and the item together, enumerate() supplies both as a pair, and the for line unpacks each pair into two variables as it goes. The count starts at zero, like every index in this chapter."],
  ["code","steps = ['knead', 'proof', 'bake']\nfor number, step in enumerate(steps):\n    print(str(number) + ' ' + step)"],
  ["code","0 knead\n1 proof\n2 bake"]
]},
{ t: "Augmented assignment and list methods",
  body: [
  ["p","total = total + 6 has a shorthand: total += 6. Every arithmetic operator has an augmented form — -=, *=, /=, %= — and += also works on lists, tacking one list onto the end of another. The pattern is always the same: take what the variable holds, apply the operator, store the result back."],
  ["code",">>> total = 0\n>>> total += 6\n>>> total += 4\n>>> total\n10\n>>> tags = ['new']\n>>> tags += ['sale']\n>>> tags\n['new', 'sale']"],
  ["p","A method is a function that belongs to a value, called with a dot after it. Lists carry a toolbox of them, and the first job is finding things: index() returns the position of the first matching item, ignoring any later duplicates. Asking for a value that is not in the list raises a ValueError, so the in guard from the last section earns its keep here."],
  ["code",">>> spices = ['clove', 'anise', 'mace', 'anise']\n>>> spices.index('anise')\n1"],
  ["p","append() adds one item at the end; insert() slips one in at any index and shifts the rest rightward. Both change the list in place and return nothing — notice that the shell prints no result line for either call."],
  ["code",">>> spices = ['clove', 'anise', 'mace', 'anise']\n>>> spices.append('sumac')\n>>> spices\n['clove', 'anise', 'mace', 'anise', 'sumac']\n>>> spices.insert(1, 'caraway')\n>>> spices\n['clove', 'caraway', 'anise', 'mace', 'anise', 'sumac']"],
  ["p","remove() deletes the first matching value. pop() deletes by position and hands the removed item back, which is what makes it useful — with no argument it takes the last item, with an index it takes that one. Like index(), remove() raises a ValueError when the value is absent."],
  ["code",">>> spices = ['clove', 'caraway', 'anise', 'mace', 'anise', 'sumac']\n>>> spices.remove('anise')\n>>> spices\n['clove', 'caraway', 'mace', 'anise', 'sumac']\n>>> spices.pop()\n'sumac'\n>>> spices.pop(0)\n'clove'\n>>> spices\n['caraway', 'mace', 'anise']"],
  ["code",">>> spices = ['caraway', 'mace', 'anise']\n>>> spices.remove('dill')\nValueError: list.remove(x): x not in list"],
  ["p","sort() orders the list in place — strings alphabetically, numbers ascending — and sort(reverse=True) flips the direction. reverse() mirrors the current order without sorting anything."],
  ["code",">>> spices = ['caraway', 'mace', 'anise']\n>>> spices.sort()\n>>> spices\n['anise', 'caraway', 'mace']\n>>> costs = [40, 5, 19]\n>>> costs.sort()\n>>> costs\n[5, 19, 40]\n>>> costs.sort(reverse=True)\n>>> costs\n[40, 19, 5]"],
  ["code",">>> spices = ['anise', 'caraway', 'mace']\n>>> spices.reverse()\n>>> spices\n['mace', 'caraway', 'anise']"],
  ["p","sort() returns None, and that produces a classic mistake: keeping the result. The program below sorts the list and then immediately loses it, because the variable now holds None instead of a list."],
  ["code","words = ['pear', 'fig']\nwords = words.sort()\nprint(words)"],
  ["code","None"],
  ["p","Two more edges. sort() refuses a list that mixes numbers and strings, because no single order covers both. And its alphabetical order is really code-point order — every capital letter sorts before every lowercase letter — so 'B' lands before 'a'. Passing key=str.lower sorts without regard to case."],
  ["code",">>> mixed = [3, 'two', 1]\n>>> mixed.sort()\nTypeError: '<' not supported between instances of 'str' and 'int'"],
  ["code",">>> letters = ['b', 'A', 'a', 'B']\n>>> letters.sort()\n>>> letters\n['A', 'B', 'a', 'b']\n>>> letters.sort(key=str.lower)\n>>> letters\n['A', 'a', 'B', 'b']"],
  ["note","sort() and reverse() change the list and return None. Writing words = words.sort() therefore replaces a freshly sorted list with no list at all — call the method on its own line and keep using the variable you already have."]
]},
{ t: "Random selection and ordering",
  body: [
  ["p","The random module pairs naturally with lists. random.choice() picks one item at random — handing it the whole list is cleaner than generating a random index and looking it up yourself."],
  ["code","import random\nflavors = ['mint', 'lemon', 'peach', 'cocoa']\nprint(random.choice(flavors))"],
  ["p","No output is shown above because there is no single right answer: each run prints one of the four flavors, and repeated runs disagree. random.shuffle() is the other list tool — it reorders the list in place, like sort() with the order thrown away."],
  ["code","import random\ncards = ['2H', '9C', 'KD', 'AS', '5S']\nrandom.shuffle(cards)\nprint(cards)"],
  ["p","After the shuffle the list holds the same five cards in some new order, different from run to run. Programs that deal hands, pick quiz questions, or rotate chores are this one line plus everything else the chapter taught."],
  ["note","shuffle() follows the sort() pattern: in place, returns None. deck = random.shuffle(deck) quietly replaces a shuffled deck with None — the same mistake, one module over."]
]},
{ t: "Tuples and immutability",
  body: [
  ["p","Every string operation so far read from strings without changing them, and that is no accident: strings are immutable. A list can be changed in place; a string cannot — assigning into one is an error."],
  ["code",">>> word = 'copper'\n>>> word[0] = 'h'\nTypeError: 'str' object does not support item assignment"],
  ["p","To change a string you build a new one from pieces of the old, with slices and +, and usually store it back under the same name. The original string was never edited; the variable just moved to a new value."],
  ["code",">>> word = 'copper'\n>>> 'h' + word[1:]\n'hopper'"],
  ["p","The tuple is the immutable cousin of the list: parentheses instead of square brackets, and no changes after creation. Reading works exactly as with lists — indexes, len(), slices — but assigning into one raises the same complaint the string made."],
  ["code",">>> size = (1920, 1080)\n>>> size[0]\n1920\n>>> len(size)\n2\n>>> size[0] = 4096\nTypeError: 'tuple' object does not support item assignment"],
  ["p","One parenthesized value is just that value — parentheses alone do not make a tuple. A trailing comma does, and it is the entire difference between the two lines below."],
  ["code",">>> type(('solo',))\n<class 'tuple'>\n>>> type(('solo'))\n<class 'str'>"],
  ["p","list() and tuple() convert between the two families, and list() also splits a string into a list of its characters. Converting is how you edit tuple data: turn it into a list, change that, and turn it back."],
  ["code",">>> list(('a', 'b'))\n['a', 'b']\n>>> tuple([1, 2, 3])\n(1, 2, 3)\n>>> list('mud')\n['m', 'u', 'd']"],
  ["code",">>> size = (1920, 1080)\n>>> size.append(720)\nAttributeError: 'tuple' object has no attribute 'append'"],
  ["note","A tuple has none of the changing methods — no append(), no sort() — and reaching for one raises the AttributeError above. Choose a tuple when the data must not change and a list when it must; the error is the type doing its job, not an obstacle."]
]},
{ t: "References and copies",
  body: [
  ["p","A variable never holds a list the way a box holds a thing; it holds a reference that points at the list. Assigning one variable to another copies the reference, not the list — after which two names point at one list."],
  ["code",">>> packed = ['tent', 'stove']\n>>> gear = packed\n>>> gear.append('rope')\n>>> packed\n['tent', 'stove', 'rope']"],
  ["p","gear was never a copy. Appending through either name changes the one list both point at, and reading through packed proves it. With numbers and strings the distinction is invisible, because immutable values cannot change underneath you — lists are where it starts to matter."],
  ["p","Function calls pass references the same way. A function that mutates its parameter is mutating the caller's list — no return statement required, and none used below."],
  ["code","def add_receipt(papers):\n    papers.append('receipt')\n\ntray = ['form', 'letter']\nadd_receipt(tray)\nprint(tray)"],
  ["code","['form', 'letter', 'receipt']"],
  ["p","When you need a genuinely independent copy, the copy module provides it. copy.copy() builds a new list with the same items, and changes to one no longer touch the other."],
  ["code",">>> import copy\n>>> packed = ['tent', 'stove']\n>>> spare = copy.copy(packed)\n>>> spare.append('lamp')\n>>> packed\n['tent', 'stove']\n>>> spare\n['tent', 'stove', 'lamp']"],
  ["p","copy.copy() copies one level deep. A list of lists copies the outer list only — original and copy still share the inner lists, so mutating an inner list shows up in both. copy.deepcopy() copies all the way down."],
  ["code",">>> import copy\n>>> bins = [['bolt'], ['washer']]\n>>> flat = copy.copy(bins)\n>>> flat[0].append('nut')\n>>> bins\n[['bolt', 'nut'], ['washer']]"],
  ["code",">>> import copy\n>>> bins = [['bolt'], ['washer']]\n>>> deep = copy.deepcopy(bins)\n>>> deep[0].append('nut')\n>>> bins\n[['bolt'], ['washer']]\n>>> deep\n[['bolt', 'nut'], ['washer']]"],
  ["note","This is the aliasing surprise: you copied a list with =, changed the copy, and the original changed behind your back — or you passed a list to a function and got it back mutated. When a list changes that your code never touched by name, look for a second reference to it. The full slice [:] from earlier also makes a one-level copy."]
]},
{ t: "A short program: the standby queue",
  body: [
  ["p","This program runs a gate agent's standby list and uses most of the chapter: append() as a traveler joins, in as a guard, remove() as someone cancels, pop() to board the head of the line, and enumerate() to number what remains. Read it and predict all four output lines before looking."],
  ["code","standby = ['Priya', 'Marcus', 'Elena']\nstandby.append('Tomas')\nprint('Waiting: ' + str(len(standby)))\nif 'Elena' in standby:\n    standby.remove('Elena')\nseat = standby.pop(0)\nprint('Now boarding: ' + seat)\nfor place, name in enumerate(standby):\n    print(str(place + 1) + '. ' + name)"],
  ["code","Waiting: 4\nNow boarding: Priya\n1. Marcus\n2. Tomas"],
  ["p","Trace it mutation by mutation. append() makes the list four long, which the first print reports. The in check finds 'Elena' present, so remove() deletes her entry. pop(0) then deletes the head of the line and returns it, and that returned value — not the list — is what prints as boarding."],
  ["p","The loop numbers the two travelers left. enumerate() counts from 0, and the + 1 turns machine numbering into the 1-based list a person expects at a gate — the same off-by-one boundary as indexes, crossed on purpose this time."],
  ["note","The in guard is what keeps remove() safe: without it, a name missing from the list would crash the program with a ValueError. Check membership first, then mutate — the habit applies to remove(), index(), and any code that assumes a value is present."]
]},
{ t: "Summary",
  body: [
  ["p","A list keeps values in order and changes in place: indexes and slices read it, assignment and del edit it, and methods — append(), insert(), remove(), pop(), sort(), reverse() — reshape it while returning None rather than a new list. for walks it, in and not in interrogate it, enumerate() numbers it, and random.choice() and random.shuffle() gamble with it. Tuples are the immutable relatives, and strings turn out to have been immutable sequences all along."],
  ["p","The deepest idea in the chapter is the reference: variables point at lists rather than contain them, so = shares a list where copy.copy() — or a full slice — duplicates it, and copy.deepcopy() duplicates nested lists too. Answer the questions from memory before revealing the answers, then clear the graded exercises below. The next chapter is Chapter 7, Dictionaries and Structuring Data — a container that looks values up by name instead of by position."]
]}
],
questions: [
{ q:"For pantry = ['rice', 'lentils', 'salt'], what do pantry[0] and pantry[-1] evaluate to?",
  a:"'rice' and 'salt'. Indexing starts at 0, and negative indexes count from the end, so -1 is always the last item." },
{ q:"What does pantry[0:2] evaluate to for that same list, and is the item at index 2 included?",
  a:"['rice', 'lentils'] — a new two-item list. The end index is excluded: a slice runs from the start index up to but not including the end index." },
{ q:"What does len(['a', ['b', 'c']]) evaluate to, and why?",
  a:"2. The inner list counts as a single item no matter how many values it holds; len() does not look inside it." },
{ q:"A list holds three items. What happens when you ask for index 3?",
  a:"IndexError: list index out of range. Three items occupy indexes 0 through 2, so 3 is one past the end — the length of a list is never a valid index." },
{ q:"Both append() and insert() add one item to a list. What is the difference?",
  a:"append(value) always adds at the end: for [1, 2], append(3) gives [1, 2, 3]. insert(index, value) adds at the index you choose and shifts the rest rightward: insert(0, 0) on that result gives [0, 1, 2, 3]." },
{ q:"What does words.sort() return, and what is wrong with words = words.sort()?",
  a:"None — sort() orders the list in place. The assignment sorts the list and then immediately replaces it with None, so the sorted data is lost." },
{ q:"For pantry = ['rice', 'lentils', 'salt'], what do 'salt' in pantry and 'tea' not in pantry evaluate to?",
  a:"Both True. in answers whether a value appears anywhere in the list; not in is its negation." },
{ q:"dims = (800, 600). What happens on dims[0] = 1024?",
  a:"TypeError: 'tuple' object does not support item assignment. Tuples are immutable — to change the data, convert with list(), edit the list, and convert back with tuple()." },
{ q:"After a = [1, 2], then b = a, then b.append(3), what does a evaluate to, and why?",
  a:"[1, 2, 3]. b = a copied the reference, not the list, so both names point at one list and a change through either name is visible through both." },
{ q:"When is copy.copy() not enough, and what do you reach for instead?",
  a:"When the list contains other lists. copy.copy() duplicates only the outer list — the inner lists stay shared between original and copy. copy.deepcopy() copies all the way down." }
],
exercises: [
{ c:"lists", t:"Ends of the shelf", book:"ch06",
  b:"Given tools = ['hammer', 'wrench', 'saw', 'drill'], print two lines: 'First: ' plus the first item, then 'Last: ' plus the last item. Use an index for the first and a negative index for the last.",
  o:"First: hammer\nLast: drill",
  h:["Index 0 is always the first item; negative indexes count backward from the end.",
     "tools[-1] is the last item however long the list is. Build each line with + between the label and the item.",
     "The first line is print('First: ' + tools[0]); the last line mirrors it with the negative index."]},
{ c:"lists", t:"Stockroom moves", book:"ch06",
  b:"Start with crates = ['apples', 'pears', 'plums']. Append 'figs', remove 'pears', insert 'kiwis' at index 0, then print the list itself.",
  o:"['kiwis', 'apples', 'plums', 'figs']",
  h:["Each change is one method call on crates; make them in the order the task states.",
     "append adds at the end, remove deletes by value, and insert takes an index first and a value second. print(crates) prints the whole list, brackets and all.",
     "crates.append('figs') is the first change; the other two follow the same dot shape, then print(crates)."]},
{ c:"loops", t:"Receipt total", book:"ch06",
  b:"Given prices = [4, 7, 2, 9], total the list with a for loop and +=, then print one line: 'Total: ' followed by the sum.",
  o:"Total: 22",
  h:["You need a running total that exists before the loop starts, beginning at 0.",
     "Each pass, += folds the current price into the total. print needs str() around a number before + can join it to a string.",
     "total = 0, then a for loop over prices adding each price into total, then one print built from 'Total: ' and str(total)."]},
{ c:"lists", t:"Roll call, alphabetized", book:"ch06",
  b:"Given names = ['Rosa', 'Amir', 'Lena'], print the line 'Roll call:' and then each name on its own line in alphabetical order.",
  o:"Roll call:\nAmir\nLena\nRosa",
  h:["Two jobs: put the list in order, then walk it with a loop.",
     "sort() rearranges the list in place and returns None — call it on its own line, never inside print.",
     "names.sort() first, print the header, then a two-line for loop prints one name per pass."]}
]
};
