/* Practice Log book — R Chapter 1: Data visualization.
   Original lesson text following the chapter-by-chapter curriculum of
   "R for Data Science" (2nd ed.) by Hadley Wickham, Mine Cetinkaya-Rundel,
   and Garrett Grolemund. Read the original chapter free at the src link below.
   Every shown output was captured by executing the code in WebR, not written from memory. */
window.BOOK_R = window.BOOK_R || { chapters: {} };
window.BOOK_R.chapters.r01 = {
n: 1,
title: "Data visualization",
src: "https://r4ds.hadley.nz/data-visualize.html",
blurb: "Building a chart out of data, aesthetic mappings, and geom layers with ggplot2 — and reading a plot back as text.",
pkgs: ["ggplot2", "tibble"],
sections: [
{ t: "What a plot is made of",
  body: [
  ["p","A plot in ggplot2 is assembled out of named parts rather than drawn one instruction at a time. Three parts do most of the work: the data, a set of aesthetic mappings that say which column controls which visual property, and one or more geoms that decide what marks land on the canvas. Keep the data and the mapping, swap the geom, and the same two columns become a different chart."],
  ["p","The parts are joined with the + operator. Each addition returns a new plot, so a plot can be stored in a variable, added to later, and examined like any other value in R. That last point matters more here than it normally would."],
  ["note","This app decides whether an answer is right by comparing text, and a chart is an image. So every output in this chapter is text pulled out of the plot object — how many layers it has, which geom a layer uses, how many rows of data it carries — and never a description of a picture. A plot object printed on its own produces no text at all in this app's R console, which means an answer ending in a bare plot object submits nothing. To see the pictures, run the same code in R on a desktop."],
  ["p","Neither package used here is part of base R, so both have to be attached before anything else. ggplot2 supplies the plotting functions; tibble supplies the kind of data frame the rest of the chapter builds."],
  ["code","library(ggplot2)\nlibrary(tibble)"]
]},
{ t: "The data to plot",
  body: [
  ["p","ggplot2 draws from a data frame, and every mapping names a column of that frame. A tibble is the tidyverse's data frame: the same rectangle of columns, with printing that tells you more. The table below holds eight secondhand bicycles, each with a model name, a wheel diameter in centimetres, a weight in kilograms, and a frame material."],
  ["code","bikes <- tibble(\n  model = c(\"Kestrel\", \"Otter\", \"Puffin\", \"Marlin\", \"Heron\", \"Wren\", \"Grebe\", \"Tern\"),\n  wheel_cm = c(66, 51, 61, 71, 66, 51, 71, 61),\n  weight_kg = c(11.2, 9.4, 10.1, 13.6, 12.0, 8.8, 14.2, 10.9),\n  frame = c(\"steel\", \"alloy\", \"alloy\", \"steel\", \"steel\", \"alloy\", \"steel\", \"alloy\")\n)\n\nbikes"],
  ["code","# A tibble: 8 × 4\n  model   wheel_cm weight_kg frame\n  <chr>      <dbl>     <dbl> <chr>\n1 Kestrel       66      11.2 steel\n2 Otter         51       9.4 alloy\n3 Puffin        61      10.1 alloy\n4 Marlin        71      13.6 steel\n5 Heron         66      12   steel\n6 Wren          51       8.8 alloy\n7 Grebe         71      14.2 steel\n8 Tern          61      10.9 alloy"],
  ["p","The header reports the shape — eight rows by four columns, written with a multiplication sign — and under the column names sits a row of abbreviated types. <chr> is character, <dbl> is double. Reading that row before you plot tells you which columns are numbers and which are labels, which is most of what decides the chart you can make."],
  ["code","nrow(bikes)\nncol(bikes)\nnames(bikes)"],
  ["code","[1] 8\n[1] 4\n[1] \"model\"     \"wheel_cm\"  \"weight_kg\" \"frame\""],
  ["p","A single column comes out with $, which is how you check a type or compute a summary outside a plot. Note that the tibble's <dbl> abbreviation and R's own class name for the same column are two different words for one thing."],
  ["code","class(bikes$wheel_cm)\nclass(bikes$frame)"],
  ["code","[1] \"numeric\"\n[1] \"character\""],
  ["p","Every column has to be the same length, because a data frame is a rectangle. Two columns of different lengths do not produce a ragged table; they produce no table at all."],
  ["code","tibble(a = c(1, 2, 3), b = c(10, 20))"],
  ["code","Error: Tibble columns must have compatible sizes."],
  ["note","The mistake that raises that error is almost never a miscount at the start. It is adding one more observation to a column you are looking at and forgetting the other three, which is exactly what happens when a tibble is written across several lines and you edit only the line in front of you. Count the values in every column after every edit."]
]},
{ t: "Your first plot",
  body: [
  ["p","ggplot() takes the data and the mappings. On its own that is enough to set up a coordinate system, and not enough to draw anything: with no geom there are no marks. The layer count is the proof, and the data is already on board."],
  ["code","blank <- ggplot(bikes, aes(x = wheel_cm, y = weight_kg))\n\nlength(blank$layers)\nnrow(blank$data)"],
  ["code","[1] 0\n[1] 8"],
  ["p","geom_point() supplies the missing layer. It draws one point per row of the data, positioned by whatever x and y are mapped to. Add it with a + at the end of the ggplot() line."],
  ["code","p <- ggplot(data = bikes, mapping = aes(x = wheel_cm, y = weight_kg)) +\n  geom_point()"],
  ["p","That assignment prints nothing, because it is an assignment. To find out what was built, ask the object three questions."],
  ["code","length(p$layers)\nclass(p$layers[[1]]$geom)[1]\nnrow(p$data)"],
  ["code","[1] 1\n[1] \"GeomPoint\"\n[1] 8"],
  ["p","Read the answers back: one layer, that layer draws points, and the plot carries all eight rows unchanged. class() on a geom returns several names because of how ggplot2 builds its objects, so [1] takes the one you want. Those three lines are how every plot in this chapter gets checked."],
  ["p","data and mapping are the first two parameters of ggplot(), and x and y are the first two of aes(), so working code usually drops all four names. The plot below is the same plot."],
  ["code","p2 <- ggplot(bikes, aes(wheel_cm, weight_kg)) + geom_point()\n\nlength(p2$layers)\nclass(p2$layers[[1]]$geom)[1]\nnrow(p2$data)"],
  ["code","[1] 1\n[1] \"GeomPoint\"\n[1] 8"],
  ["note","The + ends a line and never begins one. R finishes an expression at a line break, so moving the + down to the front of the next line does not continue the plot — it starts a fresh statement that adds a layer to nothing. The error you get names the operator rather than the plot, so it reads like a puzzle until you have seen it once. Section 8 has it."]
]},
{ t: "Aesthetics: mapping versus setting",
  body: [
  ["p","x and y are aesthetics, and so are colour, shape, size, and alpha. Naming one inside aes() maps it: the property varies row by row with the column you gave it, and ggplot2 picks a scale and builds a legend. Mapping the frame column to colour therefore adds a third entry to the plot's mapping."],
  ["code","coloured <- ggplot(bikes, aes(x = wheel_cm, y = weight_kg, colour = frame)) +\n  geom_point()\n\nnames(coloured$mapping)"],
  ["code","[1] \"x\"      \"y\"      \"colour\""],
  ["p","Layers stack in the order you add them. geom_smooth() fits a line through the same mapping and draws it as a second layer, so the points stay and the line goes over them. Asking for method \"lm\" fits a straight line; se = FALSE drops the band around it."],
  ["code","two <- coloured + geom_smooth(method = \"lm\", se = FALSE)\n\nlength(two$layers)\nclass(two$layers[[1]]$geom)[1]\nclass(two$layers[[2]]$geom)[1]"],
  ["code","[1] 2\n[1] \"GeomPoint\"\n[1] \"GeomSmooth\""],
  ["p","Setting is the other half of the pair. A property named outside aes(), as an ordinary argument to the geom, takes one fixed value for every mark and has nothing to do with the data. The mapping list stays at two entries, and the constant is filed on the layer instead."],
  ["code","fixed <- ggplot(bikes, aes(x = wheel_cm, y = weight_kg)) +\n  geom_point(colour = \"steelblue\")\n\nnames(fixed$mapping)\nfixed$layers[[1]]$aes_params$colour"],
  ["code","[1] \"x\" \"y\"\n[1] \"steelblue\""],
  ["p","So colour = frame inside aes() means one colour per frame material, and colour = \"steelblue\" outside it means every point the same. Both are legal, they read almost identically, and they are answers to different questions."],
  ["code","ggplot(bikes) + geom_point(x = wheel_cm, y = weight_kg)"],
  ["code","Error: object 'wheel_cm' not found"],
  ["note","Column names only mean anything inside aes(). Written as bare arguments to a geom, as above, R stops looking in the data frame and starts looking for ordinary variables, finds none, and gives up on the first one. The error names a column you know exists, which is what makes it confusing: it exists in bikes, and nothing told R to look there."]
]},
{ t: "Labels and titles",
  body: [
  ["p","labs() sets the text around the plot: the title, the axis labels, the name over a legend. It is another layer added with +, and what it sets is stored on the plot where you can read it back."],
  ["code","titled <- p + labs(\n  title = \"Weight against wheel size\",\n  x = \"Wheel diameter (cm)\",\n  y = \"Weight (kg)\"\n)\n\ntitled$labels$title\ntitled$labels$x\ntitled$labels$y"],
  ["code","[1] \"Weight against wheel size\"\n[1] \"Wheel diameter (cm)\"\n[1] \"Weight (kg)\""],
  ["p","When you set no labels, ggplot2 falls back to the column names — but it works them out at the moment the plot is drawn, not when it is built. So the labels slot on an unlabelled plot is empty, and get_labs() is the function that reports the labels the plot will actually use."],
  ["code","p$labels$x\nget_labs(p)$x\nget_labs(p)$y"],
  ["code","NULL\n[1] \"wheel_cm\"\n[1] \"weight_kg\""],
  ["note","Checking p$labels$x on a plot you never labelled returns NULL, and NULL reads like a broken mapping. The mapping is fine. The default label simply has not been resolved yet, because nothing has asked to draw the plot. Reach for get_labs() when you want the label that will appear, and for p$labels only when you want to know what you set yourself."]
]},
{ t: "One variable at a time",
  body: [
  ["p","A categorical column gets a bar chart. You map the column to x and supply no y at all, because the height of each bar is something ggplot2 works out rather than something you provide."],
  ["code","bars <- ggplot(bikes, aes(x = frame)) + geom_bar()\n\nclass(bars$layers[[1]]$geom)[1]\nclass(bars$layers[[1]]$stat)[1]\nggplot_build(bars)$data[[1]]$count"],
  ["code","[1] \"GeomBar\"\n[1] \"StatCount\"\n[1] 4 4"],
  ["p","A layer carries a stat as well as a geom. StatCount counts the rows in each category, and only then does GeomBar draw a rectangle per count — which is why an unasked-for y appears. ggplot_build() is the function that runs that computation without drawing, and it is how this chapter reads numbers off a chart it cannot show you: four alloy frames and four steel."],
  ["p","A numeric column gets a histogram, which has to chop the range into bins before it can count anything. binwidth sets the size of a bin, and because the binning is the stat's job, that is where the argument is stored."],
  ["code","weights <- ggplot(bikes, aes(x = weight_kg)) + geom_histogram(binwidth = 2)\n\nclass(weights$layers[[1]]$geom)[1]\nweights$layers[[1]]$stat_params$binwidth\nggplot_build(weights)$data[[1]]$count\nggplot_build(weights)$data[[1]]$xmin"],
  ["code","[1] \"GeomBar\"\n[1] 2\n[1] 1 3 2 2\n[1]  7  9 11 13"],
  ["p","Four bins two kilograms wide, starting at 7: one bike from 7 to 9 kg, three from 9 to 11, two from 11 to 13, two from 13 to 15. Note the geom — a histogram is bars drawn over binned numbers, so the geom is GeomBar, the same one the bar chart used. What separates the two charts is the stat."],
  ["p","Not every layer computes something. geom_point() puts the values on the canvas exactly as they came, and its stat says as much."],
  ["code","class(p$layers[[1]]$stat)[1]"],
  ["code","[1] \"StatIdentity\""],
  ["code","loose <- ggplot(bikes, aes(x = weight_kg)) + geom_histogram()\n\nnrow(ggplot_build(loose)$data[[1]])"],
  ["code","`stat_bin()` using `bins = 30`. Pick better value `binwidth`.\n[1] 30"],
  ["note","Leave binwidth out and ggplot2 chops the range into thirty bins and tells you it guessed. Thirty bins across eight values is not a distribution, it is twenty-six empty bars and four short ones. The message is easy to scroll past because the plot still appears; treat it as a question you are expected to answer. The other trap is checking for a geom called GeomHistogram, which does not exist — the class you will get back is GeomBar."]
]},
{ t: "Two variables, and small multiples",
  body: [
  ["p","A numeric column against a categorical one is a boxplot: one box per category, summarising the spread of the numbers inside it. Here x is the label and y is the number, the opposite of the bar chart's single mapping."],
  ["code","box <- ggplot(bikes, aes(x = frame, y = weight_kg)) + geom_boxplot()\n\nclass(box$layers[[1]]$geom)[1]\nnames(box$mapping)"],
  ["code","[1] \"GeomBoxplot\"\n[1] \"x\" \"y\""],
  ["p","Two categorical columns give a bar chart split by a second aesthetic. Mapping a column to fill divides each bar into segments, and a layer's position decides what happens when marks would occupy the same space."],
  ["code","stacked <- ggplot(bikes, aes(x = frame, fill = model)) + geom_bar()\n\nnames(stacked$mapping)\nclass(stacked$layers[[1]]$position)[1]"],
  ["code","[1] \"x\"    \"fill\"\n[1] \"PositionStack\""],
  ["p","PositionStack is the default: segments pile up into one bar. Two numeric columns are the scatterplot from section 3. When a third column matters you can map it to colour, as section 4 did, or split the plot into one panel per value with facet_wrap(). Every plot has a facet; a plain one has a facet that means a single panel."],
  ["code","faceted <- p + facet_wrap(~frame)\n\nclass(p$facet)[1]\nclass(faceted$facet)[1]"],
  ["code","[1] \"FacetNull\"\n[1] \"FacetWrap\""],
  ["p","Because this app cannot show you the chart, claims about what the chart reveals have to be settled with arithmetic instead. Correlation and a pair of group means answer the two obvious questions about this table."],
  ["code","round(cor(bikes$wheel_cm, bikes$weight_kg), 3)\nmean(bikes$weight_kg[bikes$frame == \"steel\"])\nmean(bikes$weight_kg[bikes$frame == \"alloy\"])"],
  ["code","[1] 0.937\n[1] 12.75\n[1] 9.8"],
  ["p","Wheel size and weight move together closely across these eight bikes, and the steel frames average 12.75 kg against 9.8 for alloy. Those are facts about the numbers, computed here rather than eyeballed. Whether a scatterplot makes them obvious to a reader is a separate question, and one you can only answer by looking at the drawing on a machine that draws."],
  ["note","facet_wrap() takes a formula, so the column goes after a tilde: facet_wrap(~frame). Write facet_wrap(frame) and the plot object is built with a FacetWrap in it and no complaint at all — the failure waits until something tries to draw it, and the message talks about vectors and functions without ever mentioning facets. The tilde is not decoration."]
]},
{ t: "Saving, and the errors you will hit",
  body: [
  ["p","ggsave() writes a plot to a file. Give it a filename, the plot, and a size; the extension picks the format, and width and height are in inches unless you say otherwise. Called with no plot argument it saves the last plot drawn, which is convenient and worth being explicit about anyway."],
  ["code","ggsave(\"bikes.png\", plot = p, width = 6, height = 4)\n\nfile.exists(\"bikes.png\")"],
  ["code","[1] TRUE"],
  ["note","In this app the file lands in the browser's in-memory filesystem, not in a folder on your device. file.exists() finds it and nothing else will, and it is gone when the page reloads. On a desktop the same call writes into your working directory, which is the point of the function."],
  ["p","Three errors account for most first attempts. The first is forgetting to attach the package. Every plotting function in this chapter comes from ggplot2, and none of them exist until library(ggplot2) has run — including aes(), although you never get far enough to be told that."],
  ["code","ggplot(bikes, aes(x = wheel_cm, y = weight_kg)) + geom_point()"],
  ["code","Error: could not find function \"ggplot\""],
  ["p","The second is the + moved to the front of a line, from section 3. R has already finished the first line by the time it reaches the second, so the second line asks for an addition with only a right-hand side."],
  ["code","q <- ggplot(bikes, aes(x = wheel_cm, y = weight_kg))\n+ geom_point()"],
  ["code","Error: Cannot use `+` with a single argument."],
  ["p","The third is a misspelled column. Building a plot never looks at the data, so the object is assembled with its layer intact and the mistake surfaces only when something asks for the drawing — here, ggplot_build()."],
  ["code","typo <- ggplot(bikes, aes(x = wheelcm, y = weight_kg)) + geom_point()\n\nlength(typo$layers)\nggplot_build(typo)"],
  ["code","[1] 1\nError: Problem while computing aesthetics."],
  ["note","Two of those three are silent until the plot is drawn, which is the habit to take from this section: a plot object that builds without error has not been checked. Nothing has read the data yet. Run ggplot_build() on it, or draw it, before you believe it."]
]},
{ t: "Summary",
  body: [
  ["p","A ggplot is data, a set of aesthetic mappings written inside aes(), and one or more geom layers, joined with a + that ends its line. Mapping a property inside aes() makes it vary with a column; setting the same property outside aes() fixes it for every mark. Layers stack in the order you add them, each layer carries a stat and a position as well as a geom, labs() supplies the text, facet_wrap() splits the plot into panels, and ggsave() writes the result to a file."],
  ["p","The geom you reach for follows from the columns. One categorical column takes geom_bar(), whose StatCount does the counting. One numeric column takes geom_histogram(), where binwidth is yours to choose and the geom underneath is still GeomBar. A numeric column against a categorical one takes geom_boxplot(), two numeric columns take geom_point(), and a third column becomes a colour or a facet."],
  ["p","Because this app grades text, everything above was checked by reading the plot object rather than by looking at a picture: length(p$layers), class(p$layers[[1]]$geom)[1], nrow(p$data), names(p$mapping), get_labs(p), and ggplot_build() for the numbers a stat computed. That is also a real debugging habit — a plot that looks wrong is usually a mapping you can print."],
  ["p","Answer the practice questions from memory before revealing the answers, then clear the graded exercises below. The next chapter is workflow basics: how R evaluates what you type, what makes a legal name, and the habits that keep a script readable once it outgrows a few lines."]
]}
],
questions: [
{ q:"Name the three parts every ggplot needs, and the operator that joins them.",
  a:"Data, aesthetic mappings written inside aes(), and at least one geom layer. They are joined with +, which has to end a line rather than begin one." },
{ q:"What does ggplot(bikes, aes(x = wheel_cm, y = weight_kg)) produce on its own?",
  a:"A plot with no marks on it. It sets up the coordinate system and carries the data — nrow of its data is 8 — but length of its layers is 0, so there is nothing to draw." },
{ q:"For p built with geom_point() over the bikes tibble, what do class(p$layers[[1]]$geom)[1] and nrow(p$data) report?",
  a:"\"GeomPoint\" and 8. The geom names the kind of mark the layer draws; p$data is the whole tibble handed to ggplot(), which the layer does not change." },
{ q:"What is the difference between colour = frame inside aes() and colour = \"steelblue\" as an argument to geom_point()?",
  a:"The first is a mapping: the colour varies with the frame column, and \"colour\" joins \"x\" and \"y\" in names(p$mapping). The second is a setting: one fixed colour for every point, filed on the layer as an aes param, with the mapping still listing only x and y." },
{ q:"Why does ggplot(bikes) + geom_point(x = wheel_cm, y = weight_kg) fail?",
  a:"Column names are only looked up in the data inside aes(). Outside it, R treats wheel_cm as an ordinary variable, does not find one, and stops with Error: object 'wheel_cm' not found." },
{ q:"p was never given a labs() call. What do p$labels$x and get_labs(p)$x return, and why do they differ?",
  a:"NULL and \"wheel_cm\". Default axis labels are worked out when the plot is drawn, so the labels slot holds only what you set yourself; get_labs() reports the label the plot will actually use." },
{ q:"geom_bar() is given an x and no y. Where does the height of each bar come from?",
  a:"From the layer's stat. class(p$layers[[1]]$stat)[1] is \"StatCount\", which counts the rows in each category before GeomBar draws them. By contrast geom_point()'s stat is \"StatIdentity\", which computes nothing." },
{ q:"For a plot built with geom_histogram(binwidth = 2), what does class(p$layers[[1]]$geom)[1] report, and where is the binwidth stored?",
  a:"\"GeomBar\". A histogram is bars drawn over binned numbers, so it reuses the bar geom, and there is no GeomHistogram to find. The binning belongs to the stat, so the value is in p$layers[[1]]$stat_params$binwidth, not in geom_params." },
{ q:"How do you tell from a plot object whether it has been split into panels?",
  a:"class(p$facet)[1]. A plain plot reports \"FacetNull\", meaning one panel; after facet_wrap(~frame) it reports \"FacetWrap\". The column has to follow a tilde, because facet_wrap() takes a formula." },
{ q:"Name a mistake that leaves a plot object looking healthy and only fails when the plot is drawn.",
  a:"A misspelled column inside aes(). The object is built with its layer intact — length(p$layers) is 1 — and ggplot_build() is what stops, with Error: Problem while computing aesthetics. facet_wrap(frame) written without the tilde behaves the same way. Building a plot never reads the data, which is why both survive until something draws." }
],
exercises: [
{ c:"tibbles & pipes", t:"Three garden beds", book:"r01",
  b:"Attach tibble, then build a tibble named plots with a character column bed holding \"north\", \"south\", \"east\" and a double column beans_kg holding 3.5, 4.2, 2.8, in that order. Print the tibble.",
  o:"# A tibble: 3 × 2\n  bed   beans_kg\n  <chr>    <dbl>\n1 north      3.5\n2 south      4.2\n3 east       2.8",
  h:["tibble() takes one argument per column, and the argument name becomes the column name.",
     "Each column is a vector built with c(), and both columns need the same number of values. Nothing works until library(tibble) has run.",
     "Attach the package, then assign tibble(bed = ..., beans_kg = ...) to a variable, then put the variable on a line of its own to print it."]},
{ c:"ggplot2 basics", t:"One point per row", book:"r01",
  b:"Attach ggplot2 and tibble. Build a tibble named kilns with a column hours holding 6, 8, 10, 12, 14 and a column cracks holding 1, 2, 2, 5, 7. Map hours to x and cracks to y, add a point layer, and store the plot in p. Then print, on three lines, the number of layers, the class of the first layer's geom (its first element only), and the number of rows in the plot's data.",
  o:"[1] 1\n[1] \"GeomPoint\"\n[1] 5",
  h:["The plot is a value like any other. Build it, store it, then ask it three questions on three separate lines.",
     "p$layers is a list, so its length is the layer count. The geom sits at p$layers[[1]]$geom, and class() on it returns several names, so take the first. p$data is the tibble you handed to ggplot().",
     "Three single expressions, one per line: length() over the layers, then class() of the first layer's geom subset with [1], then nrow() of the plot's data."]},
{ c:"ggplot2 basics", t:"A third column and a second layer", book:"r01",
  b:"Attach ggplot2 and tibble. Build a tibble named reefs with depth_m holding 3, 5, 8, 11, 14, 18; species holding 21, 19, 16, 12, 9, 5; and zone holding \"inner\", \"inner\", \"inner\", \"outer\", \"outer\", \"outer\". Map depth_m to x, species to y, and zone to colour; add a point layer and then a straight-line smooth with method \"lm\" and se turned off. Store it in p and print the names of the mapping, the number of layers, and the class of the second layer's geom (first element only).",
  o:"[1] \"x\"      \"y\"      \"colour\"\n[1] 2\n[1] \"GeomSmooth\"",
  h:["Three aesthetics go in one aes(), and two geoms are added one after the other.",
     "colour belongs inside aes() so that it varies with the column. names() over p$mapping lists the aesthetics, and layers are numbered in the order you added them.",
     "The mapping takes all three at once, in the shape aes(x = , y = , colour = ). The smooth layer needs a method argument and se = FALSE. The second layer is p$layers[[2]]."]},
{ c:"ggplot2 basics", t:"Bars that count for you", book:"r01",
  b:"Attach ggplot2 and tibble. Build a tibble named shifts with worker holding \"Ines\", \"Dara\", \"Yuki\", \"Omar\", \"Lena\" and depot holding \"east\", \"west\", \"east\", \"east\", \"west\". Map depot to x, add a bar layer, and store the plot in p. Print the class of the layer's geom (first element), the class of its stat (first element), and the counts the stat computed.",
  o:"[1] \"GeomBar\"\n[1] \"StatCount\"\n[1] 3 2",
  h:["A bar chart of a character column takes an x and no y, because you are not the one supplying the heights.",
     "The counting is the layer's stat, not your arithmetic. ggplot_build() runs that computation without drawing, and the numbers come back in a column named count.",
     "p$layers[[1]] holds both the geom and the stat, each needing class() and [1]. For the counts, ggplot_build(p)$data[[1]] is a data frame and count is the column you want."]}
]
};
