/* Practice Log book — R Chapter 2: Workflow: basics.
   Original lesson text following the chapter-by-chapter curriculum of
   "R for Data Science" (2nd ed.) by Hadley Wickham, Mine Cetinkaya-Rundel,
   and Garrett Grolemund. Read the original chapter free at the src link below.
   Every shown output was captured by executing the code in WebR, not written from memory. */
window.BOOK_R = window.BOOK_R || { chapters: {} };
window.BOOK_R.chapters.r02 = {
n: 2,
title: "Workflow: basics",
src: "https://r4ds.hadley.nz/workflow-basics.html",
blurb: "Assignment, names, function calls, and the environment — the console habits every later chapter assumes.",
pkgs: [],
sections: [
{ t: "The console evaluates what you type",
  body: [
  ["p","R works one expression at a time: it reads what you typed, computes a value, and prints the value back. Arithmetic is the cheapest way to watch that happen, because you already know the answers and can concentrate on the machinery."],
  ["code","1 / 200 * 30\n(59 + 73 + 2) / 3\n2 ^ 10"],
  ["code","[1] 0.15\n[1] 44.66667\n[1] 1024"],
  ["p","Every result arrives with a bracketed number in front of it, and that number is not part of the answer. R has no separate type for a single number — one value is a vector of length one — so what the bracket reports is the position within the result of the first value printed on that line. For one value the position is always the first, hence [1]."],
  ["code","1:30"],
  ["code"," [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25\n[26] 26 27 28 29 30"],
  ["p","The colon operator builds a run of whole numbers. Thirty of them do not fit across the console, so R wraps the result and labels the second line [26]: the twenty-sixth value of the vector is the first one printed there. The bracket is a ruler down the side of the output, not data."],
  ["note","Beginners read [1] as part of the answer and try to strip it out of a stored result. It exists only at printing time. Nothing you assign, add up, or pass to a function ever contains it."]
]},
{ t: "Storing a value with <-",
  body: [
  ["p","An expression that is only evaluated is gone the moment it has been printed. To keep a value you give it a name with the assignment arrow <-, which points from the value on the right into the name on the left."],
  ["code","hours <- 8\nrate <- 21.5\npay <- hours * rate\npay"],
  ["code","[1] 172"],
  ["p","Four lines ran and one line of output came back. The three assignments printed nothing, which is deliberate: storing a value is not the same as showing it. All the output above comes from the last line, where the bare name pay is an expression, and evaluating a name means fetching whatever it holds."],
  ["p","When you want a value stored and shown in one move, wrap the whole assignment in parentheses. That turns it into an expression, and R prints expressions."],
  ["code","(total <- 12 * 4)"],
  ["code","[1] 48"],
  ["p","R accepts = as an assignment operator as well, and it works exactly as you would expect."],
  ["code","speed = 60\nspeed"],
  ["code","[1] 60"],
  ["p","Almost all R code uses <- anyway, and the reason is readability rather than rule. The = sign has a second job — naming arguments inside a function call — so reserving it for that job means a line containing <- is storing something and a line containing = is configuring a call. You can tell the two apart at a glance."],
  ["code","x <- 10\nx < -3"],
  ["code","[1] FALSE"],
  ["note","The mistake: a stray space in the middle of the arrow. x < -3 is a comparison against negative three, not an assignment. It is a perfectly legal question, so R answers it instead of complaining, and x keeps whatever it held before."]
]},
{ t: "Comments",
  body: [
  ["p","A # marks the rest of the line as a comment. R ignores everything from the # to the end of that line, so a comment can occupy a line of its own or trail behind working code."],
  ["code","# Weekly pay for a part-time shift\nhours <- 8      # hours worked\nrate <- 21.5    # rate per hour\nhours * rate    # what the shift earns"],
  ["code","[1] 172"],
  ["p","Four lines, one result, and three of the four lines carry a comment that R never sees. Comments that restate the code go stale the first time you edit the line above them. The ones worth the keystrokes record why a number is what it is, or what you tried before this."],
  ["p","R has no block comment syntax. The delimiters other languages use for that are just symbols R will try to parse, and it gives up on the first one:"],
  ["code","/* this line is not a comment */\nx <- 1"],
  ["code","Error: <text>:1:1: unexpected '/'\n1: /\n    ^"],
  ["note","The mistake: reaching for /* */ or a triple-quoted block to switch off a chunk of code while you test something. Commenting out five lines of R means five separate # marks, one per line."]
]},
{ t: "What's in a name",
  body: [
  ["p","An object name can contain letters, digits, dots and underscores, and it has to begin with a letter or with a dot that is not followed by a digit. Both of the names below are legal, and both hold their value the same way."],
  ["code","total_cost <- 42\ntotal.cost2 <- 43\ntotal_cost + total.cost2"],
  ["code","[1] 85"],
  ["p","Since more than one style is allowed, pick one and stay with it. Modern R code mostly uses snake_case — lowercase words joined by underscores — and it has the advantage of surviving being read out loud to another person."],
  ["p","Names are case-sensitive. total_cost and Total_cost are two unrelated objects, and asking for one you never created produces the error you will meet more often than any other:"],
  ["code","total_cost <- 42\nTotal_cost"],
  ["code","Error: object 'Total_cost' not found"],
  ["p","An illegal name fails earlier and differently. R cannot even parse the line, so instead of telling you what is missing it tells you the position where it stopped understanding:"],
  ["code","1st_try <- 5"],
  ["code","Error: <text>:1:2: unexpected symbol\n1: 1st_try\n     ^"],
  ["note","The mistake: hyphens in names. my-total <- 5 is not rejected as a bad name — R reads it as my minus the result of an assignment, and reports Error: object 'my' not found. A name that quietly parses as arithmetic wastes more of your time than one that is refused outright."]
]},
{ t: "Calling functions",
  body: [
  ["p","A function call is a name followed by parentheses, with arguments inside separated by commas. seq() builds a regular sequence and is a good first example, because its arguments are easy to name and easy to get wrong."],
  ["code","seq(1, 10)"],
  ["code"," [1]  1  2  3  4  5  6  7  8  9 10"],
  ["p","Arguments can be supplied by position or by name. The first three arguments of seq() are from, to and by, so the two lines below are the same call written two ways:"],
  ["code","seq(2, 20, 4)\nseq(from = 2, to = 20, by = 4)"],
  ["code","[1]  2  6 10 14 18\n[1]  2  6 10 14 18"],
  ["p","Naming arguments costs a few characters and buys the reader the meaning of every number in the call. Positional arguments are fine for the first one or two, where the convention is obvious; past that, a bare number is a puzzle."],
  ["p","Many arguments have defaults, so you pass them only when you want something other than the default. round() rounds to whole numbers unless its digits argument says otherwise:"],
  ["code","round(3.14159)\nround(3.14159, digits = 2)"],
  ["code","[1] 3\n[1] 3.14"],
  ["p","c() combines values into a vector, and most functions are happy to take that whole vector as a single argument:"],
  ["code","temps <- c(12, 15, 9, 21)\nmean(temps)\nlength(temps)\nmax(temps)"],
  ["code","[1] 14.25\n[1] 4\n[1] 21"],
  ["p","class() reports what kind of value it was handed. It is the fastest way to test a suspicion about why something is not working, because a surprising number of problems turn out to be a number that is secretly text:"],
  ["code","class(21.5)\nclass(\"Tuesday\")\nclass(TRUE)"],
  ["code","[1] \"numeric\"\n[1] \"character\"\n[1] \"logical\""],
  ["note","The mistake: leaving off the parentheses. Typing mean on its own does not call anything — it asks R for the function object, and R prints the function's definition back at you. If a name you expected to do work produced a block of unfamiliar code, you forgot the ()."]
]},
{ t: "Whitespace and style",
  body: [
  ["p","R ignores the spaces between the pieces of an expression. The two blocks below are the same program as far as the machine is concerned, and they produce the same answer:"],
  ["code","x<-c(1,2,3)\nsum(x)"],
  ["code","[1] 6"],
  ["code","x <- c(1, 2, 3)\nsum(x)"],
  ["code","[1] 6"],
  ["p","Because the machine does not care, spacing is a message to the next person who reads the line, and that person is usually you a fortnight later. Put a space either side of <- and of arithmetic operators, and a space after every comma, the way you would in a sentence. Keep one statement per line."],
  ["p","R will even accept a space between a function name and its parentheses, though almost nobody writes it that way:"],
  ["code","temps <- c(12, 15, 9, 21)\nmean (temps)"],
  ["code","[1] 14.25"],
  ["p","None of this is enforced. R runs unreadable code exactly as fast as readable code, which is why style has to be a habit rather than a thing you remember to apply at the end."],
  ["note","One place whitespace does change meaning is inside the assignment arrow, and that is the argument for spacing it properly every time. Written tightly, x<-10 still assigns; but the day your finger adds a space in the wrong half you get a comparison, an answer of TRUE or FALSE, and no error to tell you."]
]},
{ t: "What the environment holds",
  body: [
  ["p","Every object you assign goes into the global environment and stays there until you remove it or the session ends. ls() lists what is currently in there, sorted by name:"],
  ["code","rm(list = ls())\nhours <- 8\nrate <- 21.5\npay <- hours * rate\nls()"],
  ["code","[1] \"hours\" \"pay\"   \"rate\""],
  ["p","The first line clears the environment before anything else runs: ls() produces the names, and rm() removes everything in the list it is given. Starting from empty is the only way to be certain what is there, because objects from an hour ago look exactly like objects from a second ago."],
  ["p","exists() asks a yes-or-no question about a single name, which beats scanning a list when you are checking one assumption:"],
  ["code","exists(\"pay\")\nexists(\"bonus\")"],
  ["code","[1] TRUE\n[1] FALSE"],
  ["p","rm() also takes plain names, and deletes them one call at a time:"],
  ["code","rm(pay)\nls()"],
  ["code","[1] \"hours\" \"rate\""],
  ["note","The mistake: a script that works only in your session. You created an object by hand in the console, later deleted the line that made it, and the script kept running because the object was still in memory. Clear the environment and run the file from the top — anything the script does not create for itself fails immediately."]
]},
{ t: "Errors you will actually hit",
  body: [
  ["p","R's errors are short, and once you have seen each of them twice they are precise about which kind of mistake you made. Three of them cover most of a first week."],
  ["p","A misspelled object name. R looked the name up, found nothing under it, and says so. The name inside the quotes is the one you actually typed, so read that before you read anything else:"],
  ["code","greeting <- \"good morning\"\nnchar(gretting)"],
  ["code","Error: object 'gretting' not found"],
  ["p","A misspelled function name. The same kind of mistake gets different wording, because R was searching for something to call rather than a value to fetch. The other cause of this one is a function from a package you have not loaded:"],
  ["code","lenght(c(1, 2, 3))"],
  ["code","Error: could not find function \"lenght\""],
  ["p","An unclosed quote. Once a quote opens, everything after it counts as text, so R runs off the end of your code still inside the string. Notice which line the message blames: the string began on line 1, so line 1 is reported, even though the line that looks wrong is line 2."],
  ["code","greeting <- \"good morning\nnchar(greeting)"],
  ["code","Error: <text>:1:13: unexpected INCOMPLETE_STRING\n1: greeting <- \"good morning\n2: nchar(greeting)\n               ^"],
  ["p","Closing the quote repairs both lines at once, because there was only ever one thing wrong:"],
  ["code","greeting <- \"good morning\"\nnchar(greeting)"],
  ["code","[1] 12"],
  ["note","The mistake: reading the error, changing nothing, and running it again in hope. Each of these three names its own category in the first line — object 'x' not found points at a name, could not find function points at a call, and unexpected INCOMPLETE_STRING points at a quote. Decide which category you are in before you touch the code."]
]},
{ t: "Summary",
  body: [
  ["p","R evaluates an expression and prints its value, with a bracketed position marker that is printing rather than data. The arrow <- stores a value under a name, silently; typing the name gets it back. Names are case-sensitive, may hold letters, digits, dots and underscores, and are worth keeping in one consistent style. Functions are called with parentheses, and their arguments can be matched by position or, more legibly, by name. Whitespace is ignored by the machine and read closely by people, with the assignment arrow the one place a space changes the meaning."],
  ["p","Everything you assign accumulates in the global environment, where ls(), exists() and rm() let you see it and clear it — the habit that stops a script from depending on objects it never created. The errors in the last section are the ones you will collect fastest, and each of them names its own category before it says anything else."],
  ["p","Answer the practice questions from memory before revealing the answers, then clear the graded exercises below. The next chapter is data transformation, where these habits get pointed at actual data: filtering rows, choosing columns, and building new ones."]
]}
],
questions: [
{ q:"What does the [1] in front of R's output mean, and when do you see something other than [1]?",
  a:"It is the position within the result of the first value printed on that line, not part of the value. A single value is always [1]. When a result is too wide for the console it wraps, and the next line is labelled with its own starting position — printing 1:30 puts [26] at the start of the second line." },
{ q:"What does hours <- 8 print, and how do you see what a name holds?",
  a:"It prints nothing; assignment is silent. Type the name on its own line to fetch and print the value, or wrap the assignment in parentheses — (hours <- 8) stores and prints in one move." },
{ q:"x holds 10. What does x < -3 evaluate to, and why is that worse than an error?",
  a:"FALSE. The space split the arrow into a less-than sign and a negative three, so the line compares rather than assigns. It is a legal question, so R answers it instead of objecting, and x is left holding whatever it held before." },
{ q:"total_cost <- 42 has run. What happens when you type Total_cost?",
  a:"Error: object 'Total_cost' not found. Names are case-sensitive, so Total_cost is a different name and was never created." },
{ q:"How do you comment out four consecutive lines of R code?",
  a:"Put a # at the start of each of the four lines. R has no block comment syntax — /* */ is not a comment but a parse error, reported as unexpected '/'." },
{ q:"Which of these are legal object names: 1st_try, my-total, total.cost2, total_cost?",
  a:"total.cost2 and total_cost. 1st_try begins with a digit, so the line does not parse. my-total is not reported as a bad name at all — R reads it as my minus an assignment and says object 'my' not found." },
{ q:"How do seq(2, 20, 4) and seq(from = 2, to = 20, by = 4) differ?",
  a:"Only in readability. The first matches arguments by position, the second by name, and both return 2 6 10 14 18. Naming arguments is what you do once the positions stop being obvious to a reader." },
{ q:"What do ls(), exists() and rm() each do?",
  a:"ls() lists the names in the global environment, sorted. exists(\"name\") answers TRUE or FALSE for one name. rm(name) deletes an object, and rm(list = ls()) clears the environment completely." },
{ q:"What is the difference between object 'x' not found and could not find function \"x\"?",
  a:"The first means R looked up a value under that name and found none — usually a typo in a variable name. The second means R looked up something to call and found none — usually a typo in a function name, or a package that has not been loaded." },
{ q:"Your script runs cleanly for you and fails on its first lines for someone else. What is the likely cause, and what is the check?",
  a:"The script depends on an object that exists in your environment but is never created by the script itself. Clear the environment with rm(list = ls()) and run the file from the top; the missing object then reports object not found straight away." }
],
exercises: [
{ c:"vectors", t:"Four weights", book:"r02",
  b:"Store the four values 62, 75, 48 and 90 in a variable named weights. Print the vector, then its length, then its mean, each on its own line and in that order.",
  o:"[1] 62 75 48 90\n[1] 4\n[1] 68.75",
  h:["c() combines loose values into one vector, and the arrow stores it under a name.",
     "A name on a line by itself prints what it holds. length() and mean() each take the whole vector as their single argument.",
     "One assignment line first, then three lines that each print one thing: the vector, its length, its mean."]},
{ c:"data types", t:"Three classes", book:"r02",
  b:"Print the class of 3.5, then the class of the string \"3.5\", then the class of TRUE — each on its own line, in that order.",
  o:"[1] \"numeric\"\n[1] \"character\"\n[1] \"logical\"",
  h:["One function, called three times, on three separate lines.",
     "class() reports the kind of value it is handed. A number inside quotes is not a number.",
     "Each line has the shape class(value). The middle one keeps its quotes; the last one has no quotes at all."]},
{ c:"vectors", t:"Counting by fours", book:"r02",
  b:"Using seq() with all three of its arguments named, build the sequence from 4 up to 40 in steps of 4, store it in a variable named fours, and print it. On the last line print how many values it holds.",
  o:" [1]  4  8 12 16 20 24 28 32 36 40\n[1] 10",
  h:["seq() builds a regular sequence, and the size of the step is one of its arguments.",
     "The three argument names are from, to and by. Naming an argument means writing name = value inside the call.",
     "fours <- seq(from = ..., to = ..., by = ...) on the first line, the name on its own on the second, and length() on the third."]},
{ c:"data types", t:"Splitting the bill", book:"r02",
  b:"Store 1000 in total and 7 in people, then store total / people in share. Print share rounded to two decimal places, using round() with its digits argument named. On the next line print the class of share.",
  o:"[1] 142.86\n[1] \"numeric\"",
  h:["Three assignments that print nothing, then two lines that do print.",
     "round() takes the value first and the number of decimal places as its digits argument. class() takes the value on its own.",
     "After share <- total / people, one line calls round on share with digits named, and the final line calls class on share."]}
]
};
