/* Practice Log book — R Chapter 3: Data transformation.
   Original lesson text following the chapter-by-chapter curriculum of
   "R for Data Science" (2nd ed.) by Hadley Wickham, Mine Cetinkaya-Rundel,
   and Garrett Grolemund. Read the original chapter free at the src link below.
   Every shown output was captured by executing the code in WebR, not written from memory. */
window.BOOK_R = window.BOOK_R || { chapters: {} };
window.BOOK_R.chapters.r03 = {
n: 3,
title: "Data transformation",
src: "https://r4ds.hadley.nz/data-transform.html",
blurb: "The dplyr verbs that reshape a data frame: filtering rows, building columns, piping, and summarising by group.",
pkgs: ["dplyr"],
sections: [
{ t: "dplyr and the harvest log",
  body: [
  ["p","A data frame is a table, and almost everything you do with a table is one of a handful of moves: keep some rows, sort them, add a column, drop a column, collapse a group down to one number. dplyr gives each move a verb. Learning the package is mostly learning which verb does which move."],
  ["p","Every verb in this chapter has the same shape. The first argument is a data frame. The arguments after it name columns, written bare — no quotes, no dollar sign — because the verb looks the names up inside the frame you handed it. The return value is a new data frame. No verb edits the frame you passed in; you get a modified copy back, and the original is unchanged until you assign over it."],
  ["p","The verbs sort into three families by what they touch. filter(), arrange(), and distinct() act on rows. mutate(), select(), rename(), and relocate() act on columns. group_by() and summarise() act on groups of rows. This chapter takes them in that order."],
  ["p","dplyr is not part of base R, so it has to be attached before any of its verbs exist. Attaching it prints a notice, and the notice is worth reading once."],
  ["code","library(dplyr)"],
  ["code","\nAttaching package: ‘dplyr’\n\nThe following objects are masked from ‘package:stats’:\n\n    filter, lag\n\nThe following objects are masked from ‘package:base’:\n\n    intersect, setdiff, setequal, union"],
  ["note","That notice is not a warning about anything you did wrong. base R already has functions called intersect and union, and stats already has filter and lag; from now on the bare names refer to dplyr's versions instead. That is the point of attaching the package. The mistake to expect is reading this as an error and hunting for a bug that does not exist."],
  ["p","Every example below uses one small table. A community garden keeps a harvest log: one row for each crop picked in one plot in one week, with the weight picked and the hours spent picking it. Ten rows is small enough to print whole and check by eye, which is the right size for learning a verb."],
  ["code","harvest <- tibble(\n  plot  = c(\"north\", \"north\", \"north\", \"south\", \"south\",\n            \"south\", \"east\", \"east\", \"east\", \"east\"),\n  crop  = c(\"kale\", \"kale\", \"beans\", \"kale\", \"beans\",\n            \"beans\", \"kale\", \"beans\", \"squash\", \"squash\"),\n  week  = c(1L, 2L, 2L, 1L, 1L, 2L, 1L, 2L, 1L, 2L),\n  kg    = c(4.2, 5.1, 2.8, 3.9, 6.0, NA, 7.4, 1.5, 9.2, 8.6),\n  hours = c(2.0, 2.5, 1.0, 3.0, 2.0, 2.0, 1.5, 1.0, 4.0, 3.5)\n)\n\nharvest"],
  ["code","# A tibble: 10 × 5\n   plot  crop    week    kg hours\n   <chr> <chr>  <int> <dbl> <dbl>\n 1 north kale       1   4.2   2  \n 2 north kale       2   5.1   2.5\n 3 north beans      2   2.8   1  \n 4 south kale       1   3.9   3  \n 5 south beans      1   6     2  \n 6 south beans      2  NA     2  \n 7 east  kale       1   7.4   1.5\n 8 east  beans      2   1.5   1  \n 9 east  squash     1   9.2   4  \n10 east  squash     2   8.6   3.5"],
  ["p","The header line is a summary of the object: ten rows, five columns. The row of abbreviations under the column names gives each column's type — <chr> for text, <int> for whole numbers, <dbl> for numbers that can carry a decimal part. Row 6 has NA in the kg column: nobody wrote down what the south plot's beans weighed in week 2. NA is R's marker for a missing value, and it is not a zero. It will change the answer twice before this chapter is over."],
  ["p","Here is the verb shape in action, and the proof that the original survives it. filter() hands back the two squash rows; harvest still has all ten."],
  ["code","filter(harvest, crop == \"squash\")\nnrow(harvest)"],
  ["code","# A tibble: 2 × 5\n  plot  crop    week    kg hours\n  <chr> <chr>  <int> <dbl> <dbl>\n1 east  squash     1   9.2   4  \n2 east  squash     2   8.6   3.5\n[1] 10"]
]},
{ t: "Rows: filter(), and the two ways it fools you",
  body: [
  ["p","filter() keeps the rows where a condition is TRUE and drops every other row. The condition is an ordinary R comparison written against the column names, and it is evaluated once per row."],
  ["code","filter(harvest, kg > 5)"],
  ["code","# A tibble: 5 × 5\n  plot  crop    week    kg hours\n  <chr> <chr>  <int> <dbl> <dbl>\n1 north kale       2   5.1   2.5\n2 south beans      1   6     2  \n3 east  kale       1   7.4   1.5\n4 east  squash     1   9.2   4  \n5 east  squash     2   8.6   3.5"],
  ["p","Give filter() more than one condition, separated by commas, and they combine with and: a row survives only if every condition holds. Read the comma as \"and also\"."],
  ["code","filter(harvest, plot == \"east\", week == 2)"],
  ["code","# A tibble: 2 × 5\n  plot  crop    week    kg hours\n  <chr> <chr>  <int> <dbl> <dbl>\n1 east  beans      2   1.5   1  \n2 east  squash     2   8.6   3.5"],
  ["p","There is no comma form for or — write it with | yourself. When one column is being tested against a list of acceptable values, %in% says the same thing as a chain of | tests and is much harder to get wrong."],
  ["code","filter(harvest, crop %in% c(\"beans\", \"squash\"))"],
  ["code","# A tibble: 6 × 5\n  plot  crop    week    kg hours\n  <chr> <chr>  <int> <dbl> <dbl>\n1 north beans      2   2.8   1  \n2 south beans      1   6     2  \n3 south beans      2  NA     2  \n4 east  beans      2   1.5   1  \n5 east  squash     1   9.2   4  \n6 east  squash     2   8.6   3.5"],
  ["p","Now the first trap. Testing for equality takes a doubled ==. A single = inside a function call means \"this is the value for the argument named on the left\", so filter(harvest, plot = \"north\") is not a comparison at all — it is an attempt to pass an argument called plot. dplyr recognises the slip and stops."],
  ["code","filter(harvest, plot = \"north\")"],
  ["code","Error: We detected a named input."],
  ["note","= assigns or names, == compares. The reason this one keeps happening is that = works fine in tibble(), in mutate(), and in summarise(), where naming is exactly what you want. Inside filter() you are asking a question, so it has to be ==."],
  ["p","The second trap produces no error at all, which is what makes it worse. NA means \"unknown\", and a comparison against an unknown value cannot answer yes or no — so it answers NA."],
  ["code","NA > 1\nNA == NA"],
  ["code","[1] NA\n[1] NA"],
  ["p","filter() keeps rows where the condition is TRUE. NA is not TRUE, so any row whose tested column is missing gets dropped, even by a test the row would obviously have passed. Every recorded weight in the log is above 1 kg, and the log has ten rows, but this filter returns nine."],
  ["code","filter(harvest, kg > 1)"],
  ["code","# A tibble: 9 × 5\n  plot  crop    week    kg hours\n  <chr> <chr>  <int> <dbl> <dbl>\n1 north kale       1   4.2   2  \n2 north kale       2   5.1   2.5\n3 north beans      2   2.8   1  \n4 south kale       1   3.9   3  \n5 south beans      1   6     2  \n6 east  kale       1   7.4   1.5\n7 east  beans      2   1.5   1  \n8 east  squash     1   9.2   4  \n9 east  squash     2   8.6   3.5"],
  ["p","Missing rows have to be asked for by name, with is.na(). To keep the missing rows alongside the matching ones, say so explicitly: filter(harvest, kg > 1 | is.na(kg)) returns all ten."],
  ["code","filter(harvest, is.na(kg))"],
  ["code","# A tibble: 1 × 5\n  plot  crop   week    kg hours\n  <chr> <chr> <int> <dbl> <dbl>\n1 south beans     2    NA     2"],
  ["note","The mistake is not noticing. A filter that quietly drops the rows with missing data looks like it worked, and every count you take afterwards is off by however many rows went missing. When a filter returns fewer rows than you expected, check for NA in the column you tested before you suspect the condition."]
]},
{ t: "Rows: arrange() and distinct()",
  body: [
  ["p","arrange() reorders rows without adding or removing any. Each column you name is a sort key: the first key sorts the whole table, and later keys break ties inside it. Sorting is ascending by default, and missing values always sink to the bottom."],
  ["code","arrange(harvest, kg)"],
  ["code","# A tibble: 10 × 5\n   plot  crop    week    kg hours\n   <chr> <chr>  <int> <dbl> <dbl>\n 1 east  beans      2   1.5   1  \n 2 north beans      2   2.8   1  \n 3 south kale       1   3.9   3  \n 4 north kale       1   4.2   2  \n 5 north kale       2   5.1   2.5\n 6 south beans      1   6     2  \n 7 east  kale       1   7.4   1.5\n 8 east  squash     2   8.6   3.5\n 9 east  squash     1   9.2   4  \n10 south beans      2  NA     2  "],
  ["p","desc() wraps a key to sort it from largest down. Note where the missing weight lands: still last. desc() reverses the real values, not the position of NA."],
  ["code","arrange(harvest, desc(kg))"],
  ["code","# A tibble: 10 × 5\n   plot  crop    week    kg hours\n   <chr> <chr>  <int> <dbl> <dbl>\n 1 east  squash     1   9.2   4  \n 2 east  squash     2   8.6   3.5\n 3 east  kale       1   7.4   1.5\n 4 south beans      1   6     2  \n 5 north kale       2   5.1   2.5\n 6 north kale       1   4.2   2  \n 7 south kale       1   3.9   3  \n 8 north beans      2   2.8   1  \n 9 east  beans      2   1.5   1  \n10 south beans      2  NA     2  "],
  ["p","Two keys sort within one another. Here the plots come out in alphabetical order, and inside each plot the later week comes first."],
  ["code","arrange(harvest, plot, desc(week))"],
  ["code","# A tibble: 10 × 5\n   plot  crop    week    kg hours\n   <chr> <chr>  <int> <dbl> <dbl>\n 1 east  beans      2   1.5   1  \n 2 east  squash     2   8.6   3.5\n 3 east  kale       1   7.4   1.5\n 4 east  squash     1   9.2   4  \n 5 north kale       2   5.1   2.5\n 6 north beans      2   2.8   1  \n 7 north kale       1   4.2   2  \n 8 south beans      2  NA     2  \n 9 south kale       1   3.9   3  \n10 south beans      1   6     2  "],
  ["p","distinct() drops duplicate rows. Name no columns and it compares whole rows; name some and it returns the unique combinations of just those, in the order they first appeared."],
  ["code","distinct(harvest, crop)\ndistinct(harvest, plot, crop)"],
  ["code","# A tibble: 3 × 1\n  crop  \n  <chr> \n1 kale  \n2 beans \n3 squash\n# A tibble: 7 × 2\n  plot  crop  \n  <chr> <chr> \n1 north kale  \n2 north beans \n3 south kale  \n4 south beans \n5 east  kale  \n6 east  beans \n7 east  squash"],
  ["p","Naming columns also throws the other columns away, which is often not what you wanted. .keep_all = TRUE keeps the full first row of each distinct group instead."],
  ["code","distinct(harvest, crop, .keep_all = TRUE)"],
  ["code","# A tibble: 3 × 5\n  plot  crop    week    kg hours\n  <chr> <chr>  <int> <dbl> <dbl>\n1 north kale       1   4.2     2\n2 north beans      2   2.8     1\n3 east  squash     1   9.2     4"],
  ["note","With .keep_all = TRUE the row you keep is whichever one happened to come first, which is a property of how the data was entered rather than a decision you made. If it matters which row survives — the heaviest pick, the latest week — arrange() first, then distinct()."]
]},
{ t: "Columns: mutate() and select()",
  body: [
  ["p","mutate() adds columns. On the left of the = is the new column's name, on the right an expression built from the columns already there. The expression runs on whole columns at once, so kg / hours divides all ten weights by all ten durations in one pass. The new column lands on the right-hand end."],
  ["code","mutate(harvest, kg_per_hour = kg / hours)"],
  ["code","# A tibble: 10 × 6\n   plot  crop    week    kg hours kg_per_hour\n   <chr> <chr>  <int> <dbl> <dbl>       <dbl>\n 1 north kale       1   4.2   2          2.1 \n 2 north kale       2   5.1   2.5        2.04\n 3 north beans      2   2.8   1          2.8 \n 4 south kale       1   3.9   3          1.3 \n 5 south beans      1   6     2          3   \n 6 south beans      2  NA     2         NA   \n 7 east  kale       1   7.4   1.5        4.93\n 8 east  beans      2   1.5   1          1.5 \n 9 east  squash     1   9.2   4          2.3 \n10 east  squash     2   8.6   3.5        2.46"],
  ["p","Row 6 shows NA spreading. An unknown weight divided by two known hours is still unknown, so the missing value survives the arithmetic and appears in the new column too. Missing data does not get fixed by being computed with."],
  ["p","On a wide table a new column at the far right is easy to miss. .before = 1 puts it first instead, and .keep = \"used\" returns only the columns the expression touched plus the one it produced — handy for checking a calculation without scrolling."],
  ["code","mutate(harvest, kg_per_hour = kg / hours, .before = 1)"],
  ["code","# A tibble: 10 × 6\n   kg_per_hour plot  crop    week    kg hours\n         <dbl> <chr> <chr>  <int> <dbl> <dbl>\n 1        2.1  north kale       1   4.2   2  \n 2        2.04 north kale       2   5.1   2.5\n 3        2.8  north beans      2   2.8   1  \n 4        1.3  south kale       1   3.9   3  \n 5        3    south beans      1   6     2  \n 6       NA    south beans      2  NA     2  \n 7        4.93 east  kale       1   7.4   1.5\n 8        1.5  east  beans      2   1.5   1  \n 9        2.3  east  squash     1   9.2   4  \n10        2.46 east  squash     2   8.6   3.5"],
  ["code","mutate(harvest, kg_per_hour = kg / hours, .keep = \"used\")"],
  ["code","# A tibble: 10 × 3\n      kg hours kg_per_hour\n   <dbl> <dbl>       <dbl>\n 1   4.2   2          2.1 \n 2   5.1   2.5        2.04\n 3   2.8   1          2.8 \n 4   3.9   3          1.3 \n 5   6     2          3   \n 6  NA     2         NA   \n 7   7.4   1.5        4.93\n 8   1.5   1          1.5 \n 9   9.2   4          2.3 \n10   8.6   3.5        2.46"],
  ["p","select() picks columns. List them to keep exactly those, in the order you listed them. A colon takes a run of neighbouring columns. A minus sign in front of a name drops that column and keeps every other one. And where() takes a test and applies it to every column, keeping the ones that pass. The three forms below do those three things in turn."],
  ["code","select(harvest, plot, crop, kg)"],
  ["code","# A tibble: 10 × 3\n   plot  crop      kg\n   <chr> <chr>  <dbl>\n 1 north kale     4.2\n 2 north kale     5.1\n 3 north beans    2.8\n 4 south kale     3.9\n 5 south beans    6  \n 6 south beans   NA  \n 7 east  kale     7.4\n 8 east  beans    1.5\n 9 east  squash   9.2\n10 east  squash   8.6"],
  ["code","select(harvest, plot:week)\nselect(harvest, -hours)\nselect(harvest, where(is.numeric))"],
  ["code","# A tibble: 10 × 3\n   plot  crop    week\n   <chr> <chr>  <int>\n 1 north kale       1\n 2 north kale       2\n 3 north beans      2\n 4 south kale       1\n 5 south beans      1\n 6 south beans      2\n 7 east  kale       1\n 8 east  beans      2\n 9 east  squash     1\n10 east  squash     2\n# A tibble: 10 × 4\n   plot  crop    week    kg\n   <chr> <chr>  <int> <dbl>\n 1 north kale       1   4.2\n 2 north kale       2   5.1\n 3 north beans      2   2.8\n 4 south kale       1   3.9\n 5 south beans      1   6  \n 6 south beans      2  NA  \n 7 east  kale       1   7.4\n 8 east  beans      2   1.5\n 9 east  squash     1   9.2\n10 east  squash     2   8.6\n# A tibble: 10 × 3\n    week    kg hours\n   <int> <dbl> <dbl>\n 1     1   4.2   2  \n 2     2   5.1   2.5\n 3     2   2.8   1  \n 4     1   3.9   3  \n 5     1   6     2  \n 6     2  NA     2  \n 7     1   7.4   1.5\n 8     2   1.5   1  \n 9     1   9.2   4  \n10     2   8.6   3.5"],
  ["note","select() keeps only what you name, so using it to move one column to the front silently deletes every column you forgot to list. The verb for reordering without dropping is relocate(), in the next section."]
]},
{ t: "Columns: rename() and relocate()",
  body: [
  ["p","rename() changes a column's name and leaves everything else alone. The argument reads new_name = old_name, the same direction as mutate(): what you are creating goes on the left of the =."],
  ["code","rename(harvest, weight_kg = kg)"],
  ["code","# A tibble: 10 × 5\n   plot  crop    week weight_kg hours\n   <chr> <chr>  <int>     <dbl> <dbl>\n 1 north kale       1       4.2   2  \n 2 north kale       2       5.1   2.5\n 3 north beans      2       2.8   1  \n 4 south kale       1       3.9   3  \n 5 south beans      1       6     2  \n 6 south beans      2      NA     2  \n 7 east  kale       1       7.4   1.5\n 8 east  beans      2       1.5   1  \n 9 east  squash     1       9.2   4  \n10 east  squash     2       8.6   3.5"],
  ["p","The reflex to fight is writing it the way you would say it out loud — \"rename kg to weight_kg\" — because that puts the names the wrong way round. There is no column called weight_kg to rename, so the call stops."],
  ["code","rename(harvest, kg = weight_kg)"],
  ["code","Error: "],
  ["note","That is the whole message: a bare Error line with no detail behind it. dplyr does have more to say about a missing column, but the extra lines do not survive the trip through this app's R runtime, so a naming mistake shows up as an error with nothing in it. Treat an empty Error from select(), rename(), or relocate() as \"you named a column that is not there\", and check the direction of the = first."],
  ["p","relocate() moves columns. Every column stays; only the order changes. With no destination given the named columns go to the front, and .before or .after put them somewhere specific. last_col() is a way of saying \"the far right\" without knowing how many columns there are."],
  ["code","relocate(harvest, kg, .before = plot)"],
  ["code","# A tibble: 10 × 5\n      kg plot  crop    week hours\n   <dbl> <chr> <chr>  <int> <dbl>\n 1   4.2 north kale       1   2  \n 2   5.1 north kale       2   2.5\n 3   2.8 north beans      2   1  \n 4   3.9 south kale       1   3  \n 5   6   south beans      1   2  \n 6  NA   south beans      2   2  \n 7   7.4 east  kale       1   1.5\n 8   1.5 east  beans      2   1  \n 9   9.2 east  squash     1   4  \n10   8.6 east  squash     2   3.5"],
  ["code","relocate(harvest, plot, .after = last_col())"],
  ["code","# A tibble: 10 × 5\n   crop    week    kg hours plot \n   <chr>  <int> <dbl> <dbl> <chr>\n 1 kale       1   4.2   2   north\n 2 kale       2   5.1   2.5 north\n 3 beans      2   2.8   1   north\n 4 kale       1   3.9   3   south\n 5 beans      1   6     2   south\n 6 beans      2  NA     2   south\n 7 kale       1   7.4   1.5 east \n 8 beans      2   1.5   1   east \n 9 squash     1   9.2   4   east \n10 squash     2   8.6   3.5 east "],
  ["p","Neither verb changes a single value. Between them, rename() and relocate() are the two ways to make a table readable without touching what it says — which matters right at the end of a pipeline, when the result is about to be looked at by a person."]
]},
{ t: "The pipe",
  body: [
  ["p","Real work is several verbs in a row: keep some rows, compute a column, sort by it, show three columns. Written as nested calls, that pipeline has to be read from the inside out — the first thing that happens is buried deepest, and the reader's eye has to travel to the middle of the line and back."],
  ["code","select(arrange(filter(harvest, crop == \"kale\"), desc(kg)), plot, week, kg)"],
  ["code","# A tibble: 4 × 3\n  plot   week    kg\n  <chr> <int> <dbl>\n1 east      1   7.4\n2 north     2   5.1\n3 north     1   4.2\n4 south     1   3.9"],
  ["p","The pipe operator |> takes the value on its left and passes it as the first argument of the call on its right. Because every dplyr verb takes its data frame first, a chain of pipes puts the steps in the order they actually happen, one per line, top to bottom."],
  ["code","harvest |>\n  filter(crop == \"kale\") |>\n  mutate(kg_per_hour = kg / hours) |>\n  arrange(desc(kg_per_hour)) |>\n  select(plot, week, kg_per_hour)"],
  ["code","# A tibble: 4 × 3\n  plot   week kg_per_hour\n  <chr> <int>       <dbl>\n1 east      1        4.93\n2 north     1        2.1 \n3 north     2        2.04\n4 south     1        1.3 "],
  ["p","Read that as a sentence: take harvest, then keep the kale, then work out kilos per hour, then sort by it, then show three columns. Each verb receives whatever the line above produced. Nothing is stored along the way, and harvest itself is still the ten-row table it always was."],
  ["note","|> has to sit at the end of a line, not the start of the next one. R finishes a statement as soon as the line is complete on its own, so a line ending in harvest is a whole expression — and the next line, beginning with |>, is a syntax error. When a pipeline fails with an unexpected '|>' complaint, look at where the line breaks are, not at the verbs."],
  ["p","You will also meet %>%, an older pipe from the magrittr package that dplyr re-exports. It does the same job in nearly every case. |> is built into R itself and needs no package, so it is the one to reach for now."]
]},
{ t: "Groups: group_by(), summarise(), and n()",
  body: [
  ["p","group_by() changes none of the values and drops none of the rows. It attaches a note to the frame saying which column marks the groups, and every later verb reads that note. You can see it in the print: a Groups line appears, with the number of distinct groups in brackets."],
  ["code","group_by(harvest, plot)"],
  ["code","# A tibble: 10 × 5\n# Groups:   plot [3]\n   plot  crop    week    kg hours\n   <chr> <chr>  <int> <dbl> <dbl>\n 1 north kale       1   4.2   2  \n 2 north kale       2   5.1   2.5\n 3 north beans      2   2.8   1  \n 4 south kale       1   3.9   3  \n 5 south beans      1   6     2  \n 6 south beans      2  NA     2  \n 7 east  kale       1   7.4   1.5\n 8 east  beans      2   1.5   1  \n 9 east  squash     1   9.2   4  \n10 east  squash     2   8.6   3.5"],
  ["p","summarise() is what makes the grouping pay. It collapses each group down to a single row, with one column for each summary you ask for. Three plots in, three rows out — and the groups come back in sorted order, not the order they appeared."],
  ["code","harvest |>\n  group_by(plot) |>\n  summarise(total_kg = sum(kg))"],
  ["code","# A tibble: 3 × 2\n  plot  total_kg\n  <chr>    <dbl>\n1 east      26.7\n2 north     12.1\n3 south     NA  "],
  ["p","The south plot's total is NA. This is the missing weight surfacing a second time, and it is R being careful rather than R failing: the true total is genuinely unknown, because one of the numbers going into it is unknown. Base R's arithmetic behaves the same way on any vector."],
  ["code","sum(c(1, NA, 3))\nsum(c(1, NA, 3), na.rm = TRUE)"],
  ["code","[1] NA\n[1] 4"],
  ["p","na.rm = TRUE tells the summary function to leave the missing values out and add up what remains. Pass it through and the south plot reports a number."],
  ["code","harvest |>\n  group_by(plot) |>\n  summarise(total_kg = sum(kg, na.rm = TRUE))"],
  ["code","# A tibble: 3 × 2\n  plot  total_kg\n  <chr>    <dbl>\n1 east      26.7\n2 north     12.1\n3 south      9.9"],
  ["p","n() counts the rows in the current group. It takes no arguments and is only meaningful inside a dplyr verb, because \"the current group\" only exists there. Ask for a count alongside an average and you can see how much data each average rests on."],
  ["code","harvest |>\n  group_by(crop) |>\n  summarise(n = n(), mean_kg = mean(kg, na.rm = TRUE)) |>\n  arrange(crop)"],
  ["code","# A tibble: 3 × 3\n  crop       n mean_kg\n  <chr>  <int>   <dbl>\n1 beans      4    3.43\n2 kale       4    5.15\n3 squash     2    8.9 "],
  ["p","When counting is the whole job, count() is the shorthand for group_by() plus summarise(n = n())."],
  ["code","count(harvest, crop)"],
  ["code","# A tibble: 3 × 2\n  crop       n\n  <chr>  <int>\n1 beans      4\n2 kale       4\n3 squash     2"],
  ["note","na.rm = TRUE does not recover the missing weight; it changes the question. The south plot's 9.9 kg is the total of the harvests that got written down, not the total it produced, and beans' mean of 3.43 is an average over three recorded weights, not four rows. Report a count next to any summary computed with na.rm = TRUE, so the gap is visible instead of hidden."]
]},
{ t: "slice_ helpers, ungrouping, and .by",
  body: [
  ["p","summarise() replaces each group with new numbers. Sometimes you want the opposite: the actual rows that won, kept whole. The slice_ helpers do that. slice_max() and slice_min() take the extreme rows of each group by some column, and slice_head() takes the first ones."],
  ["code","harvest |>\n  group_by(plot) |>\n  slice_max(kg, n = 1)"],
  ["code","# A tibble: 3 × 5\n# Groups:   plot [3]\n  plot  crop    week    kg hours\n  <chr> <chr>  <int> <dbl> <dbl>\n1 east  squash     1   9.2   4  \n2 north kale       2   5.1   2.5\n3 south beans      1   6     2  "],
  ["p","n = 1 is a maximum, not a promise. Every row tied at the extreme comes back, so a call that looks like \"one row per group\" can return more. Both beans rows below took exactly one hour, so the beans group contributes two rows and the result has four."],
  ["code","harvest |>\n  group_by(crop) |>\n  slice_min(hours, n = 1) |>\n  arrange(crop)"],
  ["code","# A tibble: 4 × 5\n# Groups:   crop [3]\n  plot  crop    week    kg hours\n  <chr> <chr>  <int> <dbl> <dbl>\n1 north beans      2   2.8   1  \n2 east  beans      2   1.5   1  \n3 east  kale       1   7.4   1.5\n4 east  squash     2   8.6   3.5"],
  ["p","Group by two columns and summarise, and dplyr has a decision to make about what grouping the result should carry. It removes the last grouping column, keeps the rest, and prints a message telling you so."],
  ["code","harvest |>\n  group_by(plot, week) |>\n  summarise(total_kg = sum(kg, na.rm = TRUE))"],
  ["code","`summarise()` has regrouped the output.\nℹ Summaries were computed grouped by plot and week.\nℹ Output is grouped by plot.\nℹ Use `summarise(.groups = \"drop_last\")` to silence this message.\nℹ Use `summarise(.by = c(plot, week))` for per-operation grouping\n  (`?dplyr::dplyr_by`) instead.\n# A tibble: 6 × 3\n# Groups:   plot [3]\n  plot   week total_kg\n  <chr> <int>    <dbl>\n1 east      1     16.6\n2 east      2     10.1\n3 north     1      4.2\n4 north     2      7.9\n5 south     1      9.9\n6 south     2      0  "],
  ["p","That message is printed, not returned, and it is telling you something real: the result is still grouped by plot, so the next verb in the chain will work per plot. .groups = \"drop\" says you want a plain ungrouped frame back, and the message goes away with it."],
  ["code","harvest |>\n  group_by(plot, week) |>\n  summarise(total_kg = sum(kg, na.rm = TRUE), .groups = \"drop\")"],
  ["code","# A tibble: 6 × 3\n  plot   week total_kg\n  <chr> <int>    <dbl>\n1 east      1     16.6\n2 east      2     10.1\n3 north     1      4.2\n4 north     2      7.9\n5 south     1      9.9\n6 south     2      0  "],
  ["p","ungroup() strips grouping from a frame at any point in a chain. Summarising a single grouping column already returns an ungrouped result, which is why a second summarise() here sees the whole table and produces one grand total rather than three."],
  ["code","harvest |>\n  group_by(plot) |>\n  summarise(total_kg = sum(kg, na.rm = TRUE)) |>\n  summarise(grand = sum(total_kg))"],
  ["code","# A tibble: 1 × 1\n  grand\n  <dbl>\n1  48.7"],
  ["p","There is a newer way to group that never leaves anything attached. Passing .by to a verb groups for that one operation and hands back an ungrouped result. Compare the row order with the group_by() version earlier: .by keeps the groups in the order they first appear in the data, while group_by() sorts them."],
  ["code","harvest |>\n  summarise(total_kg = sum(kg, na.rm = TRUE), .by = plot)"],
  ["code","# A tibble: 3 × 2\n  plot  total_kg\n  <chr>    <dbl>\n1 north     12.1\n2 south      9.9\n3 east      26.7"],
  ["note","Grouping that outlives the line you wrote it on is the bug to watch for. A frame that is still grouped gives per-group answers to a question you meant to ask of the whole table, and the numbers look plausible enough to ship. Check the Groups line in the print, and ungroup() as soon as you are done grouping."]
]},
{ t: "Summary",
  body: [
  ["p","dplyr's verbs all take a data frame first, name columns bare, and return a new frame rather than editing the old one. filter() keeps rows by a condition, arrange() sorts them, and distinct() removes duplicates. mutate() builds columns, select() picks them, rename() renames them, and relocate() reorders them. The pipe |> feeds each verb's result into the next, turning nested calls into a list of steps in the order they happen."],
  ["p","group_by() marks a column as the grouping key and summarise() collapses each group to one row; n() counts the rows in a group and count() is the shorthand for doing only that. The slice_ helpers keep whole winning rows instead of computing new ones. Grouping persists after summarise() unless you drop it, so ungroup(), .groups = \"drop\", or per-operation .by are how you decide when it ends."],
  ["p","Two mistakes are worth carrying out of this chapter. A single = inside filter() is a named argument, not a comparison, and dplyr stops with \"We detected a named input.\" And NA is not FALSE — filter() silently drops rows whose tested value is missing, and sum() and mean() return NA unless you pass na.rm = TRUE, which quietly narrows the question you are answering."],
  ["p","Answer the practice questions from memory before revealing the answers, then clear the graded exercises below. Chapter 4 is workflow: code style — how to lay out the pipelines you just learned to write so that you can still read them next month."]
]}
],
questions: [
{ q:"What do the three parts of the header line # A tibble: 10 × 5 tell you, and what does <chr> mean under a column name?",
  a:"The table has 10 rows and 5 columns. The abbreviation under each column name is its type: <chr> is text, <int> is whole numbers, <dbl> is numbers that can hold a decimal part." },
{ q:"After running filter(harvest, crop == \"squash\"), how many rows does harvest have?",
  a:"Ten — the same as before. No dplyr verb edits the frame you pass in. filter() returned a new two-row frame and harvest was untouched, which is why a pipeline has to end in an assignment if you want to keep the result." },
{ q:"Why does filter(harvest, plot = \"north\") fail, and what does R print?",
  a:"A single = inside a function call names an argument instead of comparing, so the call is trying to pass an argument called plot. dplyr catches it and prints: Error: We detected a named input. Equality needs ==." },
{ q:"Every recorded weight in the log is above 1 kg. How many rows does filter(harvest, kg > 1) return, and why?",
  a:"Nine. Row 6 has NA for kg, the comparison NA > 1 evaluates to NA rather than TRUE, and filter() keeps only rows where the condition is TRUE. Adding | is.na(kg) brings the row back and returns all ten." },
{ q:"What does NA == NA evaluate to, and what does that say about NA?",
  a:"NA. NA means unknown, and asking whether one unknown equals another unknown cannot be answered yes or no. That is why missing values are found with is.na() rather than with == NA." },
{ q:"In arrange(harvest, desc(kg)), where does the row with the missing weight end up?",
  a:"Last. Missing values sort to the bottom whether the key is ascending or descending; desc() reverses the real values, not NA's position." },
{ q:"Where does mutate() put a new column by default, and what does .before = 1 change?",
  a:"On the right-hand end, after every existing column. .before = 1 puts the new column first instead, so on a wide table you can see it without scrolling. The column order is all that changes." },
{ q:"Which way round does rename() read, and what does the backwards form print here?",
  a:"new_name = old_name, the same direction as mutate — what you are creating is on the left. Written backwards as rename(harvest, kg = weight_kg) it fails, because no column called weight_kg exists. In this app the failure prints as a bare Error: with no detail, so an empty error from a column-naming verb means a name that is not there." },
{ q:"You want to move one column to the front. Why is select() the wrong verb for that?",
  a:"select() keeps only the columns you name, so it deletes every column you did not list. relocate() reorders and keeps everything." },
{ q:"summarise(total_kg = sum(kg)) reports NA for the south plot. What causes it, what fixes it, and what does the fix cost?",
  a:"One of south's weights is missing, and sum() of anything containing NA is NA. Passing na.rm = TRUE adds up the recorded values and returns 9.9. The cost is that the answer is now the total of what was written down, not the total harvested — so report n() beside it and keep the gap visible." }
],
exercises: [
{ c:"dplyr verbs", t:"Heavy beds first", book:"r03",
  b:"Attach dplyr with suppressMessages(library(dplyr)) so the attach notice does not appear in your output. Build a tibble called beds with a column bed holding \"a\" through \"f\" and a column kg holding 3.5, 8.1, 5.2, 2.2, 9.4, 6.7 in that order. Print the beds that yielded at least 5 kg, heaviest first.",
  o:"# A tibble: 4 × 2\n  bed      kg\n  <chr> <dbl>\n1 e       9.4\n2 b       8.1\n3 f       6.7\n4 c       5.2",
  h:["Two verbs, in the order the sentence says them: keep the rows you want, then put them in order.",
     "filter() takes the condition; arrange() takes the sort key. \"At least 5\" is >=, not >.",
     "Pipe beds into filter(kg >= 5), then into arrange() with the kg key wrapped in something that reverses it."]},
{ c:"dplyr verbs", t:"Kilometres per hour", book:"r03",
  b:"Attach dplyr with suppressMessages(library(dplyr)). Build a tibble called runs with route = \"ridge\", \"creek\", \"loop\", \"flats\"; km = 12, 5, 8, 10; and mins = 90, 30, 56, 48. Add a column kmh holding the speed in kilometres per hour, then print only route and kmh, fastest first.",
  o:"# A tibble: 4 × 2\n  route   kmh\n  <chr> <dbl>\n1 flats 12.5 \n2 creek 10   \n3 loop   8.57\n4 ridge  8   ",
  h:["Three verbs: build the column, choose the columns to show, order the rows.",
     "mutate() creates kmh. The minutes have to become hours before the division means anything.",
     "kmh = km / (mins / 60), then select(route, kmh), then arrange() on the descending speed."]},
{ c:"grouping & summaries", t:"Market stall totals", book:"r03",
  b:"Attach dplyr with suppressMessages(library(dplyr)). Build a tibble called sales with stall = \"bread\", \"bread\", \"jam\", \"jam\", \"jam\", \"honey\" and items = 4L, 6L, 3L, 5L, 2L, 7L. For each stall print the number of orders in a column called orders and the total items sold in a column called total, with the stalls in alphabetical order.",
  o:"# A tibble: 3 × 3\n  stall orders total\n  <chr>  <int> <int>\n1 bread      2    10\n2 honey      1     7\n3 jam        3    10",
  h:["Group first, then collapse each group to one row, then sort.",
     "summarise() makes both columns in one call. Counting the rows of the current group is a function that takes no arguments.",
     "group_by(stall), then summarise(orders = n(), total = <the sum of items>), then arrange(stall)."]},
{ c:"tibbles & pipes", t:"What the shelf is worth", book:"r03",
  b:"Attach dplyr with suppressMessages(library(dplyr)). Build a tibble called stock with item = \"flour\", \"sugar\", \"yeast\", \"salt\"; units = 12L, 3L, 25L, 8L; and price = 1.2, 0.8, 0.5, 0.4. Add a column value holding units times price, keep only the lines worth more than 5, rename item to product, and print the result with the most valuable line first.",
  o:"# A tibble: 2 × 4\n  product units price value\n  <chr>   <int> <dbl> <dbl>\n1 flour      12   1.2  14.4\n2 yeast      25   0.5  12.5",
  h:["Four verbs piped in the order the sentence lists them. Every column stays except the one that gets a new name.",
     "The value column has to exist before you can filter on it, so mutate() comes before filter(). rename() reads new_name = old_name.",
     "stock piped into mutate(value = ...), then filter(value > 5), then rename(product = item), then arrange() on the descending value."]}
]
};
