/* Practice Log book — R Chapter 4: Workflow: code style.
   Original lesson text following the chapter-by-chapter curriculum of
   "R for Data Science" (2nd ed.) by Hadley Wickham, Mine Cetinkaya-Rundel,
   and Garrett Grolemund. Read the original chapter free at the src link below.
   Every shown output was captured by executing the code in WebR, not written from memory. */
window.BOOK_R = window.BOOK_R || { chapters: {} };
window.BOOK_R.chapters.r04 = {
n: 4,
title: "Workflow: code style",
src: "https://r4ds.hadley.nz/workflow-style.html",
blurb: "Names, spacing, pipe layout, and sectioning comments — the conventions R ignores and the next reader depends on.",
pkgs: ["dplyr"],
sections: [
{ t: "Style is written for the next reader",
  body: [
  ["p","A script is written once and read many times. Most of those readings are done by the person who wrote it, months later, with no memory of why any of it is there. Style is the work you do now so that reading later is cheap."],
  ["p","R itself is indifferent. The parser throws away your spaces, ignores your comments, and does not care whether a variable is called x2 or busy_days. Two files can be identical as far as R is concerned and worlds apart as far as a human is concerned. That gap is what this chapter is about."],
  ["code","mean(c(3,1,4,1,5))*2"],
  ["code","[1] 5.6"],
  ["code","mean(c(3, 1, 4, 1, 5)) * 2"],
  ["code","[1] 5.6"],
  ["p","Same answer, twice. Every rule in this chapter has that property: following it changes nothing about what R computes. The conventions below come from the tidyverse style guide, which is the closest thing R has to a common dialect, and the value of a common dialect is that other people can read you without translating."],
  ["note","The usual mistake is treating style as a tidy-up pass: get it working first, make it readable later. Later does not arrive. The code that is hardest to read is also the code you are most likely to give up on halfway through fixing, so the mess costs you exactly when you can least afford it."]
]},
{ t: "Naming things",
  body: [
  ["p","Names should be long enough to say what the thing is. The convention is snake_case: all lowercase, words separated by underscores. Nothing enforces it, but consistency is the whole point — a reader who has seen ten of your names should be able to guess the eleventh."],
  ["code","x1 <- c(12, 5, 9, 14, 3, 7)\nx2 <- x1[x1 > 6]\nsum(x2)"],
  ["code","[1] 42"],
  ["code","daily_cups <- c(12, 5, 9, 14, 3, 7)\nbusy_days <- daily_cups[daily_cups > 6]\nsum(busy_days)"],
  ["code","[1] 42"],
  ["p","The second version answers a question the first one raises: forty-two of what. Both compute the same number, so the only difference is how long it takes a reader to work out what the script is for."],
  ["p","When several objects belong to the same family, start their names the same way. Names like cups_north, cups_south, and cups_east sort together in a file listing and appear together the moment you type cups and hit tab. Naming them north_cups, southern_total, and e_cups scatters them, and you will hunt for the third one every time."],
  ["p","Dots in names are legal and were common in older R code. Avoid them in new code: R uses the dot to mark S3 methods, so print.data.frame is a function that prints data frames, and a variable called cups.per.shop reads like a method for objects of class shop."],
  ["code","cups.per.shop <- 3\ncups.per.shop"],
  ["code","[1] 3"],
  ["note","T and F are the trap. They are not keywords — they are ordinary variables that happen to start out equal to TRUE and FALSE, and nothing stops you from assigning over them. Do it once, deep in a long script, and every test below it quietly flips. TRUE and FALSE are reserved and cannot be reassigned, which is the only reason to type them in full."],
  ["code","T <- FALSE\nT"],
  ["code","[1] FALSE"],
  ["code","TRUE <- FALSE"],
  ["code","Error: invalid (do_set) left-hand side to assignment"]
]},
{ t: "Spaces",
  body: [
  ["p","Put spaces on both sides of the operators that sit between two values: <- for assignment, the arithmetic operators + - * /, and the comparisons == < > <= >=. The line gets longer and the eye finds the operator without searching."],
  ["p","Three operators are conventionally written tight, with no spaces: ^ for powers, : for ranges, and $ for reaching into a data frame. They bind more tightly than everything around them, and writing them tight is a visual reminder of that."],
  ["code","n <- 4\nn^2\n1:n"],
  ["code","[1] 16\n[1] 1 2 3 4"],
  ["p","Commas follow the rule they follow in English: a space after, never before. Do not put spaces just inside the brackets of a function call."],
  ["code","round(c(1.234,5.678),1)"],
  ["code","[1] 1.2 5.7"],
  ["code","round(c(1.234, 5.678), 1)"],
  ["code","[1] 1.2 5.7"],
  ["p","There is exactly one place in R where a space changes the meaning rather than the appearance, and it is the reason the habit is worth forming. The assignment arrow <- is two characters. Separate them with a space and you have a less-than sign followed by a negative number."],
  ["code","count <- 5\ncount<-3\ncount"],
  ["code","[1] 3"],
  ["code","count <- 5\ncount < -3"],
  ["code","[1] FALSE"],
  ["note","The second block is a comparison and prints FALSE; the first is an assignment and silently replaces the 5 with a 3. If you write count<-3 in a spot where you meant to ask whether count is below negative three, R does not warn you — it just overwrites the variable and moves on. Spacing your assignments consistently makes this impossible to write by accident."]
]},
{ t: "The pipe",
  body: [
  ["p","The rest of the chapter needs a package and a small table to work on. dplyr supplies both the pipeline verbs and tibble(), the function that builds the table."],
  ["code","library(dplyr)\n\nsales <- tibble(\n  shop  = c(\"north\", \"north\", \"south\", \"south\", \"south\", \"east\"),\n  drink = c(\"chai\", \"matcha\", \"chai\", \"chai\", \"matcha\", \"chai\"),\n  cups  = c(12, 5, 9, 14, 3, 7)\n)"],
  ["code","Attaching package: ‘dplyr’\n\nThe following objects are masked from ‘package:stats’:\n\n    filter, lag\n\nThe following objects are masked from ‘package:base’:\n\n    intersect, setdiff, setequal, union"],
  ["p","That block of text is library() reporting which names dplyr has taken over; the tibble assignment itself prints nothing. Notice the extra spaces after shop and cups, lining up the three = signs. Padding like that is worth it when a run of arguments reads as a block: the parser ignores it, and the reader gets a column to scan down."],
  ["code","sales"],
  ["code","# A tibble: 6 × 3\n  shop  drink   cups\n  <chr> <chr>  <dbl>\n1 north chai      12\n2 north matcha     5\n3 south chai       9\n4 south chai      14\n5 south matcha     3\n6 east  chai       7"],
  ["p","The native pipe |> takes the value on its left and passes it as the first argument of the call on its right. Those two lines below are the same instruction written two ways."],
  ["code","sqrt(c(1, 4, 9))\nc(1, 4, 9) |> sqrt()"],
  ["code","[1] 1 2 3\n[1] 1 2 3"],
  ["p","The layout conventions for a pipeline are: a space before |>, |> as the last thing on its line, and each following verb on its own line indented by two spaces. A pipeline written that way reads as a list of steps, and each step can be commented out or run on its own while you work out where it went wrong."],
  ["code","sales|>filter(cups>6)|>group_by(shop)|>summarize(total_cups=sum(cups))"],
  ["code","# A tibble: 3 × 2\n  shop  total_cups\n  <chr>      <dbl>\n1 east           7\n2 north         12\n3 south         23"],
  ["code","sales |>\n  filter(cups > 6) |>\n  group_by(shop) |>\n  summarize(total_cups = sum(cups))"],
  ["code","# A tibble: 3 × 2\n  shop  total_cups\n  <chr>      <dbl>\n1 east           7\n2 north         12\n3 south         23"],
  ["p","Identical output, character for character. The four-line version costs three extra newlines and buys a script whose steps you can point at one at a time."],
  ["p","The pipe has to end the line rather than begin it. R reads a line that could stand alone as finished, so putting |> at the front of the next line leaves it dangling with nothing to its left."],
  ["code","c(1, 4, 9)\n  |> sqrt()"],
  ["code","Error: <text>:2:3: unexpected '|>'\n1: c(1, 4, 9)\n2:   |>\n     ^"],
  ["note","That is a parse error, which means nothing in the file runs — not even the lines above the mistake. It looks alarming and it is the friendly case, because R stops and points at the character it choked on. The next section has the same mistake with a different operator and no error at all."]
]},
{ t: "Stacking layers with +",
  body: [
  ["p","ggplot2 assembles a plot by adding layers with +, and the layout convention matches the pipe: + ends the line, and each layer sits on its own line indented two spaces. The two operators look unrelated but the reading problem is the same, so the solution is the same."],
  ["code","ggplot(sales, aes(x = shop, y = cups)) +\n  geom_col() +\n  labs(title = \"Cups by shop\")"],
  ["note","This chapter loads dplyr only, and a plot is a picture rather than text, so the block above is shown without any output rather than with an invented one. Run it in desktop R with ggplot2 installed to see the chart."],
  ["p","The trap does not need ggplot2 to demonstrate, because + is an ordinary operator. Move it to the start of a line and R reads the line above as a finished expression, then reads a second, separate expression that happens to begin with a plus sign."],
  ["code","1\n  + 2"],
  ["code","[1] 1\n[1] 2"],
  ["code","1 +\n  2"],
  ["code","[1] 3"],
  ["p","Two results instead of one sum. No error, no warning — R did exactly what the characters said. In a plotting script the same break means the layers below it are no longer part of the plot above them."],
  ["note","This is the mistake worth remembering from the whole chapter: the misplaced pipe stops your script, and the misplaced plus lets it run and hands you the wrong thing. A convention that saves you from a silent wrong answer is not decoration."]
]},
{ t: "Sectioning comments",
  body: [
  ["p","Once a script outgrows a screen, it needs headings. The convention is a comment with a title and a run of dashes stretching to the right margin. Editors that fold code use these as fold points, and every other editor still gets a line the eye can find while scrolling."],
  ["code","# Setup -------------------------------------------------------------------\n\n# Chai outsells matcha everywhere, so it gets counted on its own.\nchai <- sales |>\n  filter(drink == \"chai\")\n\n# Report ------------------------------------------------------------------\n\nsum(chai$cups)"],
  ["code","[1] 42"],
  ["p","Strip every comment out and R produces the same 42. The comments are not doing arithmetic; they are telling a reader which part of the file to jump to and why the chai rows were separated out at all."],
  ["code","chai <- sales |>\n  filter(drink == \"chai\")\n\nsum(chai$cups)"],
  ["code","[1] 42"],
  ["p","The useful comment explains why, not what. A reader who knows R can see that filter() keeps rows; what they cannot see is the decision behind it. Comments that restate the code — add one to the counter, load the data — are noise that has to be read and discarded."],
  ["note","Comments are the only part of a script nothing checks. Change the code, forget the comment above it, and R will not say a word — it never read the comment in the first place. A stale comment is worse than no comment, because a reader will believe it and spend an hour reconciling it with code that stopped matching it months ago."]
]},
{ t: "Two shapes, one answer",
  body: [
  ["p","Here is a whole small analysis written both ways: keep the busy shop-days, group by shop, and report the cups and the number of days behind each total. The first version is what the keyboard produces when you are in a hurry."],
  ["code","d<-sales|>filter(cups>6)|>group_by(shop)|>summarize(total_cups=sum(cups),days=n())\nd"],
  ["code","# A tibble: 3 × 3\n  shop  total_cups  days\n  <chr>      <dbl> <int>\n1 east           7     1\n2 north         12     1\n3 south         23     2"],
  ["p","The second version applies the whole chapter: a name that says what the object holds, spaces around the operators, one verb per line, the two summary columns split onto lines of their own, and a heading above it."],
  ["code","# Busy shop-days ----------------------------------------------------------\n\nbusy_days <- sales |>\n  filter(cups > 6) |>\n  group_by(shop) |>\n  summarize(\n    total_cups = sum(cups),\n    days = n()\n  )\n\nbusy_days"],
  ["code","# A tibble: 3 × 3\n  shop  total_cups  days\n  <chr>      <dbl> <int>\n1 east           7     1\n2 north         12     1\n3 south         23     2"],
  ["p","The two transcripts match exactly. Nothing in this chapter has bought a single correct answer that was not already there, which is precisely why style has to be a habit rather than a reward — the payoff never shows up in the output, only in how long the next reading takes."],
  ["p","Two packages will do some of this for you. styler rewrites code to match the style guide, and lintr reads code and reports where it departs from the guide without changing anything. Both are installed the ordinary way, with install.packages()."],
  ["code","styler::style_text(\"x<-c(1,2,3)\")\nlintr::lint(text = \"x<-c(1,2,3)\")"],
  ["note","Neither package is loaded by this chapter — it declares dplyr only — so the two calls above are shown without output rather than with an invented one. Neither tool decides anything for you either: they enforce spacing and layout, and they have nothing to say about whether a variable called x2 should have been called busy_days."]
]},
{ t: "Summary",
  body: [
  ["p","Names go in snake_case and should be long enough to say what they hold; dots belong to S3 methods and T and F belong to nobody, because they can be assigned over. Operators between two values get spaces around them, ^ and : and $ do not, and commas take a space after and never before. Pipelines put a space before |>, end the line with it, and indent each verb two spaces; ggplot2 layers do the same with +. Sectioning comments give a long script headings, and the comments in between explain why rather than what."],
  ["p","The verified thread running through the chapter is that every one of these pairs printed the same thing. Style changes nothing R does. It changes how long it takes a person to see what R is doing, which is the only part of the cost you actually pay twice."],
  ["p","Answer the practice questions from memory before revealing the answers, then clear the graded exercises below. The next chapter is data tidying — what makes a table tidy, and how to reshape one that is not."]
]}
],
questions: [
{ q:"What does R gain when you follow the style guide?",
  a:"Nothing. The parser discards spacing and comments and does not care what a variable is called, which is why every paired example in this chapter printed identical output. The gain belongs entirely to whoever reads the code next, usually you." },
{ q:"What is the naming convention, and what makes a name good beyond its casing?",
  a:"snake_case: all lowercase, words joined by underscores. Beyond casing, a name should say what the object holds — daily_cups rather than x1 — and objects in the same family should share a leading word so they sort and autocomplete together." },
{ q:"Why avoid dots in variable names in new R code?",
  a:"R uses the dot to mark S3 methods, so print.data.frame is the printing method for data frames. A variable named cups.per.shop is legal and assigns fine, but it reads like a method for a class called shop." },
{ q:"T is shorter than TRUE. What is wrong with using it?",
  a:"T and F are ordinary variables that merely start out equal to TRUE and FALSE, so T <- FALSE is a legal assignment and every test below it flips. TRUE and FALSE are reserved: TRUE <- FALSE fails with an invalid left-hand side error." },
{ q:"Which operators get spaces around them, and which three are written tight?",
  a:"Spaces around operators that sit between two values: <- and the arithmetic + - * / and the comparisons == < > <= >=. Written tight with no spaces: ^ for powers, : for ranges, and $ for reaching into a data frame." },
{ q:"count is 5. What does count<-3 do, and what does count < -3 do?",
  a:"count<-3 is an assignment: it replaces the 5 with a 3, and printing count afterwards gives 3. count < -3 is a comparison of 5 against negative three and evaluates to FALSE. The only difference on the keyboard is a space." },
{ q:"Where does |> go when a pipeline spans several lines, and how is the next line indented?",
  a:"A space before |>, then |> as the last thing on the line, then the next verb on its own line indented two spaces. It has to end the line rather than start one." },
{ q:"c(1, 4, 9) |> sqrt() — what is this equivalent to without the pipe?",
  a:"sqrt(c(1, 4, 9)). The pipe passes the value on its left as the first argument of the call on its right; both forms print [1] 1 2 3." },
{ q:"What happens if you start a line with |>, and what happens if you start a line with +?",
  a:"A leading |> is a parse error — R reports unexpected '|>' and nothing in the file runs. A leading + is not an error at all: R reads the line above as finished and the plus as unary, so 1 followed by an indented + 2 prints [1] 1 and then [1] 2 instead of [1] 3. The silent one is the dangerous one." },
{ q:"What are sectioning comments for, and what makes an ordinary comment worth keeping?",
  a:"A sectioning comment is a title padded with dashes to the margin; it gives a long script headings you can scroll to and editors can fold on. An ordinary comment earns its place by explaining why a decision was made — comments that restate what the code plainly does are noise, and nothing in R checks whether either kind has gone stale." }
],
exercises: [
{ c:"tibbles & pipes", t:"One pipeline, three lines", book:"r04",
  b:"Given daily_cups <- c(12, 5, 9, 14, 3, 7), use the native pipe to send the vector to mean(), then send that result to round() so it shows one decimal place, and print it. Lay the pipeline out over three lines, with |> ending each line that has one.",
  o:"[1] 8.3",
  h:["x |> f() is another way of writing f(x), so two pipes chain three steps together.",
     "round() still needs to be told how many decimal places to keep — the piped value fills its first argument, not its second.",
     "The first line is daily_cups |>, the second is mean() |>, and the third is the rounding call. Nothing needs assigning; the last expression prints itself."]},
{ c:"tibbles & pipes", t:"Untangle the one-liner", book:"r04",
  b:"Start with suppressPackageStartupMessages(library(dplyr)), then build sales <- tibble(shop = c(\"north\", \"north\", \"south\", \"south\", \"south\", \"east\"), drink = c(\"chai\", \"matcha\", \"chai\", \"chai\", \"matcha\", \"chai\"), cups = c(12, 5, 9, 14, 3, 7)). Keep only the chai rows, order them from most cups to fewest, and print the result. Write the pipeline one verb per line.",
  o:"# A tibble: 4 × 3\n  shop  drink  cups\n  <chr> <chr> <dbl>\n1 south chai     14\n2 north chai     12\n3 south chai      9\n4 east  chai      7",
  h:["Two verbs are needed: one that keeps rows, and one that changes the order of the rows it kept.",
     "filter() keeps the rows where a condition is TRUE. arrange() sorts, and by default it sorts ascending — desc() around a column reverses that.",
     "sales |> filter(...) |> arrange(...), broken across lines. The condition tests drink, and the sort is on cups."]},
{ c:"dplyr verbs", t:"Name what you counted", book:"r04",
  b:"Build the same sales tibble as the previous exercise, then total the cups for each drink. Call the summary column total_cups, store the pipeline in a variable named cups_per_drink, and print that variable on its own line.",
  o:"# A tibble: 2 × 2\n  drink  total_cups\n  <chr>       <dbl>\n1 chai           42\n2 matcha          8",
  h:["Totalling within groups takes two verbs: one that declares what the groups are, and one that collapses each group to a single row.",
     "group_by() names the column that defines the groups. summarize() builds new columns out of the rows in each group, and sum() does the adding.",
     "cups_per_drink <- sales |> group_by(...) |> summarize(total_cups = ...), laid out over several lines, then a final line holding just the variable name."]},
{ c:"dplyr verbs", t:"What grouping changes", book:"r04",
  b:"Build the same sales tibble again, then print two results in this order. First, the total cups across the whole table as a one-row summary with the column named total_cups. Second, the same total broken down by shop, keeping the shop column. Both come from summarize(); only the second has a grouping verb in front of it.",
  o:"# A tibble: 1 × 1\n  total_cups\n       <dbl>\n1         50\n# A tibble: 3 × 2\n  shop  total_cups\n  <chr>      <dbl>\n1 east           7\n2 north         17\n3 south         26",
  h:["Two separate pipelines, one after the other. They differ by a single verb.",
     "summarize() on its own collapses the entire tibble to one row. group_by(shop) in front of it makes summarize() collapse each shop separately instead.",
     "Write the ungrouped pipeline first, then repeat it with group_by(shop) |> inserted before the summarize() step. The three grouped totals should add up to the single ungrouped one."]}
]
};
