/* Practice Log book — R Chapter 5: Data tidying.
   Original lesson text following the chapter-by-chapter curriculum of
   "R for Data Science" (2nd ed.) by Hadley Wickham, Mine Cetinkaya-Rundel,
   and Garrett Grolemund. Read the original chapter free at the src link below.
   Every shown output was captured by executing the code in WebR, not written from memory. */
window.BOOK_R = window.BOOK_R || { chapters: {} };
window.BOOK_R.chapters.r05 = {
n: 5,
title: "Data tidying",
src: "https://r4ds.hadley.nz/data-tidy.html",
blurb: "One variable per column, one observation per row — and the two pivots that get a table into that shape.",
pkgs: ["tidyr","dplyr"],
sections: [
{ t: "What tidy data means",
  body: [
  ["p","The same information can be written down in more than one shape, and most of those shapes will fight you. Tidy data is one particular shape, and the tidyverse is built on the assumption that your data is in it. Recognising the shape, and converting into it, is what this chapter is for."],
  ["code",'library(tidyr)\nlibrary(dplyr)'],
  ["note","Attaching dplyr prints a notice the first time in a session, listing the functions it hides from stats and base. That notice is normal, but it would land in the output the grader compares, so the exercises at the end of this chapter wrap their library() calls in suppressPackageStartupMessages() to keep it out."],
  ["p","Here is a season of yields from three vegetable plots, written the way a person would write it on paper: one row per plot, one column per season."],
  ["code",'harvest <- tibble(\n  plot   = c("north", "south", "east"),\n  spring = c(12, 9, 15),\n  summer = c(31, 24, 28),\n  autumn = c(18, 21, 11)\n)\n\nharvest'],
  ["code","# A tibble: 3 × 4\n  plot  spring summer autumn\n  <chr>  <dbl>  <dbl>  <dbl>\n1 north     12     31     18\n2 south      9     24     21\n3 east      15     28     11"],
  ["p","Tidy data obeys three rules: every column is a variable, every row is an observation, and every cell holds a single value. Hold the table above against them. The quantity being measured is kilos harvested, and there is no kilos column — those numbers are scattered across three columns named after seasons. Season is a variable too, and it is not a column at all; it has been promoted into the headings. One layout, two rules broken."],
  ["p","Written tidily, the same nine numbers look like this:"],
  ["code",'harvest_tidy <- tibble(\n  plot   = c("north", "north", "north", "south", "south", "south", "east", "east", "east"),\n  season = rep(c("spring", "summer", "autumn"), 3),\n  kilos  = c(12, 31, 18, 9, 24, 21, 15, 28, 11)\n)\n\nharvest_tidy'],
  ["code","# A tibble: 9 × 3\n  plot  season kilos\n  <chr> <chr>  <dbl>\n1 north spring    12\n2 north summer    31\n3 north autumn    18\n4 south spring     9\n5 south summer    24\n6 south autumn    21\n7 east  spring    15\n8 east  summer    28\n9 east  autumn    11"],
  ["p","Every column is now a variable — plot, season, kilos — and every row is one observation: one plot in one season. The table is taller and far more repetitive than the first one. That repetition is the whole point, because it is what lets one function call reach every value."],
  ["note","Tidy does not mean clean, and it does not mean neat. The wide table is easier for a person to read, and the tidy one is easier for a computer to work with. Tidy is a technical claim about which things are variables, not a judgement about how the table looks."]
]},
{ t: "Why tidy data pays off",
  body: [
  ["p","The payoff is that dplyr, ggplot2 and everything built alongside them assume this layout. Because season is a column, grouping by it is an argument rather than a restructuring project."],
  ["code",'harvest_tidy |>\n  group_by(season) |>\n  summarise(total = sum(kilos))'],
  ["code","# A tibble: 3 × 2\n  season total\n  <chr>  <dbl>\n1 autumn    50\n2 spring    36\n3 summer    83"],
  ["p","Computing a new variable works the same way. All the measurements live in one column, so a unit conversion touches one column, no matter how many seasons there are."],
  ["code",'harvest_tidy |>\n  mutate(pounds = round(kilos * 2.20462, 1)) |>\n  arrange(plot, season)'],
  ["code","# A tibble: 9 × 4\n  plot  season kilos pounds\n  <chr> <chr>  <dbl>  <dbl>\n1 east  autumn    11   24.3\n2 east  spring    15   33.1\n3 east  summer    28   61.7\n4 north autumn    18   39.7\n5 north spring    12   26.5\n6 north summer    31   68.3\n7 south autumn    21   46.3\n8 south spring     9   19.8\n9 south summer    24   52.9"],
  ["p","Now the wide table, where the same kind of question needs every column named by hand:"],
  ["code",'harvest |>\n  mutate(total = spring + summer + autumn)'],
  ["code","# A tibble: 3 × 5\n  plot  spring summer autumn total\n  <chr>  <dbl>  <dbl>  <dbl> <dbl>\n1 north     12     31     18    61\n2 south      9     24     21    54\n3 east      15     28     11    54"],
  ["p","That line is correct for exactly the columns it lists, and only those. Record a winter column and it keeps totalling three seasons out of four, without complaint, because nothing about it is wrong — it is just answering an older question."],
  ["note","Wide layouts are not a mistake. They are usually how data arrives, and often how people prefer to read it. The cost is that every calculation has to be rewritten whenever the columns change. Pivoting once at the start is cheaper than special-casing forever."]
]},
{ t: "Lengthening data with pivot_longer()",
  body: [
  ["p","pivot_longer() turns columns into rows. You tell it which columns are holding values rather than variables, what to call the column that will collect their headings, and what to call the column that will collect their contents."],
  ["code",'harvest |>\n  pivot_longer(\n    cols = c(spring, summer, autumn),\n    names_to = "season",\n    values_to = "kilos"\n  )'],
  ["code","# A tibble: 9 × 3\n  plot  season kilos\n  <chr> <chr>  <dbl>\n1 north spring    12\n2 north summer    31\n3 north autumn    18\n4 south spring     9\n5 south summer    24\n6 south autumn    21\n7 east  spring    15\n8 east  summer    28\n9 east  autumn    11"],
  ["p","Three arguments carry the work. cols picks the columns to fold up. names_to names the new column that receives the old headings. values_to names the new column that receives the old cells. That is the whole interface."],
  ["p","cols understands the same selection language as select(), so you can list the columns you want or name the one you want left alone. All three of these select the same thing:"],
  ["code",'a <- harvest |> pivot_longer(cols = c(spring, summer, autumn), names_to = "season", values_to = "kilos")\nb <- harvest |> pivot_longer(cols = -plot, names_to = "season", values_to = "kilos")\nd <- harvest |> pivot_longer(cols = !plot, names_to = "season", values_to = "kilos")\n\nidentical(a, b) && identical(b, d)'],
  ["code","[1] TRUE"],
  ["p","A leading minus sign, or the negation operator, both mean every column except this one. That form is worth preferring when a table has forty value columns and two identifiers, because it stays correct when the value columns change."],
  ["p","Leave names_to and values_to out entirely and tidyr supplies its own defaults:"],
  ["code",'harvest |>\n  pivot_longer(cols = -plot)'],
  ["code","# A tibble: 9 × 3\n  plot  name   value\n  <chr> <chr>  <dbl>\n1 north spring    12\n2 north summer    31\n3 north autumn    18\n4 south spring     9\n5 south summer    24\n6 south autumn    21\n7 east  spring    15\n8 east  summer    28\n9 east  autumn    11"],
  ["note","name and value are fine for a quick look and bad for anything you keep, because they describe nothing. Note also which arguments are quoted: names_to and values_to name columns that do not exist yet, so they are strings, while cols refers to columns that already exist and is written bare."]
]},
{ t: "How lengthening actually works",
  body: [
  ["p","Nothing is calculated during a pivot. The values that come out are the values that went in, relabelled and rearranged. Every cell in the selected columns becomes a row of its own, and the columns you did not select are treated as identifiers, repeating once for each cell that came out of their row."],
  ["code",'long <- harvest |>\n  pivot_longer(cols = -plot, names_to = "season", values_to = "kilos")\n\ndim(harvest)\ndim(long)'],
  ["code","[1] 3 4\n[1] 9 3"],
  ["p","The arithmetic is worth holding on to. The wide table has 3 rows and 3 value columns, so the long table has 3 × 3 = 9 rows. Its width is the number of identifier columns left alone, plus two: one for the names, one for the values."],
  ["p","Read one row back out of it. The row reading north, spring, 12 says that the north plot yielded 12 kilos in spring. That fact was in the wide table as well, sitting at the intersection of a row and a column. Lengthening turns it from a position into a statement."],
  ["note","Long tables get big, and they are supposed to. A table of 500 stores by 12 months is 500 rows before pivoting and 6,000 rows after. That is not a problem, but it is a reason to pivot the columns you actually need rather than every column in the file."]
]},
{ t: "Column names that are really data",
  body: [
  ["p","The clearest sign that a table wants lengthening is column names that are values. Years, dates, month abbreviations and product codes are all data that has been promoted into headings. Here are bird counts at two feeders over three years."],
  ["code",'feeder <- tibble(\n  site   = c("hollow", "ridge"),\n  `2021` = c(14, 8),\n  `2022` = c(19, 12),\n  `2023` = c(23, 9)\n)\n\nfeeder'],
  ["code","# A tibble: 2 × 4\n  site   `2021` `2022` `2023`\n  <chr>   <dbl>  <dbl>  <dbl>\n1 hollow     14     19     23\n2 ridge       8     12      9"],
  ["p","Names that start with a digit are not valid R names, so they have to be written in backticks, both when the tibble is built and everywhere they are referred to afterwards. Those backticks are a diagnosis in themselves: a column you cannot name without quoting is usually a value wearing a heading."],
  ["code",'feeder |>\n  pivot_longer(cols = -site, names_to = "year", values_to = "count")'],
  ["code","# A tibble: 6 × 3\n  site   year  count\n  <chr>  <chr> <dbl>\n1 hollow 2021     14\n2 hollow 2022     19\n3 hollow 2023     23\n4 ridge  2021      8\n5 ridge  2022     12\n6 ridge  2023      9"],
  ["p","The years are data now. Look at the type underneath the year heading, though: it reads <chr>, not a number. Column names in R are always character strings, so anything recovered from them arrives as text. names_transform applies a function to the new column as it is built."],
  ["code",'feeder |>\n  pivot_longer(\n    cols = -site,\n    names_to = "year",\n    values_to = "count",\n    names_transform = list(year = as.integer)\n  )'],
  ["code","# A tibble: 6 × 3\n  site    year count\n  <chr>  <int> <dbl>\n1 hollow  2021    14\n2 hollow  2022    19\n3 hollow  2023    23\n4 ridge   2021     8\n5 ridge   2022    12\n6 ridge   2023     9"],
  ["p","year is <int> this time, and the numbers have shifted right in the display, which is how a tibble shows you that a column is numeric. Comparisons like year > 2021 now mean what you intended rather than comparing text."],
  ["note","This is the quiet failure of pivoting. Nothing errors. You get a perfectly good table whose year column is text, and you find out later, when arithmetic on it fails or a sort puts 10 before 9 because that is the order those characters come in."]
]},
{ t: "Two variables in one column name",
  body: [
  ["p","Sometimes a single heading carries more than one variable. This cafe records cups sold by drink and by year, and has packed both facts into every column name."],
  ["code",'cafe <- tibble(\n  branch     = c("quay", "pier"),\n  latte_2023 = c(410, 380),\n  latte_2024 = c(455, 402),\n  mocha_2023 = c(120, 96),\n  mocha_2024 = c(133, 88)\n)\n\ncafe'],
  ["code","# A tibble: 2 × 5\n  branch latte_2023 latte_2024 mocha_2023 mocha_2024\n  <chr>       <dbl>      <dbl>      <dbl>      <dbl>\n1 quay          410        455        120        133\n2 pier          380        402         96         88"],
  ["p","Handing names_to a vector of two names says the heading splits into two columns, and names_sep says where to cut it."],
  ["code",'cafe |>\n  pivot_longer(\n    cols = -branch,\n    names_to = c("drink", "year"),\n    names_sep = "_",\n    values_to = "cups"\n  )'],
  ["code","# A tibble: 8 × 4\n  branch drink year   cups\n  <chr>  <chr> <chr> <dbl>\n1 quay   latte 2023    410\n2 quay   latte 2024    455\n3 quay   mocha 2023    120\n4 quay   mocha 2024    133\n5 pier   latte 2023    380\n6 pier   latte 2024    402\n7 pier   mocha 2023     96\n8 pier   mocha 2024     88"],
  ["p","Give names_to one name instead and the heading survives intact as a single string, which leaves the two variables exactly as tangled as they were:"],
  ["code",'cafe |>\n  pivot_longer(cols = -branch, names_to = "label", values_to = "cups")'],
  ["code","# A tibble: 8 × 3\n  branch label       cups\n  <chr>  <chr>      <dbl>\n1 quay   latte_2023   410\n2 quay   latte_2024   455\n3 quay   mocha_2023   120\n4 quay   mocha_2024   133\n5 pier   latte_2023   380\n6 pier   latte_2024   402\n7 pier   mocha_2023    96\n8 pier   mocha_2024    88"],
  ["p","Ask for two names without saying where the split falls and tidyr refuses to guess:"],
  ["code",'cafe |>\n  pivot_longer(cols = -branch, names_to = c("drink", "year"), values_to = "cups")'],
  ["code","Error: If you supply multiple names in `names_to` you must also supply one of `names_sep` or `names_pattern`."],
  ["p","A heading that splits into the wrong number of pieces is the more dangerous case, because it does not stop anything. names_sep cuts at every separator it finds, so a drink whose name already contains one produces three pieces where two were promised, and tidyr keeps the first two:"],
  ["code",'menu <- tibble(\n  shop            = c("hill", "dale"),\n  tea_2024        = c(3, 6),\n  iced_latte_2024 = c(5, 2)\n)\n\nmenu |>\n  pivot_longer(cols = -shop, names_to = c("drink", "year"), names_sep = "_", values_to = "cups")'],
  ["code","Warning: Expected 2 pieces. Additional pieces discarded in 1 rows [2].\n# A tibble: 4 × 4\n  shop  drink year   cups\n  <chr> <chr> <chr> <dbl>\n1 hill  tea   2024      3\n2 hill  iced  latte     5\n3 dale  tea   2024      6\n4 dale  iced  latte     2"],
  ["p","Read what came back. The tea rows are correct. The other two now report a drink called iced sold in a year called latte, and the 2024 has been thrown away. Nothing failed; a warning was printed and a table was returned, and the table looks entirely reasonable if you are not checking."],
  ["p","When the headings are irregular, stop describing where to cut and describe what the pieces look like instead. names_pattern takes a regular expression with one capture group per name, so the split can be anchored to the part that is predictable — here, the four digits at the end:"],
  ["code",'menu |>\n  pivot_longer(\n    cols = -shop,\n    names_to = c("drink", "year"),\n    names_pattern = "(.*)_(\\\\d{4})",\n    values_to = "cups"\n  )'],
  ["code","# A tibble: 4 × 4\n  shop  drink      year   cups\n  <chr> <chr>      <chr> <dbl>\n1 hill  tea        2024      3\n2 hill  iced_latte 2024      5\n3 dale  tea        2024      6\n4 dale  iced_latte 2024      2"],
  ["note","names_sep is only trustworthy when the separator appears exactly once in every heading, and you rarely know that until you check. Treat a warning about discarded or missing pieces as a correctness problem rather than noise: it means some rows are now describing the wrong thing, and the table gives no sign of it afterwards."]
]},
{ t: "Widening data with pivot_wider()",
  body: [
  ["p","pivot_wider() is the other direction: it turns rows into columns. You need it when a single observation has been split across several rows, which usually shows up as one column holding the name of a measurement and another holding its number."],
  ["code",'readings <- tibble(\n  station  = c("alpha", "alpha", "beta", "beta", "gamma", "gamma"),\n  measure  = c("temp", "humidity", "temp", "humidity", "temp", "humidity"),\n  reading  = c(18.5, 62.4, 21.1, 58.2, 16.9, 71.3)\n)\n\nreadings'],
  ["code","# A tibble: 6 × 3\n  station measure  reading\n  <chr>   <chr>      <dbl>\n1 alpha   temp        18.5\n2 alpha   humidity    62.4\n3 beta    temp        21.1\n4 beta    humidity    58.2\n5 gamma   temp        16.9\n6 gamma   humidity    71.3"],
  ["p","Every station appears twice, so a row here is not an observation of a station — it is half of one. The reading column is also doing double duty, holding temperatures and humidities in the same place, which means the column is not one variable. names_from says which column supplies the new headings and values_from says which supplies the cells."],
  ["code",'readings |>\n  pivot_wider(names_from = measure, values_from = reading)'],
  ["code","# A tibble: 3 × 3\n  station  temp humidity\n  <chr>   <dbl>    <dbl>\n1 alpha    18.5     62.4\n2 beta     21.1     58.2\n3 gamma    16.9     71.3"],
  ["p","The two functions undo one another. Widening and then lengthening gets the original rows back, in a different order:"],
  ["code",'readings |>\n  pivot_wider(names_from = measure, values_from = reading) |>\n  pivot_longer(cols = -station, names_to = "measure", values_to = "reading") |>\n  arrange(station, measure)'],
  ["code","# A tibble: 6 × 3\n  station measure  reading\n  <chr>   <chr>      <dbl>\n1 alpha   humidity    62.4\n2 alpha   temp        18.5\n3 beta    humidity    58.2\n4 beta    temp        21.1\n5 gamma   humidity    71.3\n6 gamma   temp        16.9"],
  ["p","When a station is missing one of its measurements there is no value to put in the cell, so tidyr fills it with NA. The table below has no humidity row for beta:"],
  ["code",'gaps <- tibble(\n  station = c("alpha", "alpha", "beta", "gamma", "gamma"),\n  measure = c("temp", "humidity", "temp", "temp", "humidity"),\n  reading = c(18.5, 62.4, 21.1, 16.9, 71.3)\n)\n\ngaps |>\n  pivot_wider(names_from = measure, values_from = reading)'],
  ["code","# A tibble: 3 × 3\n  station  temp humidity\n  <chr>   <dbl>    <dbl>\n1 alpha    18.5     62.4\n2 beta     21.1     NA  \n3 gamma    16.9     71.3"],
  ["note","That NA means no row existed for this combination, which is not the same as measured, and the value is missing. Widening makes gaps explicit that were merely absent before. If zero is the honest answer for a missing combination, say so with values_fill rather than leaving a reader to guess."]
]},
{ t: "Choosing a direction, and what goes wrong",
  body: [
  ["p","The direction question answers itself once you can say what one observation is. Write that sentence down first. If a variable is spread across several column names, lengthen. If one observation is spread across several rows, widen. A messy table sometimes needs both, in that order."],
  ["p","pivot_longer() has no useful default for cols, so leaving it out selects nothing:"],
  ["code",'harvest |> pivot_longer(names_to = "season", values_to = "kilos")'],
  ["code","Error: `cols` must select at least one column."],
  ["p","Lengthening stacks the selected columns on top of each other, which means they have to hold compatible types. Fold a number column together with a text column and tidyr stops rather than quietly turning the numbers into strings:"],
  ["code",'mixed <- tibble(\n  id    = c("a", "b"),\n  score = c(10, 20),\n  grade = c("pass", "fail")\n)\n\nmixed |>\n  pivot_longer(cols = -id, names_to = "field", values_to = "value")'],
  ["code","Error: Can't combine `score` <double> and `grade` <character>."],
  ["p","Widening has a failure of its own. If a station and measurement pair turns up twice, two values are competing for one cell, and tidyr will not pick a winner:"],
  ["code",'dupes <- tibble(\n  station = c("alpha", "alpha", "beta"),\n  measure = c("temp", "temp", "temp"),\n  reading = c(18.5, 19.2, 21.1)\n)\n\ndupes |>\n  pivot_wider(names_from = measure, values_from = reading)'],
  ["code","Warning: Values from `reading` are not uniquely identified; output will contain\nlist-cols.\n• Use `values_fn = list` to suppress this warning.\n• Use `values_fn = {summary_fun}` to summarise duplicates.\n• Use the following dplyr code to identify duplicates.\n  {data} |>\n  dplyr::summarise(n = dplyr::n(), .by = c(station, measure)) |>\n  dplyr::filter(n > 1L)\n# A tibble: 2 × 2\n  station temp     \n  <chr>   <list>   \n1 alpha   <dbl [2]>\n2 beta    <dbl [1]>"],
  ["p","The message is telling you something true about the data rather than about your code: the duplicates were always there, and the long layout was hiding them. Either they are an error to go and fix, or they are genuine repeated measurements, in which case you have to say how to combine them."],
  ["code",'dupes |>\n  pivot_wider(names_from = measure, values_from = reading, values_fn = mean)'],
  ["code","# A tibble: 2 × 2\n  station  temp\n  <chr>   <dbl>\n1 alpha    18.8\n2 beta     21.1"],
  ["note","A list-column coming out of pivot_wider() is always a duplicate-key report, never a formatting quirk. Reach for values_fn only after checking that the duplicates are real repeats — if they are two conflicting records of one reading, averaging them buries the problem instead of fixing it."]
]},
{ t: "Summary",
  body: [
  ["p","Tidy data is a layout defined by three rules: one variable per column, one observation per row, one value per cell. It is the shape the tidyverse expects, which is why reaching it early makes everything downstream shorter. pivot_longer() folds columns into rows when a variable has been stored in the column names, driven by cols, names_to and values_to. pivot_wider() spreads rows into columns when an observation has been split across rows, driven by names_from and values_from. Watch the type of any column recovered from headings, and read the duplicate warning from pivot_wider() as a fact about the data rather than a nuisance to silence."],
  ["p","Answer the practice questions from memory before revealing the answers, then clear the graded exercises below. The next chapter is R Chapter 6, Workflow: scripts and projects — moving out of the console and into files that can be rerun from a clean start."]
]}
],
questions: [
{ q:"What are the three rules of tidy data?",
  a:"Every column is a variable, every row is an observation, and every cell holds a single value. A table that breaks any of them makes dplyr and ggplot2 harder to use than they need to be." },
{ q:"The harvest table has the columns plot, spring, summer and autumn. Which rules does it break, and which variables are hidden?",
  a:"Season is a variable stored in the column names instead of in a column, so not every column is a variable; and each row carries three observations rather than one. The two hidden variables are season and kilos." },
{ q:"Which three arguments of pivot_longer() do the main work, and which of them are quoted?",
  a:"cols selects the columns to fold, names_to names the new column for the old headings, and values_to names the new column for the old cells. names_to and values_to are quoted because those columns do not exist yet; cols refers to existing columns and is written bare." },
{ q:"Folding 3 value columns out of a 3-row table gives a result of what size?",
  a:"9 rows and 3 columns. One row per cell, 3 times 3, and a width of one untouched identifier column plus one for the names and one for the values." },
{ q:"What do names_to and values_to default to when you leave them out?",
  a:"name and value. They are fine for a quick look at the data and bad for anything you keep, because neither describes what it holds." },
{ q:"After lengthening a table whose columns were named 2021, 2022 and 2023, what type is the new year column, and why?",
  a:"Character. Column names in R are always strings, so any variable recovered from them comes back as text. names_transform = list(year = as.integer) converts it as the column is built." },
{ q:"A column is named latte_2023. How do you split it into a drink column and a year column?",
  a:"Pass a vector of two names to names_to, then tell tidyr where to cut with names_sep. Supplying two names without names_sep or names_pattern is an error, because tidyr will not guess where the split falls." },
{ q:"Which two arguments does pivot_wider() need, and what does each one do?",
  a:"names_from, the column whose values become the new column headings, and values_from, the column whose values fill the new cells." },
{ q:"pivot_wider() puts an NA in a cell. What does that NA mean?",
  a:"No row existed in the long table for that combination of identifier and heading. Widening makes explicit a gap that was merely absent before, which is not the same as a value that was measured and found missing." },
{ q:"pivot_wider() warns that values are not uniquely identified and hands back a list-column. What has it found, and what are the two possible responses?",
  a:"Two or more rows share the same identifier and heading, so several values are competing for one cell. Either the duplicates are a data error to go and fix, or they are genuine repeated measurements and values_fn has to say how to combine them." }
],
exercises: [
{ c:"tidy data", t:"Fold the rehearsal ledger", book:"r05",
  b:"Attach tidyr and dplyr, then build a tibble named rooms with room = c(\"attic\", \"cellar\", \"loft\"), april = c(12, 7, 19) and may = c(15, 11, 4). Lengthen it so the month headings become a month column and the numbers become an hours column, arrange by room and then month, and print the result.",
  o:"# A tibble: 6 × 3\n  room   month hours\n  <chr>  <chr> <dbl>\n1 attic  april    12\n2 attic  may      15\n3 cellar april     7\n4 cellar may      11\n5 loft   april    19\n6 loft   may       4",
  h:["The month names are sitting in the column headings, which means a variable is stored in the wrong place. That is the signal to lengthen rather than widen.",
     "pivot_longer() needs three things: which columns to fold up, what to call the column of old headings, and what to call the column of old values. The last two are quoted because they do not exist yet.",
     "Select the value columns with cols = -room, set names_to and values_to to the two column names the question asks for, then pipe into arrange(room, month) and print."]},
{ c:"tidy data", t:"Spread the shift log", book:"r05",
  b:"Attach tidyr and dplyr, then build a tibble named shifts with crew = c(\"red\", \"red\", \"blue\", \"blue\"), task = c(\"setup\", \"teardown\", \"setup\", \"teardown\") and minutes = c(35, 20, 41, 26). Each crew is split over two rows, so a row is half an observation. Widen it so every crew is one row with a setup column and a teardown column, arrange by crew, and print the result.",
  o:"# A tibble: 2 × 3\n  crew  setup teardown\n  <chr> <dbl>    <dbl>\n1 blue     41       26\n2 red      35       20",
  h:["One observation here is one crew, and it currently occupies two rows. That is the direction that calls for widening.",
     "pivot_wider() has to be told which column supplies the new headings and which column supplies the numbers that fill them.",
     "The headings come from the task column and the cells from the minutes column; pipe the result into arrange(crew) and print it."]},
{ c:"tidy data", t:"Split the headings", book:"r05",
  b:"Attach tidyr and dplyr, then build a tibble named sales with shop = c(\"hill\", \"dale\"), tea_mon = c(31, 24), tea_tue = c(28, 30), cocoa_mon = c(9, 12) and cocoa_tue = c(14, 7). Every heading except shop packs a drink and a day together. Lengthen it into shop, drink, day and units columns, arrange by shop, then drink, then day, and print the result.",
  o:"# A tibble: 8 × 4\n  shop  drink day   units\n  <chr> <chr> <chr> <dbl>\n1 dale  cocoa mon      12\n2 dale  cocoa tue       7\n3 dale  tea   mon      24\n4 dale  tea   tue      30\n5 hill  cocoa mon       9\n6 hill  cocoa tue      14\n7 hill  tea   mon      31\n8 hill  tea   tue      28",
  h:["Each heading holds two variables, so the pivot has to produce two columns out of the names rather than one.",
     "names_to accepts a vector of column names. Once it gets more than one, tidyr has to be told where the heading splits, or it stops with an error.",
     "Pass names_to = c(\"drink\", \"day\"), give names_sep the single character the headings use between the two parts, and finish with arrange(shop, drink, day)."]},
{ c:"grouping & summaries", t:"Total after tidying", book:"r05",
  b:"Attach tidyr and dplyr, then build a tibble named beds with bed = c(\"a\", \"b\", \"c\"), jan = c(4, 6, 5) and feb = c(9, 2, 7). Lengthen it so the month headings become a month column and the numbers become a crates column, then report the total crates for each month in a column named total, arranged by month, and print the result.",
  o:"# A tibble: 2 × 2\n  month total\n  <chr> <dbl>\n1 feb      18\n2 jan      15",
  h:["The totals are wanted per month, and month is not a column yet. Fix the shape before trying to summarise.",
     "Once the table is long, month is an ordinary column, so grouping by it and summing the other column is the same job you would do on any tidy table.",
     "Lengthen with pivot_longer(), then group_by() the month column, then summarise() a total column built with sum(), then arrange(month)."]}
]
};
