/* Practice Log book — R Chapter 6: Workflow: scripts and projects.
   Original lesson text following the chapter-by-chapter curriculum of
   "R for Data Science" (2nd ed.) by Hadley Wickham, Mine Cetinkaya-Rundel,
   and Garrett Grolemund. Read the original chapter free at the src link below.
   Every shown output was captured by executing the code in WebR, not written from memory. */
window.BOOK_R = window.BOOK_R || { chapters: {} };
window.BOOK_R.chapters.r06 = {
n: 6,
title: "Workflow: scripts and projects",
src: "https://r4ds.hadley.nz/workflow-scripts.html",
blurb: "Scripts instead of console typing, code that survives a restart, and paths that still work on someone else's computer.",
pkgs: [],
sections: [
{ t: "The console and the script",
  body: [
  ["p","Everything so far could have been typed straight into the console: one line, one answer, then the next. That is fine while you are poking at data, but the console forgets. Scroll back far enough and the line you wanted is gone, and even when it is still on screen, the order you typed things in is rarely the order that would rebuild the result. A script fixes both problems. It is a plain text file, saved with a .R extension, holding the lines of R you want to keep, in the order that makes them work."],
  ["note","The workflow this chapter describes happens in RStudio, on a desktop computer: an editor pane, a Files pane, project files ending in .Rproj, and a working directory pointing somewhere on your own disk. None of that exists here. This app runs R as WebR inside your browser, with no IDE, no project files, and a small temporary filesystem that is built fresh with the runtime and is not your computer's disk. What does transfer, and what the runnable parts of this chapter drill, is the habit underneath: write code that runs top to bottom from a clean state and leans on nothing you cannot see."],
  ["p","A script is not a new kind of R. The lines are the same lines you would have typed anyway; what changes is that they are saved, ordered, and rerunnable. Three lines are already a script:"],
  ["code","counts <- c(12, 31, 7, 22)\ntotal <- sum(counts)\ntotal"],
  ["code","[1] 72"],
  ["p","R works through that file from the first line to the last, exactly as if you had typed each line into the console in that order. Nothing about the file is clever. The order is the whole point of it, and the console is the place where that order quietly stops being true."]
]},
{ t: "Running a script top to bottom",
  body: [
  ["p","In RStudio the editor and the console sit in the same window, and you move code between them with the keyboard. Ctrl+Enter — Cmd+Enter on a Mac — runs the current line or the current selection in the console and steps down to the next line, so you can walk through a script a statement at a time. Ctrl+Shift+S sources the whole file: R runs it start to finish without stopping to show you each step."],
  ["p","Sourcing is the honest test. Stepping line by line lets you skip a line, run one twice, or double back and fix something in the console instead of in the file, and none of that is recorded. Sourcing runs exactly what is written, in exactly the order it is written, which is the only version of your script that anyone else will ever run."],
  ["p","Order is not a style preference. R evaluates each line with only the results of the lines above it, so a line that uses a name before the line that creates it fails outright. Here the two statements are simply the wrong way round:"],
  ["code","rm(list = ls())\ntotal <- sum(counts)\ncounts <- c(12, 31, 7, 22)"],
  ["code","Error: object 'counts' not found"],
  ["p","Swap them and nothing else changes, because nothing else was wrong:"],
  ["code","rm(list = ls())\ncounts <- c(12, 31, 7, 22)\ntotal <- sum(counts)\ntotal"],
  ["code","[1] 72"],
  ["note","The console will happily run your lines in any order, and that is the trap. A script that only works because you ran line 8 before line 3 half an hour ago looks perfect on your screen and fails for everybody else, including you next Tuesday. If you have been experimenting, source the whole file before you believe it."]
]},
{ t: "What the editor tells you while you type",
  body: [
  ["p","RStudio reads your script as you write it and marks problems in the left margin of the editor. An unclosed bracket, a missing comma inside a function call, a quote that never ends, a name you assigned and then never used — each gets a small icon, and hovering over the icon explains what it found. The line below earns one, because the call to c() is closed but the call to mean() is not:"],
  ["code","# RStudio marks this line in the margin: the mean( bracket is never closed.\naverage <- mean(c(3, 8, 1)"],
  ["p","The editor helps in two more ways worth knowing about. Pressing Tab partway through a name completes it, which cuts down on the misspelling that produces a not-found error at run time. And typing an opening bracket or quote inserts the closing one for you, so the unbalanced-bracket warning above is a mistake you mostly make by deleting, not by typing."],
  ["p","Nothing in this section shows output, and that is deliberate: these are the editor's messages, not R's. R never sees the file until you run it, and this app has no editor pane to draw a margin icon in. On a desktop, treat every one of those icons as a line to fix before sourcing."],
  ["note","The editor catches shapes, not meanings. A script with no warning markers at all can still compute the wrong number, sort by the wrong column, or overwrite the file it was supposed to read. Clean margins mean the code will probably run, not that it is right."]
]},
{ t: "Naming files so they sort themselves",
  body: [
  ["p","File names are part of your code's interface, and three rules cover almost all of it. Keep them machine readable: no spaces, no punctuation beyond dashes and underscores, one consistent case. Keep them human readable: the name should say what the file holds. And make them sort into the order you actually want, because every file listing you ever see is sorted by name."],
  ["p","That last rule is where dates earn their keep. Written year first, then month, then day, with leading zeros, a date sorts chronologically for free, because alphabetical order and calendar order become the same order:"],
  ["code","sort(c(\"2026-02-11-counts.csv\", \"2026-01-09-counts.csv\", \"2026-01-30-counts.csv\"))"],
  ["code","[1] \"2026-01-09-counts.csv\" \"2026-01-30-counts.csv\" \"2026-02-11-counts.csv\""],
  ["p","Write the same three dates the way people say them out loud and the sort is worthless — the ninth of January lands last, because the character 9 sorts after the characters 1 and 3:"],
  ["code","sort(c(\"11-02-2026 counts.csv\", \"9-1-2026 counts.csv\", \"30-01-2026 counts.csv\"))"],
  ["code","[1] \"11-02-2026 counts.csv\" \"30-01-2026 counts.csv\" \"9-1-2026 counts.csv\""],
  ["p","Scripts meant to run in a fixed order get numbered instead of dated, and the same digit-by-digit comparison applies. Numbering without leading zeros breaks as soon as you reach ten files:"],
  ["code","sort(c(\"1-load.R\", \"2-clean.R\", \"10-report.R\"))"],
  ["code","[1] \"1-load.R\"    \"10-report.R\" \"2-clean.R\""],
  ["p","Pad the numbers to a fixed width and the listing matches the running order again:"],
  ["code","sort(c(\"01-load.R\", \"02-clean.R\", \"10-report.R\"))"],
  ["code","[1] \"01-load.R\"   \"02-clean.R\"  \"10-report.R\""],
  ["note","Sorting is character by character, not by meaning. R is comparing text: it has no idea that 9 is a smaller number than 11, or that 2026-01-30 is a date. The fix is always to write the name so that plain text comparison already gives the order you want."]
]},
{ t: "The source of truth is the script",
  body: [
  ["p","Two things exist while you work: the script, which is a file on disk, and the environment, which is the set of objects R is currently holding in memory. It is worth deciding early which of the two you trust. The answer is the script. The environment is scratch space — the result of running the script, plus whatever else you typed and forgot about — and treating it as something to protect is how workflows go bad."],
  ["p","ls() lists what the environment currently holds, and rm(list = ls()) empties it. On a clean environment, ls() has nothing to report and says so:"],
  ["code","rm(list = ls())\nls()"],
  ["code","character(0)"],
  ["p","Assign two names and they show up, alphabetically, as a character vector:"],
  ["code","rm(list = ls())\nreadings <- c(4, 9, 2)\nthreshold <- 5\nls()"],
  ["code","[1] \"readings\"  \"threshold\""],
  ["p","Now the point of all this. Code that used one of those names works while the name is in memory and fails the moment it is not — and the failure is not subtle:"],
  ["code","rm(list = ls())\nmean(readings)"],
  ["code","Error: object 'readings' not found"],
  ["p","exists() asks the same question without the error, which is useful when you are trying to work out whether a script is standing on its own or leaning on something:"],
  ["code","rm(list = ls())\nexists(\"readings\")"],
  ["code","[1] FALSE"],
  ["p","On a desktop, RStudio can save your environment to a hidden .RData file when you quit and reload it when you start, which sounds helpful and is not: it hides exactly this failure, because the leftovers come back before you notice you needed them. Turn it off in Tools then Global Options — never save the workspace, never restore it — and restart R often with Ctrl+Shift+F10, sourcing your script again each time. A script that survives a restart is a script that works."],
  ["note","The mistake to expect is not writing broken code. It is writing code that works, on your machine, this afternoon, because a variable you defined an hour ago is still sitting in memory. Nothing warns you. The first person to find out is whoever runs the file next from a clean start, and often that is you."]
]},
{ t: "Code that carries what it needs",
  body: [
  ["p","The habit that makes a script survive a restart is small: every piece of code should be handed what it needs rather than reaching out for it. Functions are where this goes wrong most often, because a function that mentions a name it does not define will happily find one in the environment outside it. This runs, and the answer is correct:"],
  ["code","rm(list = ls())\nthreshold <- 5\nover_threshold <- function(values) values[values > threshold]\nover_threshold(c(2, 8, 5))"],
  ["code","[1] 8"],
  ["p","It is still the wrong function, and removing the one line it silently depended on shows why. Nothing about the definition changed:"],
  ["code","rm(list = ls())\nover_threshold <- function(values) values[values > threshold]\nover_threshold(c(2, 8, 5))"],
  ["code","Error: object 'threshold' not found"],
  ["p","Make the hidden dependency a parameter and the function stops caring about the environment entirely. It now takes everything it uses, which also means the caller can see what it uses:"],
  ["code","rm(list = ls())\nover_threshold <- function(values, threshold) values[values > threshold]\nover_threshold(c(2, 8, 5), 5)"],
  ["code","[1] 8"],
  ["p","source() runs a file of R code as if you had typed it, which makes it the cheapest way to check that a file really does stand alone. The block below writes a two-line script into the working directory, empties the environment first so nothing can be inherited, sources the file, and then asks what the file left behind:"],
  ["code","rm(list = ls())\nwriteLines(c(\n  'greet <- function(name) paste0(\"Hello, \", name)',\n  'print(greet(\"Mira\"))'\n), \"greet.R\")\nsource(\"greet.R\")\nls()"],
  ["code","[1] \"Hello, Mira\"\n[1] \"greet\""],
  ["p","Read the two output lines as the two things worth knowing. The first came from the script running, so the file did everything it needed on its own. The second is the environment afterwards, holding exactly what the file created and nothing else — which is what a clean start looks like."],
  ["note","A function that reads a variable from outside itself is not an error and never will be, so no tool will flag it. It only fails later, in a different session, with a message about a name that has nothing obvious to do with the function you were calling. Give the function a parameter the moment you notice it reaching."]
]},
{ t: "Projects and the working directory",
  body: [
  ["p","An analysis is never one file. It is scripts, raw data you did not create, cleaned data you did, and outputs — and the moment those live in different corners of your computer, the code that ties them together stops being movable. The fix is boring and effective: one folder per analysis, with everything inside it."],
  ["p","RStudio formalises that folder as a project. Creating one puts a small file with an .Rproj extension in the folder, and opening that file starts a fresh R session whose working directory is the folder itself. The working directory is the place R measures file names from, so setting it once, automatically, at the top of every session, is most of what a project buys you. A typical layout, all of it under a single folder:"],
  ["code","bike-counts/\n  bike-counts.Rproj\n  data/\n    2026-01-09-counts.csv\n    2026-01-30-counts.csv\n  R/\n    01-load.R\n    02-clean.R\n    03-report.R\n  output/"],
  ["p","That listing has no output because it is a folder, not code, and because .Rproj files exist only in RStudio on a desktop. getwd() is the part you can run anywhere — it reports the working directory of the session you are in right now. In this app the answer is not a folder on your computer:"],
  ["code","getwd()"],
  ["code","[1] \"/home/web_user\""],
  ["p","That path lives in the browser sandbox WebR builds for itself. Its root holds a handful of directories and none of your files, which is easy enough to confirm:"],
  ["code","list.files(\"/\")"],
  ["code","[1] \"dev\"  \"etc\"  \"home\" \"proc\" \"tmp\"  \"usr\"  \"var\""],
  ["p","And a path from a real computer is simply not there, whatever it says on the machine it came from:"],
  ["code","file.exists(\"/Users/mira/Documents/counts.csv\")"],
  ["code","[1] FALSE"],
  ["note","setwd() changes the working directory from inside a script, and a setwd() line at the top of a file is a reliable sign that the file is not portable — it names one folder on one computer, so it is wrong everywhere else. If a project sets the directory for you, no script needs to set it at all."]
]},
{ t: "Relative and absolute paths",
  body: [
  ["p","A path is absolute when it starts from the root of the filesystem and names every folder down to the file: /Users/mira/Documents/counts.csv on a Mac, C:\\Users\\mira\\Documents\\counts.csv on Windows. A path is relative when it starts from the working directory instead, which makes data/counts.csv mean the same file only if you are standing in the right place. Projects exist to make sure you always are."],
  ["p","Absolute paths are the standard way to break a script for everybody else. Nothing about the code is wrong; the folder just does not exist on the machine running it, and R says so twice — once as a warning from the connection, once as the error that stops the script:"],
  ["code","readLines(\"/Users/mira/Documents/counts.csv\")"],
  ["code","Warning in file(con, \"r\") :\n  cannot open file '/Users/mira/Documents/counts.csv': No such file or directory\nError: cannot open the connection"],
  ["p","A relative path is just a file name measured from wherever you are, so the same two lines work in a project folder, on a colleague's laptop, and in this app. writeLines() sends a character vector to a file, one element per line, and readLines() brings it back:"],
  ["code","writeLines(c(\"north,12\", \"south,31\", \"east,7\"), \"readings.txt\")\ncat(readLines(\"readings.txt\"), sep = \"\\n\")"],
  ["code","north,12\nsouth,31\neast,7"],
  ["p","The file is real for as long as the runtime lives, and file.exists() will confirm it. Close the tab and the whole filesystem goes with it, which is a difference from a desktop worth remembering before you rely on anything you wrote:"],
  ["code","file.exists(\"readings.txt\")"],
  ["code","[1] TRUE"],
  ["p","When you do need to assemble a path, build it rather than typing it. file.path() joins pieces with the right separator for the system, and basename() and dirname() split a path back into the file and the folder that holds it:"],
  ["code","basename(\"data/raw-counts.csv\")\ndirname(\"data/raw-counts.csv\")\nfile.path(\"data\", \"raw-counts.csv\")"],
  ["code","[1] \"raw-counts.csv\"\n[1] \"data\"\n[1] \"data/raw-counts.csv\""],
  ["note","Writing a relative path that starts with a slash makes it absolute again — \"/data/counts.csv\" is a folder at the root of the disk, not the data folder next to your script. Leave the leading slash off and let the working directory do its job."]
]},
{ t: "Summary",
  body: [
  ["p","This chapter was about where code lives rather than what it does. Scripts hold the lines worth keeping, in the order that makes them work, and sourcing a file top to bottom is the only run that tells the truth. File names should be machine readable, human readable, and sortable, which is why dates go year first and script numbers get leading zeros. The environment is scratch space, not something to preserve: ls() shows what is in it, rm(list = ls()) empties it, and code that only works because of what is left in it is broken code that has not failed yet. Functions should take what they use as parameters. Projects put one analysis in one folder and set the working directory to it, so every path in your scripts can be relative, and relative paths are the ones that still work on somebody else's computer."],
  ["p","Answer the practice questions from memory before revealing the answers, then clear the graded exercises below. The next chapter is data import — getting real files, rather than vectors you typed yourself, into R."]
]}
],
questions: [
{ q:"What does a script give you that the console does not?",
  a:"A record and an order. The console keeps only a scrollback that eventually disappears, and the order you typed things in is rarely the order that rebuilds the result. A script is a saved .R file holding the lines you want to keep, in the order that makes them run." },
{ q:"In RStudio, what is the difference between Ctrl+Enter and Ctrl+Shift+S?",
  a:"Ctrl+Enter runs the current line or selection in the console and moves down one line, so you step through a script piece by piece. Ctrl+Shift+S sources the whole file, running it start to finish. Sourcing is the honest test, because it runs exactly what is written in exactly the written order." },
{ q:"Why does this script fail: total <- sum(counts) on line 1, counts <- c(12, 31, 7, 22) on line 2?",
  a:"R evaluates each line using only the lines above it, so line 1 asks for counts before line 2 creates it. The result is Error: object 'counts' not found. Swapping the two lines fixes it." },
{ q:"RStudio shows no warning markers in the margin of your script. What does that tell you, and what does it not?",
  a:"It tells you the shapes are fine — brackets balanced, quotes closed, commas present — so the file will probably run. It says nothing about whether the code is correct. The editor never sees your meaning, so a clean margin and a wrong answer live together comfortably." },
{ q:"Why does writing a date as 2026-01-09 rather than 9-1-2026 matter for a file name?",
  a:"Sorting compares text character by character, so year-month-day with leading zeros makes alphabetical order and calendar order the same order. Written the other way, 9-1-2026 sorts after 30-01-2026, because the character 9 comes after 3." },
{ q:"You have ten scripts named 1-load.R through 10-report.R. What goes wrong, and what is the fix?",
  a:"Sorted as text, 10-report.R lands between 1-load.R and 2-clean.R, so the listing no longer matches the running order. Pad the numbers to a fixed width — 01-load.R, 02-clean.R, 10-report.R — and text order matches number order again." },
{ q:"What do ls() and rm(list = ls()) do, and what does ls() print on a clean environment?",
  a:"ls() lists the names currently held in the environment; rm(list = ls()) removes all of them. On a clean environment ls() prints character(0), the empty character vector." },
{ q:"Why should RStudio be set to never save or restore the workspace?",
  a:"Saving the environment to .RData and reloading it hides scripts that depend on leftover objects, because the leftovers reappear before you notice they were needed. With saving off and frequent restarts, a script either rebuilds everything it uses or fails immediately, which is the point." },
{ q:"This function runs and returns the right answer: over_threshold <- function(values) values[values > threshold]. What is wrong with it?",
  a:"It never defines threshold, so it is reading one from the environment outside it. That is not an error and nothing will flag it — but in a fresh session the call fails with Error: object 'threshold' not found. Make the hidden dependency a parameter: function(values, threshold)." },
{ q:"What is the difference between an absolute and a relative path, and why do projects favour relative ones?",
  a:"An absolute path starts at the root of the filesystem and names every folder down to the file, so it describes one computer only. A relative path is measured from the working directory. An RStudio project sets the working directory to the project folder at startup, so relative paths inside it resolve correctly on any machine the folder is copied to." }
],
exercises: [
{ c:"vectors", t:"Names that sort themselves", book:"r06",
  b:"Given file_names <- c(\"2026-02-11-counts.csv\", \"2026-01-09-counts.csv\", \"2026-01-30-counts.csv\"), print the file names in sorted order, then print the earliest file name on a line of its own.",
  o:"[1] \"2026-01-09-counts.csv\" \"2026-01-30-counts.csv\" \"2026-02-11-counts.csv\"\n[1] \"2026-01-09-counts.csv\"",
  h:["The vector is in the order it was typed, and that order means nothing. Something has to put it in a useful one.",
     "sort() returns a character vector in alphabetical order — which, for dates written year first, is also chronological order.",
     "Keep the sorted vector under a name of its own so you can use it twice: print it, then print its first element."]},
{ c:"functions", t:"A function that needs nothing", book:"r06",
  b:"Write a function above(values, limit) that returns only the elements of values greater than limit — it must not mention any name defined outside itself. Call it with the vector c(3, 12, 7, 20) and a limit of 8, and print the result.",
  o:"[1] 12 20",
  h:["Two parameters, and a body short enough to fit on one line.",
     "Keeping the elements that pass a test is logical subsetting: a comparison goes inside the square brackets, and R keeps the positions where it is TRUE.",
     "The body is a single subsetting expression that uses both parameters and nothing else. The last line calls the function with the vector and 8, and lets the returned vector print."]},
{ c:"vectors", t:"A relative path round trip", book:"r06",
  b:"Write the three lines north,12 then south,31 then east,7 to a file named station-readings.txt in the working directory, using a relative path. Then read the file back and print its contents as three plain lines, with no quotes and no [1] index markers. Running your code a second time must print exactly the same thing.",
  o:"north,12\nsouth,31\neast,7",
  h:["Two steps: put the lines into the file, then get them back out. A relative path here is just the file name on its own.",
     "writeLines() takes a character vector and a file name, one element per line; readLines() hands you a character vector back. Printing a character vector shows quotes and index markers, so print it another way.",
     "Build the vector with c() and write it with writeLines — the write replaces the file every time, which is what keeps a rerun identical. Then pass readLines() straight to cat(), whose sep argument decides what goes between the elements."]},
{ c:"data frames", t:"Save it, load it, print it", book:"r06",
  b:"Given stations <- data.frame(station = c(\"north\", \"south\", \"east\"), count = c(12, 31, 7)), save it to station-counts.csv in the working directory using a relative path and with no row-number column, then read that file back and print the data frame you get. Running your code a second time must print exactly the same thing.",
  o:"  station count\n1   north    12\n2   south    31\n3    east     7",
  h:["Three steps: the frame you were given, a file written from it, and a frame read back out of that file.",
     "write.csv() and read.csv() are the pair. write.csv() adds a column of row numbers by default, and the frame you read back would then have an extra column.",
     "Give write.csv() the frame, the file name, and the argument that suppresses row names. Then let the value returned by read.csv() print itself."]}
]
};
