/* Practice Log book — R Chapter 7: Data import.
   Original lesson text following the chapter-by-chapter curriculum of
   "R for Data Science" (2nd ed.) by Hadley Wickham, Mine Cetinkaya-Rundel,
   and Garrett Grolemund. Read the original chapter free at the src link below.
   Every shown output was captured by executing the code in WebR, not written from memory. */
window.BOOK_R = window.BOOK_R || { chapters: {} };
window.BOOK_R.chapters.r07 = {
n: 7,
title: "Data import",
src: "https://r4ds.hadley.nz/data-import.html",
blurb: "Turning a file on disk into a tibble with readr: what read_csv guesses, how to correct it, and how to write results back out.",
pkgs: ["readr", "tibble"],
sections: [
{ t: "Reading a csv file",
  body: [
  ["p","Every data set so far has been one you typed. Real work starts with a file somebody else produced, and the commonest shape that file takes is csv: comma separated values, one row per line, with the first line usually naming the columns. Nothing in this app downloads files, so every file in this chapter is one you write yourself before you read it. That keeps each example self-contained, and it puts the raw text in front of you so you can see exactly what the reader is looking at."],
  ["code","library(readr)\nwriteLines(c(\"station,reading,taken_on\",\n             \"north,12,2026-03-01\",\n             \"south,31,2026-03-01\",\n             \"east,7,2026-03-02\"), \"readings.csv\")\ncat(readLines(\"readings.csv\"), sep = \"\\n\")"],
  ["code","station,reading,taken_on\nnorth,12,2026-03-01\nsouth,31,2026-03-01\neast,7,2026-03-02"],
  ["p","writeLines() put four lines of plain text on disk and cat() printed them back with no quotes and no index markers, which is what the file really contains. There is nothing clever in it: commas separate fields, the first line is a header, the other three are rows. Every csv reader in every language is looking at exactly this."],
  ["p","read_csv() turns that text into a tibble. Running it produces two things on screen, and only one of them is your data."],
  ["code","readings <- read_csv(\"readings.csv\")\nreadings"],
  ["code","Rows: 3 Columns: 3\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr  (1): station\ndbl  (1): reading\ndate (1): taken_on\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n# A tibble: 3 × 3\n  station reading taken_on  \n  <chr>     <dbl> <date>    \n1 north        12 2026-03-01\n2 south        31 2026-03-01\n3 east          7 2026-03-02"],
  ["p","The block above the tibble is a message, not a failure. readr had to decide what type each column holds, and it reports every decision so you can check it before you build anything on top. Here station came out chr, short for character; reading came out dbl, short for double, which is R's ordinary number; and taken_on came out date, because the values matched a date format. Reading those three lines is the cheapest bug prevention in this chapter."],
  ["note","The message is written to the error stream rather than the output stream, which is why some consoles show it in red. Red does not mean broken here. If you want it gone, silence it on purpose rather than training yourself to look past it — a message you always ignore is a message you will also ignore on the day it says something surprising."],
  ["code","read_csv(\"readings.csv\", show_col_types = FALSE)"],
  ["code","# A tibble: 3 × 3\n  station reading taken_on  \n  <chr>     <dbl> <date>    \n1 north        12 2026-03-01\n2 south        31 2026-03-01\n3 east          7 2026-03-02"],
  ["p","The tibble on its own is easier to read, and the decisions are still recoverable whenever you want them. spec() takes a tibble that came from readr and prints the column specification it was built with, written as R code you could paste back into the call."],
  ["code","spec(readings)"],
  ["code","cols(\n  station = col_character(),\n  reading = col_double(),\n  taken_on = col_date(format = \"\")\n)"],
  ["note","Paths in this app are relative to the working directory, which is /home/web_user. That is where writeLines() put readings.csv and where read_csv() went looking for it. Ask for a plain file name that is not there and read_csv() names the directory it searched, which is the fastest way to find out where you actually are. A path copied out of a desktop script — anything beginning with C:/ or /Users/ — names a place that does not exist inside this runtime, and you get the blunter message that the file does not exist."]
]},
{ t: "When the first row is not the header",
  body: [
  ["p","read_csv() assumes the first line of the file names the columns. Files in the wild break that assumption two ways: they carry notes above the header, or they have no header at all. Both cases still produce a tibble, which is exactly why the failure is easy to walk past."],
  ["code","writeLines(c(\"# Sensor export v3\",\n             \"# generated overnight\",\n             \"station,reading\",\n             \"north,12\",\n             \"south,31\"), \"export.csv\")\nread_csv(\"export.csv\", show_col_types = FALSE)"],
  ["code","Warning: One or more parsing issues, call `problems()` on your data frame for details,\ne.g.:\n  dat <- vroom(...)\n  problems(dat)\n# A tibble: 4 × 1\n  `# Sensor export v3` \n  <chr>                \n1 # generated overnight\n2 station,reading      \n3 north,12             \n4 south,31             "],
  ["p","Look at the table rather than at the warning. The first line of the file became the only column name, every other line became one value in that column, and no field was ever separated from its neighbour. A three-row, two-column table arrived as a four-row, one-column table of text."],
  ["p","skip tells read_csv() how many lines to throw away before it starts. Two junk lines, so skip = 2, and the header lands where the reader expects it."],
  ["code","read_csv(\"export.csv\", skip = 2, show_col_types = FALSE)"],
  ["code","# A tibble: 2 × 2\n  station reading\n  <chr>     <dbl>\n1 north        12\n2 south        31"],
  ["p","comment does the same job by pattern instead of by count. Give it the character the notes begin with and readr drops every line that starts with it, wherever those lines sit in the file."],
  ["code","read_csv(\"export.csv\", comment = \"#\", show_col_types = FALSE)"],
  ["code","# A tibble: 2 × 2\n  station reading\n  <chr>     <dbl>\n1 north        12\n2 south        31"],
  ["p","A file with no header at all needs col_names. Set it to FALSE and readr invents the names X1, X2 and so on; hand it a character vector and it uses yours, in order."],
  ["code","writeLines(c(\"north,12\", \"south,31\"), \"headless.csv\")\nread_csv(\"headless.csv\", col_names = FALSE, show_col_types = FALSE)\nread_csv(\"headless.csv\", col_names = c(\"station\", \"reading\"), show_col_types = FALSE)"],
  ["code","# A tibble: 2 × 2\n  X1       X2\n  <chr> <dbl>\n1 north    12\n2 south    31\n# A tibble: 2 × 2\n  station reading\n  <chr>     <dbl>\n1 north        12\n2 south        31"],
  ["note","The mistake: reaching for skip = 1 on a file that really does have a header. The header is discarded, the first row of data is promoted into its place, and the result looks entirely reasonable — wrong column names and one row short. Print the first few lines with readLines() before you pick a number for skip."]
]},
{ t: "Other delimiters",
  body: [
  ["p","Not every text table is separated by commas. Tabs are common in exports from statistics software, and read_tsv() is read_csv() with the tab already filled in."],
  ["code","writeLines(c(\"station\\treading\", \"north\\t12\", \"south\\t31\"), \"readings.tsv\")\nread_tsv(\"readings.tsv\", show_col_types = FALSE)"],
  ["code","# A tibble: 2 × 2\n  station reading\n  <chr>     <dbl>\n1 north        12\n2 south        31"],
  ["p","For anything else there is read_delim(), which takes the separator as an argument. Everything else about the call is identical, which is the point: the delimiter is a detail, not a different kind of problem."],
  ["code","writeLines(c(\"station|reading\", \"north|12\", \"south|31\"), \"piped.txt\")\nread_delim(\"piped.txt\", delim = \"|\", show_col_types = FALSE)"],
  ["code","# A tibble: 2 × 2\n  station reading\n  <chr>     <dbl>\n1 north        12\n2 south        31"],
  ["p","One variant deserves its own function. In much of Europe the comma is the decimal mark, so files use a semicolon to separate fields instead. read_csv2() handles both halves of that convention at once, and says so as it goes."],
  ["code","writeLines(c(\"station;reading\",\n             \"north;12,5\",\n             \"south;31,25\"), \"euro.csv\")\nread_csv2(\"euro.csv\", show_col_types = FALSE)"],
  ["code","ℹ Using \"','\" as decimal and \"'.'\" as grouping mark. Use `read_delim()` for more control.\n# A tibble: 2 × 2\n  station reading\n  <chr>     <dbl>\n1 north      12.5\n2 south      31.2"],
  ["p","Note that 31,25 arrived as 31.2 on screen. The value stored is 31.25; tibbles print numbers to a limited width by default, so the display is rounded even though nothing in the data was."],
  ["note","The mistake: opening a semicolon file with read_csv(). It does not stop — no comma matches, so each whole line becomes a single value and you get a table one column wide, with a parsing warning you may not have read. One column where you expected several is always a delimiter problem."]
]},
{ t: "Controlling column types",
  body: [
  ["p","readr picks a type per column by inspecting the values, and it is better at this than beginners expect. The case people assume it gets wrong — identifiers padded with leading zeros — it gets right, because 007 is not how R would ever write the number seven."],
  ["code","writeLines(c(\"site_id,reading\",\n             \"007,12\",\n             \"018,31\",\n             \"042,7\"), \"padded.csv\")\nread_csv(\"padded.csv\", show_col_types = FALSE)"],
  ["code","# A tibble: 3 × 2\n  site_id reading\n  <chr>     <dbl>\n1 007          12\n2 018          31\n3 042           7"],
  ["p","Take the padding away and the same identifiers become numbers, because now they look like numbers in every respect."],
  ["code","writeLines(c(\"site_id,reading\",\n             \"7,12\",\n             \"18,31\",\n             \"42,7\"), \"sites.csv\")\nread_csv(\"sites.csv\", show_col_types = FALSE)"],
  ["code","# A tibble: 3 × 2\n  site_id reading\n    <dbl>   <dbl>\n1       7      12\n2      18      31\n3      42       7"],
  ["p","readr is right about the type and wrong about the meaning. A site identifier is a label that happens to be spelled with digits; averaging it or adding to it is nonsense, and nothing will stop you doing either. The fix is to state the type instead of leaving it to be inferred. col_types takes a cols() specification naming the columns you care about, and leaves the rest to be guessed."],
  ["code","read_csv(\"sites.csv\", col_types = cols(site_id = col_character()))"],
  ["code","# A tibble: 3 × 2\n  site_id reading\n  <chr>     <dbl>\n1 7            12\n2 18           31\n3 42            7"],
  ["p","For a narrow file there is a shorthand: one letter per column, in order. c is character, d is double, i is integer, l is logical, D is date, and ? means guess this one. The string below says the first column is text and the second is a number."],
  ["code","read_csv(\"sites.csv\", col_types = \"cd\")"],
  ["code","# A tibble: 3 × 2\n  site_id reading\n  <chr>     <dbl>\n1 7            12\n2 18           31\n3 42            7"],
  ["note","Supplying col_types also silences the column specification message, because there is nothing left to report. That is the honest way to quiet it — you stated what you expect, so a file that stops matching those expectations now argues with you instead of being silently reinterpreted."]
]},
{ t: "Missing values and parsing problems",
  body: [
  ["p","A csv has no way to say missing, so every producer invents its own spelling: an empty field, NA, n/a, none, unknown, a hyphen. readr treats an empty field and the text NA as missing by default, and takes everything else at face value. One stray word is enough to change a whole column's type."],
  ["code","writeLines(c(\"station,reading\",\n             \"north,12\",\n             \"south,NA\",\n             \"east,unknown\",\n             \"west,7\"), \"gappy.csv\")\nread_csv(\"gappy.csv\", show_col_types = FALSE)"],
  ["code","# A tibble: 4 × 2\n  station reading\n  <chr>   <chr>  \n1 north   12     \n2 south   <NA>   \n3 east    unknown\n4 west    7      "],
  ["p","reading came out chr. Only one of the four values is not a number, and readr will not throw it away on your behalf, so the only type that fits all four is text. Notice the difference between the two gaps already: NA became a real missing value, printed <NA>, while unknown stayed as the word it is."],
  ["p","You can insist on a number. readr will convert what it can, put a missing value where it cannot, and warn you that it had to."],
  ["code","gappy <- read_csv(\"gappy.csv\", col_types = cols(reading = col_double()))\ngappy"],
  ["code","Warning: One or more parsing issues, call `problems()` on your data frame for details,\ne.g.:\n  dat <- vroom(...)\n  problems(dat)\n# A tibble: 4 × 2\n  station reading\n  <chr>     <dbl>\n1 north        12\n2 south        NA\n3 east         NA\n4 west          7"],
  ["p","The warning tells you the count of nothing and the location of nothing, which is why it points at problems(). Call that on the tibble and you get another tibble: one row per failure, with the row and column it happened in, the type that was expected, the text that was actually there, and the file it came from."],
  ["code","problems(gappy)"],
  ["code","# A tibble: 1 × 5\n    row   col expected actual  file                    \n  <int> <int> <chr>    <chr>   <chr>                   \n1     4     2 a double unknown /home/web_user/gappy.csv"],
  ["p","Row 4, column 2, a double expected, the word unknown found. That is enough to go and look at the file. The path is absolute because readr resolves it against the working directory, which in this app is /home/web_user."],
  ["p","Once you know what the producer writes for missing, say so with na and let readr do the conversion cleanly. It takes a character vector of every spelling that should count as missing."],
  ["code","read_csv(\"gappy.csv\", na = c(\"\", \"NA\", \"unknown\"), show_col_types = FALSE)"],
  ["code","# A tibble: 4 × 2\n  station reading\n  <chr>     <dbl>\n1 north        12\n2 south        NA\n3 east         NA\n4 west          7"],
  ["note","The mistake: seeing chr where you expected dbl and reaching for as.numeric() on the column afterwards. That works, and it converts the bad values to NA with a warning you will not investigate. Fixing it at read time with na names the problem, keeps the record of what the file actually said, and leaves problems() available when the count surprises you."]
]},
{ t: "Reading several files at once",
  body: [
  ["p","Data arrives split by day, by site, or by month far more often than it arrives in one piece. read_csv() takes a vector of paths rather than a single one, reads each file with the same rules, and stacks the results into one tibble."],
  ["code","writeLines(c(\"station,reading\", \"north,12\", \"south,31\"), \"day-01.csv\")\nwriteLines(c(\"station,reading\", \"north,9\", \"south,28\"), \"day-02.csv\")\nread_csv(c(\"day-01.csv\", \"day-02.csv\"), id = \"file\", show_col_types = FALSE)"],
  ["code","# A tibble: 4 × 3\n  file       station reading\n  <chr>      <chr>     <dbl>\n1 day-01.csv north        12\n2 day-01.csv south        31\n3 day-02.csv north         9\n4 day-02.csv south        28"],
  ["p","The id argument is what makes this usable. Stacked rows lose the one fact the file name was carrying — which day this reading belongs to — and id puts it back as a column, named whatever you pass. Without it the four rows are indistinguishable pairs."],
  ["p","Typing the paths out defeats the purpose once there are thirty files. list.files() finds them by pattern and hands the vector straight to read_csv(), so the same two lines work for two files or two hundred."],
  ["note","The mistake: assuming the files line up. Stacking demands the same column names in the same positions, and readr does check: spell reading as readings in the second file and the whole read stops with Files must have consistent column names, naming the column and both files. That is a good failure, but it is still all-or-nothing — one inconsistent file blocks the entire batch. Read one file on its own and look at its specification before you point read_csv() at the set."]
]},
{ t: "Writing to a file",
  body: [
  ["p","write_csv() is the mirror image: it takes a tibble and a path and puts plain text on disk. Here the site identifiers were read as text on purpose, and written straight back out."],
  ["code","sites <- read_csv(\"sites.csv\", col_types = \"cd\")\nwrite_csv(sites, \"sites-out.csv\")\ncat(readLines(\"sites-out.csv\"), sep = \"\\n\")"],
  ["code","site_id,reading\n7,12\n18,31\n42,7"],
  ["p","The file is correct and the type information is gone. A csv stores characters, not types, so the work you did to keep site_id as text lives in your R session and nowhere else. Read the file you just wrote and readr starts guessing again, from scratch, and reaches the same conclusion it reached the first time."],
  ["code","read_csv(\"sites-out.csv\", show_col_types = FALSE)"],
  ["code","# A tibble: 3 × 2\n  site_id reading\n    <dbl>   <dbl>\n1       7      12\n2      18      31\n3      42       7"],
  ["p","When the types matter more than the file being readable by other tools, write_rds() and read_rds() store R's own binary format instead. Nothing is guessed on the way back in, because nothing was thrown away on the way out."],
  ["code","write_rds(sites, \"sites.rds\")\nread_rds(\"sites.rds\")"],
  ["code","# A tibble: 3 × 2\n  site_id reading\n  <chr>     <dbl>\n1 7            12\n2 18           31\n3 42            7"],
  ["note","The mistake: treating a written csv as a saved analysis. It is a saved table, and everything you decided about the columns evaporates with the session. Either keep the col_types call in the script that reads it back, or write .rds and stop rediscovering the same specification every morning."]
]},
{ t: "Entering data by hand",
  body: [
  ["p","Small tables — a lookup of codes to names, a handful of thresholds — are quicker to type than to file. tibble() builds one column at a time, which suits data you already hold as vectors."],
  ["code","library(tibble)\ntibble(station = c(\"north\", \"south\", \"east\"),\n       reading = c(12, 31, 7))"],
  ["code","# A tibble: 3 × 2\n  station reading\n  <chr>     <dbl>\n1 north        12\n2 south        31\n3 east          7"],
  ["p","tribble() builds the same table one row at a time. Column names are written as formulas, with a leading tilde, and the values follow in reading order. Laid out with the columns aligned it looks like the table it produces, so a transcription error is visible on the page."],
  ["code","tribble(\n  ~station, ~reading,\n  \"north\",  12,\n  \"south\",  31,\n  \"east\",   7\n)"],
  ["code","# A tibble: 3 × 2\n  station reading\n  <chr>     <dbl>\n1 north        12\n2 south        31\n3 east          7"],
  ["note","The mistake: entering a table in a spreadsheet, exporting it, and reading the export. For twenty values that is three tools and two files where one tribble() would do, and the tribble is the only version that is visible in the script alongside the analysis that uses it."]
]},
{ t: "Summary",
  body: [
  ["p","read_csv() turns a text file into a tibble and reports the type it chose for every column; that report is a message rather than an error, and reading it is the cheapest check you will ever run. skip, comment and col_names handle files whose first line is not a header. read_tsv(), read_delim() and read_csv2() cover the other separators, and one column where you expected several always means the delimiter is wrong. Column types are guessed from the values, so state them with col_types whenever the guess would be right about the type and wrong about the meaning."],
  ["p","Missing values are whatever the producer decided to write, so name those spellings with na rather than converting the column afterwards, and use problems() to find the exact row and value behind a parsing warning. read_csv() accepts a vector of paths and stacks the results, with id keeping the file name as a column. write_csv() puts a tibble back on disk as plain text and drops every type decision with it; write_rds() keeps them. Small tables are worth typing directly with tibble() or tribble()."],
  ["p","Answer the practice questions from memory before revealing the answers, then clear the graded exercises below. The next chapter is getting help — reading R's error messages closely enough to act on them, asking R about its own functions, and writing a question that other people can actually answer."]
]}
],
questions: [
{ q:"read_csv() prints a block of text above the tibble. What is it, and is something wrong?",
  a:"It is the column specification message: the type readr chose for each column, plus a note about how to see or silence it. Nothing is wrong. It goes to the error stream, so some consoles colour it red, but it is a report rather than a failure." },
{ q:"What do chr, dbl and date mean in the tibble header, and how do you get the specification back later?",
  a:"chr is character (text), dbl is double (R's ordinary number), and date is a calendar date. spec() on a tibble that came from readr prints the full specification as cols() code you could paste into the read_csv() call." },
{ q:"A file has two lines of export notes above its header. Give two ways to read it correctly.",
  a:"skip = 2 discards a fixed number of lines before reading starts. comment = \"#\" discards every line beginning with that character, wherever it appears. skip counts, comment matches — use comment when the notes are scattered or you do not want to count them." },
{ q:"You read a file with no header and did not say so. What do you get?",
  a:"The first row of data is consumed as the column names, so the table is one row short and the names are values. Pass col_names = FALSE to get X1, X2 and so on, or col_names = c(\"a\", \"b\") to supply your own." },
{ q:"You open a semicolon-separated file with read_csv(). Describe the result.",
  a:"One column, whose name is the whole header line and whose values are whole rows, plus a parsing warning. Nothing matched the comma, so no field was ever split. A table one column wide when you expected several is always a delimiter problem — reach for read_csv2() or read_delim()." },
{ q:"A column of site identifiers written 7, 18, 42 is read as dbl. Why is that a problem, and what fixes it?",
  a:"readr is right about the type and wrong about the meaning: those digits are labels, so averaging or adding them is nonsense that nothing will flag. Fix it at read time with col_types = cols(site_id = col_character()), or with the compact string form where c is character and d is double." },
{ q:"Padded identifiers like 007 are read as chr without being asked. Why?",
  a:"Because 007 is not how R writes the number seven, so the values do not all look like numbers and character is the only type that fits. The leading zeros survive, which is what you wanted — this is the case readr gets right on its own." },
{ q:"A column holds 12, NA, unknown and 7, and reads as chr. What happened, and what are the two ways forward?",
  a:"NA counted as missing, but unknown is just a word, so text is the only type that fits all four values. Either force the type with col_types = cols(reading = col_double()), which converts what it can and warns about the rest, or list the spelling as missing with na = c(\"\", \"NA\", \"unknown\"), which converts cleanly." },
{ q:"What does problems() give you that the parsing warning does not?",
  a:"The specifics: one row per failure, giving the row and column number, the type expected, the actual text found, and the file it came from. The warning only tells you failures exist." },
{ q:"You read a csv, set col_types to keep an id as text, then write it back with write_csv(). What is preserved?",
  a:"The values, and nothing else. A csv stores characters, not types, so reading the file back starts the guessing over and the id becomes a number again. Keep the col_types call in the reading script, or write with write_rds(), which stores R's own format and needs no guessing." }
],
exercises: [
{ c:"tibbles & pipes", t:"A file and the tibble it becomes", book:"r07",
  b:"Load readr. Using writeLines(), create plots.csv in the working directory holding the header plot,trees,planted_on and then the three rows ridge,48,2026-04-02 then hollow,12,2026-04-05 then bank,31,2026-04-09. Read it with read_csv() so that no column specification message is printed, and print the tibble. Running your code a second time must print exactly the same thing.",
  o:"# A tibble: 3 × 3\n  plot   trees planted_on\n  <chr>  <dbl> <date>    \n1 ridge     48 2026-04-02\n2 hollow    12 2026-04-05\n3 bank      31 2026-04-09",
  h:["Three steps, in this order: attach the package, put the four lines on disk, read them back.",
     "writeLines() takes a character vector and a file name, one element per line. It replaces the file every time, which is what makes a second run identical. read_csv() has an argument that turns the column specification message off.",
     "Build the four lines with c(), write them to \"plots.csv\", then call read_csv() on that name with show_col_types set, and let the result print."]},
{ c:"tibbles & pipes", t:"An identifier that must stay text", book:"r07",
  b:"Load readr and write codes.csv holding the header code,trees and then the rows 0071,48 then 0180,12 then 0425,31. Read it so that code is a character column and trees is a number, stating the types in the call rather than relying on the guess, and print the tibble.",
  o:"# A tibble: 3 × 2\n  code  trees\n  <chr> <dbl>\n1 0071     48\n2 0180     12\n3 0425     31",
  h:["Same writing step as before. The reading step needs one extra argument.",
     "col_types is that argument. It accepts a cols() specification naming columns individually, or a compact string with one letter per column.",
     "Either col_types = cols(code = col_character()) or the two-letter string form, where the first letter is c for character and the second is d for double."]},
{ c:"tibbles & pipes", t:"The word that is not a number", book:"r07",
  b:"Load readr and write counts.csv holding the header plot,trees and then the rows ridge,48 then hollow,none then bank,31. Read it so that trees is a number and the word none is treated as a missing value, then print the tibble with its rows in increasing order of trees.",
  o:"# A tibble: 3 × 2\n  plot   trees\n  <chr>  <dbl>\n1 bank      31\n2 ridge     48\n3 hollow    NA",
  h:["Read it the plain way first and look at the type of trees. One word in the column is enough to make the whole column text.",
     "The na argument takes a character vector of every spelling that should count as missing. Give it the empty string, NA, and the word this file uses.",
     "After reading into a name, order() on the trees column gives the row positions in increasing order; use them inside single square brackets, remembering that a tibble is subset by row and column. Missing values sort to the end."]},
{ c:"data frames", t:"Out to disk and back", book:"r07",
  b:"Load readr and write plots.csv holding the header plot,trees,planted_on and then the rows ridge,48,2026-04-02 then hollow,12,2026-04-05 then bank,31,2026-04-09. Read it with read_csv() with the column specification message off, write that tibble to plots-out.csv with write_csv(), and then print the contents of plots-out.csv as plain lines with no quotes and no index markers. Running your code a second time must print exactly the same thing.",
  o:"plot,trees,planted_on\nridge,48,2026-04-02\nhollow,12,2026-04-05\nbank,31,2026-04-09",
  h:["Four steps: write a file, read it, write the result to a second file, then show the text of that second file.",
     "write_csv() takes the tibble first and the file name second. To show a text file as plain lines rather than as a character vector, read it with readLines() and print it with cat().",
     "The last line passes readLines(\"plots-out.csv\") to cat() with its sep argument set to a newline, which is the same pairing used to show the first file in this chapter."]}
]
};
