/* Practice Log book — R Chapter 8: Workflow: getting help.
   Original lesson text following the chapter-by-chapter curriculum of
   "R for Data Science" (2nd ed.) by Hadley Wickham, Mine Cetinkaya-Rundel,
   and Garrett Grolemund. Read the original chapter free at the src link below.
   Every shown output was captured by executing the code in WebR, not written from memory. */
window.BOOK_R = window.BOOK_R || { chapters: {} };
window.BOOK_R.chapters.r08 = {
n: 8,
title: "Workflow: getting help",
src: "https://r4ds.hadley.nz/workflow-help.html",
blurb: "Getting unstuck: reading an error closely enough to act on it, asking R about its own functions, and writing a question someone can answer.",
pkgs: [],
sections: [
{ t: "Read the error before you touch the code",
  body: [
  ["p","Every session you will ever have contains errors. The skill worth building is not avoiding them but reading them, because an R error is the most specific information R ever volunteers about your program. The instinct to change something and run it again skips the only part of the process that was going to tell you what is wrong."],
  ["code","sqrt(\"16\")"],
  ["code","Error: non-numeric argument to mathematical function"],
  ["p","Six words, and they answer three questions if you ask them one at a time. What kind of function complained: a mathematical one. What did it object to: an argument that was not numeric. What would satisfy it: a number. Nothing in the message is vague, and nothing in it is about you."],
  ["p","So the question becomes which argument was not a number, and there is only one candidate. Ask R what it thinks that value is rather than deciding for yourself, because the value looks like a number and is not one."],
  ["code","reading <- \"16\"\nclass(reading)\nsqrt(as.numeric(reading))"],
  ["code","[1] \"character\"\n[1] 4"],
  ["p","class() confirmed the diagnosis and the conversion fixed it. That is the whole loop: read the message, turn it into a question about one specific value, ask R the question, change one thing. It is slower than guessing for the first week and faster than guessing forever after."],
  ["note","The mistake: running the same code again to see whether the error was a fluke. R is deterministic — the same input produces the same error every time, and the second run costs you the attention you were going to spend reading the first one."]
]},
{ t: "What an R error message names",
  body: [
  ["p","An R error carries two things: a message saying what went wrong, and the call that was running when it went wrong. Desktop R and RStudio usually print both, in the form Error in sqrt(\"16\") : non-numeric argument to mathematical function. The console in this app prints the message only."],
  ["p","The call is not lost, just not displayed. An error is an object, and tryCatch() can hand you that object instead of letting it stop the program, at which point both halves are available to look at."],
  ["code","e <- tryCatch(sqrt(\"16\"), error = function(e) e)\nconditionMessage(e)\ndeparse(conditionCall(e))"],
  ["code","[1] \"non-numeric argument to mathematical function\"\n[1] \"sqrt(\\\"16\\\")\""],
  ["p","conditionMessage() gives the text you already saw and conditionCall() gives the expression that produced it, deparsed back into code. This is worth knowing rather than worth doing every time: in normal work you know which line you just ran. It matters when the failing call is buried three functions deep in something you did not write."],
  ["p","On the desktop, traceback() is the tool for that: called immediately after an error, it prints the chain of calls that led to the failure, innermost first. Here it has nothing to report, because each submission runs in a fresh evaluation and the stack is gone by the time you could ask."],
  ["code","traceback()"],
  ["code","No traceback available "],
  ["note","This app runs R through WebR, which reports errors as Error: followed by the message and drops the Error in <call> : prefix that desktop R prints. Nothing about the error itself is different — only how much of it reaches the screen. When you need the call here, catch the condition as above; when you are on the desktop, traceback() answers the same question with more context."]
]},
{ t: "Errors you will actually meet",
  body: [
  ["p","Most of a beginner's errors are a handful of messages seen over and over. Reading each one once, on purpose, is what turns them from noise into a diagnosis. Arithmetic on text is the first."],
  ["code","\"12\" + 1"],
  ["code","Error: non-numeric argument to binary operator"],
  ["p","A binary operator is one that takes a value on each side. R will not guess that the text \"12\" was meant as a number, and the fix is as.numeric() on whichever side is quoted. Next, asking for something past the end of a list."],
  ["code","readings <- list(12, 31, 7)\nreadings[[5]]"],
  ["code","Error: subscript out of bounds"],
  ["p","Three elements, and the code asked for the fifth. This one usually means a loop counter has run past the length of what it was walking, so length() on the object is the first thing to check. Next, a condition that could not answer yes or no."],
  ["code","reading <- NA\nif (reading > 10) \"high\""],
  ["code","Error: missing value where TRUE/FALSE needed"],
  ["p","NA > 10 is NA, not TRUE and not FALSE, and if() has no branch for that. The message is telling you there is a missing value in data you assumed was complete. Next, the two errors that come from calling a function wrongly."],
  ["code","band <- function(reading, limit) if (reading > limit) \"high\" else \"low\"\nband(12)"],
  ["code","Error: argument \"limit\" is missing, with no default"],
  ["p","The function needs two values and got one, and R names the argument it is short of. The opposite mistake gets its own message, and it is the one that catches misspelled argument names."],
  ["code","band(12, limit = 10, units = \"mm\")"],
  ["code","Error: unused argument (units = \"mm\")"],
  ["p","R matched reading and limit, had nothing to match units to, and refused. Last, the error you get before any of your own code runs."],
  ["code","library(dplyrr)"],
  ["code","Error: there is no package called ‘dplyrr’"],
  ["p","A package that is not installed, or a package name that is misspelled, and there is no way for R to tell those apart. Check the spelling first, because it is free."],
  ["note","One more worth recognising on sight: object of type 'closure' is not subsettable. A closure is a function, so this means you used [ ] or $ on a function name. It happens because several base R functions have short, tempting names — df is the F distribution density, data is a function, c is a function — so df$reading fails while looking exactly like ordinary data frame code. Naming your objects something less generic prevents it entirely."]
]},
{ t: "Warnings are quieter and worse",
  body: [
  ["p","An error stops the program. A warning does not: R tells you something was odd, produces a result anyway, and carries on. That makes warnings easier to miss and more expensive to miss, because the result is already in a variable and already being used."],
  ["code","log(-4)"],
  ["code","Warning in log(-4) : NaNs produced\n[1] NaN"],
  ["p","NaN means not a number, and it is now a value that will spread through every calculation it touches. Notice that the warning names its call, log(-4), where the errors in this chapter did not — warnings carry the call to the screen even here."],
  ["code","mean(c(\"12\", \"31\"))"],
  ["code","Warning in mean.default(c(\"12\", \"31\")) :\n  argument is not numeric or logical: returning NA\n[1] NA"],
  ["p","mean() was handed text, declined to guess, and returned NA rather than stopping. If that line sat in the middle of a script you would get a report full of NA and no indication of which step introduced them. The next warning is subtler still, because the answer looks completely normal."],
  ["code","c(1, 2, 3, 4, 5) + c(10, 20)"],
  ["code","Warning in c(1, 2, 3, 4, 5) + c(10, 20) :\n  longer object length is not a multiple of shorter object length\n[1] 11 22 13 24 15"],
  ["p","R recycled the short vector to the length of the long one: 10, 20, 10, 20, 10. Five numbers came back, every one of them a plausible value, and only the warning says that the pairing was invented. Recycling is a deliberate feature, and it is silent when the lengths divide evenly — which is why this warning appears exactly when the vectors were probably meant to match and did not."],
  ["code","to_number <- function(x) as.numeric(x)\nto_number(c(\"12\", \"twelve\", \"7\"))"],
  ["code","Warning in to_number(c(\"12\", \"twelve\", \"7\")) :\n  NAs introduced by coercion\n[1] 12 NA  7"],
  ["p","NAs introduced by coercion is the one you will see most. It means a conversion was asked for and some values could not make the trip. Two of three converted, one became NA, and the vector is now shorter in usable values than its length suggests."],
  ["note","In this app the warning is printed before the value, because it is signalled while the expression is being evaluated and the value is printed after. A desktop console usually prints warnings after the result instead. Either way the ordering is a display detail — what matters is that a warning means the number you are about to use was produced under protest."]
]},
{ t: "The failures that print nothing at all",
  body: [
  ["p","Below warnings there is a third category, and it is the one that costs whole afternoons: code that runs cleanly and answers the wrong question. A misspelled column name is the standard example."],
  ["code","d <- data.frame(station = c(\"north\", \"south\"), reading = c(12, 31))\nd$readings"],
  ["code","NULL"],
  ["code","sum(d$readings)"],
  ["code","[1] 0"],
  ["p","Asking a data frame for a column it does not have returns NULL rather than an error, and the sum of nothing is zero. So a typo produces the number 0, which is a perfectly plausible total, and nothing anywhere says the column was never found. Whenever a total is suspiciously round, print names(d) before you look for anything cleverer."],
  ["p","Misspelled argument names can behave the same way, depending on the function. This one does warn — but read what it returned."],
  ["code","seq(1, 10, step = 2)"],
  ["code","Warning: In seq.default(1, 10, step = 2) :\n extra argument ‘step’ will be disregarded\n [1]  1  2  3  4  5  6  7  8  9 10"],
  ["p","The argument is called by, not step. R disregarded the unknown name and used its defaults, so the answer is a complete, correct sequence in steps of one — a full answer to a question you did not ask. Ten numbers came back where five were wanted, and nothing about the shape of the result looks wrong."],
  ["p","Missing values are the third quiet failure, because they spread rather than stop."],
  ["code","readings <- c(12, NA, 7)\nreadings > 10\nmean(readings)"],
  ["code","[1]  TRUE    NA FALSE\n[1] NA"],
  ["p","The comparison answers for two of three values and refuses for the third, and mean() of anything containing NA is NA. That is R being careful rather than R failing: it will not average around a hole without being told to, which is what na.rm = TRUE says."],
  ["note","The mistake: treating no error as evidence that the code is right. Those are different claims. After every step that matters, look at the thing you just made — nrow(), names(), summary(), or simply printing it — because the only failures that survive a session are the ones that never announced themselves."]
]},
{ t: "Asking R itself",
  body: [
  ["p","Before searching the web, ask R. It ships with documentation for every function it has, and it will also answer smaller questions about the objects in front of you, usually faster than a search would."],
  ["note","?mean and help(mean) open a documentation page. This app has no help pane to open one in, so no help page can be shown here — and inventing what it says would be worse than showing nothing. Everything else in this section runs, and prints exactly what you see. On the desktop, make ? the first thing you try: the Arguments section answers most questions faster than a search does, and the Examples at the bottom are runnable."],
  ["p","args() prints a function's argument list, including the defaults, and it works here. It is the fastest way to check the name of the argument you half remember."],
  ["code","args(round)"],
  ["code","function (x, digits = 0, ...) \nNULL"],
  ["p","Read it as: round() takes x, takes digits with a default of 0, and accepts further arguments. The NULL underneath is an artefact of what args() returns rather than part of the answer. For a function with more arguments the value of this grows."],
  ["code","args(seq.default)"],
  ["code","function (from = 1, to = 1, by = ((to - from)/(length.out - 1)), \n    length.out = NULL, along.with = NULL, ...) \nNULL"],
  ["p","There is the by from the previous section, sitting where step was not. When you want the names alone, without the defaults getting in the way, formals() gives them as a character vector."],
  ["code","names(formals(seq.default))"],
  ["code","[1] \"from\"       \"to\"         \"by\"         \"length.out\" \"along.with\"\n[6] \"...\"       "],
  ["p","The other half of asking R is asking about your own values rather than its functions. class() and is.numeric() settle the single commonest confusion in one line each."],
  ["code","reading <- \"12\"\nclass(reading)\nis.numeric(reading)"],
  ["code","[1] \"character\"\n[1] FALSE"],
  ["p","str() is the general version: it prints the structure of anything — type, length, and a sample of contents — and it is the right first move on an object you did not build yourself."],
  ["code","rec <- list(station = \"north\", reading = 12)\nstr(rec)"],
  ["code","List of 2\n $ station: chr \"north\"\n $ reading: num 12"],
  ["note","The mistake: reading the whole help page for a function you have already used ten times, when the question was only what an argument is called. args() answers that in one line. Save ? for the first time you meet a function, and for the Examples section when a call is not doing what you expected."]
]},
{ t: "Searching well, and asking well",
  body: [
  ["p","When R's own answers are not enough, the next step is a search, and the quality of the answer depends almost entirely on the query. Paste the error message, but strip out the parts that are yours: your object names, your file paths, your values. What remains is the part thousands of other people have also hit, and it is the part search engines can match."],
  ["p","So non-numeric argument to mathematical function is a good query and Error in sqrt(my_readings_2026) is a bad one. Add the function name or the package name when the message alone is generic. Adding r to the query helps less than it used to and rarely hurts."],
  ["p","If the search does not settle it, you are going to ask a person, and the thing to hand them is a reprex: a reproducible example. It has three properties, and a question missing any of them usually gets a request for it rather than an answer. It runs on somebody else's machine, from the top, with no files and no objects they do not have. It is the smallest program that still shows the problem. And it says what you expected as well as what happened."],
  ["p","The block below has all three. The data is created in the code rather than loaded from a file, everything unrelated to the failure has been deleted, and the intent is stated so a reader can see the gap between what was wanted and what arrived."],
  ["code","# Expected: the mean of the two readable readings.\n# Got: NA, and I do not understand where it comes from.\nlibrary(readr)\nwriteLines(c(\"station,reading\", \"north,12\", \"south,thirty\"), \"readings.csv\")\nd <- read_csv(\"readings.csv\", col_types = \"cd\")\nmean(d$reading)"],
  ["note","This section is output-free on purpose. The block above is a template for a question rather than something to run here, and the tools it belongs to are all part of a desktop setup: the reprex package formats and checks an example like this on your own machine, Stack Overflow and the Posit Community forum are websites, and the help pane belongs to RStudio. None of them can run inside this app, and fabricating the replies they might give would be no more honest than fabricating output."],
  ["p","Two habits do most of the work over a year. Keep the examples you write: half of them answer themselves while you are cutting them down, and that is the point rather than a waste. And read release notes and package documentation when you are not stuck, because the fastest way out of a problem is to have already met it."],
  ["note","The mistake: asking with a screenshot, or with the three lines around the error and nothing else. Nobody can run a screenshot, and three lines that reference objects only you have are not a question anyone can test. If cutting the example down is too much work to be worth it, the problem is not yet worth someone else's afternoon either."]
]},
{ t: "Summary",
  body: [
  ["p","An R error names a category before it names anything else, and the loop is always the same: read the message, turn it into a question about one specific value, ask R that question, change one thing. This app prints Error: followed by the message and leaves out the call that desktop R shows, so when the call matters, tryCatch() with conditionMessage() and conditionCall() recovers both halves. The handful of messages in this chapter — non-numeric argument, subscript out of bounds, missing value where TRUE/FALSE needed, argument missing with no default, unused argument, no package called — cover most of a beginner's first months."],
  ["p","Warnings are the harder problem, because the program keeps going and hands you a result produced under protest: NaN, NA, or a silently recycled vector. Quieter still is the code that produces no message at all, like a misspelled column that returns NULL and sums to zero. No error is not evidence of correctness, so look at what you just made after every step that matters. Ask R first — args(), formals(), class(), is.numeric() and str() all run here, and ? is the desktop starting point. When you do ask a person, hand them a reprex: self-contained, minimal, and clear about what you expected."],
  ["p","Answer the practice questions from memory before revealing the answers, then clear the graded exercises below. The next chapter is Layers, which goes back to ggplot2 and takes the grammar apart properly — aesthetics, geoms, statistical transformations, position adjustments, and coordinate systems."]
]}
],
questions: [
{ q:"What are the three questions to ask of any error message?",
  a:"What was running, what did it object to, and what would satisfy it. For non-numeric argument to mathematical function the answers are: a mathematical function, an argument that was not numeric, and a number. That turns the message into a question about one specific value." },
{ q:"Desktop R prints Error in sqrt(\"16\") : non-numeric argument to mathematical function. What does this app print, and is anything lost?",
  a:"Only Error: non-numeric argument to mathematical function. The call is not lost, just not displayed — this app runs R through WebR, which drops the Error in <call> : prefix. tryCatch() with conditionCall() recovers the call when you need it." },
{ q:"What does traceback() do, and why is it no use here?",
  a:"On the desktop, called straight after an error, it prints the chain of calls that led to the failure, innermost first. In this app each submission runs in a fresh evaluation, so the stack is already gone and traceback() reports that none is available." },
{ q:"What is the difference between argument \"limit\" is missing, with no default and unused argument (units = \"mm\")?",
  a:"The first means the function needs an argument you did not supply, and it names the one it is short of. The second means you supplied something the function has no argument for — usually a misspelled argument name. One is too few, the other is one too many." },
{ q:"You get object of type 'closure' is not subsettable. What did you do?",
  a:"You used [ ] or $ on a function. A closure is a function, and it has no elements to take. It usually happens with short base R names — df, data, c — so df$reading fails while looking like ordinary data frame code. Give your objects less generic names." },
{ q:"Why is a warning more dangerous than an error?",
  a:"An error stops the program, so you deal with it. A warning produces a result and carries on, so the questionable value is already stored and already being used by the time you notice — or you never notice, because the report is finished and the numbers look plausible." },
{ q:"c(1, 2, 3, 4, 5) + c(10, 20) returns five numbers and a warning. What did R do?",
  a:"It recycled the shorter vector to the length of the longer one, pairing 1 with 10, 2 with 20, 3 with 10 and so on, and warned only because the lengths do not divide evenly. Every returned value is plausible, and the pairing after the second element was invented." },
{ q:"A data frame d has a column called reading. What does sum(d$readings) return, and why is that the worst possible behaviour?",
  a:"0. A column that does not exist evaluates to NULL rather than raising an error, and the sum of nothing is zero. A typo produces a perfectly plausible total with no message anywhere, which is why a suspiciously round number should send you to names(d)." },
{ q:"Which of args(), formals(), class(), str() and ?mean can this app show you, and what is each for?",
  a:"All except ?mean, which needs a help pane this app does not have. args() prints a function's arguments with defaults, formals() gives the argument names as a vector, class() reports what one value is, and str() prints the structure of any object — type, length and a sample of contents." },
{ q:"What are the three properties of a good reprex?",
  a:"It runs on somebody else's machine from the top, with no files and no objects they do not have. It is the smallest program that still shows the problem. And it states what you expected as well as what happened. Half of them answer themselves while you are cutting them down." }
],
exercises: [
{ c:"data types", t:"The number that was text", book:"r08",
  b:"Given readings <- c(\"12\", \"31\", \"7\"), print the class of readings, then convert it to numbers and store that under the name numbers, then print the class of numbers, then print the largest of them. Four printed lines are not wanted — print the class, the class, and the maximum, in that order, on three lines.",
  o:"[1] \"character\"\n[1] \"numeric\"\n[1] 31",
  h:["The quotes in the vector are the whole story. One function reports what a value is, another changes it.",
     "class() reports the type. as.numeric() converts text to numbers. Assignment prints nothing, so only the lines you want shown should be bare expressions.",
     "Print class(readings) first, then assign the converted vector to numbers, then print its class and then max() of it."]},
{ c:"functions", t:"Catch it and read it", book:"r08",
  b:"Without letting it stop your code, capture the error that sqrt(\"16\") produces into a variable named e. Then print the error's message on one line and, on the next, the call that produced it, deparsed back into code.",
  o:"[1] \"non-numeric argument to mathematical function\"\n[1] \"sqrt(\\\"16\\\")\"",
  h:["An R error is an object with two parts. Something has to catch it before it reaches the console.",
     "tryCatch(expr, error = function(e) e) returns the condition object instead of stopping. Two functions then read it: one for the message, one for the call.",
     "After e <- tryCatch(...), the message line is conditionMessage(e). The call line needs conditionCall(e) wrapped in the function that turns an expression back into text."]},
{ c:"functions", t:"Fail early, in your own words", book:"r08",
  b:"Write a function safe_double(x) that returns x * 2 when x is a number, and otherwise stops with the message x must be numeric. Print the result of safe_double(21). Then, on the next line, print the message that safe_double(\"21\") produces, caught so that it does not stop your code.",
  o:"[1] 42\n[1] \"x must be numeric\"",
  h:["Two parts: a function that refuses bad input, and a call that survives the refusal.",
     "is.numeric() is the test, and stop() raises an error with whatever message you give it. tryCatch() with an error handler is how you catch it afterwards.",
     "The body is one if with two branches: doubling when the test passes, stop() with your message otherwise. The last line wraps the failing call in tryCatch and returns conditionMessage(e) from the handler."]},
{ c:"data types", t:"What a missing value does", book:"r08",
  b:"Given readings <- c(12, NA, 7), print the result of comparing readings with 10 using greater-than, then print whether any of the values are missing, then print the total of the values with the missing one ignored.",
  o:"[1]  TRUE    NA FALSE\n[1] TRUE\n[1] 19",
  h:["Three printed lines, one expression each. A comparison against a vector answers once per element.",
     "NA in, NA out: the comparison cannot answer for a value that is not there. is.na() tests each element, and any() collapses a logical vector to one answer.",
     "The last line is sum() on the vector with the argument that tells it to drop missing values before adding."]}
]
};
