/* Practice Log book — R Chapter 9: Layers.
   Original lesson text following the chapter-by-chapter curriculum of
   "R for Data Science" (2nd ed.) by Hadley Wickham, Mine Cetinkaya-Rundel,
   and Garrett Grolemund. Read the original chapter free at the src link below.
   Every shown output was captured by executing the code in WebR, not written from memory. */
window.BOOK_R = window.BOOK_R || { chapters: {} };
window.BOOK_R.chapters.r09 = {
n: 9,
title: "Layers",
src: "https://r4ds.hadley.nz/layers.html",
blurb: "The seven parts every ggplot is made of — data, mapping, geom, stat, position, facet, coordinate system — and how to read each one off the object.",
pkgs: ["ggplot2", "tibble"],
sections: [
{ t: "Layers, one at a time",
  body: [
  ["p","Chapter 1 built plots out of three parts: data, a mapping written inside aes(), and a geom. That description is true and incomplete. A ggplot actually has seven parts, and five of them were being filled in for you by defaults. This chapter names all seven, shows where each one is stored, and works through what changes when you set them yourself."],
  ["p","The parts are the data, the aesthetic mappings, the geom, the stat, the position adjustment, the facet, and the coordinate system. Every plot you have built already has all seven. A scatterplot has a stat that computes nothing, a position that moves nothing, one panel, and ordinary Cartesian axes — but they are there, and each is a slot you can change."],
  ["note","This app grades text, and a chart is an image. Every output below is text read off the plot object or out of ggplot_build(), never a description of a picture. Printing a plot object on its own produces no text at all in this app's R console, so an answer that ends on a bare plot object submits nothing. Run the same code in R on a desktop when you want to see the drawings."],
  ["code","library(ggplot2)\nlibrary(tibble)"],
  ["p","The table below holds twelve food stalls at a two-site market. Each row has a stall name, the queue length in minutes, the price of one plate, the kind of food, and which of the two venues it stands in. Two numeric columns and two categorical ones is enough to reach every part of the grammar."],
  ["code","stalls <- tibble(\n  stall = c(\"Anvil\", \"Basil\", \"Cinder\", \"Dune\", \"Ember\", \"Fig\",\n            \"Gable\", \"Hollow\", \"Ivy\", \"Juniper\", \"Kettle\", \"Lark\"),\n  wait_min = c(4, 12, 7, 19, 9, 15, 6, 22, 11, 3, 17, 8),\n  price = c(6.5, 9, 7.25, 12, 8.5, 10.5, 6, 13.5, 9.75, 5.5, 11, 7.5),\n  cuisine = c(\"noodles\", \"grill\", \"sweets\", \"grill\", \"noodles\", \"grill\",\n              \"sweets\", \"grill\", \"noodles\", \"sweets\", \"noodles\", \"grill\"),\n  venue = c(\"north\", \"north\", \"south\", \"south\", \"north\", \"north\",\n            \"south\", \"north\", \"south\", \"north\", \"south\", \"south\")\n)\n\nstalls"],
  ["code","# A tibble: 12 × 5\n   stall   wait_min price cuisine venue\n   <chr>      <dbl> <dbl> <chr>   <chr>\n 1 Anvil          4  6.5  noodles north\n 2 Basil         12  9    grill   north\n 3 Cinder         7  7.25 sweets  south\n 4 Dune          19 12    grill   south\n 5 Ember          9  8.5  noodles north\n 6 Fig           15 10.5  grill   north\n 7 Gable          6  6    sweets  south\n 8 Hollow        22 13.5  grill   north\n 9 Ivy           11  9.75 noodles south\n10 Juniper        3  5.5  sweets  north\n11 Kettle        17 11    noodles south\n12 Lark           8  7.5  grill   south"],
  ["p","Before plotting anything, count the categories. Several of the numbers later in this chapter are these counts arriving by a longer route, and knowing them in advance is how you tell a working plot from a plausible-looking one."],
  ["code","table(stalls$cuisine)\ntable(stalls$cuisine, stalls$venue)"],
  ["code","\n  grill noodles  sweets \n      5       4       3 \n         \n          north south\n  grill       3     2\n  noodles     2     2\n  sweets      1     2"],
  ["p","Five grill stalls, four noodles, three sweets, split across the two venues as shown. Now the base plot: data and a mapping, no layers yet."],
  ["code","p <- ggplot(stalls, aes(x = wait_min, y = price))\n\nlength(p$layers)\nnrow(p$data)"],
  ["code","[1] 0\n[1] 12"],
  ["p","p carries all twelve rows and draws nothing. Everything in this chapter is added to p, or built alongside it, so that one change at a time is visible."]
]},
{ t: "Aesthetic mappings",
  body: [
  ["p","An aesthetic is a visual property of a mark: its position, its colour, its shape, its size, its transparency. Naming a column inside aes() maps that column to the property, which means the property varies row by row and ggplot2 builds a scale and a legend for it. The mapping is stored on the plot, and names() lists which aesthetics are in play."],
  ["p","Mappings can sit on the plot, where every layer sees them, or on a single layer, where only that layer does. Both are aes() calls; only the place changes."],
  ["code","q <- p + geom_point(aes(colour = cuisine, shape = venue))\n\nnames(q$mapping)\nnames(q$layers[[1]]$mapping)"],
  ["code","[1] \"x\" \"y\"\n[1] \"colour\" \"shape\" "],
  ["p","Two lists, not one. The plot's mapping still holds only x and y, because that is what was handed to ggplot(); colour and shape belong to the point layer. When the plot is drawn the two are merged, so the points get all four — but they are stored apart, and the next section shows why that separation matters."],
  ["p","size and alpha are the other two aesthetics you will reach for early. size scales the mark, alpha controls how see-through it is, and both take a numeric column happily."],
  ["code","sized <- ggplot(stalls, aes(x = wait_min, y = price, size = price, alpha = wait_min)) +\n  geom_point()\n\nnames(sized$mapping)"],
  ["code","[1] \"x\"     \"y\"     \"size\"  \"alpha\""],
  ["p","Not every aesthetic accepts every kind of column. shape draws from a fixed set of symbols, so it needs a categorical column with a small number of levels; there is no sensible way to turn a continuous price into a smooth run of shapes. ggplot2 does not object while the plot is being assembled, because assembling a plot never looks at the data. The complaint arrives when something asks for the drawing."],
  ["code","bad <- ggplot(stalls, aes(x = wait_min, y = price, shape = price)) + geom_point()\n\nlength(bad$layers)\nggplot_build(bad)"],
  ["code","[1] 1\nError: Problem while computing aesthetics."],
  ["note","The mistake is trusting a plot object that assembled without complaint. bad has its layer, its mapping, and its data, and looks exactly as healthy as a working plot. Nothing has read the price column yet. Run ggplot_build() on a plot before you believe it, especially when you have just mapped a column to an aesthetic you have not used before."]
]},
{ t: "Geometric objects",
  body: [
  ["p","The geom decides what shape the marks take. Keep the data and the mapping fixed, swap the geom, and the same two columns become a different chart. Each geom has a class name you can read back, and every geom also comes with a default stat."],
  ["code","pts <- p + geom_point()\nlns <- p + geom_line()\n\nclass(pts$layers[[1]]$geom)[1]\nclass(lns$layers[[1]]$geom)[1]\nclass(lns$layers[[1]]$stat)[1]"],
  ["code","[1] \"GeomPoint\"\n[1] \"GeomLine\"\n[1] \"StatIdentity\""],
  ["p","Both of those geoms take the numbers as they came, so both carry StatIdentity. geom_smooth() does not: it fits a model to the data and draws the fitted values, which is a computation, so its stat is StatSmooth. Adding it to a plot that already has points gives a second layer, and layers are numbered in the order you added them."],
  ["code","both <- p + geom_point() + geom_smooth(method = \"lm\", se = FALSE)\n\nlength(both$layers)\nclass(both$layers[[2]]$geom)[1]\nclass(both$layers[[2]]$stat)[1]"],
  ["code","[1] 2\n[1] \"GeomSmooth\"\n[1] \"StatSmooth\""],
  ["p","Now the reason plot-level and layer-level mappings are kept apart. Put colour on the point layer only, and the smooth layer never sees it. The smooth layer has no mapping of its own at all, so names() on it returns NULL."],
  ["code","local <- p + geom_point(aes(colour = cuisine)) + geom_smooth(method = \"lm\", se = FALSE)\n\nnames(local$mapping)\nnames(local$layers[[1]]$mapping)\nnames(local$layers[[2]]$mapping)"],
  ["code","[1] \"x\" \"y\"\n[1] \"colour\"\nNULL"],
  ["p","Move that same colour up into ggplot(), and both layers see it. A colour mapping splits the data into groups, and a layer that fits a model fits one model per group. The number of groups in a built layer is what proves it."],
  ["code","global <- ggplot(stalls, aes(x = wait_min, y = price, colour = cuisine)) +\n  geom_point() +\n  geom_smooth(method = \"lm\", se = FALSE)\n\nlength(unique(ggplot_build(global)$data[[2]]$group))\nlength(unique(ggplot_build(local)$data[[2]]$group))"],
  ["code","`geom_smooth()` using formula = 'y ~ x'\n[1] 3\n`geom_smooth()` using formula = 'y ~ x'\n[1] 1"],
  ["p","Three trend lines against one. Neither is wrong; they answer different questions. Three lines ask whether each cuisine prices its queue differently, one line asks whether the market as a whole does. The message about the formula is ggplot2 telling you which model it fitted, and it appears once per build."],
  ["note","The mistake is writing colour into ggplot() because you want coloured points, then wondering why one trend line turned into three. Anything mapped at the plot level reaches every layer, including the layers you add later. When a colour is meant to be decoration for one geom, map it inside that geom."]
]},
{ t: "Facets",
  body: [
  ["p","A facet splits one plot into a grid of panels, one panel per value of a column, with the same mapping and the same scales in each. It is the alternative to a third aesthetic: instead of three colours on one set of axes, three sets of axes side by side. facet_wrap() takes one column, written after a tilde because it is a formula."],
  ["code","f1 <- pts + facet_wrap(~cuisine)\n\nclass(f1$facet)[1]\nnames(f1$facet$params$facets)\nnrow(ggplot_build(f1)$layout$layout)"],
  ["code","[1] \"FacetWrap\"\n[1] \"cuisine\"\n[1] 3"],
  ["p","Three panels, because cuisine has three values. The layout is not a fact about the plot object — it is worked out during the build, which is why the panel count comes from ggplot_build() rather than from the facet itself."],
  ["p","facet_grid() takes two columns in one formula, rows on the left of the tilde and columns on the right. It makes every combination, whether or not any rows land in it."],
  ["code","f2 <- pts + facet_grid(venue ~ cuisine)\n\nclass(f2$facet)[1]\nnames(f2$facet$params$rows)\nnames(f2$facet$params$cols)"],
  ["code","[1] \"FacetGrid\"\n[1] \"venue\"\n[1] \"cuisine\""],
  ["p","The layout table itself names every panel, with the row and column it occupies and the values that define it. Reading it is the honest way to check a faceted plot in this app."],
  ["code","ggplot_build(f2)$layout$layout"],
  ["code","  PANEL ROW COL venue cuisine SCALE_X SCALE_Y COORD\n1     1   1   1 north   grill       1       1     1\n2     2   1   2 north noodles       1       1     1\n3     3   1   3 north  sweets       1       1     1\n4     4   2   1 south   grill       1       1     1\n5     5   2   2 south noodles       1       1     1\n6     6   2   3 south  sweets       1       1     1"],
  ["p","Six panels, two venues by three cuisines. SCALE_X and SCALE_Y are all 1, meaning every panel shares one x scale and one y scale — that is what makes panels comparable. The scales argument relaxes it, one axis at a time."],
  ["code","free <- pts + facet_wrap(~venue, scales = \"free_y\")\n\nfree$facet$params$free$x\nfree$facet$params$free$y"],
  ["code","[1] FALSE\n[1] TRUE"],
  ["note","Free scales are easy to switch on and hard to read. Once the y axes differ between panels, two bars of the same height are two different numbers, and every comparison across panels has to be done by reading the axis. Reach for scales = \"free_y\" when the panels hold quantities on genuinely different ranges, not to fill the empty space in a panel."]
]},
{ t: "Statistical transformations",
  body: [
  ["p","Every layer carries a stat as well as a geom. The stat is the calculation that happens between the data and the marks. For a scatterplot it is StatIdentity and nothing happens. For a bar chart of one categorical column it is StatCount, which counts the rows per category and hands the counts on as the bar heights — which is why geom_bar() needs an x and no y."],
  ["code","bars <- ggplot(stalls, aes(x = cuisine)) + geom_bar()\n\nclass(bars$layers[[1]]$geom)[1]\nclass(bars$layers[[1]]$stat)[1]\nggplot_build(bars)$data[[1]]$count"],
  ["code","[1] \"GeomBar\"\n[1] \"StatCount\"\n[1] 5 4 3"],
  ["p","Five, four, three — the same numbers table() gave in section 1, computed by the plot this time. ggplot_build() returns the data each layer will actually draw, as an ordinary data frame with one row per mark, so you can pull out whichever columns the stat produced."],
  ["code","ggplot_build(bars)$data[[1]][, c(\"count\", \"prop\", \"flipped_aes\")]"],
  ["code","  count prop flipped_aes\n1     5    1       FALSE\n2     4    1       FALSE\n3     3    1       FALSE"],
  ["p","When the heights are already in a column of your data, you do not want a stat that counts. geom_col() is geom_bar() with StatIdentity in place of StatCount: it takes x and y, and draws each row at the height you gave it."],
  ["code","cols <- ggplot(stalls, aes(x = stall, y = price)) + geom_col()\n\nclass(cols$layers[[1]]$stat)[1]\nggplot_build(cols)$data[[1]]$y"],
  ["code","[1] \"StatIdentity\"\n [1]  6.50  9.00  7.25 12.00  8.50 10.50  6.00 13.50  9.75  5.50 11.00  7.50"],
  ["p","Twelve bars, one per stall, at the twelve prices unchanged. Other stats compute summaries. stat_summary() takes functions rather than a fixed calculation, so you say which summary you want; give it a middle, a bottom, and a top and ggplot2 picks a geom that can draw all three."],
  ["code","summ <- ggplot(stalls, aes(x = cuisine, y = price)) +\n  stat_summary(fun.min = min, fun = median, fun.max = max)\n\nclass(summ$layers[[1]]$stat)[1]\nclass(summ$layers[[1]]$geom)[1]\nggplot_build(summ)$data[[1]]$y"],
  ["code","[1] \"StatSummary\"\n[1] \"GeomPointrange\"\n[1] 10.500  9.125  6.000"],
  ["p","Median plate prices of 10.50 at the grills, 9.125 at the noodle stalls, 6.00 at the sweets, drawn as a point with a line through it. Note that you never named a geom and got GeomPointrange anyway: three values per category is a range, and the default geom follows from the stat."],
  ["code","wrongbar <- ggplot(stalls, aes(x = cuisine, y = price)) + geom_bar()\n\nggplot_build(wrongbar)"],
  ["code","Error: Problem while computing stat."],
  ["note","That error is what you get for handing geom_bar() a y. StatCount produces the y itself, so supplying one leaves the stat with two answers and no way to choose. The fix is geom_col(), or geom_bar(stat = \"identity\") which is the same thing spelled out. The mistake is reading the message as being about the bar, when the word that matters is stat."]
]},
{ t: "Position adjustments",
  body: [
  ["p","A position adjustment decides what happens when two marks would occupy the same spot. Bars of a stacked chart, points sitting on identical values, boxes of two groups at one x — all of them are collisions, and the position is the rule for resolving them. It is stored on the layer, next to the geom and the stat."],
  ["p","Map a second categorical column to fill and the default takes over: PositionStack, which piles the segments on top of each other. The built data has a ymin and a ymax per segment, and reading them shows the stacking."],
  ["code","stacked <- ggplot(stalls, aes(x = cuisine, fill = venue)) + geom_bar()\n\nclass(stacked$layers[[1]]$position)[1]\nggplot_build(stacked)$data[[1]]$ymin\nggplot_build(stacked)$data[[1]]$ymax"],
  ["code","[1] \"PositionStack\"\n[1] 2 0 2 0 2 0\n[1] 5 2 4 2 3 2"],
  ["p","Six segments, two per cuisine. The grill bar runs 0 to 2 for one venue and 2 to 5 for the other, which is the 3 and 2 from the cross-tabulation stacked into a bar of height 5. Position fill stretches every bar to the same height so the segments become proportions."],
  ["code","filled <- ggplot(stalls, aes(x = cuisine, fill = venue)) + geom_bar(position = \"fill\")\n\nclass(filled$layers[[1]]$position)[1]\nround(ggplot_build(filled)$data[[1]]$ymax, 3)"],
  ["code","[1] \"PositionFill\"\n[1] 1.000 0.400 1.000 0.500 1.000 0.667"],
  ["p","Every bar now tops out at 1, and the inner boundaries are the shares: 0.4 of the grill stalls in one venue, 0.5 of the noodle stalls, 0.667 of the sweets. That chart answers a question about proportions and destroys the information about totals, which is the trade you are making. Position dodge puts the segments side by side instead, which keeps both."],
  ["code","dodged <- ggplot(stalls, aes(x = cuisine, fill = venue)) + geom_bar(position = \"dodge\")\n\nclass(dodged$layers[[1]]$position)[1]\nround(as.numeric(ggplot_build(dodged)$data[[1]]$xmin), 2)\nround(as.numeric(ggplot_build(dodged)$data[[1]]$xmax), 2)"],
  ["code","[1] \"PositionDodge\"\n[1] 0.55 1.00 1.55 2.00 2.55 3.00\n[1] 1.00 1.45 2.00 2.45 3.00 3.45"],
  ["p","The heights are untouched and the widths moved: at the first category two half-width bars sit at 0.55 to 1.00 and 1.00 to 1.45 rather than one bar from 0.55 to 1.45. Position jitter is the odd one out — it adds a small random offset so that points landing on identical values stop hiding each other. Random means it draws differently every time unless you fix a seed."],
  ["code","jittered <- ggplot(stalls, aes(x = cuisine, y = price)) +\n  geom_point(position = position_jitter(width = 0.2, seed = 7))\n\nclass(jittered$layers[[1]]$position)[1]\njittered$layers[[1]]$position$width\njittered$layers[[1]]$position$seed"],
  ["code","[1] \"PositionJitter\"\n[1] 0.2\n[1] 7"],
  ["note","The string form and the function form are not interchangeable once you want to configure anything. position = \"jitter\" is legal and gives you the defaults; the moment you need a width or a seed you have to write position = position_jitter(width = 0.2). Passing width straight to geom_point() sets the geom's own width instead and the jitter stays at its default, with no error to tell you."]
]},
{ t: "Coordinate systems",
  body: [
  ["p","The coordinate system maps the built numbers onto the page. The default is Cartesian: x runs left to right, y runs bottom to top, and distances are whatever the panel's shape makes them. Changing it is the last of the seven slots, and like the others it has a class you can read."],
  ["code","class(pts$coordinates)[1]\nclass((pts + coord_flip())$coordinates)[1]\nclass((bars + coord_polar())$coordinates)[1]"],
  ["code","[1] \"CoordCartesian\"\n[1] \"CoordFlip\"\n[1] \"CoordPolar\""],
  ["p","coord_flip() swaps the axes at drawing time, which is how you get horizontal bars with long category labels that fit. coord_polar() bends the x axis into a circle, turning a stacked bar into a pie and a set of bars into a wind rose. coord_fixed() forces a fixed ratio between one unit of y and one unit of x, which matters when both axes are the same kind of quantity."],
  ["code","fixed <- pts + coord_fixed(ratio = 2)\n\nclass(fixed$coordinates)\nfixed$coordinates$ratio"],
  ["code","[1] \"CoordCartesian\" \"Coord\"          \"ggproto\"        \"gg\"            \n[1] 2"],
  ["p","There is no CoordFixed in that vector. coord_fixed() returns an ordinary Cartesian coordinate system carrying a ratio, so the way to tell a fixed plot from a plain one is the ratio slot, which is NULL when you did not set one. coord_flip() by contrast does have its own class, sitting in front of CoordCartesian."],
  ["p","A CoordFixed object does exist in ggplot2, which is what makes the guess reasonable. It is simply not what coord_fixed() hands back."],
  ["code","inherits(coord_fixed(), \"CoordFixed\")\nclass(CoordFixed)[1]"],
  ["code","[1] FALSE\n[1] \"CoordFixed\""],
  ["p","Changing coordinates does not change the data. The build still produces the same twelve rows with the same y values; only the drawing differs."],
  ["code","flipped <- pts + coord_flip()\n\nnrow(ggplot_build(flipped)$data[[1]])\nidentical(ggplot_build(pts)$data[[1]]$y, ggplot_build(flipped)$data[[1]]$y)"],
  ["code","[1] 12\n[1] TRUE"],
  ["note","Testing class(p$coordinates)[1] against \"CoordFixed\" will never match, even though the name is spelled correctly and the object it names is real. The same trap catches coord_cartesian(xlim = c(0, 10)), which is also just CoordCartesian with a slot filled in. When you want to know whether a coordinate system was customised, look at the slot you set rather than at the class name."]
]},
{ t: "The layered grammar of graphics",
  body: [
  ["p","All seven parts, on one object. Build a plot that sets each of them deliberately and then read them back in order: the data, the mapping, the geom, the stat, the position, the facet, the coordinate system."],
  ["code","full <- ggplot(stalls, aes(x = cuisine, y = price, fill = venue)) +\n  geom_boxplot(position = position_dodge(width = 0.8)) +\n  facet_wrap(~venue) +\n  coord_flip()\n\nnrow(full$data)\nnames(full$mapping)\nclass(full$layers[[1]]$geom)[1]\nclass(full$layers[[1]]$stat)[1]\nclass(full$layers[[1]]$position)[1]\nclass(full$facet)[1]\nclass(full$coordinates)[1]"],
  ["code","[1] 12\n[1] \"x\"    \"y\"    \"fill\"\n[1] \"GeomBoxplot\"\n[1] \"StatBoxplot\"\n[1] \"PositionDodge\"\n[1] \"FacetWrap\"\n[1] \"CoordFlip\""],
  ["p","Seven answers to seven questions, and no part of that plot is a mystery. The point of the grammar is that the same seven questions apply to a plot you never wrote, so an unfamiliar chart can be taken apart rather than guessed at."],
  ["p","The plainest possible scatterplot has the same seven slots filled with defaults. Nothing was left out of it; four choices were simply made on your behalf."],
  ["code","class(pts$layers[[1]]$stat)[1]\nclass(pts$layers[[1]]$position)[1]\nclass(pts$coordinates)[1]\nclass(pts$facet)[1]"],
  ["code","[1] \"StatIdentity\"\n[1] \"PositionIdentity\"\n[1] \"CoordCartesian\"\n[1] \"FacetNull\""],
  ["p","Because a layer is a geom and a stat together, either one can name the layer. geom_bar() means the bar geom with its default stat; stat_count() means the counting stat with its default geom. Written the second way and given the same geom, the two produce the same layer."],
  ["code","bygeom <- ggplot(stalls, aes(x = cuisine)) + geom_bar()\nbystat <- ggplot(stalls, aes(x = cuisine)) + stat_count(geom = \"bar\")\n\nclass(bystat$layers[[1]]$geom)[1]\nclass(bystat$layers[[1]]$stat)[1]\nidentical(ggplot_build(bygeom)$data[[1]]$count, ggplot_build(bystat)$data[[1]]$count)"],
  ["code","[1] \"GeomBar\"\n[1] \"StatCount\"\n[1] TRUE"],
  ["note","Every geom_ function has a stat argument and every stat_ function has a geom argument, so there are two spellings of nearly every layer. That is worth knowing when you read someone else's code and worth ignoring when you write your own: pick the geom_ form, since the mark is usually what you are thinking about."]
]},
{ t: "Summary",
  body: [
  ["p","A ggplot has seven parts. The data and the aesthetic mappings say what is being shown; the geom says what shape the marks take; the stat is the calculation between data and marks; the position resolves collisions between marks; the facet splits the plot into panels; the coordinate system puts the result on the page. Five of the seven have defaults, which is why a three-part description of a plot works until it does not."],
  ["p","Mappings live in two places and the difference is real. An aes() inside ggplot() reaches every layer, including layers added later, which is why a plot-level colour turns one trend line into one per group. An aes() inside a geom reaches that layer alone. Stats are what makes geom_bar() different from geom_col(): StatCount computes the heights, StatIdentity takes yours, and handing a y to the one that counts is an error about the stat, not about the bar."],
  ["p","Everything above was checked by reading the object rather than by looking at a picture: length(p$layers), names(p$mapping), class of the layer's geom, stat, and position, class(p$facet)[1], class(p$coordinates)[1], and ggplot_build() for the numbers a stat produced and the panels a facet made. Two traps are worth remembering — a plot that assembles cleanly has not been checked, since nothing has read the data until the build, and coord_fixed() reports CoordCartesian rather than the CoordFixed you would expect."],
  ["p","Answer the practice questions from memory before revealing the answers, then clear the graded exercises below. The next chapter is exploratory data analysis: using counts, summaries, and plots to ask what varies in a table, what varies together, and which values do not belong."]
]}
],
questions: [
{ q:"Name the seven parts of a ggplot and say which ones you usually leave to defaults.",
  a:"Data, aesthetic mappings, geom, stat, position adjustment, facet, and coordinate system. You normally supply the data, the mapping, and the geom; the stat, position, facet, and coordinate system come from defaults — StatIdentity, PositionIdentity, FacetNull, and CoordCartesian for a plain scatterplot." },
{ q:"aes(colour = cuisine) is written inside geom_point() rather than inside ggplot(). What do names(p$mapping) and names(p$layers[[1]]$mapping) report?",
  a:"\"x\" \"y\" for the plot and \"colour\" for the layer. A mapping given to a geom is stored on that layer, not on the plot; the two are merged only when the plot is drawn." },
{ q:"Why does moving colour = cuisine from geom_point() up into ggplot() change a single trend line into three?",
  a:"A plot-level mapping reaches every layer, including geom_smooth(). Mapping colour to a categorical column splits the data into groups, and a layer that fits a model fits one per group — length(unique(ggplot_build(p)$data[[2]]$group)) goes from 1 to 3." },
{ q:"How do you find out how many panels a faceted plot has, and why is the answer not on the facet itself?",
  a:"nrow(ggplot_build(p)$layout$layout). The panel layout is worked out during the build, from the values actually present in the data, so the facet object only stores which columns to split on — names(p$facet$params$facets) for facet_wrap, or params$rows and params$cols for facet_grid." },
{ q:"What is the difference between geom_bar() and geom_col(), in terms of the grammar?",
  a:"Only the stat. geom_bar() uses StatCount, which counts rows per category and produces the heights itself, so it takes an x and no y. geom_col() uses StatIdentity and draws the y you supply. geom_bar(stat = \"identity\") is the same layer as geom_col()." },
{ q:"ggplot_build(p) on a bar chart of one categorical column returns what, and where are the bar heights?",
  a:"A built plot whose $data is a list with one data frame per layer. For the bar layer, $data[[1]] has one row per bar and a count column holding the heights — 5, 4, 3 for the stalls table — alongside columns like prop and flipped_aes that the stat also produced." },
{ q:"geom_bar() is handed both an x and a y and ggplot_build() stops. What is the error, and what is it really about?",
  a:"Error: Problem while computing stat. StatCount computes the y itself, so a supplied y leaves it with two answers. The word to read is stat: the fix is geom_col(), or geom_bar(stat = \"identity\")." },
{ q:"For a bar chart with fill mapped to a second column, what do PositionStack, PositionFill, and PositionDodge each do to the built data?",
  a:"Stack leaves the widths alone and sets ymin and ymax so segments sit on top of each other — 0 to 2 then 2 to 5. Fill rescales every bar so ymax reaches 1 and the boundaries become proportions. Dodge leaves the heights alone and changes xmin and xmax so the segments sit side by side at half width." },
{ q:"Why does class(p$coordinates)[1] report \"CoordCartesian\" on a plot built with coord_fixed(ratio = 2)?",
  a:"Because coord_fixed() does not return an object of that class. It hands back an ordinary Cartesian coordinate system with its ratio slot filled in, so the test is p$coordinates$ratio rather than the class name. A CoordFixed object does exist in ggplot2, which is what makes the wrong guess tempting — inherits(coord_fixed(), \"CoordFixed\") is FALSE all the same. coord_flip() by contrast does have its own class, CoordFlip, ahead of CoordCartesian." },
{ q:"Name two mistakes that leave a plot object looking healthy and fail only when it is drawn.",
  a:"Mapping a continuous column to shape, and misspelling a column inside aes(). Both assemble with the layer intact — length(p$layers) is 1 — and both stop at ggplot_build() with Error: Problem while computing aesthetics. Building a plot never reads the data, so an object that assembled cleanly has not been checked." }
],
exercises: [
{ c:"ggplot2 basics", t:"Where the mapping lives", book:"r09",
  b:"Attach ggplot2 and tibble. Build a tibble named lifts with minutes holding 4, 7, 9, 12, 15, 18; load_kg holding 120, 180, 210, 260, 300, 340; and crew holding \"dawn\", \"dawn\", \"dawn\", \"dusk\", \"dusk\", \"dusk\". Map minutes to x and load_kg to y at the plot level. Add a point layer that maps crew to colour on the layer itself, then add a straight-line smooth with method \"lm\" and se turned off. Store it in p and print, on four lines, the names of the plot's mapping, the names of the first layer's mapping, the number of layers, and the class of the second layer's geom (first element only).",
  o:"[1] \"x\" \"y\"\n[1] \"colour\"\n[1] 2\n[1] \"GeomSmooth\"",
  h:["Two aes() calls, in two different places. One goes to ggplot(), the other goes inside the geom.",
     "A mapping written inside a geom is stored on that layer, so p$mapping and p$layers[[1]]$mapping are two separate lists. Layers are numbered in the order you added them.",
     "The plot call takes aes(x = , y = ) only. The point layer takes its own aes() with colour in it. Then four single expressions: names() of the plot mapping, names() of the first layer's mapping, length() of the layers, and class() of the second layer's geom subset with [1]."]},
{ c:"ggplot2 basics", t:"A grid of panels", book:"r09",
  b:"Attach ggplot2 and tibble. Build a tibble named orchards with tree holding \"a\" through \"l\" in order; yield_kg holding 31, 44, 27, 38, 52, 19, 41, 36, 48, 25, 33, 57; block holding \"east\" six times then \"west\" six times; and season holding \"spring\", \"spring\", \"summer\", \"summer\", \"autumn\", \"autumn\" twice over. Plot tree against yield_kg with points, then split it into a grid with block down the rows and season across the columns. Store it in p and print the class of the facet (first element), the name of the row variable, the name of the column variable, and the number of panels.",
  o:"[1] \"FacetGrid\"\n[1] \"block\"\n[1] \"season\"\n[1] 6",
  h:["facet_grid() takes one formula holding both columns, and the tilde separates rows from columns.",
     "The facet stores which columns it splits on, in p$facet$params$rows and p$facet$params$cols, and names() reads a name out of each. The panel count is not stored there — it is worked out during the build.",
     "The facet call has the shape facet_grid(rows ~ cols). For the panel count, ggplot_build(p)$layout$layout is a data frame with one row per panel."]},
{ c:"ggplot2 basics", t:"Bars scaled to one", book:"r09",
  b:"Attach ggplot2 and tibble. Build a tibble named routes with depot holding \"harbour\" four times, \"ridge\" three times, and \"summit\" three times; and mode holding \"van\", \"van\", \"van\", \"bike\", \"van\", \"bike\", \"bike\", \"van\", \"van\", \"bike\" in that order. Map depot to x and mode to fill, add a bar layer whose segments are rescaled so every bar reaches the same height, and store it in p. Print the class of the layer's position (first element), the class of its stat (first element), and the layer's ymax values rounded to 3 decimal places.",
  o:"[1] \"PositionFill\"\n[1] \"StatCount\"\n[1] 1.000 0.750 1.000 0.333 1.000 0.667",
  h:["Bars that all reach the same height are a position adjustment, not a different geom. It is passed to the geom as an argument.",
     "The position and the stat both sit on the layer, at p$layers[[1]]$position and p$layers[[1]]$stat, and each needs class() with [1]. The heights the layer will draw come from ggplot_build().",
     "The bar layer takes position = \"fill\". For the numbers, ggplot_build(p)$data[[1]] is a data frame and ymax is the column to round."]},
{ c:"data frames", t:"Reading the bins back", book:"r09",
  b:"Attach ggplot2 and tibble. Build a tibble named hauls with boat holding \"Ada\", \"Brig\", \"Coot\", \"Dory\", \"Egret\", \"Fern\", \"Gull\", \"Hake\", \"Isle\", \"Jetty\" and weight_kg holding 3, 6, 8, 11, 12, 14, 17, 19, 22, 27. Map weight_kg to x and add a histogram layer with a bin width of 5. Store the plot in p, then pull the built layer's data frame down to just the xmin, xmax, and count columns, store that in bins, and print it.",
  o:"  xmin xmax count\n1  2.5  7.5     2\n2  7.5 12.5     3\n3 12.5 17.5     2\n4 17.5 22.5     2\n5 22.5 27.5     1",
  h:["The bin edges and the counts are computed by the layer's stat, so they do not exist until the plot is built.",
     "ggplot_build(p)$data[[1]] is an ordinary data frame with one row per bar. Selecting columns from a data frame uses the bracket form with a column vector after the comma.",
     "Build the plot, then subset with df[, c(\"xmin\", \"xmax\", \"count\")], assign that to bins, and put bins on a line of its own to print it."]}
]
};
