/* Practice Log book — R Chapter 10: Exploratory data analysis.
   Original lesson text following the chapter-by-chapter curriculum of
   "R for Data Science" (2nd ed.) by Hadley Wickham, Mine Cetinkaya-Rundel,
   and Garrett Grolemund. Read the original chapter free at the src link below.
   Every shown output was captured by executing the code in WebR, not written from memory. */
window.BOOK_R = window.BOOK_R || { chapters: {} };
window.BOOK_R.chapters.r10 = {
n: 10,
title: "Exploratory data analysis",
src: "https://r4ds.hadley.nz/EDA.html",
blurb: "Asking a table what varies, what varies together, which values do not belong, and which are not there at all.",
pkgs: ["ggplot2", "tibble", "dplyr"],
sections: [
{ t: "Questions worth asking",
  body: [
  ["p","Exploratory data analysis is not a procedure with a fixed order. It is a loop: ask a question about the data, answer it with a count or a summary or a plot, and let the answer suggest the next question. Most questions you will ask are versions of two. What varies within one column, and what varies together between two columns. Everything in this chapter is one of those two questions pointed at a different pair of columns."],
  ["p","The loop is meant to be cheap and slightly wasteful. Most of what you compute you will throw away. That is fine — the output of exploration is not a chart, it is knowing what your data actually contains, including the parts that are wrong."],
  ["note","This app grades text, and most EDA output is text anyway: counts, quantiles, group summaries. Where a plot is the right tool the plot is still built here, and inspected rather than drawn — a plot object printed on its own produces no text in this app's R console. The one exception is worth knowing: when drawing a plot raises a warning, the warning does appear, and section 5 shows one. Run this code in R on a desktop when you want to see the pictures."],
  ["p","Three packages. dplyr supplies count, filter, mutate, group_by, and summarise; ggplot2 and tibble are as before. Attaching dplyr normally prints a paragraph about masked functions, because it replaces base R's filter and lag with its own. suppressMessages keeps that paragraph out of the transcript."],
  ["code","suppressMessages(library(dplyr))\nlibrary(ggplot2)\nlibrary(tibble)"],
  ["p","The table below holds thirty water samples taken from three ponds. Each row records the pond, the water temperature in degrees Celsius, the clarity in centimetres, and the weather at the time. It is small enough to read and large enough to have the problems real tables have — two broken sensor readings and four gaps."],
  ["code","samples <- tibble(\n  pond = c(rep(\"alder\", 12), rep(\"birch\", 10), rep(\"cedar\", 8)),\n  temp_c = c(12.4, 13.1, 12.8, 14.0, 13.6, 12.2, 91.4, 13.9, 12.5, 14.4, 13.2, 12.9,\n             16.8, 17.2, 16.1, 18.0, 17.5, 16.4, 17.9, 16.6, 17.1, 0.4,\n             20.3, 21.1, 19.8, 20.9, 21.6, 20.1, 19.5, 20.7),\n  clarity_cm = c(48, 52, NA, 55, 49, 51, 47, NA, 53, 50, 54, 46,\n                 71, 68, 74, NA, 70, 72, 69, 75, 67, 73,\n                 88, 91, 85, 90, NA, 87, 92, 86),\n  weather = c(\"clear\", \"clear\", \"cloudy\", \"rain\", \"clear\", \"cloudy\",\n              \"clear\", \"rain\", \"cloudy\", \"clear\", \"cloudy\", \"rain\",\n              \"clear\", \"cloudy\", \"clear\", \"rain\", \"cloudy\", \"clear\",\n              \"clear\", \"rain\", \"cloudy\", \"clear\",\n              \"clear\", \"clear\", \"cloudy\", \"rain\", \"clear\", \"cloudy\",\n              \"clear\", \"rain\")\n)\n\nsamples"],
  ["code","# A tibble: 30 × 4\n   pond  temp_c clarity_cm weather\n   <chr>  <dbl>      <dbl> <chr>  \n 1 alder   12.4         48 clear  \n 2 alder   13.1         52 clear  \n 3 alder   12.8         NA cloudy \n 4 alder   14           55 rain   \n 5 alder   13.6         49 clear  \n 6 alder   12.2         51 cloudy \n 7 alder   91.4         47 clear  \n 8 alder   13.9         NA rain   \n 9 alder   12.5         53 cloudy \n10 alder   14.4         50 clear  \n# ℹ 20 more rows"],
  ["p","A tibble prints ten rows and tells you how many it held back. Two of the problems are already visible in those ten — the NA in row 3 and the 91.4 in row 7 — which is luck rather than method. glimpse() turns the table on its side and shows the start of every column at once, which is the better first look when a table is wide."],
  ["code","glimpse(samples)"],
  ["code","Rows: 30\nColumns: 4\n$ pond       <chr> \"alder\", \"alder\", \"alder\", \"alder\", \"alder\", \"alder\", \"alde…\n$ temp_c     <dbl> 12.4, 13.1, 12.8, 14.0, 13.6, 12.2, 91.4, 13.9, 12.5, 14.4,…\n$ clarity_cm <dbl> 48, 52, NA, 55, 49, 51, 47, NA, 53, 50, 54, 46, 71, 68, 74,…\n$ weather    <chr> \"clear\", \"clear\", \"cloudy\", \"rain\", \"clear\", \"cloudy\", \"cle…"],
  ["p","Thirty rows, four columns, two of them numbers and two of them labels. That is the map. The rest of the chapter works one column, then one pair of columns, at a time."]
]},
{ t: "Variation",
  body: [
  ["p","Variation is the tendency of a column's values to change from row to row. For a categorical column, describing the variation means counting how often each value appears. count() does exactly that and returns a tibble, which is more useful than table()'s printed grid because you can pipe it onwards."],
  ["code","count(samples, pond)"],
  ["code","# A tibble: 3 × 2\n  pond      n\n  <chr> <int>\n1 alder    12\n2 birch    10\n3 cedar     8"],
  ["p","Twelve, ten, and eight. Uneven group sizes are worth noticing early, because every comparison later in the chapter is between groups of different sizes, and a count of 5 means something different out of 12 than out of 8."],
  ["p","For a numeric column, describing the variation means asking where the values sit and how far they spread. summarise() reduces a column to one row of answers, and n() counts the rows that went in."],
  ["code","summarise(samples,\n  n = n(),\n  lo = min(temp_c),\n  med = median(temp_c),\n  hi = max(temp_c)\n)"],
  ["code","# A tibble: 1 × 4\n      n    lo   med    hi\n  <int> <dbl> <dbl> <dbl>\n1    30   0.4  16.7  91.4"],
  ["p","A median of 16.7 with a minimum of 0.4 and a maximum of 91.4. Pond water does not reach 91 degrees, and the water in a pond that has been sampled thirty times does not drop to 0.4 either. Two of these numbers are wrong, and the fact that the summary makes that obvious in one line is the point of computing it before anything else."],
  ["p","A histogram is the usual next step, and its bins are numbers you can read even when the drawing is not available. Give it a bin width and read the built layer back."],
  ["code","h <- ggplot(samples, aes(x = temp_c)) + geom_histogram(binwidth = 5)\n\nggplot_build(h)$data[[1]][, c(\"xmin\", \"xmax\", \"count\")]"],
  ["code","   xmin xmax count\n1  -2.5  2.5     1\n2   2.5  7.5     0\n3   7.5 12.5     3\n4  12.5 17.5    15\n5  17.5 22.5    10\n6  22.5 27.5     0\n7  27.5 32.5     0\n8  32.5 37.5     0\n9  37.5 42.5     0\n10 42.5 47.5     0\n11 47.5 52.5     0\n12 52.5 57.5     0\n13 57.5 62.5     0\n14 62.5 67.5     0\n15 67.5 72.5     0\n16 72.5 77.5     0\n17 77.5 82.5     0\n18 82.5 87.5     0\n19 87.5 92.5     1"],
  ["note","Nineteen bins, fourteen of them empty, and twenty-five of the thirty samples crammed into two bars. That is what a single bad value does to a histogram: the range stretches to cover it, and the shape you wanted to see collapses into two columns. The mistake is concluding the data is boring. The distribution is fine; the axis is being held open by one number."]
]},
{ t: "Typical values",
  body: [
  ["p","Once the range is known, the question becomes which values are common and which are rare. cut_width() chops a numeric column into equal-width intervals, and counting those intervals gives the same information a histogram carries, as text."],
  ["code","count(samples, bin = cut_width(temp_c, width = 5, boundary = 0))"],
  ["code","# A tibble: 5 × 2\n  bin         n\n  <fct>   <int>\n1 [0,5]       1\n2 (10,15]    11\n3 (15,20]    11\n4 (20,25]     6\n5 (90,95]     1"],
  ["p","Five rows, not nineteen. count() drops groups that are empty, so the intervals holding nothing simply do not appear. That is more readable and slightly dishonest: the gap between 25 and 90 is real information about the data, and here it shows up as an absence rather than as a row. Setting .drop to FALSE keeps every level of the factor cut_width made."],
  ["code","count(samples, bin = cut_width(temp_c, width = 5, boundary = 0), .drop = FALSE)"],
  ["code","# A tibble: 19 × 2\n   bin         n\n   <fct>   <int>\n 1 [0,5]       1\n 2 (5,10]      0\n 3 (10,15]    11\n 4 (15,20]    11\n 5 (20,25]     6\n 6 (25,30]     0\n 7 (30,35]     0\n 8 (35,40]     0\n 9 (40,45]     0\n10 (45,50]     0\n11 (50,55]     0\n12 (55,60]     0\n13 (60,65]     0\n14 (65,70]     0\n15 (70,75]     0\n16 (75,80]     0\n17 (80,85]     0\n18 (85,90]     0\n19 (90,95]     1"],
  ["p","Both views are true and they answer different questions. The dropped version tells you where the data is; the full version tells you how much emptiness sits between the clusters. Now narrow the window to the part of the range that looks like real measurements, and use a smaller bin so the shape has room to appear."],
  ["code","samples |>\n  filter(temp_c < 40) |>\n  count(bin = cut_width(temp_c, width = 2, boundary = 0)) |>\n  arrange(bin)"],
  ["code","# A tibble: 6 × 2\n  bin         n\n  <fct>   <int>\n1 [0,2]       1\n2 (12,14]    10\n3 (14,16]     1\n4 (16,18]     9\n5 (18,20]     2\n6 (20,22]     6"],
  ["p","Three clumps — ten samples near 13, nine near 17, six near 21 — with thin gaps between them. Clusters like that are a question, not an answer: something is dividing these samples into three kinds, and section 6 finds out what. Note also the row that says [0,2] holds 1. Filtering on temp_c under 40 removed the 91.4 and left the 0.4 exactly where it was, which is the sort of half-fix that survives a whole analysis if nobody prints the result."],
  ["note","cut_width(temp_c, width = 5) without boundary picks its own alignment, so bins can come out as (7.5,12.5] instead of (10,15] and the counts shift. Set boundary to a round number when you want intervals a reader can predict. The mistake is comparing two of these tables built with different alignments and reading the difference as a change in the data."]
]},
{ t: "Unusual values",
  body: [
  ["p","An unusual value is one that does not fit the pattern the rest of the column follows. Some are real and interesting; some are measurement faults. You cannot tell which from the number alone, and deciding is a judgement about the thing being measured, not a calculation. What the computer can do is find them. quantile() gives the five-number summary in one line."],
  ["code","quantile(samples$temp_c)"],
  ["code","    0%    25%    50%    75%   100% \n 0.400 13.300 16.700 19.725 91.400 "],
  ["p","The middle half of the samples sits between 13.3 and 19.725, a span of about six and a half degrees. The two ends are 0.4 and 91.4. A value more than a couple of interquartile ranges outside the quartiles deserves a look; these are both many times that. Pull them out and look at whole rows, because the rest of the row is where the explanation usually is."],
  ["code","filter(samples, temp_c > 40 | temp_c < 5)"],
  ["code","# A tibble: 2 × 4\n  pond  temp_c clarity_cm weather\n  <chr>  <dbl>      <dbl> <chr>  \n1 alder   91.4         47 clear  \n2 birch    0.4         73 clear  "],
  ["p","Both rows have a sensible clarity and a sensible weather. Only the temperature is impossible, which points at the temperature sensor rather than at the sample. That is the case for replacing the two temperatures with NA and keeping everything else the rows have to offer."],
  ["code","clean <- mutate(samples, temp_c = if_else(temp_c > 40 | temp_c < 5, NA, temp_c))\n\nsummarise(clean,\n  faults = sum(is.na(temp_c)),\n  lo = min(temp_c, na.rm = TRUE),\n  med = median(temp_c, na.rm = TRUE),\n  hi = max(temp_c, na.rm = TRUE)\n)"],
  ["code","# A tibble: 1 × 4\n  faults    lo   med    hi\n   <int> <dbl> <dbl> <dbl>\n1      2  12.2  16.7  21.6"],
  ["p","Now the range is 12.2 to 21.6, which is what pond water does, and the median has not moved at all — 16.7 before and after. A median ignores how far away the extremes are, so it was already telling the truth while the mean and the range were not. That is the reason to reach for the median first when you have not yet checked for faults."],
  ["note","The tempting fix is filter(samples, temp_c < 40), which throws away the entire row. Doing that loses a perfectly good clarity reading and a perfectly good weather value along with the bad temperature, and it quietly changes the group sizes you counted in section 2. Replace the single wrong cell with NA and let each calculation decide what to do about it."]
]},
{ t: "Missing values",
  body: [
  ["p","NA means the value is not known. It is not zero and it is not an error, and R propagates it: any arithmetic touching an NA gives NA, because the answer genuinely is not known. That is a safety feature and it is also how a whole summary turns into a single NA."],
  ["code","summarise(samples,\n  gaps = sum(is.na(clarity_cm)),\n  mean_raw = mean(clarity_cm),\n  mean_ok = mean(clarity_cm, na.rm = TRUE)\n)"],
  ["code","# A tibble: 1 × 3\n   gaps mean_raw mean_ok\n  <int>    <dbl>   <dbl>\n1     4       NA    67.8"],
  ["p","Four gaps, and the plain mean is NA. na.rm = TRUE drops them and gives 67.8, which is the mean of the twenty-six readings that exist. Both answers are correct; they answer different questions, and the second one only means something once you know how many rows it quietly ignored. Counting the gaps per group is how you find out whether they are spread evenly or concentrated somewhere."],
  ["code","samples |>\n  group_by(pond) |>\n  summarise(n = n(), gaps = sum(is.na(clarity_cm))) |>\n  arrange(pond)"],
  ["code","# A tibble: 3 × 3\n  pond      n  gaps\n  <chr> <int> <int>\n1 alder    12     2\n2 birch    10     1\n3 cedar     8     1"],
  ["p","Roughly even, so dropping the gaps will not tilt a comparison between ponds. Had all four been in one pond, that pond's average would be built on much thinner evidence than the others, and the comparison would need saying so. The next thing to know is that filter() drops rows where the condition is NA, because NA is not TRUE."],
  ["code","nrow(samples)\nnrow(filter(samples, clarity_cm > 60))\nnrow(filter(samples, clarity_cm <= 60))"],
  ["code","[1] 30\n[1] 16\n[1] 10"],
  ["p","Sixteen and ten make twenty-six, not thirty. The four rows with no clarity reading are in neither half, because the question was never answered for them. Nothing warned you. ggplot2 is more talkative: it drops missing values too, and says how many when it draws."],
  ["code","ggplot(clean, aes(x = temp_c)) + geom_histogram(binwidth = 2)"],
  ["code","Warning: Removed 2 rows containing non-finite outside the scale range (`stat_bin()`)."],
  ["note","That warning is the whole visible output of the block above, because a plot object produces no text of its own here. Treat the number in it as a fact worth checking rather than noise to scroll past: two removed rows out of thirty is the two sensor faults, and a plot that silently removed a third of the data would look exactly as convincing. The complementary-filter trap is the same problem without the warning — whenever two filters that ought to partition a table do not add up to nrow(), the difference is NAs."]
]},
{ t: "Covariation: a category and a number",
  body: [
  ["p","Covariation is the tendency of two columns to change together. The most common pairing is one categorical column and one numeric one, and the question is whether the numbers differ by group. Section 3 found three clumps of temperature with no explanation; pond is the obvious candidate."],
  ["code","clean |>\n  group_by(pond) |>\n  summarise(\n    n = n(),\n    med = median(temp_c, na.rm = TRUE),\n    iqr = IQR(temp_c, na.rm = TRUE)\n  ) |>\n  arrange(pond)"],
  ["code","# A tibble: 3 × 4\n  pond      n   med   iqr\n  <chr> <int> <dbl> <dbl>\n1 alder    12  13.1 1.1  \n2 birch    10  17.1 0.900\n3 cedar     8  20.5 0.925"],
  ["p","Three medians about four degrees apart, and three interquartile ranges around one degree. The gaps between the ponds are three to four times the spread within any of them, which is what makes the three clumps in section 3 the three ponds. Reporting the spread alongside the middle is what turns a difference into a claim worth making — three medians on their own would say nothing about whether the groups overlap."],
  ["p","A boxplot draws that same comparison, and its stat computes the same medians. Note what the transcript contains: the warning about the two dropped faults, and then the numbers."],
  ["code","b <- ggplot(clean, aes(x = pond, y = temp_c)) + geom_boxplot()\n\nclass(b$layers[[1]]$stat)[1]\nggplot_build(b)$data[[1]]$middle"],
  ["code","[1] \"StatBoxplot\"\nWarning: Removed 2 rows containing non-finite outside the scale range\n(`stat_boxplot()`).\n[1] 13.1 17.1 20.5"],
  ["p","The middles are 13.1, 17.1, and 20.5, matching the summarise() above exactly, which is the check worth doing whenever a plot and a table are supposed to say the same thing. Ordering the groups by the thing being measured, rather than alphabetically, is what makes a comparison readable."],
  ["code","clean |>\n  group_by(pond) |>\n  summarise(med = median(temp_c, na.rm = TRUE)) |>\n  arrange(desc(med))"],
  ["code","# A tibble: 3 × 2\n  pond    med\n  <chr> <dbl>\n1 cedar  20.5\n2 birch  17.1\n3 alder  13.1"],
  ["note","Three ponds sort into a sensible order by accident here, because alder, birch, and cedar happen to run coolest to warmest in alphabetical order too. With ten groups it will not happen, and a reader given an alphabetical axis has to do the sorting in their head. arrange(desc()) fixes a table; for a plot the equivalent is turning the column into a factor whose levels are in the order you want."]
]},
{ t: "Two categories, and two numbers",
  body: [
  ["p","Two categorical columns covary if the mix of one differs across the values of the other. count() takes both columns and returns one row per observed combination, which is the cross-tabulation in tidy form."],
  ["code","count(samples, pond, weather) |> arrange(pond, weather)"],
  ["code","# A tibble: 9 × 3\n  pond  weather     n\n  <chr> <chr>   <int>\n1 alder clear       5\n2 alder cloudy      4\n3 alder rain        3\n4 birch clear       5\n5 birch cloudy      3\n6 birch rain        2\n7 cedar clear       4\n8 cedar cloudy      2\n9 cedar rain        2"],
  ["p","Nine rows of counts that are hard to compare directly, because the three ponds were sampled a different number of times. Five clear days out of twelve is not the same as five out of ten. Dividing by the group total turns the counts into shares, which is the comparison you actually wanted."],
  ["code","samples |>\n  count(pond, weather) |>\n  group_by(pond) |>\n  mutate(share = round(n / sum(n), 3)) |>\n  ungroup() |>\n  arrange(pond, weather)"],
  ["code","# A tibble: 9 × 4\n  pond  weather     n share\n  <chr> <chr>   <int> <dbl>\n1 alder clear       5 0.417\n2 alder cloudy      4 0.333\n3 alder rain        3 0.25 \n4 birch clear       5 0.5  \n5 birch cloudy      3 0.3  \n6 birch rain        2 0.2  \n7 cedar clear       4 0.5  \n8 cedar cloudy      2 0.25 \n9 cedar rain        2 0.25 "],
  ["p","The shares are close: clear weather runs from 0.417 to 0.5 across the three ponds, rain from 0.2 to 0.25. With group sizes of twelve, ten, and eight, differences that small are what you would expect from nothing at all. That is a real finding and the useful kind — weather is not what separates these ponds."],
  ["p","Two numeric columns covary in a way one number can summarise. cor() reports how tightly they move together, from -1 to 1, and needs telling what to do about the missing values."],
  ["code","round(cor(clean$temp_c, clean$clarity_cm, use = \"complete.obs\"), 3)"],
  ["code","[1] 0.962"],
  ["p","0.962 is close to the maximum, so warmer samples are clearer almost without exception. A correlation is a single number describing a straight-line relationship, and it hides everything about the shape, so back it up by binning both columns and counting the combinations."],
  ["code","clean |>\n  filter(complete.cases(temp_c, clarity_cm)) |>\n  count(warm = temp_c > 16, wide = clarity_cm > 60) |>\n  arrange(warm, wide)"],
  ["code","# A tibble: 2 × 3\n  warm  wide      n\n  <lgl> <lgl> <int>\n1 FALSE FALSE     9\n2 TRUE  TRUE     15"],
  ["p","Two rows where four were possible. Every sample above 16 degrees is also above 60 centimetres of clarity and every sample below 16 is below 60, with no exceptions in the twenty-four rows that have both readings. The two combinations that would contradict the pattern have no rows, and because count() drops empty groups, they are absent rather than shown as zero."],
  ["note","A correlation that high on a table with an obvious grouping usually means the groups are doing the work. These samples split into three ponds that differ in both temperature and clarity, so a line through all thirty measures the difference between ponds and not a relationship within them. Before reporting a correlation, check whether it survives inside each group — the next section does that with residuals."]
]},
{ t: "Patterns and models",
  body: [
  ["p","A pattern is a claim that knowing one column tells you something about another. A model makes that claim precise: it fits a rule, and what is left over after the rule has done its work is the residual. lm() fits a straight line, and its coefficients say what the line is."],
  ["code","fit <- lm(clarity_cm ~ temp_c, data = clean)\n\nround(coef(fit), 3)\nround(summary(fit)$r.squared, 3)"],
  ["code","(Intercept)      temp_c \n    -13.792       4.981 \n[1] 0.925"],
  ["p","About five centimetres of clarity per degree, and an r squared of 0.925, meaning the line accounts for most of the variation in clarity. Now the question raised at the end of the last section: is that a relationship, or is it three ponds sitting at three points on a line. Group the residuals and look at whether they cluster by pond."],
  ["code","resids <- clean |>\n  filter(complete.cases(temp_c, clarity_cm)) |>\n  mutate(resid = round(residuals(fit), 2))\n\nresids |>\n  group_by(pond) |>\n  summarise(n = n(), mean_resid = round(mean(resid), 2)) |>\n  arrange(pond)"],
  ["code","# A tibble: 3 × 3\n  pond      n mean_resid\n  <chr> <int>      <dbl>\n1 alder     9      -0.79\n2 birch     8       0.11\n3 cedar     7       0.89"],
  ["p","The mean residual moves from -0.79 at alder to 0.89 at cedar. A model that had captured everything would leave residuals with no group pattern at all, averaging near zero everywhere; this one is slightly low for the cool pond and slightly high for the warm one. The effect is small next to the range of the residuals, so the line is a decent description rather than a wrong one — but it is not the whole story, and pond is the column carrying the rest."],
  ["code","round(range(residuals(fit)), 3)"],
  ["code","[1] -7.936  8.661"],
  ["p","Residuals running from about -8 to 8.7, against group means under 1 in size. The group effect is real and it is small. Reporting both facts is more honest than reporting either one, and neither is visible from the correlation alone."],
  ["note","residuals(fit) has one value per row the model actually used, which is not the number of rows in clean — lm() drops rows with an NA in either column. Attaching residuals to a table with mutate() only works when the rows line up, which is why the filter on complete.cases comes first. Skip that filter and mutate() stops with a length error, and the version of this mistake that does not stop is worse: on a table where the lengths happen to match, the residuals get attached to the wrong rows."]
]},
{ t: "Summary",
  body: [
  ["p","Exploratory data analysis is a loop of questions, and two of them cover most ground: what varies within a column, and what varies together between columns. For a categorical column, variation is a count. For a numeric one it is a middle and a spread — summarise() with median and IQR, quantile() for the five-number summary, and cut_width() with count() when you want the shape of a distribution as text."],
  ["p","Check for unusual values before believing any summary. A range of 0.4 to 91.4 degrees is a broken sensor, not a finding, and one such value is enough to flatten a histogram into two bars. Replace the wrong cell with NA rather than dropping the whole row, and remember that missing values then travel: mean() returns NA until you pass na.rm, filter() drops rows whose condition is NA so two complementary filters stop adding up to nrow(), and ggplot2 says how many rows it removed when it draws."],
  ["p","Covariation between a category and a number is a grouped summary — the three ponds differed by about four degrees with a spread of about one, which is what made the difference worth stating. Between two categories it is counts turned into shares, since groups of different sizes cannot be compared as raw counts. Between two numbers it is a correlation backed up by something that shows the shape, and a high correlation on grouped data usually means the groups are doing the work. A model makes a pattern precise and the residuals say what it missed."],
  ["p","Answer the practice questions from memory before revealing the answers, then clear the graded exercises below. The next chapter is communication: turning the plots you built while exploring into plots someone else can read, with labels, annotations, scales, and themes chosen on purpose."]
]}
],
questions: [
{ q:"What are the two questions that most of exploratory data analysis reduces to?",
  a:"What varies within a single column, and what varies together between two columns. Variation is answered with counts for categorical columns and with a middle and a spread for numeric ones; covariation is answered with grouped summaries, shares, or a correlation, depending on which kinds of column are paired." },
{ q:"The temperature column summarises to a minimum of 0.4, a median of 16.7, and a maximum of 91.4. What do you conclude, and what does it do to a histogram?",
  a:"That two values are measurement faults rather than water temperatures. The histogram stretches its axis to cover 91.4, so at a bin width of 5 it produces 19 bins, 14 of them empty, with 25 of the 30 samples squeezed into two bars. The distribution is fine; one value is holding the axis open." },
{ q:"count() on a cut_width() column returned 5 rows the first time and 19 the second. What changed, and why does it matter?",
  a:"The second call passed .drop = FALSE, which keeps factor levels that have no rows. count() drops empty groups by default, so the intervals holding nothing simply vanish — readable, but it hides the size of the gap between the clusters and the outlier." },
{ q:"Why replace a bad temperature with NA instead of filtering the row out?",
  a:"Because only one cell is wrong. The row's clarity and weather readings are fine and filtering discards them too, and it changes the group sizes you counted earlier. mutate() with if_else() replaces the single cell and lets each later calculation decide what to do about the gap." },
{ q:"After the two faults were replaced with NA, the median of temp_c was unchanged at 16.7. Why is that not a coincidence?",
  a:"A median depends only on the rank order of the values, not on how far the extremes reach, so two values at the ends can be arbitrarily wrong without moving it. The mean and the range are not protected that way, which is the reason to look at the median first on data you have not yet checked." },
{ q:"nrow() of the table is 30, but filtering on clarity_cm > 60 gives 16 rows and filtering on clarity_cm <= 60 gives 10. Where did the other 4 go?",
  a:"They are the rows with a missing clarity. filter() keeps rows where the condition is TRUE, and a comparison against NA is NA rather than TRUE, so those rows fail both filters. Nothing warns you — whenever two complementary filters do not add up to nrow(), the difference is NAs." },
{ q:"What is the only text a ggplot produces in this app, and what should you do with it?",
  a:"A warning raised while drawing. The plot itself renders nothing here, so a line such as Removed 2 rows containing non-finite outside the scale range is the entire visible output. Read the number: it tells you how much of the data the plot silently left out." },
{ q:"Why report IQR alongside the median when comparing groups?",
  a:"Because a difference between middles only means something relative to the spread within each group. The three ponds had medians about 4 degrees apart with interquartile ranges around 1, so the gaps are three to four times the internal spread and the groups barely overlap. Three medians on their own would not support that claim." },
{ q:"Two categorical columns were counted and the counts then divided by the group total. What was wrong with the raw counts?",
  a:"The groups were different sizes — 12, 10, and 8 samples. Five clear days out of 12 is not the same proportion as 5 out of 10, so the raw counts cannot be compared across ponds. group_by() the first column and divide n by sum(n) to get shares that can." },
{ q:"clarity_cm and temp_c correlate at 0.962. Why is that not yet evidence of a relationship, and how did the chapter check?",
  a:"Because the data is three ponds that differ in both columns, so a line through all the rows can be measuring the difference between ponds rather than any relationship within them. The check was to fit the line and group the residuals: the mean residual ran from -0.79 at the coolest pond to 0.89 at the warmest, showing a small leftover group effect the line had not captured." }
],
exercises: [
{ c:"dplyr verbs", t:"Two readings that do not belong", book:"r10",
  b:"Attach dplyr with suppressMessages, and attach tibble. Build a tibble named gauges with station holding \"A1\", \"A2\", \"A3\", \"B1\", \"B2\", \"B3\", \"C1\", \"C2\", \"C3\", \"D1\", \"D2\", \"D3\" and reading holding 4.2, 4.6, 4.1, 5.0, 4.8, 512.0, 4.4, 4.9, 0.0, 5.2, 4.7, 4.5. Keep only the rows whose reading is above 10 or below 1, sort them from smallest reading to largest, and print the result.",
  o:"# A tibble: 2 × 2\n  station reading\n  <chr>     <dbl>\n1 C3            0\n2 B3          512",
  h:["Two conditions joined by or, then a sort. Both are single dplyr verbs.",
     "filter() keeps the rows where the condition is TRUE, and the vertical bar is or. arrange() sorts ascending unless you wrap the column in desc().",
     "Pipe the tibble into filter(reading > 10 | reading < 1), then into arrange(reading). Print the result rather than assigning it."]},
{ c:"grouping & summaries", t:"Middle and spread per field", book:"r10",
  b:"Attach dplyr with suppressMessages, and attach tibble. Build a tibble named harvest with field holding \"east\" four times, \"north\" three times, and \"west\" five times, and tonnes holding 3.2, 4.1, 3.8, 3.5, 5.6, 5.1, 6.0, 2.4, 2.9, 2.2, 3.1, 2.6 in that order. For each field report three columns — n holding the row count, med holding the median of tonnes, and iqr holding the interquartile range of tonnes — sorted by field, and print it.",
  o:"# A tibble: 3 × 4\n  field     n   med   iqr\n  <chr> <int> <dbl> <dbl>\n1 east      4  3.65 0.450\n2 north     3  5.6  0.45 \n3 west      5  2.6  0.5  ",
  h:["Grouping first, then one summarise() producing all three columns at once.",
     "n() counts the rows in the current group and needs no argument. The interquartile range has its own function, spelled in capitals. Column names come from the names you give inside summarise().",
     "Pipe into group_by(field), then summarise(n = n(), med = , iqr = ), then arrange(field). Nothing here needs na.rm, because this tibble has no gaps."]},
{ c:"grouping & summaries", t:"Counts that cannot be compared", book:"r10",
  b:"Attach dplyr with suppressMessages, and attach tibble. Build a tibble named tickets with line holding \"blue\" five times, \"green\" three times, and \"red\" twice, and fare holding \"adult\", \"adult\", \"child\", \"child\", \"adult\", \"adult\", \"child\", \"adult\", \"child\", \"adult\" in that order. Count every combination of line and fare, then add a column named share holding each count divided by the total for its line, rounded to 3 decimal places. Remove the grouping, sort by line then fare, and print it.",
  o:"# A tibble: 6 × 4\n  line  fare      n share\n  <chr> <chr> <int> <dbl>\n1 blue  adult     3 0.6  \n2 blue  child     2 0.4  \n3 green adult     2 0.667\n4 green child     1 0.333\n5 red   adult     1 0.5  \n6 red   child     1 0.5  ",
  h:["count() takes both columns at once and names its output column n. The share has to be computed within each line, not across the whole table.",
     "Group the counted tibble by line before computing the share, so that sum(n) means the total for that line rather than for everything. mutate() adds a column without collapsing rows.",
     "The shape is count(line, fare), then group_by(line), then mutate(share = round(n / sum(n), 3)), then ungroup(), then arrange(line, fare)."]},
{ c:"dplyr verbs", t:"Where the gaps are", book:"r10",
  b:"Attach dplyr with suppressMessages, and attach tibble. Build a tibble named loggers with site holding \"dune\" four times then \"fen\" four times, and humidity holding 62, NA, 58, 65, 81, 79, NA, NA in that order. For each site report n holding the row count, gaps holding how many humidity values are missing, and mean_ok holding the mean of the humidity values that are present, rounded to 2 decimal places. Sort by site and print it.",
  o:"# A tibble: 2 × 4\n  site      n  gaps mean_ok\n  <chr> <int> <int>   <dbl>\n1 dune      4     1    61.7\n2 fen       4     2    80  ",
  h:["Counting missing values and averaging around them are two different jobs, and each has its own idiom.",
     "is.na() returns TRUE or FALSE for every element, and summing a logical vector counts the TRUEs. mean() returns NA if any value is missing unless you tell it otherwise.",
     "Group by site, then summarise with n = n(), gaps = sum(is.na(humidity)), and a mean that takes na.rm = TRUE before being rounded."]}
]
};
