/* Practice Log book — R Chapter 11: Communication.
   Original lesson text following the chapter-by-chapter curriculum of
   "R for Data Science" (2nd ed.) by Hadley Wickham, Mine Cetinkaya-Rundel,
   and Garrett Grolemund. Read the original chapter free at the src link below.
   Every shown output was captured by executing the code in WebR, not written from memory. */
window.BOOK_R = window.BOOK_R || { chapters: {} };
window.BOOK_R.chapters.r11 = {
n: 11,
title: "Communication",
src: "https://r4ds.hadley.nz/communication.html",
blurb: "Turning a chart that works into one somebody else can read: labels, annotations, scales, zooming, themes, and saving the result.",
pkgs: ["ggplot2", "tibble"],
sections: [
{ t: "A plot that has to travel",
  body: [
  ["p","Up to now a plot has been something you made to answer your own question. You knew what the columns meant, you knew which rows were odd, and a chart with axes reading wheel_cm and weight_kg told you everything you needed. This chapter is about the other kind of plot: the one that leaves your screen. Once it does, everything you were carrying in your head has to be written on the picture instead."],
  ["p","The work divides into six jobs, and they are the sections below. Labels put words on the axes, the legend, and the top of the plot. Annotations mark the specific thing you want noticed. Scales control the numbers along an axis and the colours in a legend. Zooming decides what part of the data is in frame. Themes handle everything that is not data — the grey background, the grid, where the legend sits. And saving turns the result into a file you can send."],
  ["note","This app decides whether an answer is right by comparing text, and a chart is an image. So every output in this chapter is text read back off the plot object — the labels it will use, how many layers it holds, which scales are attached, what its coordinate system is — and never a description of a picture. A plot object printed on its own produces no text at all here, so an answer ending in a bare plot object submits nothing. Run the same code in R on a desktop when you want to see the drawings."],
  ["p","Two packages, neither of them part of base R. ggplot2 supplies the plotting functions and tibble supplies the data frame."],
  ["code","library(ggplot2)\nlibrary(tibble)"],
  ["p","The table is eight island ferry routes: a name, the crossing time in minutes, the single adult fare in euro, and which of two operators runs it."],
  ["code","crossings <- tibble(\n  route    = c(\"Aran\", \"Blasket\", \"Clare\", \"Dursey\", \"Inish\", \"Sherkin\", \"Tory\", \"Valentia\"),\n  minutes  = c(45, 25, 20, 10, 55, 15, 75, 5),\n  fare_eur = c(28, 18, 12, 8, 34, 10, 40, 4),\n  operator = c(\"north\", \"south\", \"south\", \"south\", \"north\", \"south\", \"north\", \"south\")\n)\n\ncrossings"],
  ["code","# A tibble: 8 × 4\n  route    minutes fare_eur operator\n  <chr>      <dbl>    <dbl> <chr>   \n1 Aran          45       28 north   \n2 Blasket       25       18 south   \n3 Clare         20       12 south   \n4 Dursey        10        8 south   \n5 Inish         55       34 north   \n6 Sherkin       15       10 south   \n7 Tory          75       40 north   \n8 Valentia       5        4 south   "],
  ["p","The plot underneath the whole chapter is a scatterplot of fare against crossing time, coloured by operator. It works, and get_labs() reports the three labels it will draw with."],
  ["code","p <- ggplot(crossings, aes(x = minutes, y = fare_eur, colour = operator)) +\n  geom_point()\n\nlength(p$layers)\nget_labs(p)$x\nget_labs(p)$y\nget_labs(p)$colour"],
  ["code","[1] 1\n[1] \"minutes\"\n[1] \"fare_eur\"\n[1] \"operator\""],
  ["p","Those are column names, not words. fare_eur is readable to you because you typed it; to a reader it is a variable from a script they have never seen. Nothing has been set by hand, so the labels slot on the plot is empty and there is no title at all."],
  ["code","length(p$labels)\nget_labs(p)$title"],
  ["code","[1] 0\nNULL"],
  ["p","Keep the two apart as you read the rest of the chapter. p$labels holds what you set. get_labs(p) reports what the plot will actually draw, filling in the defaults."]
]},
{ t: "Labels",
  body: [
  ["p","labs() is the function for every piece of text around the plot, and it is added with a + like any other layer. A title states the finding rather than naming the variables, a subtitle carries the detail a reader needs to trust the title, and a caption credits the data."],
  ["code","titled <- p + labs(\n  title = \"Fare rises with crossing time\",\n  subtitle = \"Eight island routes, single adult fare, 2026 timetable\",\n  caption = \"Sample data, not a real timetable\",\n  x = \"Crossing time (minutes)\",\n  y = \"Fare (EUR)\",\n  colour = \"Operator\"\n)\n\nget_labs(titled)$title\nget_labs(titled)$subtitle\nget_labs(titled)$caption"],
  ["code","[1] \"Fare rises with crossing time\"\n[1] \"Eight island routes, single adult fare, 2026 timetable\"\n[1] \"Sample data, not a real timetable\""],
  ["p","The same call named the axes and the legend. There is no separate function for a legend title: a legend belongs to an aesthetic, so the name you give that aesthetic in labs() is the heading the legend gets. Here colour = \"Operator\" retitles the colour legend."],
  ["code","get_labs(titled)$x\nget_labs(titled)$y\nget_labs(titled)$colour"],
  ["code","[1] \"Crossing time (minutes)\"\n[1] \"Fare (EUR)\"\n[1] \"Operator\""],
  ["p","Units belong in the axis label, because a reader has no other place to look for them. Fare (EUR) and Crossing time (minutes) each answer a question the number alone leaves open."],
  ["p","labs() checks the names you hand it against the aesthetics it knows about. A name it does not recognise is reported and dropped, and the plot goes on being built without it."],
  ["code","p + labs(titel = \"Fare rises with crossing time\")"],
  ["code","Ignoring unknown labels:\n• titel : \"Fare rises with crossing time\""],
  ["note","That is a message, not an error, and the plot still draws — with no title. On a desktop the picture appears immediately underneath the message, which is exactly the moment you stop reading the console. If a title you definitely wrote refuses to show up, the spelling of the argument name is the first thing to check, not the text you gave it."]
]},
{ t: "Annotations",
  body: [
  ["p","A label on the plot beats a legend the reader has to look up, and a note pointing at one observation beats a paragraph underneath. geom_text() is the geom that draws text, and it takes a label aesthetic the way geom_point() takes x and y."],
  ["code","labelled <- p + geom_text(aes(label = route))\n\nlength(labelled$layers)\nclass(labelled$layers[[2]]$geom)[1]\nnames(labelled$layers[[2]]$mapping)"],
  ["code","[1] 2\n[1] \"GeomText\"\n[1] \"label\""],
  ["p","That draws eight route names over eight points, which on this data is clutter rather than communication. Usually one observation is the point of the chart. Pick it out as a one-row table first — here the longest crossing, found with which.max()."],
  ["code","slowest <- crossings[which.max(crossings$minutes), ]\n\nslowest"],
  ["code","# A tibble: 1 × 4\n  route minutes fare_eur operator\n  <chr>   <dbl>    <dbl> <chr>   \n1 Tory       75       40 north   "],
  ["p","Then hand that table to the text layer through its own data argument. A layer given no data of its own inherits the plot's, and the placeholder ggplot2 stores for that is called a waiver. Layer one has a waiver; layer two has a single row. nudge_y lifts the text clear of the point it sits on."],
  ["code","marked <- p + geom_text(data = slowest, aes(label = route), nudge_y = 3)\n\nclass(marked$layers[[1]]$data)[1]\nnrow(marked$layers[[2]]$data)\nclass(marked$layers[[2]]$position)[1]"],
  ["code","[1] \"waiver\"\n[1] 1\n[1] \"PositionNudge\""],
  ["p","Text that is not in any data frame — a sentence you want on the plot — goes through annotate(). You give it the geom to use, the position, and the text, and it draws exactly one of them."],
  ["code","once <- p + annotate(\"text\", x = 20, y = 36, label = \"north routes charge more per minute\")\n\nlength(once$layers)\nclass(once$layers[[2]]$geom)[1]\nonce$layers[[2]]$aes_params$label\nnrow(ggplot_build(once)$data[[2]])"],
  ["code","[1] 2\n[1] \"GeomText\"\n[1] \"north routes charge more per minute\"\n[1] 1"],
  ["p","Reaching for geom_text() instead looks like it does the same thing, and the plot object even looks similar. The built data is where the two part company."],
  ["code","many <- p + geom_text(aes(label = \"north routes charge more per minute\"), x = 20, y = 36)\n\nnrow(ggplot_build(many)$data[[2]])"],
  ["code","[1] 8"],
  ["note","A constant put inside aes() is still a mapping, so it is recycled once per row: eight copies of the sentence drawn on top of each other at the same spot. On screen that reads as one label in a slightly too heavy, slightly furry typeface, which is a strange enough symptom that people blame the font. Use annotate() when the text is not in the data."]
]},
{ t: "Scales and legends",
  body: [
  ["p","Every mapped aesthetic gets a scale, and ggplot2 picks a sensible one for you based on the column's type. Those defaults are added at drawing time, so a plot you have not touched carries no scales at all."],
  ["code","length(p$scales$scales)"],
  ["code","[1] 0"],
  ["p","Adding one by hand replaces the default. The names follow a pattern — scale, then the aesthetic, then the kind of column — so the x axis of a numeric column is scale_x_continuous(). Its name argument sets the axis title, exactly as labs(x = ) does, and breaks decides which values get a tick and a number."],
  ["code","scaled <- p + scale_x_continuous(name = \"Crossing time (minutes)\", breaks = c(0, 25, 50, 75))\n\nlength(scaled$scales$scales)\nsapply(scaled$scales$scales, function(s) s$aesthetics[1])\nscaled$scales$scales[[1]]$breaks\nget_labs(scaled)$x"],
  ["code","[1] 1\n[1] \"x\"\n[1]  0 25 50 75\n[1] \"Crossing time (minutes)\""],
  ["p","Colour works the same way. scale_colour_manual() takes a named vector, one colour per level of the column, and ggplot_build() shows the colour each of the eight rows ends up with."],
  ["code","manual <- p + scale_colour_manual(values = c(north = \"navy\", south = \"darkorange\"))\n\nsapply(manual$scales$scales, function(s) s$aesthetics[1])\nggplot_build(manual)$data[[1]]$colour"],
  ["code","[1] \"colour\"\n[1] \"navy\"       \"darkorange\" \"darkorange\" \"darkorange\" \"navy\"      \n[6] \"darkorange\" \"navy\"       \"darkorange\""],
  ["p","Where the legend sits is not a property of the scale. It is a theme setting, because it is a fact about the layout rather than about the data."],
  ["code","bottom <- p + theme(legend.position = \"bottom\")\n\nbottom$theme$legend.position"],
  ["code","[1] \"bottom\""],
  ["p","Removing a legend entirely is a third thing again: guides(), which controls what each aesthetic's key looks like, or whether it appears."],
  ["code","hidden <- p + guides(colour = \"none\")\n\nnames(hidden$guides$guides)\nhidden$guides$guides$colour"],
  ["code","[1] \"colour\"\n[1] \"none\""],
  ["p","One aesthetic gets one scale. Add a second scale for the same aesthetic and ggplot2 keeps the newer one, tells you it did, and the list still has a length of one."],
  ["code","twice <- p + scale_x_continuous(breaks = c(0, 25, 50)) + scale_x_continuous(breaks = c(0, 50))\n\nlength(twice$scales$scales)\ntwice$scales$scales[[1]]$breaks"],
  ["code","Scale for x is already present.\nAdding another scale for x, which will replace the existing scale.\n[1] 1\n[1]  0 50"],
  ["note","This bites when a plot is built up over several lines and you add scale_x_continuous() twice — once for the axis name, later for the breaks — expecting them to combine. They do not. The second call wins outright and the name you set in the first one is gone. Put every x setting in a single scale_x_continuous(), or set the name with labs() and leave the scale for the numbers."]
]},
{ t: "Zooming",
  body: [
  ["p","There are three ways to look at a smaller part of a plot, and only one of them is looking. The other two change the data that reaches the layers, which is fine when you meant it and a silent mistake when you did not."],
  ["p","Setting limits on a scale throws away every value outside them. Nothing is deleted from the tibble, but the layer receives NA where the number used to be, and three of the eight crossings are longer than thirty minutes."],
  ["code","cut_scale <- p + scale_x_continuous(limits = c(0, 30))\n\nsum(is.na(ggplot_build(cut_scale)$data[[1]]$x))"],
  ["code","[1] 3"],
  ["p","xlim() is shorthand for the same thing. It attaches a scale, and the count of discarded values is identical."],
  ["code","lim <- p + xlim(0, 30)\n\nlength(lim$scales$scales)\nsum(is.na(ggplot_build(lim)$data[[1]]$x))"],
  ["code","[1] 1\n[1] 3"],
  ["p","coord_cartesian() is the one that only looks. Every row still reaches every layer; the viewport is cropped afterwards, so nothing is discarded."],
  ["code","zoomed <- p + coord_cartesian(xlim = c(0, 30))\n\nclass(zoomed$coordinates)[1]\nzoomed$coordinates$limits$x\nsum(is.na(ggplot_build(zoomed)$data[[1]]$x))"],
  ["code","[1] \"CoordCartesian\"\n[1]  0 30\n[1] 0"],
  ["p","Checking the coordinate class alone will not tell the two apart, because every plot already has a Cartesian coordinate system. The limits slot is the part that changed."],
  ["code","class(p$coordinates)[1]\np$coordinates$limits$x"],
  ["code","[1] \"CoordCartesian\"\nNULL"],
  ["p","With points only, the difference is invisible in the drawing: either way you see five points. Add a layer that computes something and it stops being invisible. Below, the same straight-line fit is put on the same data twice, once with the range cut and once merely zoomed, and the fitted line is a different line."],
  ["code","q <- ggplot(crossings, aes(x = minutes, y = fare_eur)) +\n  geom_point() +\n  geom_smooth(method = \"lm\", se = FALSE)\n\nround(range(ggplot_build(q + scale_x_continuous(limits = c(0, 30)))$data[[2]]$y), 2)\nround(range(ggplot_build(q + coord_cartesian(xlim = c(0, 30)))$data[[2]]$y), 2)"],
  ["code","`geom_smooth()` using formula = 'y ~ x'\nWarning: Removed 3 rows containing non-finite outside the scale range (`stat_smooth()`).\n[1]  4.0 16.8\n`geom_smooth()` using formula = 'y ~ x'\n[1]  5.27 42.56"],
  ["note","The warning is the tell, and it is worth reading in full: three rows were removed before the statistic ran, so the line was fitted to five crossings rather than eight. If a summary line moves when you zoom in, you did not zoom — you filtered. Reach for coord_cartesian() when you want a closer look and for scale limits only when you actually mean to exclude the data."]
]},
{ t: "Themes",
  body: [
  ["p","Everything on a plot that is not data is the theme: the panel background, the grid lines, the fonts, the spacing, where the legend goes. ggplot2 ships several complete themes, and adding one replaces the whole set at once. A plot you have not themed carries nothing, and a plot with theme_bw() carries a full set of settings, including a white panel instead of the default grey."],
  ["code","length(p$theme)\n\nthemed <- p + theme_bw()\n\nclass(themed$theme)[1]\nlength(themed$theme) > 0\nthemed$theme$panel.background$fill"],
  ["code","[1] 0\n[1] \"theme\"\n[1] TRUE\n[1] \"white\""],
  ["p","theme() is the other half: it changes named elements one at a time and leaves everything else to the default. Setting a single element gives a theme of length one."],
  ["code","tweaked <- p + theme(legend.position = \"bottom\")\n\nlength(tweaked$theme)\ntweaked$theme$legend.position"],
  ["code","[1] 1\n[1] \"bottom\""],
  ["p","Mixing the two is where order starts to matter. A complete theme is complete: it supplies a value for every element, so it overwrites anything set before it."],
  ["code","both <- p + theme(legend.position = \"bottom\") + theme_bw()\n\nboth$theme$legend.position"],
  ["code","[1] \"right\""],
  ["p","Swap the two additions and the tweak survives, because now it is applied to a theme that is already in place."],
  ["code","ordered <- p + theme_bw() + theme(legend.position = \"bottom\")\n\nordered$theme$legend.position"],
  ["code","[1] \"bottom\""],
  ["note","Nothing warns you about the first version. The plot builds, it draws, and the legend is simply back on the right where it started, which reads as theme(legend.position = ) being broken. The rule is short: complete theme first, individual tweaks after."]
]},
{ t: "Saving, and plots side by side",
  body: [
  ["p","ggsave() writes a plot to a file. It takes a filename whose extension chooses the format, the plot to save, and a size; width and height are inches unless you say otherwise, and dpi sets the resolution of raster formats like PNG."],
  ["code","ggsave(\"crossings.png\", plot = titled, width = 6, height = 4, dpi = 150)\n\nfile.exists(\"crossings.png\")\nlist.files(pattern = \"png$\")"],
  ["code","[1] TRUE\n[1] \"crossings.png\""],
  ["p","Give ggsave() a size every time. Called without one it uses the dimensions of the current graphics device, which means the file you send depends on how big your plot window happened to be, and text that looked right on screen comes out too small or too large in the document."],
  ["note","In this app the file lands in the browser's temporary filesystem, not in a folder on your device. file.exists() finds it, nothing else will, and it disappears with the page. On a desktop the same call writes into your working directory, which is the point of the function."],
  ["p","Putting several finished plots into one figure is a job for patchwork, a separate package that overloads + and / to mean beside and above. It is not installed in this app, so the block below is shown without output rather than with output invented for it — run it on a desktop after install.packages(\"patchwork\")."],
  ["code","library(patchwork)\n\nfares <- ggplot(crossings, aes(minutes, fare_eur)) + geom_point()\nspread <- ggplot(crossings, aes(operator, minutes)) + geom_boxplot()\n\nfares + spread"],
  ["note","Nothing above was executed, so treat the syntax as read rather than as verified. That is the honest position: the rest of this chapter shows only output captured from a real run, and a package this app cannot install cannot produce any."]
]},
{ t: "Summary",
  body: [
  ["p","Communication is the work that happens after a plot answers your question. labs() sets the title, subtitle, caption, axis names, and legend headings, and the heading on a legend is the name of the aesthetic it belongs to. get_labs() reports the labels a plot will draw with, defaults included, while p$labels holds only what you set. geom_text() draws text from a column, a layer given its own one-row data frame labels a single observation, and annotate() draws a note that lives in no data frame at all."],
  ["p","Scales control the values: scale_x_continuous() for axis names and breaks, scale_colour_manual() for the colours a categorical column gets. One aesthetic keeps one scale, and a second one for the same aesthetic replaces the first with a message. Legend position is a theme setting, and guides(colour = \"none\") removes a legend altogether. Zooming has three forms, and the choice matters: scale limits and xlim() discard values outside the range before the layers see them, so a fitted line changes, while coord_cartesian() crops the view and leaves every row intact."],
  ["p","Themes cover everything that is not data. A complete theme such as theme_bw() replaces the lot, theme() adjusts single elements, and a complete theme added after a tweak wipes it out without saying so — so put theme_bw() first and the tweaks after. ggsave() writes the result out, always with an explicit width and height, and patchwork assembles several plots into one figure on a desktop."],
  ["p","Answer the practice questions from memory before revealing the answers, then clear the graded exercises below. The next chapter is logical vectors: comparisons, the reason 0.1 plus 0.2 is not 0.3, what happens when a comparison meets a missing value, and the functions that turn a condition into a column."]
]}
],
questions: [
{ q:"Where do the axis and legend labels come from on a plot you have not called labs() on, and how do you read them back?",
  a:"They default to the column names in the mapping, worked out when the plot is drawn. get_labs(p) reports what the plot will actually use — \"minutes\", \"fare_eur\", \"operator\" here. p$labels holds only what you set yourself, so on an untouched plot its length is 0 and get_labs(p)$title is NULL." },
{ q:"What belongs in a title, a subtitle, and a caption?",
  a:"The title states the finding, not the variables: \"Fare rises with crossing time\" rather than \"Fare against minutes\". The subtitle carries the detail a reader needs to trust that claim, such as what the rows are and when they were collected. The caption credits the source." },
{ q:"How do you set the heading over a colour legend?",
  a:"With labs(colour = \"Operator\"). A legend belongs to an aesthetic, so it takes its heading from the label for that aesthetic — there is no separate legend-title function." },
{ q:"You wrote labs(titel = \"Fare rises with crossing time\") and no title appeared. What did R do?",
  a:"It printed \"Ignoring unknown labels:\" naming titel, dropped that argument, and built the plot without a title. It is a message rather than an error, and the plot still draws, so it is easy to scroll past. Check the spelling of the argument name before you doubt the text." },
{ q:"What is the difference between geom_text(aes(label = route)) and geom_text(data = slowest, aes(label = route))?",
  a:"The first inherits the plot's data and draws all eight route names, one per point. The second is given its own one-row table, so it labels exactly one observation. class(p$layers[[1]]$data)[1] on an inheriting layer reports \"waiver\", the placeholder meaning use the plot's data." },
{ q:"Why use annotate(\"text\", ...) rather than geom_text() for a sentence you want on the plot?",
  a:"annotate() draws the text once — nrow(ggplot_build(p)$data[[2]]) is 1. A constant label put inside aes() is still a mapping, so it is recycled once per row: eight identical copies stacked on the same spot, which shows up as oddly heavy text rather than as an error." },
{ q:"What does length(p$scales$scales) report on a plot you have added no scales to, and what happens when you add two scales for the same aesthetic?",
  a:"0 — the default scales are supplied at draw time, not stored on the object. Adding a second scale for the same aesthetic keeps the newer one, prints \"Scale for x is already present. Adding another scale for x, which will replace the existing scale.\", and leaves the list at length 1. The settings do not combine." },
{ q:"Where does legend position live, and how do you get rid of a legend?",
  a:"Position is a theme setting: theme(legend.position = \"bottom\"), readable back as p$theme$legend.position. Removing a legend is guides(colour = \"none\"), which is stored under p$guides$guides$colour. Neither is a property of the scale." },
{ q:"Name the three ways to zoom and say which of them lose data.",
  a:"scale_x_continuous(limits = ) and its shorthand xlim() both discard values outside the range before the layers see them — the built data holds NA in their place, three of eight here. coord_cartesian(xlim = ) crops the view after everything is computed, so sum(is.na(...)) stays 0. The first two change any statistic in the plot; the third does not." },
{ q:"Why does p + theme(legend.position = \"bottom\") + theme_bw() end up with the legend on the right?",
  a:"theme_bw() is a complete theme: it supplies a value for every element, so it overwrites the tweak added before it and legend.position goes back to \"right\". Nothing warns you. Add the complete theme first and the individual theme() calls after it." }
],
exercises: [
{ c:"ggplot2 basics", t:"Labels a stranger can read", book:"r11",
  b:"Attach ggplot2 and tibble. Build a tibble named orchards with a column trees holding 40, 65, 90, 120, 150 and a column crates holding 22, 35, 51, 68, 84. Map trees to x and crates to y, add a point layer, and give the plot the title \"Crates rise with tree count\", the x label \"Trees in the orchard\", and the y label \"Crates picked\". Store it in p, then print the title, the x label, and the y label the plot will use, in that order, on three lines.",
  o:"[1] \"Crates rise with tree count\"\n[1] \"Trees in the orchard\"\n[1] \"Crates picked\"",
  h:["All three pieces of text come from one function, added to the plot with a +.",
     "labs() takes title, x, and y as named arguments. Reading a label back off the plot is get_labs(), not p$labels, because p$labels only ever holds what you set and prints differently.",
     "Build the tibble, build the plot with geom_point() and labs(...), assign it to p, then three separate lines each pulling one element out of get_labs(p)."]},
{ c:"ggplot2 basics", t:"Label one point only", book:"r11",
  b:"Attach ggplot2 and tibble. Build a tibble named towers with town holding \"Ardee\", \"Beltra\", \"Cong\", \"Doon\"; height_m holding 18, 31, 24, 42; and visitors holding 900, 1500, 1200, 2100. Map height_m to x and visitors to y and add a point layer. Then add a text layer that labels the single tallest tower with its town name and nothing else — pick that row out of the tibble rather than typing it. Store the plot in p and print the number of layers, the class of the second layer's geom (first element only), the number of rows the second layer carries, and the town in that layer's data.",
  o:"[1] 2\n[1] \"GeomText\"\n[1] 1\n[1] \"Doon\"",
  h:["The text layer needs a table of its own holding exactly the row you want labelled.",
     "which.max() gives the position of the largest value in a column, and a data frame can be subset by row with that position and an empty column slot. geom_text() takes a data argument as well as a mapping.",
     "Build the one-row table first and give it a name. Then add geom_text(data = <that table>, aes(label = town)) to the point plot, and ask p four questions on four lines — the last one reaches into p$layers[[2]]$data."]},
{ c:"ggplot2 basics", t:"Zoom without dropping rows", book:"r11",
  b:"Attach ggplot2 and tibble. Build a tibble named runs with km holding 3, 6, 9, 12, 15, 18 and minutes holding 16, 33, 51, 70, 92, 115. Build a point plot of minutes against km and store it in base. Make two versions restricted to x from 0 to 10: one that only crops the view, and one that puts limits on the x scale. Print the class of the cropping version's coordinate system (first element only), then the number of NA x values in the built data of the cropping version, then the same count for the scale-limits version.",
  o:"[1] \"CoordCartesian\"\n[1] 0\n[1] 3",
  h:["Two of the three ways to zoom discard data and one does not. This exercise asks for one of each, so you can see the counts differ.",
     "coord_cartesian() crops after the layers are computed; scale_x_continuous(limits = ) replaces out-of-range values with NA before they get there. ggplot_build() runs the computation without drawing, and the point layer is $data[[1]].",
     "Build base once and add to it twice, storing each result. The counts come from sum(is.na(...$x)) over ggplot_build of each version, and the coordinate class from the coordinates slot of the cropped plot."]},
{ c:"data frames", t:"A frame of annotations", book:"r11",
  b:"Attach ggplot2. Build a data frame named peaks with climb_km holding 2, 5, 9, 14 and metres holding 180, 430, 760, 1120. Build a second data frame named notes with climb_km holding 5 and 14, metres holding 430 and 1120, and label holding \"halfway hut\" and \"summit cairn\". Plot metres against climb_km as points, then add a text layer that draws the notes at their own positions. Store the plot in p and print the class of the first layer's data (first element only), the number of rows in the second layer's data, and the labels from that data in alphabetical order.",
  o:"[1] \"waiver\"\n[1] 2\n[1] \"halfway hut\"  \"summit cairn\"",
  h:["Two data frames: one is the plot's data, the other belongs to a single layer.",
     "A layer that was given no data of its own stores a placeholder rather than a copy, and class() on it names that placeholder. geom_text() takes both a data argument and a mapping that names the label column.",
     "Build peaks and notes with data.frame(), then p as geom_point() plus geom_text(data = notes, aes(label = label)). The three answers all come out of p$layers, and the last one needs sort() around the label column."]}
]
};
