/* Practice Log book — R Chapter 12: Logical vectors.
   Original lesson text following the chapter-by-chapter curriculum of
   "R for Data Science" (2nd ed.) by Hadley Wickham, Mine Cetinkaya-Rundel,
   and Garrett Grolemund. Read the original chapter free at the src link below.
   Every shown output was captured by executing the code in WebR, not written from memory. */
window.BOOK_R = window.BOOK_R || { chapters: {} };
window.BOOK_R.chapters.r12 = {
n: 12,
title: "Logical vectors",
src: "https://r4ds.hadley.nz/logicals.html",
blurb: "Comparisons, the arithmetic that makes 0.1 plus 0.2 miss 0.3, what a missing value does to a test, and turning conditions into columns.",
pkgs: ["dplyr", "tibble"],
sections: [
{ t: "Comparisons make logical vectors",
  body: [
  ["p","A logical vector holds three possible values: TRUE, FALSE, and NA. You have been making them since the first filter() you wrote, because that is what a comparison returns. Pulling the comparison out of the pipeline and looking at it on its own is the point of this chapter — once you can see the vector, the behaviour of every verb that takes a condition stops being mysterious."],
  ["p","Two packages. tibble builds the table, and dplyr supplies the verbs plus three functions that appear later: near(), if_else(), and case_when()."],
  ["code","library(tibble)\nlibrary(dplyr)"],
  ["code","\nAttaching package: ‘dplyr’\n\nThe following objects are masked from ‘package:stats’:\n\n    filter, lag\n\nThe following objects are masked from ‘package:base’:\n\n    intersect, setdiff, setequal, union\n"],
  ["p","The table is a week of weather from six forest stations: a name, rainfall in millimetres, and a temperature in degrees Celsius. Two readings never arrived, and they are in the table as NA rather than as zero, because a gauge that was not read is not a gauge that read nothing."],
  ["code","readings <- tibble(\n  station = c(\"alder\", \"birch\", \"cedar\", \"dogwood\", \"elm\", \"fir\"),\n  rain_mm = c(0, 12, 4, NA, 31, 7),\n  temp_c  = c(18.5, 14.2, 21.0, 16.8, 11.4, NA)\n)\n\nreadings"],
  ["code","# A tibble: 6 × 3\n  station rain_mm temp_c\n  <chr>     <dbl>  <dbl>\n1 alder         0   18.5\n2 birch        12   14.2\n3 cedar         4   21  \n4 dogwood      NA   16.8\n5 elm          31   11.4\n6 fir           7   NA  "],
  ["p","A comparison is applied element by element and hands back a vector of the same length. R has five comparison operators you can write without special characters — greater than, greater than or equal, less than, less than or equal, and == for equality — and each of them turns numbers into TRUE, FALSE, or NA."],
  ["code","readings$rain_mm > 5\nreadings$temp_c <= 15"],
  ["code","[1] FALSE  TRUE FALSE    NA  TRUE  TRUE\n[1] FALSE  TRUE FALSE FALSE  TRUE    NA"],
  ["p","Six values in, six values out, in the same order, with NA wherever the input was NA. Putting the result back beside the data with mutate() is often the fastest way to see what a condition is doing; .keep = \"used\" prints only the columns involved."],
  ["code","readings |> mutate(wet = rain_mm > 5, .keep = \"used\")"],
  ["code","# A tibble: 6 × 2\n  rain_mm wet  \n    <dbl> <lgl>\n1       0 FALSE\n2      12 TRUE \n3       4 FALSE\n4      NA NA   \n5      31 TRUE \n6       7 TRUE "],
  ["p","filter() is that comparison plus one rule: keep the rows where the condition is TRUE. Three rows come back out of six."],
  ["code","readings |> filter(rain_mm > 5)"],
  ["code","# A tibble: 3 × 3\n  station rain_mm temp_c\n  <chr>     <dbl>  <dbl>\n1 birch        12   14.2\n2 elm          31   11.4\n3 fir           7   NA  "],
  ["p","Six rows became three, and only two of the three that left were FALSE. Section 3 is about the other one. To ask the opposite question, compare the logical vector to FALSE — a logical vector is data like any other, so comparing it flips every TRUE and every FALSE and leaves NA alone."],
  ["code","(readings$rain_mm > 5) == FALSE"],
  ["code","[1]  TRUE FALSE  TRUE    NA FALSE FALSE"],
  ["note","R has two more operators for this job: a negation operator written as an exclamation mark in front of a logical vector, and a not-equal operator written as an exclamation mark followed by an equals sign. Both are everywhere in real code, and both do exactly what the comparison above does, NA included. This book writes == FALSE instead so its text carries no exclamation marks, which is a house rule and not a fact about R. Read the two operators as a shorter spelling of what you see here."]
]},
{ t: "Floating point comparison",
  body: [
  ["p","Here is the first result in this book that looks like a bug in R."],
  ["code","0.1 + 0.2 == 0.3"],
  ["code","[1] FALSE"],
  ["p","R stores these numbers as doubles, in binary, with a fixed number of digits. A tenth cannot be written exactly in binary any more than a third can be written exactly in decimal, so both sides of that comparison are approximations — and they are not the same approximation. Printing more digits than R normally shows makes the gap visible."],
  ["code","print(0.1 + 0.2, digits = 18)\nprint(0.3, digits = 18)"],
  ["code","[1] 0.300000000000000044\n[1] 0.299999999999999989"],
  ["p","The two values differ from the seventeenth digit onward. R rounds to seven significant digits when it prints, so on screen both are 0.3, and == compares what is stored rather than what is shown. Anything that goes through arithmetic can land in the same place."],
  ["code","sqrt(2) ^ 2 == 2"],
  ["code","[1] FALSE"],
  ["p","The fix is to stop asking whether two doubles are identical and start asking whether they are close enough. dplyr's near() does that, with a tolerance that is already set to something sensible."],
  ["code","near(0.1 + 0.2, 0.3)\nnear(sqrt(2) ^ 2, 2)"],
  ["code","[1] TRUE\n[1] TRUE"],
  ["p","Whole numbers stored as doubles have exact binary representations, so plenty of arithmetic compares equal without any trouble at all."],
  ["code","1 + 2 == 3\n0.1 + 0.7 == 0.8"],
  ["code","[1] TRUE\n[1] FALSE"],
  ["note","That inconsistency is the whole problem. Testing == on computed doubles works most of the time, which means it passes your first few checks and then quietly drops a row six months later, on a number you never thought about. The rule is simple: compare whole numbers with ==, and compare anything that has been through decimal arithmetic with near()."]
]},
{ t: "Missing values",
  body: [
  ["p","NA is not a value. It is a note saying a value should be here and is unknown, which is why almost anything you do with it produces another NA — the result is unknown too."],
  ["code","NA > 5\nNA == NA\nNA + 10"],
  ["code","[1] NA\n[1] NA\n[1] NA"],
  ["p","The middle line is the one that catches people. It looks like it should be TRUE, and it is not, because the question being asked is whether one unknown number equals another unknown number. Two people whose ages you do not know are not thereby the same age. R answers that it does not know, which is correct."],
  ["p","So == cannot test for missingness, and there is a dedicated function instead. is.na() returns TRUE exactly where the value is missing, and it never returns NA itself."],
  ["code","is.na(readings$rain_mm)\nsum(is.na(readings$rain_mm))"],
  ["code","[1] FALSE FALSE FALSE  TRUE FALSE FALSE\n[1] 1"],
  ["p","That also makes is.na() the way to look at the rows a filter dropped. In section 1, filter(rain_mm > 5) returned three rows out of six: two were FALSE, and this one was neither."],
  ["code","readings |> filter(is.na(rain_mm))"],
  ["code","# A tibble: 1 × 3\n  station rain_mm temp_c\n  <chr>     <dbl>  <dbl>\n1 dogwood      NA   16.8"],
  ["p","filter() keeps TRUE rows, so a row whose condition is NA is discarded along with the FALSE ones, and nothing tells you the difference. When the unknown rows matter — and for a rainfall gauge that failed, they matter — ask for them explicitly."],
  ["code","readings |> filter(rain_mm > 5 | is.na(rain_mm))"],
  ["code","# A tibble: 4 × 3\n  station rain_mm temp_c\n  <chr>     <dbl>  <dbl>\n1 birch        12   14.2\n2 dogwood      NA   16.8\n3 elm          31   11.4\n4 fir           7   NA  "],
  ["p","Reaching for == to find the missing rows instead produces a table with no rows and no complaint, because every comparison in the condition evaluated to NA and no row was ever TRUE."],
  ["code","readings |> filter(rain_mm == NA)"],
  ["code","# A tibble: 0 × 3\n# ℹ 3 variables: station <chr>, rain_mm <dbl>, temp_c <dbl>"],
  ["note","Zero rows and no error is the worst possible answer, because an empty result reads as a fact about the data — nothing is missing — rather than as a broken condition. Any time a filter returns nothing at all, check whether the column you tested has NA in it before you believe the emptiness."]
]},
{ t: "Boolean algebra",
  body: [
  ["p","Conditions get combined with & for and, with | for or, and with xor() for exactly one of the two. Applied to a vector containing NA, they follow one rule: if the known values already settle the answer, R gives the answer, and otherwise it gives NA."],
  ["code","c(TRUE, FALSE, NA) & TRUE\nc(TRUE, FALSE, NA) & FALSE\nc(TRUE, FALSE, NA) | TRUE"],
  ["code","[1]  TRUE FALSE    NA\n[1] FALSE FALSE FALSE\n[1] TRUE TRUE TRUE"],
  ["p","Read the second and third lines carefully, because they are where NA stops spreading. One FALSE settles an &, whatever the other side turns out to be, so NA & FALSE is FALSE. One TRUE settles an |, so NA | TRUE is TRUE. Only the first line has a case where the unknown still matters."],
  ["code","xor(TRUE, TRUE)\nxor(TRUE, FALSE)"],
  ["code","[1] FALSE\n[1] TRUE"],
  ["p","Two columns combine the same way, element by element. Row four is NA because its rainfall is unknown, and row six is NA because its temperature is."],
  ["code","readings$rain_mm > 5 & readings$temp_c > 12"],
  ["code","[1] FALSE  TRUE FALSE    NA FALSE    NA"],
  ["p","Now the mistake everybody makes once. Written out loud, dry or twelve millimetres is a sensible sentence. Written in R, it is not the condition you meant."],
  ["code","readings$rain_mm == 0 | 12"],
  ["code","[1] TRUE TRUE TRUE TRUE TRUE TRUE"],
  ["p","Every row is TRUE, including the row with no reading. R applied == first, then handed | a logical vector on the left and the bare number 12 on the right, where any non-zero number counts as TRUE. So the whole thing became something-or-TRUE, which is TRUE everywhere. No error, no warning, and a filter built on it keeps the entire table. Written out properly, both sides are comparisons."],
  ["code","readings$rain_mm == 0 | readings$rain_mm == 12"],
  ["code","[1]  TRUE  TRUE FALSE    NA FALSE FALSE"],
  ["p","Repeating the column name gets tedious after two or three values, and %in% says the same thing once. It asks whether each element appears anywhere in the vector on the right."],
  ["code","readings$rain_mm %in% c(0, 12)"],
  ["code","[1]  TRUE  TRUE FALSE FALSE FALSE FALSE"],
  ["p","Compare row four across the last two results: NA under ==, FALSE under %in%. That is a real difference in meaning and not a rounding of it. %in% never returns NA, because it is asking about membership in a set rather than about equality, and NA is allowed to be a member of a set."],
  ["code","NA %in% c(4, NA, 7)\nNA == 4"],
  ["code","[1] TRUE\n[1] NA"],
  ["note","%in% treating NA as a matchable value is convenient right up to the moment you write x %in% c(1, 2, NA) expecting the NA to be ignored, and quietly collect every missing row. If you want membership without the missing rows, test membership and being known separately and combine them with &."]
]},
{ t: "Summaries",
  body: [
  ["p","A logical vector collapses to a single answer with any() and all(). any() is TRUE when at least one element is TRUE, all() is TRUE only when every element is."],
  ["code","any(readings$rain_mm > 20)\nall(readings$rain_mm > 20)"],
  ["code","[1] TRUE\n[1] FALSE"],
  ["p","Neither of those is NA, even though the vector contains one, and the reason is the rule from the previous section. One TRUE settles an any(); one FALSE settles an all(). Change the question so that the unknown could decide it and NA comes straight back."],
  ["code","any(readings$temp_c > 25)\nall(readings$temp_c > 10)"],
  ["code","[1] NA\n[1] NA"],
  ["p","No temperature on record is above 25, but one is unrecorded, so R cannot say that none is. Every recorded temperature is above 10, but one is unrecorded, so R cannot say they all are. na.rm = TRUE tells it to answer the question about the values it does have."],
  ["code","any(readings$temp_c > 25, na.rm = TRUE)\nall(readings$temp_c > 10, na.rm = TRUE)"],
  ["code","[1] FALSE\n[1] TRUE"],
  ["p","Numeric summaries work too, because R treats TRUE as 1 and FALSE as 0 when a number is wanted. sum() over a logical vector counts the TRUE values, and mean() gives the proportion that are TRUE."],
  ["code","sum(readings$rain_mm > 5, na.rm = TRUE)\nmean(readings$rain_mm > 5, na.rm = TRUE)"],
  ["code","[1] 3\n[1] 0.6"],
  ["p","Read that 0.6 slowly. Three stations out of six recorded more than 5 mm, which would be 0.5 — but na.rm dropped the unknown before the mean was taken, so the denominator is 5, not 6. The proportion is of the stations that reported, and nothing on screen says so."],
  ["code","sum(is.na(readings$rain_mm) == FALSE)\n3 / 5"],
  ["code","[1] 5\n[1] 0.6"],
  ["p","Inside summarise(), the same three ideas give a count, a share, and an honest note of how much data the share was computed from."],
  ["code","readings |> summarise(\n  wet = sum(rain_mm > 5, na.rm = TRUE),\n  share = mean(rain_mm > 5, na.rm = TRUE),\n  unrecorded = sum(is.na(rain_mm))\n)"],
  ["code","# A tibble: 1 × 3\n    wet share unrecorded\n  <int> <dbl>      <int>\n1     3   0.6          1"],
  ["note","na.rm = TRUE on a mean of a condition changes the denominator, which changes what the number means. Report the count of missing values next to any proportion you compute this way, or the reader will assume the share is of all the rows. That is the whole reason the third column above exists."]
]},
{ t: "Logical subsetting",
  body: [
  ["p","Square brackets accept a logical vector and keep the positions where it is TRUE. It is the same idea as filter(), one dimension down, and it does not behave the same way when a condition is NA."],
  ["code","readings$rain_mm[readings$rain_mm > 5]"],
  ["code","[1] 12 NA 31  7"],
  ["p","Four elements came back from a condition with three TRUE values. R could not decide whether position four belonged, so it kept a placeholder rather than dropping the element or inventing an answer. That NA is now sitting in the middle of what you probably think is a list of wet stations."],
  ["p","which() converts a logical vector into the positions of its TRUE values, and positions cannot be unknown, so the ambiguity disappears."],
  ["code","readings$rain_mm[which(readings$rain_mm > 5)]"],
  ["code","[1] 12 31  7"],
  ["p","The other approach is to remove the unknown values first and ask the question afterwards."],
  ["code","readings$rain_mm[is.na(readings$rain_mm) == FALSE]"],
  ["code","[1]  0 12  4 31  7"],
  ["p","filter() already does what which() does, which is why the earlier pipeline returned three rows rather than four."],
  ["code","readings |> filter(rain_mm > 5) |> nrow()"],
  ["code","[1] 3"],
  ["note","The same condition, applied to a vector and to a data frame, gives you four things and three rows. Neither is wrong and neither warns you. If you subset a vector with brackets and then count what you got, count is.na() at the same time, or you will report one wet station too many."]
]},
{ t: "Conditional transformations",
  body: [
  ["p","A condition is often not the answer you want. You want a value that depends on the condition, and if_else() is the two-way version: a logical vector, what to use where it is TRUE, what to use where it is FALSE."],
  ["code","if_else(readings$rain_mm > 5, \"wet\", \"dry\")"],
  ["code","[1] \"dry\" \"wet\" \"dry\" NA    \"wet\" \"wet\""],
  ["p","The unknown stayed unknown, which is the honest default: with no rainfall figure, the station is neither wet nor dry. When you would rather label it, if_else() takes a third case."],
  ["code","if_else(readings$rain_mm > 5, \"wet\", \"dry\", missing = \"unknown\")"],
  ["code","[1] \"dry\"     \"wet\"     \"dry\"     \"unknown\" \"wet\"     \"wet\"    "],
  ["p","More than two outcomes means case_when(). Each argument is a condition, then a tilde, then the value to use; the first condition that is TRUE for an element wins, and .default covers whatever is left."],
  ["code","case_when(\n  readings$rain_mm == 0 ~ \"none\",\n  readings$rain_mm < 10 ~ \"light\",\n  readings$rain_mm < 30 ~ \"steady\",\n  .default = \"heavy\"\n)"],
  ["code","[1] \"none\"   \"steady\" \"light\"  \"heavy\"  \"heavy\"  \"light\" "],
  ["p","Position four is the station with no reading, and it has been labelled heavy. None of the three conditions was TRUE for it — they were all NA — so .default swept it up along with the genuinely heavy rainfall at elm. Give missingness a branch of its own, above the default and first for readability, and the row gets a label rather than a guess."],
  ["code","case_when(\n  is.na(readings$rain_mm) ~ \"unrecorded\",\n  readings$rain_mm == 0 ~ \"none\",\n  readings$rain_mm < 10 ~ \"light\",\n  readings$rain_mm < 30 ~ \"steady\",\n  .default = \"heavy\"\n)"],
  ["code","[1] \"none\"       \"steady\"     \"light\"      \"unrecorded\" \"heavy\"     \n[6] \"light\"     "],
  ["p","Both functions insist that every branch produces the same type, because a vector holds one type and they have to return a vector. Mixing a string and a number is an error rather than a silent conversion."],
  ["code","if_else(readings$rain_mm > 5, \"wet\", 0)"],
  ["code","Error: Can't combine `true` <character> and `false` <double>."],
  ["code","case_when(readings$rain_mm > 5 ~ \"wet\", .default = 0)"],
  ["code","Error: Can't combine <character> and `.default` <double>."],
  ["p","In a pipeline the result becomes a column like any other, and arrange() makes the printed order something you chose rather than something you inherited."],
  ["code","readings |>\n  mutate(band = case_when(\n    is.na(rain_mm) ~ \"unrecorded\",\n    rain_mm == 0 ~ \"none\",\n    rain_mm < 10 ~ \"light\",\n    .default = \"steady\"\n  )) |>\n  arrange(station)"],
  ["code","# A tibble: 6 × 4\n  station rain_mm temp_c band      \n  <chr>     <dbl>  <dbl> <chr>     \n1 alder         0   18.5 none      \n2 birch        12   14.2 steady    \n3 cedar         4   21   light     \n4 dogwood      NA   16.8 unrecorded\n5 elm          31   11.4 steady    \n6 fir           7   NA   light     "],
  ["note","case_when() branches are tried in order and the first match wins, so a broad condition written above a narrow one hides it completely. Read your branches top to bottom the way R does, put the NA branch first, and keep .default for the case you can actually name rather than for everything you did not think about."]
]},
{ t: "Summary",
  body: [
  ["p","A comparison returns a logical vector the same length as its input, holding TRUE, FALSE, and NA. Doubles that have been through decimal arithmetic rarely compare equal — 0.1 + 0.2 == 0.3 is FALSE, and near() is the function that asks whether two numbers are close enough instead. NA means unknown, so any comparison involving it is unknown too, including NA == NA; is.na() is the only way to test for it."],
  ["p","& and | propagate NA only when the unknown could still change the answer, which is why NA & FALSE is FALSE and NA | TRUE is TRUE. Writing x == 0 | 12 gives every row TRUE with no complaint, because | received a bare number and treated it as TRUE; write both comparisons out, or use %in%, remembering that %in% treats NA as a value it can match. any() and all() collapse a logical vector, sum() counts its TRUE values, and mean() gives the proportion — with na.rm = TRUE quietly shrinking the denominator to the values that were recorded."],
  ["p","filter() keeps only TRUE rows, so NA rows disappear along with the FALSE ones; ask for them with is.na() when they matter. Subsetting a vector with brackets keeps an NA placeholder where filter() would have dropped the row, and which() removes the difference. if_else() handles two outcomes and takes a missing argument, case_when() handles more with its branches tried in order, and both require every branch to return the same type."],
  ["p","Answer the practice questions from memory before revealing the answers, then clear the graded exercises below. The next chapter is numbers: turning strings into numbers, counting, the arithmetic that runs element by element, rounding, and the summary functions that go beyond mean and sum."]
]}
],
questions: [
{ q:"What does readings$rain_mm > 5 return, and how long is it?",
  a:"A logical vector the same length as the column — six elements here — holding TRUE where the comparison holds, FALSE where it does not, and NA at every position where the input was NA. Comparisons work element by element and never change the length." },
{ q:"Why is 0.1 + 0.2 == 0.3 FALSE, and what do you write instead?",
  a:"Doubles are stored in binary with a fixed number of digits, and a tenth has no exact binary form, so the two sides are different approximations: printed to 18 digits they are 0.300000000000000044 and 0.299999999999999989. R shows seven digits, so both look like 0.3. Use near(0.1 + 0.2, 0.3), which returns TRUE, whenever the numbers have been through decimal arithmetic." },
{ q:"Why is NA == NA not TRUE?",
  a:"NA means the value is unknown, and the question being asked is whether one unknown number equals another unknown number. R cannot know, so it answers NA. That is also why == cannot be used to look for missing values, and why is.na() exists." },
{ q:"What happens to rows whose filter condition is NA, and how do you keep them?",
  a:"filter() keeps rows where the condition is TRUE, so NA rows are dropped along with the FALSE ones and nothing marks the difference. Add the missing rows explicitly: filter(rain_mm > 5 | is.na(rain_mm)). Writing filter(rain_mm == NA) instead returns a table with zero rows and no error, because every comparison evaluated to NA." },
{ q:"Why is NA & FALSE equal to FALSE, while NA & TRUE is NA?",
  a:"One FALSE settles an and regardless of the other side, so the unknown cannot change the answer and R gives FALSE. With TRUE on the other side the unknown decides the result, so R gives NA. The same rule the other way round makes NA | TRUE equal to TRUE." },
{ q:"What does readings$rain_mm == 0 | 12 evaluate to, and why?",
  a:"TRUE for every row. R applies == first, then hands | a logical vector and the bare number 12, and any non-zero number counts as TRUE, so the result is something-or-TRUE everywhere. There is no error or warning. Write both comparisons out, or use rain_mm %in% c(0, 12)." },
{ q:"How does %in% differ from == when NA is involved?",
  a:"%in% never returns NA: it asks about membership in a set, and NA counts as a member, so NA %in% c(4, NA, 7) is TRUE while NA == 4 is NA. For the rainfall column, row four is NA under == and FALSE under %in% c(0, 12). That convenience becomes a trap when the vector on the right contains NA, because every missing row then matches." },
{ q:"When do any() and all() return NA, and what does na.rm = TRUE change?",
  a:"When the missing value could still decide the answer. any(readings$rain_mm > 20) is TRUE because one element is already TRUE, and all(readings$rain_mm > 20) is FALSE because one is already FALSE. But any(temp_c > 25) and all(temp_c > 10) are both NA, since the unrecorded temperature could go either way. na.rm = TRUE answers the question about the recorded values only, giving FALSE and TRUE." },
{ q:"What does mean() over a logical vector give you, and what is its denominator with na.rm = TRUE?",
  a:"The proportion of TRUE values, because R counts TRUE as 1 and FALSE as 0. mean(readings$rain_mm > 5, na.rm = TRUE) is 0.6, which is three out of five — na.rm drops the missing reading, so the denominator is the number of stations that reported, not the six in the table. Report the count of missing values beside any such share." },
{ q:"Give the two mistakes case_when() invites, and the fix for each.",
  a:"Branches are tried in order, so a broad condition above a narrow one hides it — read them top to bottom the way R does. And a row whose conditions are all NA falls through to .default, which is why the missing station was labelled \"heavy\" — no branch can match NA, so give missingness one of its own above the default. Both if_else() and case_when() also require every branch to return the same type, so mixing \"wet\" with 0 is an error rather than a conversion." }
],
exercises: [
{ c:"vectors", t:"Counting the clear days", book:"r12",
  b:"Given sightings <- c(4, 0, 9, NA, 12, 3), print five things on five lines: the logical vector saying which sightings are greater than 3, the number of them that are, the proportion of the recorded values that are, the number of elements you get when you pull those sightings out of the vector, and those sightings in increasing order. The fourth line must agree with the second.",
  o:"[1]  TRUE FALSE  TRUE    NA  TRUE FALSE\n[1] 3\n[1] 0.6\n[1] 3\n[1]  4  9 12",
  h:["The first line is just the comparison. The next two are summary functions applied to that same comparison, and the last two subset the vector with it.",
     "R counts TRUE as 1 and FALSE as 0, so sum() over a logical vector counts and mean() gives a proportion — both need na.rm = TRUE here, and the proportion is out of the values that are not missing.",
     "Subsetting with the raw comparison keeps an NA placeholder, so the fourth line would come out as 4 and contradict the second. Turn the condition into positions first, and use that same subset for the last line with sort() around it."]},
{ c:"data types", t:"Almost the same number", book:"r12",
  b:"Attach dplyr with suppressMessages(library(dplyr)) so the attach notice does not appear in your output. Store 0.1 + 0.2 in x. Print whether x is exactly equal to 0.3, then whether it is close enough to 0.3, then x itself shown to 18 significant digits.",
  o:"[1] FALSE\n[1] TRUE\n[1] 0.300000000000000044",
  h:["Three lines, all about the same number. Two of them are comparisons that disagree.",
     "== compares what is stored; the dplyr function for close enough is near(), which takes the two numbers.",
     "The third line needs print() with its digits argument set to 18 — the default of seven is what hides the problem in the first place."]},
{ c:"vectors", t:"Handling the unknowns", book:"r12",
  b:"Given depths <- c(12, NA, 7, 20, NA, 15), print four things on four lines: the logical vector saying which elements are missing, how many are missing, the recorded depths in increasing order, and the mean of the recorded depths.",
  o:"[1] FALSE  TRUE FALSE FALSE  TRUE FALSE\n[1] 2\n[1]  7 12 15 20\n[1] 13.5",
  h:["Missingness has its own function; == will not find it.",
     "is.na() returns TRUE where a value is missing, and summing that logical vector counts them. To keep the recorded values, subset with a condition that is TRUE where the value is present.",
     "Compare the is.na() result to FALSE to get a keep-this vector, use it inside square brackets, and sort the result. The mean takes na.rm = TRUE, or the vector you already filtered."]},
{ c:"dplyr verbs", t:"Band the plots", book:"r12",
  b:"Attach dplyr with suppressMessages(library(dplyr)) and attach tibble. Build a tibble named plots with plot_id holding \"p1\" through \"p5\" and yield_kg holding 0, 6, NA, 18, 11. Add a column band that is \"unrecorded\" where the yield is missing, \"none\" where it is 0, \"light\" where it is under 12, and \"heavy\" otherwise. Print the result ordered by plot_id.",
  o:"# A tibble: 5 × 3\n  plot_id yield_kg band      \n  <chr>      <dbl> <chr>     \n1 p1             0 none      \n2 p2             6 light     \n3 p3            NA unrecorded\n4 p4            18 heavy     \n5 p5            11 light     ",
  h:["Four outcomes means one function rather than nested two-way choices, and the new column is added with mutate().",
     "case_when() takes condition ~ value pairs and a .default for what is left. Its branches are tried in order, so the order you write them in decides the answer.",
     "No condition can ever be TRUE for a missing yield, so without a branch testing for it directly that row falls through to .default and comes out labelled heavy. Write that branch first, and finish the pipeline with arrange() on the id column."]}
]
};
