/* Practice Log book — R Chapter 13: Numbers.
   Original lesson text following the chapter-by-chapter curriculum of
   "R for Data Science" (2nd ed.) by Hadley Wickham, Mine Cetinkaya-Rundel,
   and Garrett Grolemund. Read the original chapter free at the src link below.
   Every shown output was captured by executing the code in WebR, not written from memory. */
window.BOOK_R = window.BOOK_R || { chapters: {} };
window.BOOK_R.chapters.r13 = {
n: 13,
title: "Numbers",
src: "https://r4ds.hadley.nz/numbers.html",
blurb: "Turning text into numbers, counting rows, and the arithmetic R does its own way — recycling, remainders, rounding, bins, ranks, offsets, and summaries.",
pkgs: ["readr", "dplyr", "tibble"],
sections: [
{ t: "Numbers that arrive as text",
  body: [
  ["p","Numbers rarely reach you as numbers. They arrive from a spreadsheet exported as plain text, from a table someone copied out of a web page, from a column where a currency symbol was typed in front of every figure. Nothing can be added or averaged until that text has become a double, so parsing is the first step of most numeric work rather than a detail at the end of it."],
  ["p","readr supplies the parsers. dplyr supplies the counting, ranking, and offset functions used later in the chapter, and tibble supplies the table. None of the three is part of base R. Attaching dplyr prints the notice you met in chapter 3, listing the base functions it hides; suppressMessages() keeps that notice out of the output so the rest of this chapter shows only what the code produced."],
  ["code","library(readr)\nlibrary(tibble)\nsuppressMessages(library(dplyr))"],
  ["p","parse_double() is the strict parser. It accepts strings that contain a number and nothing else, and hands back a double vector."],
  ["code","parse_double(c(\"3.5\", \"-2.25\", \"0.125\"))"],
  ["code","[1]  3.500 -2.250  0.125"],
  ["p","Notice that all three values printed to three decimal places. A double vector has one display width for the whole vector, chosen so the value needing the most digits is shown in full, so 3.5 becomes 3.500 because 0.125 is in the same vector. That is a printing decision, not a change to the stored numbers."],
  ["p","parse_number() is the forgiving parser. It looks for the first number inside each string and discards everything wrapped around it: currency symbols, thousands separators, percent signs, padding spaces."],
  ["code","gate <- c(\"1,204\", \"£3.50\", \"18%\", \" 42 \")\n\nparse_number(gate)"],
  ["code","[1] 1204.0    3.5   18.0   42.0"],
  ["p","Read the third value carefully. \"18%\" parsed to 18, not to 0.18. Throwing away the symbol is the whole of what parse_number() promises, and a percentage that has to become a proportion is a division you write yourself. Both parsers return an ordinary numeric vector, which is what every function in the rest of the chapter expects."],
  ["code","class(parse_double(c(\"3.5\", \"-2.25\")))\nclass(parse_number(\"1,204\"))"],
  ["code","[1] \"numeric\"\n[1] \"numeric\""],
  ["p","The base R alternative is as.numeric(), and it is the wrong tool for messy text. Handed a string it cannot read, it does not stop — it returns NA and warns."],
  ["code","as.numeric(\"£3.50\")"],
  ["code","Warning in eval(ei, envir) : NAs introduced by coercion\n[1] NA"],
  ["note","That NA is the failure mode to watch for. A whole column of prices run through as.numeric() becomes a whole column of NA, the warning scrolls past, and the first symptom is a mean of NA several steps later — by which point the cause is three functions back. The warning line in this app names R's internals before the colon rather than your code; the message you want is the part after it."]
]},
{ t: "Counting",
  body: [
  ["p","Before any average is worth computing it is worth knowing how many rows went into it. Counting is the cheapest check on a table you have not seen before, and dplyr gives it a verb of its own. The table below records lane bookings at a swimming pool: which session, which lane, how many swimmers turned up, and how long the lane was held."],
  ["code","pool <- tibble(\n  session = c(\"dawn\", \"dawn\", \"midday\", \"midday\", \"midday\", \"evening\", \"evening\", \"evening\"),\n  lane    = c(1L, 2L, 1L, 2L, 3L, 1L, 2L, 3L),\n  swimmers = c(4L, 7L, 12L, 9L, 15L, 22L, 18L, 25L),\n  minutes = c(45, 60, 30, 55, 40, 75, 62, 80)\n)\n\npool"],
  ["code","# A tibble: 8 × 4\n  session  lane swimmers minutes\n  <chr>   <int>    <int>   <dbl>\n1 dawn        1        4      45\n2 dawn        2        7      60\n3 midday      1       12      30\n4 midday      2        9      55\n5 midday      3       15      40\n6 evening     1       22      75\n7 evening     2       18      62\n8 evening     3       25      80"],
  ["p","count() takes a data frame and one or more columns, and returns one row per distinct combination with the number of rows in a column called n. The result is sorted by the grouping column, which is why evening comes before midday here — alphabetical order, not the order of the day."],
  ["code","count(pool, session)"],
  ["code","# A tibble: 3 × 2\n  session     n\n  <chr>   <int>\n1 dawn        2\n2 evening     3\n3 midday      3"],
  ["p","sort = TRUE reorders the answer by n, largest first, which is what you want when the question is which category dominates. Ties keep the order they had."],
  ["code","count(pool, session, sort = TRUE)"],
  ["code","# A tibble: 3 × 2\n  session     n\n  <chr>   <int>\n1 evening     3\n2 midday      3\n3 dawn        2"],
  ["p","The wt argument changes what is being counted. Without it, every row contributes 1. With wt = swimmers, every row contributes its own swimmers value, so n becomes a total rather than a tally. The column is still called n, which is the part that catches people out."],
  ["code","count(pool, session, wt = swimmers)"],
  ["code","# A tibble: 3 × 2\n  session     n\n  <chr>   <int>\n1 dawn       11\n2 evening    65\n3 midday     36"],
  ["p","count() is shorthand. The long form is group_by() and summarise() with n(), and the long form is what you reach for once the answer needs more than one number per group. n() takes no arguments; it reports the number of rows in whatever group is current."],
  ["code","pool |>\n  group_by(session) |>\n  summarise(lanes = n(), people = sum(swimmers))"],
  ["code","# A tibble: 3 × 3\n  session lanes people\n  <chr>   <int>  <int>\n1 dawn        2     11\n2 evening     3     65\n3 midday      3     36"],
  ["p","n_distinct() answers the other counting question: how many different values are in a vector, rather than how many entries. Three sessions were run across eight bookings, and no two bookings drew the same number of swimmers."],
  ["code","n_distinct(pool$session)\nn_distinct(pool$swimmers)"],
  ["code","[1] 3\n[1] 8"],
  ["note","n() is not the same as n_distinct(), and the similar names cost people an afternoon. n() counts rows and works only inside a dplyr verb, because it needs to know which group it is in. n_distinct() counts unique values in a vector you hand it, and works anywhere. Calling n() at the console gives an error about being used in the wrong context, not a number."]
]},
{ t: "Arithmetic and recycling",
  body: [
  ["p","Arithmetic on two vectors of the same length is elementwise: R pairs up position one with position one, position two with position two, and so on. The result is a vector as long as the inputs. Four lane lengths and four lap counts give four distances."],
  ["code","lengths_m <- c(25, 25, 50, 50)\nlaps <- c(12, 20, 6, 9)\n\nlengths_m * laps"],
  ["code","[1] 300 500 300 450"],
  ["p","A single number is a vector of length one, so multiplying a vector by 2 is the same operation with a shorter partner. R repeats the short vector until it is as long as the other one. This is called recycling, and it is why arithmetic with a constant needs no loop and no special syntax."],
  ["code","laps * 2\nlaps + 100"],
  ["code","[1] 24 40 12 18\n[1] 112 120 106 109"],
  ["p","Recycling is not limited to length one. When the longer length is a whole multiple of the shorter, R repeats the short vector as many times as it takes and says nothing about it. A vector of two against a vector of six is three full repeats."],
  ["code","c(1, 2, 3, 4, 5, 6) * c(10, 100)"],
  ["code","[1]  10 200  30 400  50 600"],
  ["p","When the longer length is not a whole multiple, R still does the work — it recycles as far as it can and stops in the middle of a repeat — but it warns, because that is almost never what anyone meant."],
  ["code","c(1, 2, 3, 4, 5) * c(10, 100)"],
  ["code","Warning in c(1, 2, 3, 4, 5) * c(10, 100) :\n  longer object length is not a multiple of shorter object length\n[1]  10 200  30 400  50"],
  ["note","The warning is the only protection you get, and it appears in exactly one case: a mismatch that is not a multiple. Two vectors of length 6 and length 2 recycle silently, so a filtered column that has quietly dropped to a third of its original length can multiply against another column with no complaint at all and produce a plausible, wrong answer. Compare lengths yourself before you multiply columns that came from different places."],
  ["p","min() and max() take everything they are given and return one number. pmin() and pmax() are the elementwise versions: they compare position against position and return a vector. The p stands for parallel, and mixing the two up is the difference between one answer and a column of them."],
  ["code","pmin(c(3, 9, 4), c(5, 2, 4))\npmax(c(3, 9, 4), c(5, 2, 4))\nmin(c(3, 9, 4), c(5, 2, 4))"],
  ["code","[1] 3 2 4\n[1] 5 9 4\n[1] 2"]
]},
{ t: "Integer division, remainders, and logarithms",
  body: [
  ["p","Ordinary division gives a decimal. Two other operators split a division into its whole part and its leftover: %/% returns how many times the divisor goes in, and %% returns what is left over. Together they turn a duration in seconds into minutes and seconds."],
  ["code","seconds <- c(75, 130, 3599, 45)\n\nseconds %/% 60\nseconds %% 60"],
  ["code","[1]  1  2 59  0\n[1] 15 10 59 45"],
  ["p","Both are vectorised like every other operator here, so one line converts the whole column. %% is also the standard test for divisibility: a value is even when x %% 2 is 0, and every tenth row is the one where the row number %% 10 is 0."],
  ["p","Negative numbers are where the two operators stop agreeing with intuition. %/% rounds down towards negative infinity rather than towards zero, so -7 %/% 2 is -4 and not -3."],
  ["code","-7 %/% 2\n-7 %% 2\n-7 / 2"],
  ["code","[1] -4\n[1] 1\n[1] -3.5"],
  ["p","The remainder is 1, a positive number, because R defines the pair so that the whole part times the divisor plus the remainder returns the original value: -4 times 2 plus 1 is -7. The consequence is that %% in R takes the sign of the divisor, not the sign of the value being divided. Flip the sign of the divisor and the remainder flips with it."],
  ["code","7 %/% -2\n7 %% -2"],
  ["code","[1] -4\n[1] -1"],
  ["note","If you have written modular arithmetic in C, Java, or JavaScript, this is the opposite of the rule you know: those languages truncate towards zero and give a remainder with the sign of the left-hand side. R follows the mathematical convention instead. Code that tests x %% 2 == 1 to find odd numbers works in R for negatives and fails in those languages, and code translated the other way fails here."],
  ["p","Dividing by zero does not raise an error in either operator. It produces the special values Inf and NaN, which then travel through every calculation downstream without ever stopping anything."],
  ["code","2.5 %/% 0.5\n5 %/% 0\n5 %% 0"],
  ["code","[1] 5\n[1] Inf\n[1] NaN"],
  ["p","log() is the natural logarithm; log2() and log10() are the ones worth using when the answer has to be read by a person. log2() answers how many doublings, so a jump of 1 is twice as much. log10() answers how many powers of ten, so a jump of 1 is an order of magnitude. exp() undoes the natural log."],
  ["code","log(100)\nlog10(100)\nlog2(1024)\nexp(log(100))"],
  ["code","[1] 4.60517\n[1] 2\n[1] 10\n[1] 100"]
]},
{ t: "Rounding",
  body: [
  ["p","round() looks like the simplest function in R and hides the chapter's best surprise. Round a run of values sitting exactly halfway and the answers do not alternate the way school arithmetic taught you."],
  ["code","round(0.5)\nround(1.5)\nround(2.5)\nround(3.5)\nround(-1.5)"],
  ["code","[1] 0\n[1] 2\n[1] 2\n[1] 4\n[1] -2"],
  ["p","0.5 rounded down to 0 and 1.5 rounded up to 2, and both landed on an even number. So did 2.5 and 3.5. This is round half to even, sometimes called banker's rounding: when a value is exactly halfway, R picks whichever neighbour is even. Seen as a single vector the pattern is unmistakable."],
  ["code","round(c(0.5, 1.5, 2.5, 3.5, 4.5))"],
  ["code","[1] 0 2 2 4 4"],
  ["p","The reason is bias. Always rounding halves upwards pushes every total in a data set slightly high, and over thousands of values that drift is measurable. Splitting the halves evenly between up and down cancels it. The cost is that round(2.5) returns 2, which looks like a bug the first time you see it in a report."],
  ["p","A second argument says how many decimal places to keep. Make it negative and rounding moves left of the decimal point instead: -2 rounds to the nearest hundred."],
  ["code","round(3.14159, 2)\nround(1234.567, -2)\nround(2.675, 2)"],
  ["code","[1] 3.14\n[1] 1200\n[1] 2.67"],
  ["p","That last answer is not banker's rounding. 2.675 cannot be stored exactly in binary, and the value R actually holds is a hair below 2.675, so it is not a halfway case at all and rounds down honestly. Which brings up the other thing every numeric chapter has to say."],
  ["code","0.1 + 0.2 == 0.3\n0.1 + 0.2 - 0.3\nnear(0.1 + 0.2, 0.3)"],
  ["code","[1] FALSE\n[1] 5.551115e-17\n[1] TRUE"],
  ["note","Doubles are stored in binary, and 0.1, 0.2, and 2.675 have no exact binary form, in the same way that a third has no exact decimal form. The error is around 5.55e-17, far too small to see and more than enough to break ==. Never test computed doubles with ==; dplyr's near() compares them with a tolerance and is the function to reach for. Whole numbers are stored exactly, so == is safe on counts."],
  ["p","floor() and ceiling() always go one way regardless of the fractional part. trunc() throws the fraction away, which matches floor() for positive values and ceiling() for negative ones."],
  ["code","floor(2.7)\nceiling(2.1)\nfloor(-2.1)\nceiling(-2.1)\ntrunc(-2.7)"],
  ["code","[1] 2\n[1] 3\n[1] -3\n[1] -2\n[1] -2"],
  ["p","There is no built-in function for rounding to the nearest 5 or 25, and none is needed: divide, round, multiply back. The same trick with floor() gives the bin a value falls into, which is one way of doing what the next section does properly."],
  ["code","round(c(11, 12, 13, 14, 17) / 5) * 5"],
  ["code","[1] 10 10 15 15 15"]
]},
{ t: "Cutting numbers into bins",
  body: [
  ["p","Turning a numeric column into a small set of named groups is one of the most common moves in data work: depths become shallow and deep, ages become brackets, scores become bands. cut() does it. Give it a vector and a set of break points, and it returns a factor saying which interval each value fell into."],
  ["code","depth_cm <- c(80, 120, 95, 200, 145, 60, 175)\n\ncut(depth_cm, breaks = c(0, 100, 150, 250))"],
  ["code","[1] (0,100]   (100,150] (0,100]   (150,250] (100,150] (0,100]   (150,250]\nLevels: (0,100] (100,150] (150,250]"],
  ["p","Four break points produce three intervals, which is the first thing to count when the number of groups comes out wrong. The level names are interval notation: a round bracket means the endpoint is excluded, a square bracket means it is included. So (0,100] runs above 0 up to and including 100."],
  ["p","Machine-generated labels like (100,150] are precise and unreadable in a report. The labels argument replaces them, and there must be exactly as many labels as intervals. The result is a factor, so table() counts it directly."],
  ["code","zone <- cut(depth_cm,\n            breaks = c(0, 100, 150, 250),\n            labels = c(\"shallow\", \"middle\", \"deep\"))\n\nzone\nclass(zone)\ntable(zone)"],
  ["code","[1] shallow middle  shallow deep    middle  shallow deep   \nLevels: shallow middle deep\n[1] \"factor\"\nzone\nshallow  middle    deep \n      3       2       2 "],
  ["p","By default the intervals are open on the left and closed on the right, so a value sitting exactly on a break goes into the lower interval. right = FALSE flips every interval the other way, and the printed levels change with it — the brackets in the output always tell you which convention is in force."],
  ["code","cut(c(100, 150), breaks = c(0, 100, 150, 250))\ncut(c(100, 150), breaks = c(0, 100, 150, 250), right = FALSE)"],
  ["code","[1] (0,100]   (100,150]\nLevels: (0,100] (100,150] (150,250]\n[1] [100,150) [150,250)\nLevels: [0,100) [100,150) [150,250)"],
  ["p","The lowest break is the one to think about. With the default settings it is excluded from everything, so a value equal to the smallest break belongs to no interval and comes back as NA. include.lowest = TRUE pulls it into the first interval."],
  ["code","cut(50, breaks = c(50, 100))\ncut(50, breaks = c(50, 100), include.lowest = TRUE)"],
  ["code","[1] <NA>\nLevels: (50,100]\n[1] [50,100]\nLevels: [50,100]"],
  ["note","Values outside the range of the breaks also become NA, silently. Set your outer breaks from the data — or from -Inf and Inf when you want a catch-all — and count the NA values afterwards with sum(is.na(...)). A binned column that lost a tenth of its rows to out-of-range values looks completely normal until someone adds up the groups and finds they do not reach the row total."]
]},
{ t: "Cumulative aggregates, ranks, and offsets",
  body: [
  ["p","The functions in this section all share one property: each answer depends on where the value sits in the vector, not only on the value itself. That makes order meaningful, so arrange the data before you use any of them."],
  ["p","The cumulative family walks along a vector keeping a running answer. cumsum() gives the running total, cummax() the largest value seen so far, cummin() the smallest. Each returns a vector the same length as its input."],
  ["code","daily <- c(4, 7, 12, 9, 15, 22, 18, 25)\n\ncumsum(daily)\ncummax(daily)\ncummin(daily)"],
  ["code","[1]   4  11  23  32  47  69  87 112\n[1]  4  7 12 12 15 22 22 25\n[1] 4 4 4 4 4 4 4 4"],
  ["p","Reading cummax() back gives the record-so-far at every point: the run of 12 12 says day four did not beat day three. cumsum() ends at 112, the same number sum() would give, which is a quick sanity check that nothing was dropped."],
  ["p","Ranking asks a different question: where does each value stand against the others. dplyr has three ranking functions and they differ only in how they treat ties, which is exactly the case a small example has to include."],
  ["code","scores <- c(12, 9, 12, 15, 9)\n\nmin_rank(scores)\ndense_rank(scores)\nrow_number(scores)"],
  ["code","[1] 3 1 3 5 1\n[1] 2 1 2 3 1\n[1] 3 1 4 5 2"],
  ["p","min_rank() gives tied values the same rank and then leaves a gap: the two nines both rank 1, so nothing ranks 2. dense_rank() gives them the same rank and leaves no gap, so its ranks run 1, 2, 3 with no numbers missing. row_number() refuses to tie anything — it breaks ties by position, so the first nine gets 1 and the second gets 2, and the result is always a permutation of 1 to n."],
  ["p","All three rank smallest first. For largest first, wrap the column in desc()."],
  ["code","min_rank(desc(scores))"],
  ["code","[1] 2 4 2 1 4"],
  ["p","The offset functions shift a vector along by one position. lag() moves values forward so each position holds the previous one, and lead() moves them back so each position holds the next one. The end that has nothing to shift in gets NA, and subtracting a lagged vector from the original gives the change from row to row."],
  ["code","lag(daily)\nlead(daily)\ndaily - lag(daily)"],
  ["code","[1] NA  4  7 12  9 15 22 18\n[1]  7 12  9 15 22 18 25 NA\n[1] NA  3  5 -3  6  7 -4  7"],
  ["p","The n argument shifts further than one place, and default supplies a value to use instead of NA at the exposed end. A default of 0 is right when the series starts from nothing and wrong when the value before the first row is simply unknown, so choose it rather than reaching for it."],
  ["code","lag(daily, n = 2)\nlag(daily, default = 0)"],
  ["code","[1] NA NA  4  7 12  9 15 22\n[1]  0  4  7 12  9 15 22 18"],
  ["p","consecutive_id() numbers runs rather than values. It increases by one every time the value changes from the previous position, so a value that comes back later gets a new number rather than its old one."],
  ["code","consecutive_id(c(\"open\", \"open\", \"shut\", \"open\", \"open\"))"],
  ["code","[1] 1 1 2 3 3"],
  ["note","dplyr's lag() hides a base R function of the same name that works on time series and does something else entirely. That is one of the names listed in the attach notice from chapter 3. If lag() returns an object you did not expect, dplyr is probably not attached, and the fix is stats::lag versus dplyr::lag rather than anything wrong with your data."]
]},
{ t: "Numeric summaries",
  body: [
  ["p","A summary replaces many numbers with one, and the choice of which one is a decision about what you are willing to lose. mean() is the balance point and moves with every extreme value; median() is the middle value and mostly does not. Reporting both is the cheapest test for skew: when they differ a lot, something is pulling the mean."],
  ["code","minutes <- pool$minutes\n\nmean(minutes)\nmedian(minutes)\nsd(minutes)\nIQR(minutes)\nrange(minutes)"],
  ["code","[1] 55.875\n[1] 57.5\n[1] 17.0833\n[1] 21.5\n[1] 30 80"],
  ["p","sd() and IQR() both describe spread. The standard deviation uses every value and inherits the mean's sensitivity to extremes; the interquartile range is the distance between the 25th and 75th percentiles and ignores the tails entirely. range() returns two numbers rather than one, the minimum and the maximum."],
  ["p","quantile() generalises the median. Ask for 0.5 and you get the median; ask for several probabilities at once and you get a named vector, with the names telling you which is which."],
  ["code","quantile(minutes, c(0.25, 0.5, 0.75))"],
  ["code","  25%   50%   75% \n43.75 57.50 65.25 "],
  ["p","Missing values stop every one of these functions cold, and deliberately. A mean over a vector containing NA is NA, because R will not guess what the missing value would have been. na.rm = TRUE says to drop them, and the honest habit is to count them first so you know how much of the data the summary is ignoring."],
  ["code","gaps <- c(4, NA, 9, 12)\n\nmean(gaps)\nmean(gaps, na.rm = TRUE)\nsum(is.na(gaps))"],
  ["code","[1] NA\n[1] 8.333333\n[1] 1"],
  ["p","A comparison returns a logical vector, and R treats TRUE as 1 and FALSE as 0 in arithmetic. So sum() over a comparison counts how many rows satisfy it, and mean() over the same comparison gives the proportion. These two lines replace a great deal of counting code."],
  ["code","sum(pool$swimmers > 10)\nmean(pool$swimmers > 10)"],
  ["code","[1] 5\n[1] 0.625"],
  ["p","Every summary function above works inside summarise(), which is where they earn their keep: one call, one row per group, several statistics side by side. Arrange the result so the order is yours rather than whatever the grouping happened to produce."],
  ["code","pool |>\n  group_by(session) |>\n  summarise(\n    lanes = n(),\n    mean_swimmers = mean(swimmers),\n    busiest = max(swimmers)\n  ) |>\n  arrange(session)"],
  ["code","# A tibble: 3 × 4\n  session lanes mean_swimmers busiest\n  <chr>   <int>         <dbl>   <int>\n1 dawn        2           5.5       7\n2 evening     3          21.7      25\n3 midday      3          12        15"],
  ["note","The mean_swimmers column prints as 21.7 and 12, not 21.66667 and 12.00000. A tibble picks a display width for the whole column and shows three significant figures by default, so a summary can look rounder than it is. The stored value is unrounded; if the rounding is meant to be real, do it yourself with round() inside summarise() rather than trusting what you see."]
]},
{ t: "Summary",
  body: [
  ["p","Text becomes numbers through readr: parse_double() for strings that are already clean, parse_number() for strings wearing currency symbols, separators, and percent signs. as.numeric() answers a failure with NA and a warning rather than an error, which is why a bad parse is usually found late. Counting comes before summarising: count() for a tally, count() with wt for a total, n() inside a dplyr verb for rows in a group, n_distinct() for unique values anywhere."],
  ["p","Arithmetic is elementwise and recycles the shorter vector, silently when the lengths divide and with a warning when they do not. %/% and %% split a division into whole part and remainder, both rounding towards negative infinity so that negatives behave differently from most other languages. round() rounds halves to the nearest even number, a second argument sets decimal places and goes negative to round left of the point, and doubles compared with == will eventually betray you — use near()."],
  ["p","cut() turns a numeric column into a labelled factor, with intervals closed on the right until right = FALSE says otherwise and values outside the breaks silently becoming NA. cumsum() and cummax() carry a running answer along a vector. min_rank(), dense_rank(), and row_number() rank the same values three different ways, differing only over ties. lag() and lead() shift a vector by a position so that row-to-row change becomes a subtraction. mean(), median(), sd(), IQR(), and quantile() summarise, na.rm = TRUE is how missing values are excluded, and sum() or mean() over a comparison counts or proportions it."],
  ["p","Answer the practice questions from memory before revealing the answers, then clear the graded exercises below. The next chapter is Strings: how to write one with quotes and escapes, how to build many of them from the columns of a table, and how to pull them apart again."]
]}
],
questions: [
{ q:"What is the difference between parse_double() and parse_number(), and what does parse_number() return for \"18%\"?",
  a:"parse_double() only accepts strings that contain a number and nothing else. parse_number() finds the first number in a string and discards the surrounding characters, so \"1,204\" becomes 1204 and \"£3.50\" becomes 3.5. For \"18%\" it returns 18, not 0.18 — dropping the symbol is all it does, and converting a percentage to a proportion is your own division." },
{ q:"You run as.numeric() over a column of prices written as \"£3.50\". What happens, and why is it a problem?",
  a:"Every value it cannot read becomes NA and R prints a warning rather than stopping. The column looks like a numeric column, so nothing fails until a mean or a sum comes back as NA several steps later, with the cause well out of sight. parse_number() is the tool that handles the symbol." },
{ q:"count(pool, session) and count(pool, session, wt = swimmers) both return a column called n. What does each one hold?",
  a:"Without wt, every row contributes 1, so n is the number of rows per session: 2, 3, 3. With wt = swimmers, every row contributes its own swimmers value, so n is the total number of swimmers: 11 for dawn, 65 for evening, 36 for midday. The column name does not change, which is what makes the two easy to confuse." },
{ q:"c(1, 2, 3, 4, 5, 6) * c(10, 100) runs without complaint but c(1, 2, 3, 4, 5) * c(10, 100) warns. Why?",
  a:"R recycles the shorter vector to the length of the longer one. Six is a whole multiple of two, so the short vector repeats exactly three times and R says nothing. Five is not a multiple of two, so the last repeat is cut off part way and R warns that the longer object length is not a multiple of the shorter. The result is still returned either way." },
{ q:"What do -7 %/% 2 and -7 %% 2 return, and how does that compare with C or JavaScript?",
  a:"-4 and 1. %/% rounds down towards negative infinity rather than towards zero, and the remainder is defined so that -4 times 2 plus 1 gives -7, which makes the remainder take the sign of the divisor. C and JavaScript truncate towards zero and give -3 and -1 instead, so modular arithmetic translated between the two languages breaks on negative values." },
{ q:"round(0.5) returns 0 and round(1.5) returns 2. What rule is R following, and why?",
  a:"Round half to even, also called banker's rounding: a value sitting exactly halfway goes to whichever neighbour is even. Over a whole column it removes the upward bias that always-round-up introduces. The whole run makes the pattern plain — round(c(0.5, 1.5, 2.5, 3.5, 4.5)) gives 0 2 2 4 4." },
{ q:"Why does 0.1 + 0.2 == 0.3 return FALSE, and what should you use instead?",
  a:"Doubles are stored in binary and 0.1, 0.2, and 0.3 have no exact binary representation, so the sum differs from 0.3 by about 5.55e-17. Use dplyr's near(), which compares with a tolerance. Whole numbers are stored exactly, so == is safe for counts." },
{ q:"cut(50, breaks = c(50, 100)) returns NA. What happened, and what are the two arguments that change binning behaviour?",
  a:"By default the intervals are open on the left and closed on the right, so the lowest break is excluded from every interval and a value equal to it belongs to none. include.lowest = TRUE pulls it into the first interval. right = FALSE flips every interval to be closed on the left instead. Values outside the range of the breaks also become NA, silently." },
{ q:"For scores of 12, 9, 12, 15, 9, what do min_rank(), dense_rank(), and row_number() return?",
  a:"min_rank() gives 3 1 3 5 1 — ties share a rank and leave a gap after it. dense_rank() gives 2 1 2 3 1 — ties share a rank and leave no gap. row_number() gives 3 1 4 5 2 — ties are broken by position, so the result is always a permutation of 1 to n. All three rank smallest first; wrap the column in desc() to rank largest first." },
{ q:"How do you compute the change from one row to the next, and what does mean() do when the vector contains NA?",
  a:"Subtract the lagged vector from the original: daily - lag(daily). lag() shifts values forward one position and leaves NA at the start, so the first difference is NA. mean() over a vector containing NA returns NA, because R will not guess the missing value; na.rm = TRUE drops them, and sum(is.na(x)) tells you how many were dropped." }
],
exercises: [
{ c:"vectors", t:"Minutes and seconds", book:"r13",
  b:"Build a numeric vector named elapsed holding 95, 240, 61, 3725, in that order. Print, on two lines, the number of whole minutes in each value and then the seconds left over.",
  o:"[1]  1  4  1 62\n[1] 35  0  1  5",
  h:["Splitting a division into a whole part and a leftover takes two operators, not one.",
     "%/% gives the whole number of times the divisor fits, and %% gives the remainder. Both work on a whole vector at once, so neither line needs a loop.",
     "Assign the vector with c(), then write two single expressions on two lines: the vector divided by 60 with the integer-division operator, then the vector against 60 with the remainder operator."]},
{ c:"vectors", t:"Running totals and standings", book:"r13",
  b:"Attach dplyr with suppressMessages(library(dplyr)). Build a numeric vector named points holding 6, 11, 6, 14, 9, in that order. Print three lines: the running total, the rank of each value with the largest counted as first and ties sharing a rank, and the rank of each value smallest first with no gaps left by ties.",
  o:"[1]  6 17 23 37 46\n[1] 4 2 4 1 3\n[1] 1 3 1 4 2",
  h:["Three functions, three lines, and the vector is never sorted — every answer keeps the original positions.",
     "The running total is a cumulative sum. Ranking largest first means wrapping the vector in desc(). The two ranking functions differ only in whether a tie leaves a gap behind it.",
     "Line one is cumsum(). Line two is one of the rank functions applied to desc(points), the one where tied values share a rank and the next rank is skipped. Line three is the rank function whose output never skips a number."]},
{ c:"grouping & summaries", t:"Parcels per depot", book:"r13",
  b:"Attach dplyr with suppressMessages(library(dplyr)) and tibble with library(tibble). Build a tibble named deliveries with a character column depot holding \"north\", \"south\", \"north\", \"east\", \"south\", \"north\" and an integer column parcels holding 12L, 9L, 4L, 21L, 15L, 8L. Print the total number of parcels for each depot, with the depots in alphabetical order and the total in a column named n.",
  o:"# A tibble: 3 × 2\n  depot     n\n  <chr> <int>\n1 east     21\n2 north    24\n3 south    24",
  h:["The column has to be named n, which is a strong hint about which verb produces it.",
     "count() counts rows by default, and its wt argument changes what each row contributes. Follow it with arrange() so the order is yours rather than incidental.",
     "Build the tibble, then pipe it into count() with the grouping column and wt set to the column being totalled, then pipe that into arrange() on the depot column."]},
{ c:"grouping & summaries", t:"Firing time by glaze", book:"r13",
  b:"Attach dplyr with suppressMessages(library(dplyr)) and tibble with library(tibble). Build a tibble named kiln with a character column glaze holding \"ash\", \"ash\", \"ash\", \"salt\", \"salt\", \"tin\", \"tin\" and a double column hours holding 9.5, 11.25, 8.75, 14, 12.5, 6.5, 7.25. For each glaze print the number of firings in a column named firings and the mean number of hours rounded to one decimal place in a column named mean_hours, with the glazes in alphabetical order.",
  o:"# A tibble: 3 × 3\n  glaze firings mean_hours\n  <chr>   <int>      <dbl>\n1 ash         3        9.8\n2 salt        2       13.2\n3 tin         2        6.9",
  h:["Two statistics per group means summarise() rather than count().",
     "Group by the glaze column first. Inside summarise(), n() counts the rows in the current group and mean() averages a column; the rounding is a function wrapped around the mean, not an argument to it.",
     "The shape is group_by() then summarise(firings = ..., mean_hours = round(..., 1)) then arrange(). A tibble shortens what it displays, so the rounding has to happen in the code — leaving it out gives visibly different numbers here."]}
]
};
