/* Practice Log book — R Chapter 14: Strings.
   Original lesson text following the chapter-by-chapter curriculum of
   "R for Data Science" (2nd ed.) by Hadley Wickham, Mine Cetinkaya-Rundel,
   and Garrett Grolemund. Read the original chapter free at the src link below.
   Every shown output was captured by executing the code in WebR, not written from memory. */
window.BOOK_R = window.BOOK_R || { chapters: {} };
window.BOOK_R.chapters.r14 = {
n: 14,
title: "Strings",
src: "https://r4ds.hadley.nz/strings.html",
blurb: "Quoting and escaping text, building many strings out of columns, splitting them apart again, and counting letters in writing that is not English.",
pkgs: ["stringr", "tibble", "tidyr", "dplyr"],
sections: [
{ t: "Writing a string down",
  body: [
  ["p","A string is a piece of text, and R gives you two ways to write one: between double quotes or between single quotes. The two are not two kinds of string. They produce exactly the same value, and R stores no memory of which one you typed."],
  ["p","stringr supplies the string functions in this chapter. It is the tidyverse package for text, every function is named str_ followed by a verb, and the string you are working on is always the first argument, which is what makes the pipe work. tidyr and dplyr appear later for splitting columns and building tables; tibble prints them."],
  ["code","library(stringr)\nlibrary(tibble)\nlibrary(tidyr)\nsuppressMessages(library(dplyr))"],
  ["code","identical('badger', \"badger\")"],
  ["code","[1] TRUE"],
  ["p","Since the two are interchangeable, the choice is about what is inside the text. A string holding an apostrophe is easiest in double quotes; a string holding a double quote is easiest in single quotes. Pick the quote character the text does not contain and there is nothing to escape."],
  ["code","apostrophe <- \"it's a dry summer\"\nquotation <- 'she wrote \"no rain since May\"'\n\napostrophe\nquotation"],
  ["code","[1] \"it's a dry summer\"\n[1] \"she wrote \\\"no rain since May\\\"\""],
  ["p","Look at the second line of that output. R stored the text you typed, but it printed the string wrapped in double quotes with backslashes in front of the inner ones. That display is the first thing to understand about strings in R, and the next section is about it. For now, note that the escaped double-quoted version is the same string as the single-quoted one."],
  ["code","escaped <- \"she wrote \\\"no rain since May\\\"\"\n\nidentical(escaped, quotation)"],
  ["code","[1] TRUE"],
  ["note","The tidyverse convention is double quotes everywhere, with single quotes used only when the text contains a double quote. Mixing the two at random is legal and makes a script harder to scan. Decide once."]
]},
{ t: "Escapes, and the two ways a string is shown",
  body: [
  ["p","Some characters cannot be typed inside a string directly, so R uses a backslash followed by a letter to stand in for them. Backslash-t is a tab and backslash-n is a newline. Both are one character in the string, however many characters it took to write them down."],
  ["p","Printing a string at the console shows its source form: quotes around it and escapes spelled out, so that what you see could be pasted back into a script. cat() shows the string itself, with the escapes resolved into the characters they stand for. Every confusion about strings in R starts here."],
  ["code","tabbed <- \"gauge\\t14\"\n\ntabbed\ncat(tabbed)"],
  ["code","[1] \"gauge\\t14\"\ngauge\t14"],
  ["p","One value, two renderings. The first line is R showing you how to write the string; the second is R showing you the string. A newline behaves the same way, which is more obvious because the effect takes up a line."],
  ["code","lines <- \"first line\\nsecond line\"\n\nlines\ncat(lines)"],
  ["code","[1] \"first line\\nsecond line\"\nfirst line\nsecond line"],
  ["p","Because a backslash starts an escape, a string containing a real backslash needs two of them: the first says an escape is coming, the second says the escape is a backslash. A Windows file path is the usual place this bites. Count the characters and you can see that the doubling is only in the writing."],
  ["code","path <- \"C:\\\\field\\\\notes.txt\"\n\npath\nstr_length(path)\ncat(path)"],
  ["code","[1] \"C:\\\\field\\\\notes.txt\"\n[1] 18\nC:\\field\\notes.txt"],
  ["p","Eighteen characters, one backslash between each part. The doubled backslashes exist in the source you type and in the printed source form, and nowhere else. str_view() is stringr's answer to the confusion: it shows the string with the invisible characters marked in braces instead of escaped, so a tab reads as a tab and a backslash reads as one backslash."],
  ["code","str_view(c(\"gauge\\t14\", \"C:\\\\field\"))"],
  ["code","[1] │ gauge{\\t}14\n[2] │ C:\\field"],
  ["note","The mistake this section exists to prevent: counting the backslashes in printed output and concluding the string is wrong. A path printed as \"C:\\\\field\" holds one backslash, not two. When you are unsure which you have, str_length() settles it and str_view() shows it."]
]},
{ t: "Raw strings and other special characters",
  body: [
  ["p","Doubling every backslash is bearable for one path and unbearable for a pattern full of them, which is exactly what the next chapter is about. A raw string turns escaping off. Write r, then a quote, then an opening bracket, then the text, then a closing bracket and the quote. Everything between the brackets is taken literally."],
  ["code","raw <- r\"(C:\\field\\notes.txt)\"\n\nstr_length(raw)\nidentical(raw, path)\ncat(raw)"],
  ["code","[1] 18\n[1] TRUE\nC:\\field\\notes.txt"],
  ["p","Same eighteen characters, same string, no doubling. The bracket style can be round, square, or curly, and you can put dashes between the quote and the bracket when the text itself contains the closing pair. Square brackets let a raw string hold double quotes and backslashes at once."],
  ["code","tricky <- r\"[a \"quoted\" word and a \\backslash]\"\n\ncat(tricky)"],
  ["code","a \"quoted\" word and a \\backslash"],
  ["p","Characters outside the keyboard are written with a Unicode escape: backslash-u and four hex digits for the common ones, backslash-U and eight for the rest. This matters because a source file with accented characters typed straight into it depends on the file's encoding surviving every editor it passes through, and an escape does not."],
  ["code","\"\\u00e9\"\n\"\\u2713\"\nstr_length(\"\\u2713\")"],
  ["code","[1] \"é\"\n[1] \"✓\"\n[1] 1"],
  ["note","A raw string cannot be built up in pieces, and there is no raw version of a variable — r\"(...)\" is a way of writing a literal, not a function. If the text has to be assembled from values, you are back to ordinary strings and ordinary escaping, which is what the rest of this chapter does."]
]},
{ t: "Building many strings with str_c",
  body: [
  ["p","str_c() joins strings end to end. Given several arguments it pastes them in order with nothing between, and sep puts a separator between every pair."],
  ["code","str_c(\"bay\", \"leaf\")\nstr_c(\"bay\", \"leaf\", sep = \" \")"],
  ["code","[1] \"bayleaf\"\n[1] \"bay leaf\""],
  ["p","The point of str_c() is that it is vectorised. Hand it a vector and a single string and it recycles the short one, exactly as arithmetic did in chapter 13, giving one result per element rather than one result overall."],
  ["code","herbs <- c(\"bay\", \"dill\", \"sage\")\n\nstr_c(herbs, \" leaves\")\nstr_c(\"dried \", herbs, sep = \"\")"],
  ["code","[1] \"bay leaves\"  \"dill leaves\" \"sage leaves\"\n[1] \"dried bay\"  \"dried dill\" \"dried sage\""],
  ["p","Missing values are contagious. A string joined to NA is NA, because R has no idea what the joined text would have said. That is the correct answer and it is rarely the one you wanted in a label column."],
  ["code","str_c(\"plot \", c(\"north\", NA, \"east\"))"],
  ["code","[1] \"plot north\" NA           \"plot east\" "],
  ["p","There are two ways out, and they mean different things. coalesce() from dplyr replaces the missing value with text of your choosing before the join, so the label says what you decided. str_replace_na() turns the missing value into the literal string \"NA\", which keeps the gap visible in the output."],
  ["code","str_c(\"plot \", coalesce(c(\"north\", NA, \"east\"), \"unnamed\"))\nstr_c(\"plot \", str_replace_na(c(\"north\", NA, \"east\")))"],
  ["code","[1] \"plot north\"   \"plot unnamed\" \"plot east\"   \n[1] \"plot north\" \"plot NA\"    \"plot east\" "],
  ["p","The collapse argument changes the job entirely. Without it str_c() returns a vector as long as its input; with it, the whole vector is folded into one string with collapse between the pieces."],
  ["code","str_c(herbs, collapse = \", \")"],
  ["code","[1] \"bay, dill, sage\""],
  ["note","sep and collapse are not alternatives to each other. sep goes between the arguments of one result and leaves the length alone; collapse goes between the elements and reduces the length to one. Reaching for sep when the answer should be a single string is the most common str_c() error, and it fails quietly by returning a vector that looks nearly right."]
]},
{ t: "str_glue and str_flatten",
  body: [
  ["p","Building a sentence out of str_c() calls means counting spaces across a long argument list. str_glue() takes the sentence as one string and evaluates whatever sits inside curly braces, so the layout of the text is visible in the code."],
  ["code","keeper <- \"Mira\"\njars <- 3L\n\nstr_glue(\"{keeper} sealed {jars} jars\")"],
  ["code","Mira sealed 3 jars"],
  ["p","Anything inside the braces is R code, not just a name, so a calculation can go straight into the text. Note also that the result printed without quotes and without an index — a glue object prints as the text itself."],
  ["code","str_glue(\"{jars} jars at {jars * 40} g each\")"],
  ["code","3 jars at 120 g each"],
  ["p","Curly braces are therefore special, and text that needs a real brace has to double it, the same trick a doubled backslash uses."],
  ["code","str_glue(\"a literal brace looks like {{this}}\")"],
  ["code","a literal brace looks like {this}"],
  ["p","Inside mutate() the braces see the columns, which is where str_glue() earns its place: one readable template, one label per row."],
  ["code","jam <- tibble(\n  fruit = c(\"plum\", \"quince\", \"sloe\"),\n  jars = c(4L, 2L, 7L)\n)\n\njam |>\n  mutate(label = str_glue(\"{jars} jars of {fruit}\")) |>\n  arrange(fruit)"],
  ["code","# A tibble: 3 × 3\n  fruit   jars label           \n  <chr>  <int> <glue>          \n1 plum       4 4 jars of plum  \n2 quince     2 2 jars of quince\n3 sloe       7 7 jars of sloe  "],
  ["p","The new column's type prints as <glue> rather than <chr>. It behaves as text almost everywhere; as.character() converts it when a function objects. Note too that {jars} inside mutate() used the column of 4, 2, 7 rather than the loose variable holding 3 — inside a dplyr verb, columns win."],
  ["p","str_flatten() is the reduce-to-one-string function, the same job as str_c() with collapse but built for it. Its last argument sets what goes before the final element, which is the difference between a machine list and an English one."],
  ["code","str_flatten(herbs, \", \")\nstr_flatten(herbs, \", \", last = \" and \")"],
  ["code","[1] \"bay, dill, sage\"\n[1] \"bay, dill and sage\""],
  ["p","Because it returns exactly one value it belongs in summarise(), where every other function also returns one value per group. Sort the vector first so the sentence is not written in whatever order the rows arrived."],
  ["code","jam |>\n  summarise(shelf = str_flatten(sort(fruit), \", \", last = \" and \"))"],
  ["code","# A tibble: 1 × 1\n  shelf                \n  <chr>                \n1 plum, quince and sloe"],
  ["note","str_glue() evaluates the braces in the calling environment, so a typo inside braces is an error about an object that was not found, pointing at a name buried in the middle of a sentence. Keep the expressions inside braces short — a column name, or a column and an operator — and do the real work in a mutate() step before the template."]
]},
{ t: "Pulling strings apart",
  body: [
  ["p","The opposite job is splitting one column of packed text into several pieces. tidyr has two functions for it, and they differ in where the pieces go. separate_longer_delim() gives each piece its own row, which is what you want when a cell holds a list of things."],
  ["code","beds <- tibble(\n  bed = c(\"north\", \"south\"),\n  planted = c(\"bay;dill;sage\", \"mint;sage\")\n)\n\nbeds |>\n  separate_longer_delim(planted, delim = \";\")"],
  ["code","# A tibble: 5 × 2\n  bed   planted\n  <chr> <chr>  \n1 north bay    \n2 north dill   \n3 north sage   \n4 south mint   \n5 south sage   "],
  ["p","Two rows became five, and the bed column repeated itself to match. separate_wider_delim() gives each piece its own column instead, which is what you want when the text is a structured code with a fixed number of parts. You supply the names, and the number of names is the number of pieces expected."],
  ["code","labels <- tibble(code = c(\"NW-2024-11\", \"SE-2023-04\"))\n\nlabels |>\n  separate_wider_delim(code, delim = \"-\", names = c(\"region\", \"year\", \"week\"))"],
  ["code","# A tibble: 2 × 3\n  region year  week \n  <chr>  <chr> <chr>\n1 NW     2024  11   \n2 SE     2023  04   "],
  ["p","Every piece comes back as character, including the ones that look like numbers. 2024 and 04 are text until you convert them, and 04 is a good reminder of why: as a number it would lose its leading zero."],
  ["p","A row with the wrong number of pieces stops the whole call. This is deliberate — a silent partial split is a much worse outcome than an error — but it means real data usually needs a decision about what to do with the exceptions."],
  ["code","ragged <- tibble(code = c(\"NW-2024-11\", \"SE-2023\"))\n\nragged |>\n  separate_wider_delim(code, delim = \"-\", names = c(\"region\", \"year\", \"week\"))"],
  ["code","Error: Expected 3 pieces in each element of `code`."],
  ["p","too_few says what to do with a short value. Setting it to \"align_start\" fills the pieces from the left and leaves NA at the end. There is a matching too_many for values with extra pieces, where \"drop\" discards the surplus and \"merge\" glues it onto the last column."],
  ["code","ragged |>\n  separate_wider_delim(code, delim = \"-\", names = c(\"region\", \"year\", \"week\"),\n                       too_few = \"align_start\")"],
  ["code","# A tibble: 2 × 3\n  region year  week \n  <chr>  <chr> <chr>\n1 NW     2024  11   \n2 SE     2023  <NA> "],
  ["code","long <- tibble(code = c(\"NW-2024-11-a\", \"SE-2023-04-b\"))\n\nlong |>\n  separate_wider_delim(code, delim = \"-\", names = c(\"region\", \"year\", \"week\"),\n                       too_many = \"drop\")"],
  ["code","# A tibble: 2 × 3\n  region year  week \n  <chr>  <chr> <chr>\n1 NW     2024  11   \n2 SE     2023  04   "],
  ["p","Outside a data frame, str_split() does the same job on a plain vector. It returns a list, because each element can split into a different number of pieces and a list is the only shape that holds that."],
  ["code","str_split(\"bay;dill;sage\", \";\")"],
  ["code","[[1]]\n[1] \"bay\"  \"dill\" \"sage\""],
  ["note","Reaching for too_few or too_many to make an error go away is the wrong instinct. The error is telling you the column is not the shape you assumed, and the rows that break it are usually the interesting ones. Look at them first, then choose the setting, and say in a comment which rows it is covering for."]
]},
{ t: "Letters: length and subsetting",
  body: [
  ["p","str_length() counts characters, and it counts what is in the string rather than what it took to type. An empty string is 0, and an escaped tab is one character."],
  ["code","str_length(c(\"bay\", \"rosemary\", \"\"))\nstr_length(\"gauge\\t14\")"],
  ["code","[1] 3 8 0\n[1] 8"],
  ["p","str_sub() extracts a run of characters by position, counting from 1. Negative positions count back from the end, so -1 is the last character. Asking for more than there is returns what exists rather than an error, which is convenient and also means a wrong end position fails silently."],
  ["code","str_sub(\"rosemary\", 1, 4)\nstr_sub(\"rosemary\", -4, -1)\nstr_sub(\"bay\", 1, 10)"],
  ["code","[1] \"rose\"\n[1] \"mary\"\n[1] \"bay\""],
  ["p","Like everything else in stringr, str_sub() is vectorised, so one call takes the first letter of every element. Combining it with str_c() capitalises a vector without a loop: take the first character, upper-case it, and stick the rest back on."],
  ["code","str_sub(herbs, 1, 1)\nstr_c(str_to_upper(str_sub(herbs, 1, 1)), str_sub(herbs, 2))"],
  ["code","[1] \"b\" \"d\" \"s\"\n[1] \"Bay\"  \"Dill\" \"Sage\""],
  ["p","str_sub() can also appear on the left of an assignment, which replaces the characters at those positions and leaves the rest alone."],
  ["code","word <- \"rosemary\"\nstr_sub(word, 1, 1) <- \"R\"\n\nword"],
  ["code","[1] \"Rosemary\""],
  ["note","str_sub() with a single position argument does not give you one character — the second argument defaults to the end of the string, so str_sub(x, 2) is everything from the second character onward. That is what makes the capitalising trick above short, and it surprises anyone expecting the behaviour of an index."]
]},
{ t: "Non-English text",
  body: [
  ["p","Everything above assumed that a character is a character. Once text stops being plain English that assumption needs care, because the same visible letter can be stored in more than one way. An accented e can be one character with the accent built in, or two characters — a plain e followed by a combining accent that draws on top of it."],
  ["code","composed <- \"\\u00e9\"\ndecomposed <- \"e\\u0301\"\n\ncomposed\ndecomposed\nstr_length(composed)\nstr_length(decomposed)\ncomposed == decomposed"],
  ["code","[1] \"é\"\n[1] \"é\"\n[1] 1\n[1] 2\n[1] FALSE"],
  ["p","They print identically and they are not equal. Nothing on screen tells you which one a value came in as, and text pasted from different sources routinely mixes the two. str_equal() compares them the way a reader would, by normalising first."],
  ["code","str_equal(composed, decomposed)"],
  ["code","[1] TRUE"],
  ["p","Changing case is also not a fixed rule. Turkish has a dotted and a dotless i, and the upper case of a dotted i keeps its dot. Every stringr function whose answer depends on language takes a locale argument, given as a two-letter code, and the default is a locale-free standard rather than whatever the machine happens to be set to — which is what makes results reproducible on someone else's computer."],
  ["code","str_to_upper(\"istanbul\")\nstr_to_upper(\"istanbul\", locale = \"tr\")"],
  ["code","[1] \"ISTANBUL\"\n[1] \"İSTANBUL\""],
  ["p","Sorting depends on language for the same reason. In English and German an a with an umlaut sorts among the a words; in Swedish it is a separate letter that comes after z."],
  ["code","str_sort(c(\"zebra\", \"älg\", \"apple\"))\nstr_sort(c(\"zebra\", \"älg\", \"apple\"), locale = \"sv\")"],
  ["code","[1] \"älg\"   \"apple\" \"zebra\"\n[1] \"apple\" \"zebra\" \"älg\"  "],
  ["p","Even within English, stringr and base R disagree. str_sort() sorts the way a dictionary does, ignoring case; base sort() sorts by character code in the current locale, which in this runtime puts every capital letter first."],
  ["code","str_sort(c(\"apple\", \"Banana\", \"cherry\"))\nsort(c(\"apple\", \"Banana\", \"cherry\"))"],
  ["code","[1] \"apple\"  \"Banana\" \"cherry\"\n[1] \"Banana\" \"apple\"  \"cherry\""],
  ["p","Counting and subsetting work on characters rather than bytes, so scripts with no alphabet behave the way you would hope. Encoding() reports how R is storing the text, and in the tidyverse the answer should always be UTF-8."],
  ["code","str_length(\"日本語\")\nstr_sub(\"日本語\", 1, 2)\nEncoding(\"café\")"],
  ["code","[1] 3\n[1] \"日本\"\n[1] \"UTF-8\""],
  ["note","The failure this section describes is not loud. Two spellings of the same word that differ only in how the accent is stored will fail to join, fail to group together, and fail an equality filter, while looking identical in every printout you check. If a join drops rows of accented text for no visible reason, compare str_length() on the two sides before you look anywhere else."]
]},
{ t: "Summary",
  body: [
  ["p","Single and double quotes produce the same string, so pick whichever quote the text does not contain. A backslash starts an escape, so a real backslash is written twice and a real quote inside the same quote character is written once with a backslash in front. Printing a string shows its source form with escapes spelled out; cat() shows the string itself; str_view() shows it with the invisible characters marked. A raw string written as r\"(...)\" switches escaping off for literals, and backslash-u writes a character by its Unicode number."],
  ["p","str_c() joins strings and is vectorised, recycling a short argument across a long one. NA joined to anything is NA, and coalesce() or str_replace_na() is how that is dealt with deliberately. sep goes between arguments, collapse folds the whole vector into one string. str_glue() puts the template in the text and evaluates whatever is inside braces, doubling a brace to write a literal one, and inside mutate() the braces see the columns. str_flatten() reduces a vector to one string with a separate last separator, which makes it the right function for summarise()."],
  ["p","separate_longer_delim() turns packed text into more rows, separate_wider_delim() turns it into more columns, and a row with the wrong number of pieces is an error until too_few or too_many says otherwise. str_split() does the same on a bare vector and returns a list. str_length() counts characters and str_sub() takes them by position, counting from 1 and from -1 at the end. For text that is not English, the same letter can be stored two ways, so str_equal() rather than ==, and case and sorting take a locale argument because their answers depend on language."],
  ["p","Answer the practice questions from memory before revealing the answers, then clear the graded exercises below. The next chapter is Regular expressions: a small language for describing patterns in text, and the stringr functions that use it to find, extract, and replace."]
]}
],
questions: [
{ q:"Are 'badger' and \"badger\" different strings, and how do you decide which quote to use?",
  a:"They are the same string — identical() on the two returns TRUE, and R keeps no record of which you typed. Choose the quote the text itself does not contain: double quotes for text with an apostrophe, single quotes for text with a double quote. The tidyverse convention is double quotes unless the content forces the other." },
{ q:"path holds a Windows file path and prints as \"C:\\\\field\\\\notes.txt\". How many backslashes are actually in the string, and how would you confirm it?",
  a:"One between each part, three characters fewer than the printout suggests — str_length(path) is 18. Printing a string shows its source form, where a real backslash has to be written twice. cat(path) shows the string itself, and str_view(path) shows it with invisible characters marked instead of escaped." },
{ q:"What is the difference between printing a string and passing it to cat()?",
  a:"Printing shows the source form: quotes around the value, escapes spelled out, so the line could be pasted back into a script. cat() writes the string itself, so a backslash-t becomes an actual tab and a backslash-n starts a new line. One value, two renderings — the string never changes." },
{ q:"What does a raw string do, and when is it worth using?",
  a:"r\"(...)\" turns escaping off, so every character between the brackets is taken literally and backslashes need no doubling. The brackets can be round, square, or curly. It is worth it for paths and, from the next chapter, for patterns full of backslashes. It only works for a literal — there is no raw version of a variable." },
{ q:"str_c(\"plot \", c(\"north\", NA, \"east\")) returns NA in the middle. Why, and what are the two fixes?",
  a:"Joining anything to a missing value gives a missing value, because R cannot know what the text would have said. coalesce() replaces the NA with wording you choose before the join, so the label reads \"plot unnamed\". str_replace_na() turns it into the literal string \"NA\", so the gap stays visible in the output. They are different decisions, not two spellings of one." },
{ q:"What is the difference between the sep and collapse arguments of str_c()?",
  a:"sep goes between the arguments of a single result and leaves the length of the answer alone. collapse goes between the elements of the vector and folds the whole thing into one string. Using sep when you needed collapse fails quietly by returning a vector of nearly right pieces instead of the one string you wanted." },
{ q:"How do you write a literal curly brace inside str_glue(), and what does {jars} refer to inside mutate()?",
  a:"Double it: str_glue(\"{{this}}\") produces {this}. Inside mutate() the braces are evaluated where the columns are visible, so {jars} is the jars column even when a loose variable of the same name exists — columns win inside a dplyr verb." },
{ q:"separate_longer_delim() and separate_wider_delim() both split a column. What does each produce, and what happens to a row with the wrong number of pieces?",
  a:"separate_longer_delim() gives each piece its own row and repeats the other columns to match. separate_wider_delim() gives each piece its own column, named by you, and every piece comes back as character. A row with too few or too many pieces stops the call with an error until too_few or too_many says what to do, which is deliberate — a silent partial split is worse than a failure." },
{ q:"What does str_sub(\"rosemary\", -4, -1) return, and what does str_sub(x, 2) return?",
  a:"\"mary\" — negative positions count back from the end, so -1 is the last character. str_sub(x, 2) is everything from the second character to the end, because the second argument defaults to the end of the string rather than to a single character. Asking for a position past the end returns what exists rather than raising an error." },
{ q:"Two values both print as \"é\" but a filter comparing them returns FALSE. What has happened, and what do you use instead?",
  a:"One is a single composed character and the other is a plain e followed by a combining accent, so str_length() gives 1 and 2 and == gives FALSE. Nothing on screen distinguishes them. str_equal() normalises before comparing and returns TRUE. The same problem makes joins drop rows of accented text for no visible reason." }
],
exercises: [
{ c:"strings & regex", t:"Labels for the jars", book:"r14",
  b:"Attach stringr with library(stringr). Build a character vector named fruit holding \"plum\", \"quince\", \"sloe\" and an integer vector named jars holding 4L, 2L, 7L, in that order. Print one label per fruit reading like 4 jars of plum, as a character vector.",
  o:"[1] \"4 jars of plum\"   \"2 jars of quince\" \"7 jars of sloe\"  ",
  h:["One call produces all three labels, because the joining function works on whole vectors at once.",
     "str_c() takes several pieces and pastes them in order, recycling any argument of length one. The spaces have to be part of the pieces you pass, since no separator is being set.",
     "The shape is str_c(jars, \" jars of \", fruit) — three arguments, the middle one a literal with a space at each end. No sep argument and no collapse argument."]},
{ c:"strings & regex", t:"One line for the shelf", book:"r14",
  b:"Attach stringr with library(stringr). Build a character vector named herbs holding \"sage\", \"bay\", \"dill\", in that order. Print a single string listing them in alphabetical order, separated by a comma and a space, with the word and before the final one: bay, dill and sage.",
  o:"[1] \"bay, dill and sage\"",
  h:["The answer is one string, not three, so the function has to reduce the vector rather than map over it.",
     "str_flatten() folds a vector into one string, and its last argument sets what goes before the final element. Alphabetical order is not the order the vector was written in, so it has to be sorted first.",
     "Sort the vector, then pass it to str_flatten() with the ordinary separator as the second argument and last set to the text that goes before the final element."]},
{ c:"strings & regex", t:"Codes from the station names", book:"r14",
  b:"Attach stringr with library(stringr). Build a character vector named stations holding \"harbour\", \"quay\", \"lighthouse\", in that order. Print two lines: the number of characters in each name, then the first three characters of each name in upper case.",
  o:"[1]  7  4 10\n[1] \"HAR\" \"QUA\" \"LIG\"",
  h:["Both lines work on the whole vector at once, so neither needs a loop.",
     "One function counts characters. The second line is two functions nested: take the characters at positions 1 to 3, then change the case of the result.",
     "Line one is str_length(). Line two wraps str_to_upper() around str_sub() with a start of 1 and an end of 3."]},
{ c:"tidy data", t:"Splitting the reference codes", book:"r14",
  b:"Attach tibble with library(tibble), tidyr with library(tidyr), and dplyr with suppressMessages(library(dplyr)). Build a tibble named readings with one character column ref holding \"NW-2024-11\", \"SE-2023-04\", \"NE-2024-03\". Split ref on the dash into three columns named region, year, and week, and print the result ordered by region.",
  o:"# A tibble: 3 × 3\n  region year  week \n  <chr>  <chr> <chr>\n1 NE     2024  03   \n2 NW     2024  11   \n3 SE     2023  04   ",
  h:["Each code has a fixed number of parts and each part deserves its own column, which decides which of the two tidyr splitters to use.",
     "separate_wider_delim() needs the column, the delimiter, and a names vector whose length is the number of pieces expected. The ordering is a separate step afterwards.",
     "Pipe the tibble into separate_wider_delim(ref, delim = \"-\", names = ...) and then into arrange() on the first of the new columns. Every piece comes back as character, so no conversion is needed."]}
]
};
