/* Practice Log book — R Chapter 15: Regular expressions.
   Original lesson text following the chapter-by-chapter curriculum of
   "R for Data Science" (2nd ed.) by Hadley Wickham, Mine Cetinkaya-Rundel,
   and Garrett Grolemund. Read the original chapter free at the src link below.
   Every shown output was captured by executing the code in WebR, not written from memory. */
window.BOOK_R = window.BOOK_R || { chapters: {} };
window.BOOK_R.chapters.r15 = {
n: 15,
title: "Regular expressions",
src: "https://r4ds.hadley.nz/regexps.html",
blurb: "Describing text with a pattern instead of a literal, the four stringr functions that use one, and the two layers of backslash that break every first attempt.",
pkgs: ["stringr", "tibble", "dplyr"],
sections: [
{ t: "Patterns, and the functions that use them",
  body: [
  ["p","A regular expression is a small language for describing the shape of text. Instead of asking whether a string equals cumin, you describe a shape — a c, then any one character, then an n — and ask which strings fit it. The description is itself just a string, which is why patterns end up quoted inside your code and why quoting them correctly turns out to be most of the difficulty."],
  ["p","Base R has pattern matching built in. The stringr package puts the same engine behind a set of functions whose names all begin with str_ and whose first argument is always the vector of strings. That consistency is the reason to use it: every function in this chapter reads the same way and drops into a pipeline without rearrangement."],
  ["p","None of those functions exist until the package is attached. This app installs a chapter's packages for you and stops there, so the library() call is yours to write, in the graded exercises as well as here."],
  ["code","str_detect(c(\"kestrel\", \"wren\"), \"e\")"],
  ["code","Error: could not find function \"str_detect\""],
  ["code","library(stringr)\nlibrary(tibble)"],
  ["p","The examples run on a shelf of six spice jars, held as a plain character vector."],
  ["code","spices <- c(\"cardamom\", \"cinnamon\", \"clove\", \"cumin\", \"nutmeg\", \"saffron\")\n\nstr_detect(spices, \"c\")"],
  ["code","[1]  TRUE  TRUE  TRUE  TRUE FALSE FALSE"],
  ["p","str_detect() takes the strings first and the pattern second, and answers once per element: a logical vector exactly as long as the input. The pattern here is a single literal character, and a literal matches anywhere in the string rather than only at the start, so the four spices containing a c are TRUE and nutmeg and saffron are FALSE."],
  ["note","Strings first, pattern second. Base R's grepl() takes them the other way round, so a line copied from a base-R answer will not drop into a stringr pipeline unchanged, and the two argument orders are easy to blur together after an hour of reading both."]
]},
{ t: "Pattern basics",
  body: [
  ["p","Most characters in a pattern stand for themselves. The interesting ones do not. A dot matches any single character, a plus means one or more of whatever came before it, and a vertical bar separates alternatives. str_view() is the tool for seeing what a pattern actually caught: it prints the elements that matched, numbered by their position in the input, with the matched text wrapped in angle brackets."],
  ["code","str_view(spices, \"cu\")"],
  ["code","[4] │ <cu>min"],
  ["p","One line came back, numbered 4. str_view() shows matches rather than the whole vector, so the numbers are positions in the original and the missing numbers are the elements that failed."],
  ["code","str_view(spices, \"m\")"],
  ["code","[1] │ carda<m>o<m>\n[2] │ cinna<m>on\n[4] │ cu<m>in\n[5] │ nut<m>eg"],
  ["p","A pattern can match more than once inside one string, and str_view() marks every occurrence. Cardamom has two m characters and both are wrapped."],
  ["code","str_view(spices, \"c.n\")"],
  ["code","[2] │ <cin>namon"],
  ["p","The dot is the first metacharacter. c.n means a c, then any one character, then an n — three characters in total, and only cinnamon has that run. Note what it did not catch: cumin also has a c and an n, but with three characters between them, and the dot stands for exactly one."],
  ["code","str_view(spices, \"c.+n\")"],
  ["code","[2] │ <cinnamon>\n[4] │ <cumin>"],
  ["p","Adding a plus to the dot means one or more of any character, so the run between c and n can now be any length. Both spices qualify, and each match runs all the way to the final n rather than stopping at the first, because these quantifiers are greedy by default."],
  ["code","str_view(spices, \"clove|cumin\")"],
  ["code","[3] │ <clove>\n[4] │ <cumin>"],
  ["p","The bar means or. It has the lowest precedence of anything in a pattern, so it splits the whole expression: clove|cumin is the word clove or the word cumin, not clov followed by e or c followed by umin. Parentheses are how you limit its reach, which section 6 comes back to."],
  ["code","str_view(spices, \"^c\")"],
  ["code","[1] │ <c>ardamom\n[2] │ <c>innamon\n[3] │ <c>love\n[4] │ <c>umin"],
  ["p","A caret at the front anchors the pattern to the start of the string. Anchors get their own treatment in section 5; the caret appears this early because so many useful patterns begin with one."],
  ["note","str_view() is a reading tool, not a testing tool. Nothing came back means nothing matched, and nothing came back is also exactly what a subtly wrong pattern produces, so success and failure look identical. When you want a decision per element rather than a picture, use str_detect() and read the logicals."]
]},
{ t: "Detect, count, replace, extract",
  body: [
  ["p","Four functions cover most of the work. str_detect() answers yes or no, str_count() answers how many, str_replace() rewrites the match, and str_extract() pulls the matched text out. str_subset() is a shorthand worth knowing on its own: it keeps the elements that matched."],
  ["code","str_subset(spices, \"^c\")"],
  ["code","[1] \"cardamom\" \"cinnamon\" \"clove\"    \"cumin\"   "],
  ["p","That is the same result as subsetting the vector with the logical vector str_detect() returns, written in one step instead of two."],
  ["code","str_count(spices, \"m\")"],
  ["code","[1] 2 1 0 1 1 0"],
  ["p","str_count() counts non-overlapping matches and returns one integer per element, zero where the pattern never fired. Cardamom has two m characters, clove and saffron have none."],
  ["code","str_replace(spices, \"m\", \"M\")\nstr_replace_all(spices, \"m\", \"M\")"],
  ["code","[1] \"cardaMom\" \"cinnaMon\" \"clove\"    \"cuMin\"    \"nutMeg\"   \"saffron\" \n[1] \"cardaMoM\" \"cinnaMon\" \"clove\"    \"cuMin\"    \"nutMeg\"   \"saffron\" "],
  ["p","str_replace() changes the first match in each element and stops there. str_replace_all() changes every match. Cardamom is the only element with two m characters, so it is the only place the two lines differ — which is precisely the shape of data that lets the wrong choice pass a quick read."],
  ["code","str_extract(spices, \"^c.\")"],
  ["code","[1] \"ca\" \"ci\" \"cl\" \"cu\" NA   NA  "],
  ["p","str_extract() returns the text that matched, and NA where nothing did. That NA is a genuine missing value rather than an empty string, so anything you do downstream has to account for it."],
  ["p","Inside a data frame these functions need no special handling, because they return ordinary vectors. dplyr sees a logical vector from str_detect() and an integer vector from str_count() and treats them like any other."],
  ["code","suppressMessages(library(dplyr))\n\njars <- tibble(\n  label = c(\"cardamom pods\", \"cinnamon bark\", \"clove whole\", \"cumin seed\"),\n  grams = c(120, 85, 60, 200)\n)\n\njars |>\n  filter(str_detect(label, \"seed|whole\")) |>\n  arrange(label)"],
  ["code","# A tibble: 2 × 2\n  label       grams\n  <chr>       <dbl>\n1 clove whole    60\n2 cumin seed    200"],
  ["code","jars |>\n  mutate(letter_o = str_count(label, \"o\")) |>\n  arrange(label)"],
  ["code","# A tibble: 4 × 3\n  label         grams letter_o\n  <chr>         <dbl>    <int>\n1 cardamom pods   120        2\n2 cinnamon bark    85        1\n3 clove whole      60        2\n4 cumin seed      200        0"],
  ["p","suppressMessages() around library(dplyr) hides the attach banner listing the base functions dplyr masks. The banner is worth reading once and is noise in a graded exercise, where the only output should be the one you meant to print."],
  ["note","The default that costs the most time is str_replace() stopping after the first match. Test any cleanup on a value you know contains the pattern twice. If both functions give the same answer on your test data, the test data is the problem."]
]},
{ t: "Escaping: two layers of backslash",
  body: [
  ["p","The dot matches any character, which becomes a problem the moment the character you want is a dot. Here are four file names, one of which has no extension."],
  ["code","files <- c(\"notes.txt\", \"report.final.pdf\", \"raw_data\", \"chart.png\")\n\nstr_detect(files, \".\")"],
  ["code","[1] TRUE TRUE TRUE TRUE"],
  ["p","Everything matched, raw_data included. A pattern of one dot asks whether the string contains any character at all, and every non-empty string does. Four TRUEs where you expected three is the quietest possible failure, because a column of TRUE looks like the code worked."],
  ["p","In a regular expression a metacharacter is made literal by putting a backslash in front of it, so the pattern you want is a backslash then a dot. The catch is that the pattern has to be typed inside an R string, and R's strings use backslash for their own escapes."],
  ["code","str_detect(files, \"\\.\")"],
  ["code","Error: '\\.' is an unrecognized escape in character string (<text>:1:21)"],
  ["p","R never reached the regular expression. It was still reading the string literal, found a backslash followed by a dot, looked for an escape by that name, and found none. The error is about R's parser, not about matching."],
  ["p","So the backslash has to be escaped for R first, and the regex engine gets what survives. Two backslashes in your source produce one backslash in the string, and that one backslash is what the pattern language reads."],
  ["code","writeLines(\"\\\\.\")"],
  ["code","\\."],
  ["p","writeLines() prints a string's contents rather than its source, which is the only dependable way to see how many backslashes you actually have. Two in the source, one in the string, and that two-character string is the regex meaning a literal dot."],
  ["code","str_detect(files, \"\\\\.\")\nstr_count(files, \"\\\\.\")\nstr_extract(files, \"\\\\.[a-z]+$\")"],
  ["code","[1]  TRUE  TRUE FALSE  TRUE\n[1] 1 2 0 1\n[1] \".txt\" \".pdf\" NA     \".png\""],
  ["p","Now raw_data is FALSE, report.final.pdf counts two dots, and the extension comes out with its dot attached because the pattern includes it."],
  ["p","A literal backslash needs the same trick applied twice. The regex for one backslash is two characters, a backslash escaping a backslash, and writing those two characters into an R string takes four in the source."],
  ["code","paths <- c(\"data\\\\raw\", \"data/clean\")\n\nwriteLines(paths)\nstr_detect(paths, \"\\\\\\\\\")"],
  ["code","data\\raw\ndata/clean\n[1]  TRUE FALSE"],
  ["p","writeLines() shows one backslash sitting in the data, even though the source that built it had two. The pattern is four characters of source, two characters of string, one escaped backslash of regular expression. Every layer halves the count."],
  ["note","Count backslashes in the string, not in the source, and reach for writeLines() whenever you lose track. R rejecting the escape outright, as it did above, is the good outcome — the error tells you where you are. The dangerous case is a pattern that parses cleanly and matches far more than you meant, like the bare dot at the top of this section."]
]},
{ t: "Anchors and character classes",
  body: [
  ["p","A caret matches the start of a string and a dollar matches the end. Both match a position rather than a character, so neither adds anything to the text a match contains — they only constrain where the rest of the pattern is allowed to sit."],
  ["code","tokens <- c(\"PX9\", \"px9\", \"P 9\", \"P-9\", \"PX99\")\n\nstr_detect(tokens, \"^P\")\nstr_detect(tokens, \"\\\\d$\")"],
  ["code","[1]  TRUE FALSE  TRUE  TRUE  TRUE\n[1] TRUE TRUE TRUE TRUE TRUE"],
  ["p","Four of the five start with a capital P; px9 is lower case, and patterns are case sensitive until you say otherwise. All five end in a digit. That backslash-d is a character class: a shorthand standing for any one digit."],
  ["p","The three common shorthands are \\\\d for a digit, \\\\s for whitespace, and \\\\w for a word character, meaning a letter, a digit, or an underscore. Each has an upper-case form for its opposite, so \\\\D is any character that is not a digit. All of them need the doubled backslash from section 4."],
  ["code","str_extract(tokens, \"\\\\d+\")\nstr_detect(tokens, \"\\\\s\")"],
  ["code","[1] \"9\"  \"9\"  \"9\"  \"9\"  \"99\"\n[1] FALSE FALSE  TRUE FALSE FALSE"],
  ["p","The plus takes the whole run of digits, so PX99 yields 99 rather than 9. Only P 9 contains whitespace."],
  ["p","Square brackets build a class by hand out of whatever characters you list, and a caret as the first character inside the brackets inverts the whole set."],
  ["code","str_extract(spices, \"[aeiou]\")\nstr_extract(spices, \"[^aeiou]+\")"],
  ["code","[1] \"a\" \"i\" \"o\" \"u\" \"u\" \"a\"\n[1] \"c\"  \"c\"  \"cl\" \"c\"  \"n\"  \"s\" "],
  ["p","The first line pulls the earliest vowel out of each spice. The second pulls the run of non-vowels that opens it, and clove is the one that opens with two consonants, so the plus collects both."],
  ["p","A word boundary, written as backslash b, is another position: the join between a word character and something that is not one. It is how you match a whole word rather than a fragment of a longer one."],
  ["code","str_replace_all(\"sum summary sums\", \"\\\\bsum\\\\b\", \"TOTAL\")"],
  ["code","[1] \"TOTAL summary sums\""],
  ["p","Only the standalone word was replaced. Without the boundaries the pattern would also have hit the opening of summary and of sums, leaving two words mangled in the middle."],
  ["note","The caret has two unrelated jobs. Outside square brackets it anchors to the start of the string. As the first character inside them it negates the class. So [^abc] is any character other than those three, while ^[abc] is a string beginning with one of them. Reading a pattern correctly means noticing which side of the bracket you are standing on."]
]},
{ t: "Quantifiers, groups, and backreferences",
  body: [
  ["p","A quantifier says how many times the thing before it may repeat. A question mark is zero or one, a plus is one or more, a star is zero or more, {n} is exactly n times, and {n,m} is between n and m."],
  ["code","codes <- c(\"AB-1\", \"AB-22\", \"AB-333\", \"AB-\", \"ABC-44\")\n\nstr_detect(codes, \"^AB-\\\\d+$\")\nstr_extract(codes, \"\\\\d{2,3}\")"],
  ["code","[1]  TRUE  TRUE  TRUE FALSE FALSE\n[1] NA    \"22\"  \"333\" NA    \"44\" "],
  ["p","The first pattern is anchored at both ends, so it demands exactly AB, a hyphen, and at least one digit, with nothing else anywhere: AB- fails for having no digits and ABC-44 fails for the extra C. The second pattern is unanchored and takes the first run of two or three digits it can find, which is why AB-1 comes back NA and ABC-44 comes back with 44 despite failing the first test."],
  ["code","str_detect(c(\"color\", \"colour\"), \"colou?r\")\nstr_extract(c(\"aaa\", \"ab\", \"b\"), \"a*\")"],
  ["code","[1] TRUE TRUE\n[1] \"aaa\" \"a\"   \"\"   "],
  ["p","The question mark made the u optional, so both spellings passed. The star allows zero, which means a pattern built only from stars can succeed while matching nothing at all: for the string b the extraction is an empty string. NA means no match. An empty string means a match of length zero. They are different answers."],
  ["p","Parentheses do two jobs at once. They group part of a pattern so a quantifier or a bar applies to the whole group, and they capture whatever that part matched. str_match() is the function that hands the captures back — a matrix with the entire match in the first column and one column per group after it."],
  ["code","str_match(codes, \"^([A-Z]+)-(\\\\d+)$\")"],
  ["code","     [,1]     [,2]  [,3] \n[1,] \"AB-1\"   \"AB\"  \"1\"  \n[2,] \"AB-22\"  \"AB\"  \"22\" \n[3,] \"AB-333\" \"AB\"  \"333\"\n[4,] NA       NA    NA   \n[5,] \"ABC-44\" \"ABC\" \"44\" "],
  ["p","The letters and the digits arrive in separate columns, which is the thing str_extract() cannot do. Row 4 is NA the whole way across, because a row that failed the pattern has no captures to report."],
  ["code","people <- c(\"Ada Lovelace\", \"Grace Hopper\")\n\nstr_replace(people, \"(\\\\w+) (\\\\w+)\", \"\\\\2, \\\\1\")"],
  ["code","[1] \"Lovelace, Ada\" \"Hopper, Grace\""],
  ["p","Inside a replacement string, backslash-1 and backslash-2 stand for the first and second captured groups, so this swaps the two words and drops a comma between them. The doubling rule from section 4 applies to the replacement exactly as it does to the pattern."],
  ["code","str_detect(c(\"abba\", \"abab\", \"noon\", \"stop\"), \"(.)(.)\\\\2\\\\1\")"],
  ["code","[1]  TRUE FALSE  TRUE FALSE"],
  ["p","The same numbered references work inside a pattern, where they are called backreferences. Two dots capture any two characters, and the references then demand the same two again in reverse, which is a four-character palindrome."],
  ["note","Read backslash-1 as the first group's text, never as the first group's pattern. In the palindrome above the reference has to match whatever that dot actually caught, which is why abba passes and abab, whose halves differ, does not. Reading it as the pattern would make abab pass too, and then the result looks like a bug in stringr."]
]},
{ t: "Flags and fixed matches",
  body: [
  ["p","By default a pattern is case sensitive, treats a string as one long line, and lets the dot match anything except a newline. regex() wraps a pattern to change those defaults, and the wrapped object goes wherever a plain pattern would."],
  ["code","str_detect(c(\"Tea\", \"tea\", \"TEA\"), \"tea\")\nstr_detect(c(\"Tea\", \"tea\", \"TEA\"), regex(\"tea\", ignore_case = TRUE))"],
  ["code","[1] FALSE  TRUE FALSE\n[1] TRUE TRUE TRUE"],
  ["p","fixed() goes the other way and turns the pattern language off. Every character stands for itself, nothing needs escaping, and nothing is interpreted."],
  ["code","str_count(\"a.b.c\", \".\")\nstr_count(\"a.b.c\", fixed(\".\"))"],
  ["code","[1] 5\n[1] 2"],
  ["p","The bare dot counted all five characters. The fixed dot counted the two dots. This is the second answer to section 4's problem: escape the metacharacter, or declare that there are no metacharacters."],
  ["code","str_detect(\"one\\ntwo\", \"^two\")\nstr_detect(\"one\\ntwo\", regex(\"^two\", multiline = TRUE))"],
  ["code","[1] FALSE\n[1] TRUE"],
  ["p","A caret normally means the start of the whole string, and this string starts with one. multiline = TRUE redefines the caret and the dollar to mean the start and end of any line, so the second line becomes reachable."],
  ["code","str_view(\"one\\ntwo\", regex(\"^two\", multiline = TRUE))"],
  ["code","[1] │ one\n    │ <two>"],
  ["p","str_view() prints both lines of the value, marking the match on the second and leaving the first as context, with the element number shown once."],
  ["code","str_extract(\"a\\nb\", \"a.b\")\nstr_extract(\"a\\nb\", regex(\"a.b\", dotall = TRUE))"],
  ["code","[1] NA\n[1] \"a\\nb\""],
  ["p","dotall = TRUE lets the dot cross a newline. The extracted value prints with the newline written as an escape, because printing a character vector shows its source form; writeLines() would show it as an actual line break, which is the same distinction section 4 settled."],
  ["p","Last, the error you get when the pattern itself is malformed."],
  ["code","str_detect(spices, \"^(c\")"],
  ["code","Error: Incorrectly nested parentheses in regex pattern. (U_REGEX_MISMATCHED_PAREN, context=`^(c`)"],
  ["p","This one comes from the regex engine rather than from R, so it names an engine condition and echoes the fragment it choked on. An unclosed group is the usual cause, and the echoed context is the fastest way to find which of several patterns on a line was the bad one."],
  ["note","fixed() is not a faster regex(), it is a different kind of match. Nothing inside it is pattern syntax, so a fixed pattern cannot hold a class, a quantifier, or an anchor — writing fixed(\"^AB\") searches for a caret. Use it when the target is genuinely literal text, and escape properly for everything else."]
]},
{ t: "Summary",
  body: [
  ["p","A regular expression describes a shape rather than a value. Literal characters stand for themselves; a dot is any character, a bar separates alternatives, and the quantifiers ?, +, *, {n} and {n,m} say how often the piece before them repeats. A caret and a dollar anchor to the start and end, a caret inside square brackets negates the class instead, and \\\\d, \\\\s and \\\\w are shorthands for digits, whitespace and word characters. Parentheses group and capture, and a numbered backreference stands for the text a group matched."],
  ["p","stringr supplies the verbs. str_detect() gives one logical per element, str_subset() keeps the elements that matched, str_count() gives one integer per element, str_replace() rewrites the first match while str_replace_all() rewrites all of them, str_extract() returns the matched text or NA, and str_match() returns a matrix with a column per capture group. All of them take the strings first and the pattern second, and all of them return ordinary vectors, so they sit inside filter() and mutate() without ceremony."],
  ["p","The recurring hazard is the backslash. A metacharacter is made literal by a backslash in the regular expression, and a backslash is made literal for R by another backslash in the source, so a literal dot is two characters of source and a literal backslash is four. Count the backslashes in the string rather than in the source, use writeLines() when the count stops being obvious, and remember that regex() sets flags such as ignore_case, multiline and dotall while fixed() turns the pattern language off entirely."],
  ["p","Answer the practice questions from memory before revealing the answers, then clear the graded exercises below. The next chapter is Factors: how R stores a categorical variable, why a factor sorts differently from the character vector it came from, and how forcats reorders and renames the levels once the default alphabetical order stops being the one you want."]
]}
],
questions: [
{ q:"What does str_detect() return, and how long is the result?",
  a:"A logical vector exactly as long as the input, one TRUE or FALSE per element. It says whether each string contains a match anywhere, not where the match was or how many there were." },
{ q:"What is the difference between str_detect() and str_subset()?",
  a:"str_detect() returns logicals, one per element. str_subset() returns the strings themselves, keeping only the elements that matched, so it is shorter than the input whenever something failed. str_subset(x, p) is the same as x[str_detect(x, p)]." },
{ q:"str_detect() on four non-empty file names with the pattern \".\" returned TRUE four times, including for a name with no dot in it. Why?",
  a:"A dot is a metacharacter meaning any single character, so the pattern asks whether the string contains anything at all, and every non-empty string does. To ask about a literal dot the pattern has to be an escaped dot, written \"\\\\.\" in R source." },
{ q:"Why does str_detect(files, \"\\.\") stop with an error before any matching happens?",
  a:"R is still reading the string literal at that point. Inside a string, a backslash starts an R escape sequence, and there is no escape called backslash-dot, so R's parser rejects it: '\\.' is an unrecognized escape in character string. The regex engine never sees the pattern." },
{ q:"How many characters does the R string \"\\\\.\" contain, and what does the regex engine make of it?",
  a:"Two: a backslash and a dot. writeLines() on it prints \\. rather than \\\\. The regex engine reads those two characters as an escaped dot, meaning a literal full stop. Four characters of source, two of string, one metacharacter neutralised." },
{ q:"What do you write to match a single literal backslash, and why is it that many?",
  a:"Four backslashes in the source. The regex for a literal backslash is a backslash escaping a backslash, which is two characters, and each of those two characters needs its own R escape to survive the string literal. Every layer halves the count." },
{ q:"A caret appears in two very different roles. What are they?",
  a:"Outside square brackets it is an anchor meaning the start of the string, so ^c matches strings beginning with c. As the first character inside square brackets it negates the class, so [^aeiou] matches any character that is not one of those five." },
{ q:"str_replace() and str_replace_all() gave the same answer on your test vector. What has that told you, and what has it not?",
  a:"Nothing useful. They only differ on elements containing the pattern more than once, so matching answers mean the test data has no such element rather than that the choice was right. Test any cleanup on a value you know contains the pattern twice." },
{ q:"What does str_match() give you that str_extract() cannot?",
  a:"The captured groups. str_extract() returns the whole match as a character vector; str_match() returns a matrix whose first column is the whole match and whose remaining columns are the parenthesised groups, so a code like AB-333 comes back split into AB and 333. A non-matching element is NA across the whole row." },
{ q:"When would you wrap a pattern in regex(), and when in fixed()?",
  a:"regex() when you want the pattern language with different defaults — ignore_case for case-insensitive matching, multiline to make ^ and $ mean line starts and ends, dotall to let the dot cross a newline. fixed() when the target is literal text and you want no pattern language at all, so a dot means a dot and nothing needs escaping. A fixed pattern cannot hold a class, quantifier or anchor." }
],
exercises: [
{ c:"strings & regex", t:"Six birds", book:"r15",
  b:"Attach stringr. Build a character vector named birds holding \"wren\", \"swift\", \"swan\", \"raven\", \"rook\", \"swallow\", in that order. Then print three things on three separate lines: whether each name starts with sw, the names that end in n, and how many times the letter w appears in each name.",
  o:"[1] FALSE  TRUE  TRUE FALSE FALSE  TRUE\n[1] \"wren\"  \"swan\"  \"raven\"\n[1] 1 1 1 0 0 2",
  h:["Three different questions means three different str_ functions, one per line, over the same vector.",
     "Starts with and ends in are anchors: a caret pins the pattern to the start, a dollar to the end. The middle line asks for the strings themselves rather than logicals, so it is not str_detect().",
     "Line one is str_detect() with an anchored pattern. Line two is str_subset() with the other anchor. Line three is str_count() with a plain literal and no anchor at all."]},
{ c:"strings & regex", t:"A dot that means a dot", book:"r15",
  b:"Attach stringr. Build a character vector named docs holding \"map.v2.png\", \"index.html\", \"LICENSE\", \"notes.md\", in that order. Print three lines: how many literal dots each name contains, the file extension of each name including its leading dot (NA where there is none), and whether each name contains a dot, this time using a fixed match rather than a pattern.",
  o:"[1] 2 1 0 1\n[1] \".png\"  \".html\" NA      \".md\"  \n[1]  TRUE  TRUE FALSE  TRUE",
  h:["A bare dot in a pattern matches any character, so all three lines have to say somehow that the dot is meant literally.",
     "Two of the lines escape the dot inside the pattern, which takes two backslashes in your source. The third line takes the other route and declares that the pattern is not a pattern.",
     "For the extension, anchor to the end and allow one or more lower-case letters or digits after the escaped dot: something of the shape \"\\\\.[a-z0-9]+$\". The third line wraps a plain dot in fixed()."]},
{ c:"strings & regex", t:"Splitting a log line", book:"r15",
  b:"Attach stringr. Build a character vector named entries holding \"2019-07: hull\", \"2020-11: keel\", \"bad line\", \"2021-03: mast\", in that order. First print the matrix that results from matching each entry against a fully anchored pattern of four digits, a hyphen, two digits, a colon and a space, then one or more word characters — with the year, the month and the word each captured as a group. Then print the entries with the leading year and month rewritten as month slash year, leaving everything else untouched.",
  o:"     [,1]            [,2]   [,3] [,4]  \n[1,] \"2019-07: hull\" \"2019\" \"07\" \"hull\"\n[2,] \"2020-11: keel\" \"2020\" \"11\" \"keel\"\n[3,] NA              NA     NA   NA    \n[4,] \"2021-03: mast\" \"2021\" \"03\" \"mast\"\n[1] \"07/2019: hull\" \"11/2020: keel\" \"bad line\"      \"03/2021: mast\"",
  h:["A matrix with a column per group is what one particular stringr function returns; the rest return vectors.",
     "Use {4} and {2} for the fixed-width digit runs, wrap each piece you want back in parentheses, and anchor both ends for the first line. The second line does not need to match the whole entry, only its opening.",
     "The first line is str_match() with a pattern shaped like \"^(...)-(...): (...)$\". The second is str_replace() whose pattern anchors only at the start and whose replacement refers to the groups by number, in the other order, with a slash between them."]},
{ c:"tibbles & pipes", t:"Filtering crates by their code", book:"r15",
  b:"Attach stringr and tibble, and attach dplyr with the startup messages suppressed. Build a tibble named crates with a character column code holding \"MX-14\", \"mx-9\", \"MX-207\", \"TZ-3\", \"MX-88\" and a double column mass holding 12, 4, 31, 7, 19. Keep only the rows whose code starts with an upper-case MX and a hyphen, add an integer column named number holding the digits from the code, and print the result ordered from the largest number to the smallest.",
  o:"# A tibble: 3 × 3\n  code    mass number\n  <chr>  <dbl>  <int>\n1 MX-207    31    207\n2 MX-88     19     88\n3 MX-14     12     14",
  h:["The regex functions return ordinary vectors, so they go straight inside the dplyr verbs you already know. Three verbs, in the order the brief describes them.",
     "Patterns are case sensitive by default, so the lower-case code drops out on its own once the pattern is anchored. str_extract() returns text, and the brief asks for an integer column, so something has to convert it.",
     "filter(str_detect(code, ...)), then mutate(number = as.integer(str_extract(code, ...))), then arrange() with desc() around the new column. The digits pattern is one or more digit characters."]}
]
};
