/* Practice Log book — R Chapter 16: Factors.
   Original lesson text following the chapter-by-chapter curriculum of
   "R for Data Science" (2nd ed.) by Hadley Wickham, Mine Cetinkaya-Rundel,
   and Garrett Grolemund. Read the original chapter free at the src link below.
   Every shown output was captured by executing the code in WebR, not written from memory. */
window.BOOK_R = window.BOOK_R || { chapters: {} };
window.BOOK_R.chapters.r16 = {
n: 16,
title: "Factors",
src: "https://r4ds.hadley.nz/factors.html",
blurb: "Storing a categorical variable so that its vocabulary and its order are properties of the data, and reordering and renaming levels with forcats once alphabetical stops being useful.",
pkgs: ["forcats", "tibble", "dplyr"],
sections: [
{ t: "Why a factor is not a character vector",
  body: [
  ["p","A categorical variable has a fixed set of possible values, and those values often have an order that has nothing to do with the alphabet. Stored as a character vector, R knows neither fact: any string at all is allowed, and the only order available is alphabetical. A factor records both. It keeps the permitted values as its levels, in the order you give them, and stores the data as positions into that list."],
  ["p","factor() itself is base R. forcats is the tidyverse package for working on a factor after it exists, and every one of its functions begins with fct_. tibble and dplyr appear from section 4 onward, where the examples move into a data frame."],
  ["code","library(forcats)\nlibrary(tibble)\nsuppressMessages(library(dplyr))"],
  ["p","Here are five garment sizes recorded as plain text, sorted the only way a character vector can be sorted."],
  ["code","sizes <- c(\"small\", \"large\", \"medium\", \"large\", \"small\")\n\nsort(sizes)"],
  ["code","[1] \"large\"  \"large\"  \"medium\" \"small\"  \"small\" "],
  ["p","Alphabetical, which puts large first and medium in the middle: an order nobody asked for, and one that would rearrange itself if medium were ever renamed regular. Sorting a character vector answers a question about spelling."],
  ["note","This is not only a display problem. A table, a grouped summary and a bar chart all take their order from the column, so an alphabetical order propagates into every output that touches it. Fixing the order once, where the column is created, is cheaper than fixing it in every summary that follows."]
]},
{ t: "Creating a factor",
  body: [
  ["p","factor() takes the data and a levels argument listing every permitted value, in the order you want them. Supplying levels is the whole point; leaving it out gives away both of the properties a factor exists to hold."],
  ["code","size_levels <- c(\"small\", \"medium\", \"large\")\nsizes_f <- factor(sizes, levels = size_levels)\n\nsizes_f"],
  ["code","[1] small  large  medium large  small \nLevels: small medium large"],
  ["p","Printing a factor shows the values without quotes, then a Levels line carrying the vocabulary in your order rather than in the data's order. None of the values changed. What was added is the list of what a value is allowed to be."],
  ["code","levels(sizes_f)\nsort(sizes_f)"],
  ["code","[1] \"small\"  \"medium\" \"large\" \n[1] small  small  medium large  large \nLevels: small medium large"],
  ["p","levels() reads the vocabulary back as a character vector, and sorting now follows it: two smalls, one medium, two larges. Same data, different answer, because the question the sort is answering has changed from spelling to rank."],
  ["code","as.integer(sizes_f)"],
  ["code","[1] 1 3 2 3 1"],
  ["p","Underneath, a factor is an integer vector: 1 for the first level, 2 for the second, and so on. small is 1 and large is 3. That storage is why a factor sorts by level, and it is also the source of the trap in the next section."],
  ["code","factor(c(\"small\", \"mediun\", \"large\"), levels = size_levels)"],
  ["code","[1] small <NA>  large\nLevels: small medium large"],
  ["p","A value that is not one of the levels becomes NA. There is no warning and no message. The typo mediun did not create a fourth category and did not stop anything; it left a hole. That is the strongest reason to pass levels explicitly, because it converts a misspelling into a missing value you can count rather than a category you never notice."],
  ["code","factor(sizes)\nlevels(factor(sizes))"],
  ["code","[1] small  large  medium large  small \nLevels: large medium small\n[1] \"large\"  \"medium\" \"small\" "],
  ["p","Leave levels out and factor() uses the sorted unique values of the data, which is alphabetical order again — the very thing a factor was supposed to fix. It is a defensible default and almost never the one you want for a vocabulary that has a natural sequence."],
  ["note","Nothing warns you about the typo. After building a factor from data you did not type yourself, count the missing values with sum(is.na(x)) and compare against what you expected, because a level list is only as good as the spelling in the source, and a category that quietly became NA is indistinguishable from data that was never collected."]
]},
{ t: "Counting, and converting back",
  body: [
  ["p","table() counts the values and reports them in level order, with the name of the vector on the header line."],
  ["code","table(sizes_f)"],
  ["code","sizes_f\n small medium  large \n     2      1      2 "],
  ["p","Now the conversion that catches everyone. A factor built from labels that look like numbers still stores integer codes, and asking for the numbers gets you the codes."],
  ["code","years <- factor(c(\"2019\", \"2021\", \"2020\"))\n\nas.numeric(years)\nas.numeric(as.character(years))"],
  ["code","[1] 1 3 2\n[1] 2019 2021 2020"],
  ["p","as.numeric() returned 1, 3, 2 because that is where each label sits in the level list, which is alphabetical and therefore also chronological here. Going through as.character() first reads the labels and converts those instead."],
  ["p","Assignment is the one place R does speak up. Writing a value that is not a level into a factor warns, and then does it anyway."],
  ["code","sizes_edit <- sizes_f\n\nsizes_edit[6] <- \"huge\"\nsizes_edit"],
  ["code","Warning in `[<-.factor`(`*tmp*`, 6, value = \"huge\") :\n  invalid factor level, NA generated\n[1] small  large  medium large  small  <NA>  \nLevels: small medium large"],
  ["p","The vector grew by one element and that element is NA. To store huge you would have to add it to the levels first, because a factor cannot hold a value its vocabulary does not contain."],
  ["note","as.numeric() on a factor of numeric labels is the loudest silent bug in R. It returns plausible small integers rather than an error, so a column of years becomes a column of ranks and everything computed from it is wrong without looking wrong. The fix is as.numeric(as.character(f)), and the habit is to check the first few values against the labels you can see."]
]},
{ t: "A survey worth ordering",
  body: [
  ["p","The rest of the chapter works on a small survey: twelve people, how each of them travels to work, and how long the journey takes in minutes. The mode column was built with factor() and no levels argument, so its vocabulary came out of the data alphabetically."],
  ["code","commutes <- tibble(\n  who = c(\"Ada\", \"Bo\", \"Cai\", \"Dee\", \"Eli\", \"Fay\", \"Gus\", \"Hana\", \"Ida\", \"Jo\", \"Kit\", \"Lev\"),\n  mode = factor(c(\"bike\", \"bus\", \"walk\", \"bike\", \"car\", \"bus\",\n                  \"bike\", \"walk\", \"car\", \"bike\", \"tram\", \"bus\")),\n  minutes = c(18, 34, 25, 22, 41, 30, 15, 28, 55, 20, 37, 26)\n)\n\ncommutes"],
  ["code","# A tibble: 12 × 3\n   who   mode  minutes\n   <chr> <fct>   <dbl>\n 1 Ada   bike       18\n 2 Bo    bus        34\n 3 Cai   walk       25\n 4 Dee   bike       22\n 5 Eli   car        41\n 6 Fay   bus        30\n 7 Gus   bike       15\n 8 Hana  walk       28\n 9 Ida   car        55\n10 Jo    bike       20\n11 Kit   tram       37\n12 Lev   bus        26"],
  ["p","The abbreviation under mode is <fct>, which is how a tibble reports a factor. A character column would read <chr>, so the two are told apart at a glance without calling class()."],
  ["code","levels(commutes$mode)\ncount(commutes, mode)"],
  ["code","[1] \"bike\" \"bus\"  \"car\"  \"tram\" \"walk\"\n# A tibble: 5 × 2\n  mode      n\n  <fct> <int>\n1 bike      4\n2 bus       3\n3 car       2\n4 tram      1\n5 walk      2"],
  ["p","count() gives one row per level, in level order, so the counts arrive alphabetically. Four people cycle, three take the bus, two drive, one takes the tram, two walk. Every remaining section of this chapter is about replacing that default order with one that says something."],
  ["note","count() does have a sort argument, and using it changes only the printed table. The column is unchanged, so the next summary or chart built from the same data is alphabetical all over again. Reordering the factor itself is the change that sticks."]
]},
{ t: "Modifying factor order",
  body: [
  ["p","forcats names its ordering functions for what they do to the level list. Each one returns a new factor holding the same values with the levels rearranged."],
  ["code","count(mutate(commutes, mode = fct_infreq(mode)), mode)"],
  ["code","# A tibble: 5 × 2\n  mode      n\n  <fct> <int>\n1 bike      4\n2 bus       3\n3 car       2\n4 walk      2\n5 tram      1"],
  ["p","fct_infreq() puts the most common level first. The counts are identical to the previous section; only the rows moved, because the level order moved. Note the tie between car and walk at two each, broken by the order they already had."],
  ["code","levels(fct_reorder(commutes$mode, commutes$minutes))"],
  ["code","[1] \"bike\" \"walk\" \"bus\"  \"tram\" \"car\" "],
  ["p","fct_reorder() orders the levels by a summary of a second variable, the median by default. Cyclists have the lowest middle journey time and drivers the highest. The claim is worth checking rather than trusting."],
  ["code","commutes |>\n  group_by(mode) |>\n  summarise(mid = median(minutes)) |>\n  arrange(mid)"],
  ["code","# A tibble: 5 × 2\n  mode    mid\n  <fct> <dbl>\n1 bike   19  \n2 walk   26.5\n3 bus    30  \n4 tram   37  \n5 car    48  "],
  ["p","The same order, computed by hand: 19, 26.5, 30, 37, 48. Doing that once is how fct_reorder() stops being magic and becomes a summary you could have written."],
  ["code","levels(fct_relevel(commutes$mode, \"walk\", \"tram\"))"],
  ["code","[1] \"walk\" \"tram\" \"bike\" \"bus\"  \"car\" "],
  ["p","fct_relevel() moves the levels you name to the front, in the order you named them, and leaves everything else behind them in its existing order. It is the right tool when one category is a baseline and the rest do not matter."],
  ["code","levels(fct_rev(commutes$mode))"],
  ["code","[1] \"walk\" \"tram\" \"car\"  \"bus\"  \"bike\""],
  ["p","fct_rev() reverses the whole list. It exists because horizontal bar charts draw the first level at the bottom, so the ordering that reads correctly in a table reads upside down in a plot."],
  ["note","None of these functions modify the factor in place. Each returns a new one, so a call written on its own line changes nothing at all — the result has to be assigned, or piped into mutate(), for the reorder to survive. fct_reorder() additionally wants the factor and the numbers as two vectors from the same rows, so neither argument can be summarised first."]
]},
{ t: "Modifying factor levels",
  body: [
  ["p","Reordering keeps the labels and changes their sequence. Recoding changes the labels themselves, which matters when the values in the data are codes, abbreviations, or wordings you would rather not put in front of a reader."],
  ["code","levels(fct_recode(commutes$mode, cycle = \"bike\", coach = \"bus\"))"],
  ["code","[1] \"cycle\" \"coach\" \"car\"   \"tram\"  \"walk\" "],
  ["p","fct_recode() takes new = old pairs: the new name on the left of the equals sign, the existing level on the right. Levels you do not mention are left alone, and nothing moves — cycle sits where bike sat."],
  ["code","grouped <- fct_collapse(commutes$mode, public = c(\"bus\", \"tram\"), private = c(\"bike\", \"car\"))\n\nlevels(grouped)\ntable(grouped)"],
  ["code","[1] \"private\" \"public\"  \"walk\"   \ngrouped\nprivate  public    walk \n      6       4       2 "],
  ["p","fct_collapse() is recoding many levels onto one: each argument names a new level and lists the old ones it absorbs. Six private journeys, four public, and walk left alone because it was never mentioned. The new levels appear in the position of their earliest member rather than in the order the arguments were written, which is why private comes first despite public being named first — bike sat ahead of bus."],
  ["code","levels(fct_recode(commutes$mode, walk = \"hike\"))"],
  ["code","Warning: Unknown levels in `f`: hike\n[1] \"bike\" \"bus\"  \"car\"  \"tram\" \"walk\""],
  ["p","Naming a level that does not exist warns and changes nothing. The warning is easy to lose in the middle of a long pipeline, and the symptom is a recode that appears to have done nothing at all."],
  ["p","Filtering rows is a separate matter: it never touches the level list. Here are the journeys made by bike or car, pulled out of the full column."],
  ["code","kept <- commutes$mode[commutes$mode %in% c(\"bike\", \"car\")]\n\ntable(kept)\nlevels(kept)"],
  ["code","kept\nbike  bus  car tram walk \n   4    0    2    0    0 \n[1] \"bike\" \"bus\"  \"car\"  \"tram\" \"walk\""],
  ["p","Six values remain and all five levels are still there, three of them with a count of zero. Sometimes that is exactly right, because a category with no rows is information. Sometimes it is three empty bars on a chart and three pointless rows in a table."],
  ["code","small <- droplevels(kept)\n\nlevels(small)\ntable(small)"],
  ["code","[1] \"bike\" \"car\" \nsmall\nbike  car \n   4    2 "],
  ["code","levels(fct_drop(kept))"],
  ["code","[1] \"bike\" \"car\" "],
  ["p","droplevels() in base R and fct_drop() in forcats both discard levels with no rows behind them, and here they agree exactly. Use whichever fits the surrounding code."],
  ["note","fct_recode() is written new = old, which is the reverse of what most people guess. Read backwards, it either warns about an unknown level or, when both names happen to be real levels, quietly merges the two in the direction you did not intend — and a merge looks like a successful rename until the counts are checked."]
]},
{ t: "Lumping rare levels",
  body: [
  ["p","A factor with a long tail of rare levels makes an unreadable chart and a summary table nobody reads to the end. The fct_lump family collapses that tail into a single Other level, and the members differ only in how they decide what counts as the tail."],
  ["code","fct_count(commutes$mode, sort = TRUE)"],
  ["code","# A tibble: 5 × 2\n  f         n\n  <fct> <int>\n1 bike      4\n2 bus       3\n3 car       2\n4 walk      2\n5 tram      1"],
  ["p","fct_count() with sort = TRUE is the quickest way to see the shape you are about to lump. Bike leads with four and tram trails with one, so any threshold between those two numbers is a decision worth making on purpose."],
  ["code","top2 <- fct_lump_n(commutes$mode, n = 2)\n\nlevels(top2)\ntable(top2)"],
  ["code","[1] \"bike\"  \"bus\"   \"Other\"\ntop2\n bike   bus Other \n    4     3     5 "],
  ["p","fct_lump_n() keeps the n most common levels and folds the rest together. With n = 2 that leaves bike and bus by name, and the remaining five journeys become Other, which is placed last where a chart wants it. Note that Other is now the largest group, which is a signal that two was too aggressive."],
  ["code","common <- fct_lump_min(commutes$mode, min = 2)\n\ntable(common)"],
  ["code","common\n bike   bus   car  walk Other \n    4     3     2     2     1 "],
  ["p","fct_lump_min() defines the tail by a threshold instead of a count: every level with fewer than min rows is lumped. At min = 2 only tram falls short, so four levels keep their names and Other holds a single journey. Same data, same family of functions, a very different table."],
  ["note","Other is an ordinary level, so it can be recoded, reordered and lumped again. What it cannot do is be taken apart later, because the original labels are gone from the factor. Lump last, after the filtering and joining are finished, and keep the unlumped column around if anything downstream might need the detail."]
]},
{ t: "Ordered factors",
  body: [
  ["p","An ordered factor claims more than a sequence: it claims a ranking, so comparison operators mean something. ordered = TRUE turns one on, and the levels argument still supplies the order, lowest first."],
  ["code","grades <- factor(c(\"pass\", \"distinction\", \"fail\", \"pass\"),\n                 levels = c(\"fail\", \"pass\", \"distinction\"),\n                 ordered = TRUE)\n\ngrades\nclass(grades)"],
  ["code","[1] pass        distinction fail        pass       \nLevels: fail < pass < distinction\n[1] \"ordered\" \"factor\" "],
  ["p","The Levels line now separates the levels with less-than signs, and the class is ordered followed by factor. An ordered factor is still a factor, so everything earlier in this chapter continues to apply to it."],
  ["code","grades > \"fail\"\nsort(grades)"],
  ["code","[1]  TRUE  TRUE FALSE  TRUE\n[1] fail        pass        pass        distinction\nLevels: fail < pass < distinction"],
  ["p","Comparing against a level is a question about rank, answered per element. Sorting behaves as it did for the unordered factors above, because sorting only ever needed the level order and never needed the claim that the order is a ranking."],
  ["code","plain <- factor(c(\"pass\", \"fail\"), levels = c(\"fail\", \"pass\"))\n\nplain > \"fail\""],
  ["code","Warning in Ops.factor(plain, \"fail\") : ‘>’ not meaningful for factors\n[1] NA NA"],
  ["p","On a plain factor the same comparison returns NA for every element and warns that the operator has no meaning. R is right to refuse. The level order of an unordered factor is a presentation choice, and treating it as a ranking would invent a fact about the data."],
  ["code","tibble(g = grades)"],
  ["code","# A tibble: 4 × 1\n  g          \n  <ord>      \n1 pass       \n2 distinction\n3 fail       \n4 pass       "],
  ["p","A tibble reports an ordered factor as <ord>, distinct from both <fct> and <chr>, so the extra claim is visible in any printed table."],
  ["note","Reach for ordered factors sparingly. When all you need is a sensible order in a table or a chart, an ordinary factor with the levels in the right sequence does the whole job and tempts nobody into arithmetic on ranks. Turn ordered on when the comparison operators are genuinely part of the analysis, and leave it off otherwise."]
]},
{ t: "Summary",
  body: [
  ["p","A factor is a categorical variable that carries its own vocabulary. factor(x, levels = ...) sets the permitted values and their order, printing shows a Levels line, levels() reads that list back, and any value outside it silently becomes NA. Underneath the labels the storage is integer codes, which is why sorting a factor follows the levels while sorting the character vector it came from follows the alphabet, and why as.numeric() on a factor of numeric labels returns ranks rather than numbers."],
  ["p","forcats changes the order without touching the values: fct_infreq() by frequency, fct_reorder() by a summary of another column, fct_relevel() by moving named levels to the front, and fct_rev() by turning the list around. It changes the labels with fct_recode(), written new = old, and fct_collapse() for many onto one. It removes unused levels with fct_drop(), the counterpart of base R's droplevels(), and it folds a rare tail into Other with fct_lump_n() by count or fct_lump_min() by threshold. Every one of them returns a new factor, so the result has to be kept."],
  ["p","ordered = TRUE adds a ranking on top of the order, which makes the comparison operators meaningful, prints the levels with less-than signs between them, and shows as <ord> in a tibble. On an unordered factor the same comparison gives NA and a warning, which is the correct answer to a question the data cannot support."],
  ["p","Answer the practice questions from memory before revealing the answers, then clear the graded exercises below. The next chapter is Dates and times: parsing a date out of text, the components you can pull from one, and the arithmetic that makes durations and time zones harder than they look."]
]}
],
questions: [
{ q:"What does a factor store that a character vector does not?",
  a:"Its vocabulary. The levels list every permitted value in an order you choose, and the data itself is held as integer positions into that list. A character vector allows any string and has no order beyond the alphabet." },
{ q:"You build a factor with levels = c(\"small\", \"medium\", \"large\") and one of the values is the typo \"mediun\". What happens?",
  a:"It becomes NA, with no warning and no message. The typo does not create a fourth level and does not stop anything. That is the argument for always passing levels: a misspelling turns into a missing value you can count instead of a category you never notice." },
{ q:"Why does sorting a factor give a different answer from sorting the character vector it was built from?",
  a:"Sorting a character vector compares spellings, so the result is alphabetical. Sorting a factor compares the integer codes underneath, which are positions in the level list, so the result follows the order you declared in levels." },
{ q:"A column of years was stored as a factor with the labels \"2019\", \"2021\", \"2020\". What does as.numeric() return, and what should you have written?",
  a:"It returns 1, 3, 2 — the integer codes, which are positions in the alphabetically sorted level list, not the years. The fix is as.numeric(as.character(years)), which reads the labels first. Nothing warns, because small integers are a perfectly valid result." },
{ q:"What levels does factor() choose when you omit the levels argument?",
  a:"The sorted unique values of the data, which is alphabetical order — the order a factor was supposed to replace. It is a reasonable default for a vocabulary with no natural sequence and the wrong one for anything ranked." },
{ q:"What is the difference between fct_infreq() and fct_reorder()?",
  a:"fct_infreq() orders the levels by how often each occurs, most common first, using only the factor. fct_reorder() orders them by a summary of a second variable — the median by default — so it needs the factor and the numbers as two vectors from the same rows." },
{ q:"Which way round are the arguments to fct_recode(), and what goes wrong if you reverse them?",
  a:"New name on the left, existing level on the right: fct_recode(f, cycle = \"bike\"). Reversed, you either get a warning that the level is unknown and no change at all, or, if both names happen to be real levels, a quiet merge of the two in the direction you did not intend." },
{ q:"You filter a data frame down to two of the five travel modes. What does table() on the factor column show, and how do you change it?",
  a:"All five levels, three of them with a count of zero, because filtering rows never touches the level list. droplevels() in base R or fct_drop() in forcats removes the levels with no rows behind them. Keeping the empty levels is sometimes what you want, so it is a choice rather than a bug." },
{ q:"What does fct_lump_n(x, n = 2) do, and what does it cost?",
  a:"It keeps the two most common levels by name and folds every other level into a single level called Other, placed last. The cost is that the original labels are gone from the factor, so the lumping cannot be undone later. Lump after the filtering and joining are finished." },
{ q:"What does ordered = TRUE change, and what happens if you use a comparison operator on a plain factor?",
  a:"It marks the level order as a ranking, so comparison operators work, the Levels line prints with less-than signs between the levels, the class becomes ordered followed by factor, and a tibble shows the column as <ord>. On a plain factor the same comparison returns NA for every element with a warning that the operator is not meaningful for factors." }
],
exercises: [
{ c:"factors & dates", t:"Three membership tiers", book:"r16",
  b:"Attach forcats. Build a factor named tiers_f from the values \"bronze\", \"gold\", \"silver\", \"gold\", \"bronze\", \"gold\", in that order, with the levels declared as bronze, then silver, then gold. Print the factor, then its levels, then a table of its counts.",
  o:"[1] bronze gold   silver gold   bronze gold  \nLevels: bronze silver gold\n[1] \"bronze\" \"silver\" \"gold\"  \ntiers_f\nbronze silver   gold \n     2      1      3 ",
  h:["The values and the levels are two different arguments, and they are in two different orders here on purpose.",
     "factor() takes the data first and levels second. Without the levels argument the vocabulary comes out alphabetical, which is not the order the brief asks for.",
     "One factor() call assigned to tiers_f, then three lines: the variable on its own, levels() of it, and table() of it. The table header will carry the variable name."]},
{ c:"factors & dates", t:"A typo becomes a hole", book:"r16",
  b:"Attach forcats. Build a factor named ranks_f from the values \"low\", \"high\", \"mid\", \"hgh\", \"low\", in that order, with the levels declared as low, then mid, then high. Note that the fourth value is misspelt and is not one of the levels. Print the factor, then the factor sorted, then the number of missing values it contains.",
  o:"[1] low  high mid  <NA> low \nLevels: low mid high\n[1] low  low  mid  high\nLevels: low mid high\n[1] 1",
  h:["A value that is not one of the levels does not raise an error. Look at what the printed factor holds in the fourth position.",
     "sort() on a factor follows the level order rather than the alphabet, and it drops missing values from its result rather than placing them somewhere.",
     "Three lines after the factor() call: the variable, sort() of it, and a count of the missing values built from is.na() and sum()."]},
{ c:"factors & dates", t:"Two ways to order the same routes", book:"r16",
  b:"Attach forcats, tibble, and dplyr with its startup messages suppressed. Build a tibble named trips with a factor column route holding \"north\", \"south\", \"north\", \"east\", \"south\", \"north\", \"east\", \"east\", \"east\" and a double column km holding 4, 30, 5, 12, 28, 6, 14, 11, 20. Declare no levels, so the vocabulary comes from the data. Print three things: the levels after ordering by frequency, the levels after ordering by the median of km, and a count of the rows per route.",
  o:"[1] \"east\"  \"north\" \"south\"\n[1] \"north\" \"east\"  \"south\"\n# A tibble: 3 × 2\n  route     n\n  <fct> <int>\n1 east      4\n2 north     3\n3 south     2",
  h:["Two different forcats functions produce two different orders here, and the point of the exercise is that they disagree.",
     "One of them needs only the factor. The other needs the factor and the numbers as two separate vectors pulled from the same tibble. Wrap each call in levels() to print the order rather than the whole factor.",
     "levels(fct_infreq(trips$route)) for the first line and levels(fct_reorder(trips$route, trips$km)) for the second. The third line is count() over the tibble, which follows the untouched level order."]},
{ c:"grouping & summaries", t:"Boxes per crew", book:"r16",
  b:"Attach forcats, tibble, and dplyr with its startup messages suppressed. Build a tibble named shifts with a factor column crew holding \"dawn\", \"dusk\", \"dawn\", \"night\", \"dusk\", \"night\", \"dawn\", \"night\", with the levels declared as dawn, then dusk, then night, and a double column boxes holding 40, 55, 44, 61, 52, 66, 38, 70. Group by crew and report two summaries per group, a column named total holding the sum of boxes and a column named mid holding the median, ordered from the largest total to the smallest.",
  o:"# A tibble: 3 × 3\n  crew  total   mid\n  <fct> <dbl> <dbl>\n1 night   197  66  \n2 dawn    122  40  \n3 dusk    107  53.5",
  h:["Three dplyr verbs in a pipeline, and the factor column is just a grouping column like any other.",
     "summarise() can create more than one column in a single call, separated by a comma. The brief names both columns, so use those names exactly.",
     "group_by(crew), then summarise(total = ..., mid = ...), then arrange() with desc() around the total. The printed order comes from arrange(), not from the level order."]}
]
};
