/* Practice Log book — R Chapter 17: Dates and times.
   Original lesson text following the chapter-by-chapter curriculum of
   "R for Data Science" (2nd ed.) by Hadley Wickham, Mine Cetinkaya-Rundel,
   and Garrett Grolemund. Read the original chapter free at the src link below.
   Every shown output was captured by executing the code in WebR, not written from memory. */
window.BOOK_R = window.BOOK_R || { chapters: {} };
window.BOOK_R.chapters.r17 = {
n: 17,
title: "Dates and times",
src: "https://r4ds.hadley.nz/datetimes.html",
blurb: "Turning text into a date, pulling the components back out, rounding to a boundary, and the three different things people mean by the length of a time span.",
pkgs: ["lubridate", "tibble", "dplyr"],
sections: [
{ t: "Dates, times, and date-times",
  body: [
  ["p","R has two classes worth learning here. A Date is a calendar day with no time on it, and a date-time is an instant: a day plus a clock reading plus the zone that clock was in. The second class is called POSIXct, a name that tells you nothing and appears constantly, so it is worth recognising on sight rather than understanding."],
  ["p","Both are numbers wearing a label. A Date counts whole days from the first of January 1970, and a date-time counts seconds from the same moment. Every convenience in this chapter is a function that reads that number, or writes one, so that you never have to."],
  ["p","lubridate is the tidyverse package for this work. It is not part of base R and it has to be attached, which produces a message worth reading rather than scrolling past."],
  ["code","library(lubridate)"],
  ["code","\nAttaching package: ‘lubridate’\n\nThe following objects are masked from ‘package:base’:\n\n    date, intersect, setdiff, union"],
  ["p","Attaching lubridate replaces four base functions with its own versions, including intersect and union, which have nothing to do with dates and which you may already be using on vectors. That is what masking means: the same name now reaches a different function. The two later sections that build tables also need tibble and dplyr."],
  ["code","library(tibble)\nsuppressMessages(library(dplyr))"],
  ["p","Here is a day and an instant, each built from text by a function named after the order the parts appear in."],
  ["code","launch_day <- ymd(\"2026-03-14\")\nlaunch_moment <- ymd_hms(\"2026-03-14 09:05:00\", tz = \"UTC\")\n\nlaunch_day\nlaunch_moment"],
  ["code","[1] \"2026-03-14\"\n[1] \"2026-03-14 09:05:00 UTC\""],
  ["p","The printed forms look like strings, and they are quoted, which is misleading. Ask each one what it is and what number is underneath, and the two classes separate."],
  ["code","class(launch_day)\nclass(launch_moment)\nas.numeric(launch_day)\nas.numeric(launch_moment)"],
  ["code","[1] \"Date\"\n[1] \"POSIXct\" \"POSIXt\" \n[1] 20526\n[1] 1773479100"],
  ["note","A date that is still a character vector will pass through most of a script without complaint. It sorts, it prints, it goes into a table. It only breaks when you subtract two of them or ask for a weekday, and by then the code is long. Check class() on any column that came out of a file before you rely on it being a date, because reading a file gives you character columns far more often than it gives you dates."]
]},
{ t: "Parsing a date out of text",
  body: [
  ["p","Dates arrive as text, written in whatever order the person who typed them preferred. lubridate solves this with a family of functions whose names are the order of the parts: ymd, dmy, mdy. You pick the function that matches the string, and it works out the separators on its own."],
  ["code","ymd(\"2026-03-14\")\nmdy(\"March 14, 2026\")\ndmy(\"14/03/2026\")\nymd(20260314)"],
  ["code","[1] \"2026-03-14\"\n[1] \"2026-03-14\"\n[1] \"2026-03-14\"\n[1] \"2026-03-14\""],
  ["p","Four different inputs, one answer, and the last one was not even text. Slashes, dashes, spaces, a spelled-out month, or no separator at all: the function name supplies the order and the parser handles the rest. Add a time by extending the name with the parts of the clock reading you have."],
  ["code","ymd_hms(\"2026-03-14 09:05:00\")\nymd_hm(\"2026-03-14 09:05\")\nmdy_hms(\"03/14/2026 09:05:00\")"],
  ["code","[1] \"2026-03-14 09:05:00 UTC\"\n[1] \"2026-03-14 09:05:00 UTC\"\n[1] \"2026-03-14 09:05:00 UTC\""],
  ["p","Every one of those came back as UTC, which is the default when you do not say otherwise. It is a safe default and a quiet one — nothing warns you that the zone was assumed. Name the zone with tz when you know it, and the printed abbreviation changes to match."],
  ["code","ymd_hms(\"2026-03-14 09:05:00\", tz = \"Europe/Lisbon\")"],
  ["code","[1] \"2026-03-14 09:05:00 WET\""],
  ["p","Strings that do not parse become NA, and lubridate counts them for you. A date that does not exist counts as a failure just as a sentence does."],
  ["code","ymd(c(\"2026-03-14\", \"2026-02-30\", \"the fourteenth\"))"],
  ["code","Warning:  2 failed to parse.\n[1] \"2026-03-14\" NA           NA          "],
  ["p","Base R does the same job with as.Date and a format string, where each part of the date is a percent code. It is more typing and it is what you will find in older scripts, so it is worth being able to read."],
  ["code","as.Date(\"14/03/2026\", format = \"%d/%m/%Y\")\nas.Date(\"14/03/2026\")"],
  ["code","[1] \"2026-03-14\"\n[1] \"0014-03-20\""],
  ["note","Look at the second line again. as.Date without a format did not fail — it decided the string was year 14, month 3, day 20, and returned a date two thousand years early with no warning at all. That is the worst kind of wrong answer, because nothing downstream will question it. Either pass format every time you call as.Date, or use the lubridate function whose name states the order."]
]},
{ t: "Building one from components",
  body: [
  ["p","When the parts are already separate columns, there is nothing to parse. make_date takes a year, a month and a day; make_datetime takes those plus as much of the clock as you have, and a zone."],
  ["code","make_date(2026, 3, 14)\nmake_datetime(2026, 3, 14, 9, 5, 0, tz = \"UTC\")"],
  ["code","[1] \"2026-03-14\"\n[1] \"2026-03-14 09:05:00 UTC\""],
  ["p","Numbers that are already counts of seconds or days convert directly. as_datetime reads seconds since the start of 1970, as_date reads days since the same point, and either one will also convert between the two classes."],
  ["code","as_datetime(0)\nas_datetime(1773478800)\nas_date(launch_moment)\nas_date(20526)"],
  ["code","[1] \"1970-01-01 UTC\"\n[1] \"2026-03-14 09:00:00 UTC\"\n[1] \"2026-03-14\"\n[1] \"2026-03-14\""],
  ["p","The table below is the working example for the rest of the chapter: six ferry sailings, each with a route, a departure instant parsed in UTC, and a crossing time in minutes. Parsing the whole column in one call is the normal shape — these functions are vectorised, so a column costs the same one line as a single value."],
  ["code","sailings <- tibble(\n  route = c(\"Skerry\", \"Rosehill\", \"Marlow\", \"Skerry\", \"Rosehill\", \"Marlow\"),\n  departed = ymd_hms(c(\"2026-03-06 07:15:00\", \"2026-03-14 13:40:00\",\n                       \"2026-03-22 19:05:00\", \"2026-04-02 06:50:00\",\n                       \"2026-04-11 15:25:00\", \"2026-04-19 21:00:00\"),\n                     tz = \"UTC\"),\n  minutes = c(95, 130, 110, 95, 145, 110)\n)\n\nsailings"],
  ["code","# A tibble: 6 × 3\n  route    departed            minutes\n  <chr>    <dttm>                <dbl>\n1 Skerry   2026-03-06 07:15:00      95\n2 Rosehill 2026-03-14 13:40:00     130\n3 Marlow   2026-03-22 19:05:00     110\n4 Skerry   2026-04-02 06:50:00      95\n5 Rosehill 2026-04-11 15:25:00     145\n6 Marlow   2026-04-19 21:00:00     110"],
  ["p","The abbreviation under departed is <dttm>, which is the tibble's word for a date-time. A plain Date column shows as <date>. If either of those columns had come back as <chr>, the parse silently did not happen, and that row of abbreviations is the cheapest place to notice."],
  ["note","make_datetime with no tz argument gives you UTC, exactly like the parsers. That is fine when the data really is in UTC and wrong the rest of the time, and the mistake costs you nothing until you compare against an instant that was recorded properly. Decide the zone once, when the column is created, and pass it explicitly even when it happens to match the default."]
]},
{ t: "Pulling components back out",
  body: [
  ["p","Each part of a date has an accessor function named after it. They take a date or a date-time and give back a plain number."],
  ["code","year(launch_moment)\nmonth(launch_moment)\nmday(launch_moment)\nyday(launch_moment)\nhour(launch_moment)\nminute(launch_moment)"],
  ["code","[1] 2026\n[1] 3\n[1] 14\n[1] 73\n[1] 9\n[1] 5"],
  ["p","mday is the day of the month and yday is the day of the year, which is why the same date answers 14 and 73. lubridate also exports day(), but it is only another name for mday() — it reads as though it might mean either, and it answers the day of the month. Write mday when that is what you mean, and yday when it is not."],
  ["p","month and wday will also return a label instead of a number. What comes back is an ordered factor, the class from the previous chapter, so the calendar order is carried in the levels rather than left to the alphabet."],
  ["code","month(launch_moment, label = TRUE)\nwday(launch_moment)\nwday(launch_moment, label = TRUE, abbr = FALSE)"],
  ["code","[1] Mar\n12 Levels: Jan < Feb < Mar < Apr < May < Jun < Jul < Aug < Sep < ... < Dec\n[1] 7\n[1] Saturday\n7 Levels: Sunday < Monday < Tuesday < Wednesday < Thursday < ... < Saturday"],
  ["p","Note that wday numbers the week from Sunday, so Saturday is 7 rather than 6. The labelled version removes the need to remember that. Because the result is an ordered factor, counting it gives the days back in week order rather than alphabetically."],
  ["code","sailings |>\n  mutate(day_name = wday(departed, label = TRUE, abbr = FALSE)) |>\n  count(day_name)"],
  ["code","# A tibble: 4 × 2\n  day_name     n\n  <ord>    <int>\n1 Sunday       2\n2 Thursday     1\n3 Friday       1\n4 Saturday     2"],
  ["p","Four weekdays across six sailings, listed Sunday first because that is where the level list starts. Had the column been the character strings instead, the same count would have come back Friday, Saturday, Sunday, Thursday, which is an ordering of spellings."],
  ["note","Every accessor reads the date in its own zone. hour() on an instant stored as UTC gives you the UTC hour, and the same instant viewed from Tokyo has a different hour and possibly a different date. So a summary of activity by hour of day is a statement about a zone, and if the column was parsed with the default UTC while the events happened somewhere else, the summary is quietly about the wrong clock."]
]},
{ t: "Rounding and rewriting",
  body: [
  ["p","Rounding a date means moving it to a boundary — the start of the hour, the start of the month. Three functions do it, and they differ only in which direction they go. The unit is a string naming the boundary."],
  ["code","floor_date(launch_moment, \"hour\")\nround_date(launch_moment, \"hour\")\nceiling_date(launch_moment, \"hour\")"],
  ["code","[1] \"2026-03-14 09:00:00 UTC\"\n[1] \"2026-03-14 09:00:00 UTC\"\n[1] \"2026-03-14 10:00:00 UTC\""],
  ["p","floor_date always goes back, ceiling_date always goes forward, and round_date goes to whichever boundary is nearer — here 09:05 is nearer the start of the hour, so it agrees with the floor. The same three functions take any unit, including ones bigger than a day."],
  ["code","floor_date(launch_moment, \"month\")\nfloor_date(launch_day, \"week\")\nceiling_date(launch_day, \"month\")"],
  ["code","[1] \"2026-03-01 UTC\"\n[1] \"2026-03-08\"\n[1] \"2026-04-01\""],
  ["p","Flooring to a month is the standard way to group daily records into monthly ones: it maps every day in March onto the same value, which then becomes the grouping key. Flooring to a week here lands on Sunday the eighth, because a week starts on Sunday unless you tell it otherwise."],
  ["p","The accessor functions also work on the left of an assignment, which rewrites that one component and leaves the rest alone."],
  ["code","moved <- launch_moment\nyear(moved) <- 2027\nhour(moved) <- 6\nmoved"],
  ["code","[1] \"2027-03-14 06:05:00 UTC\""],
  ["p","Two assignments, two components changed, minutes and seconds untouched. update() does the same job in one call and does not modify the original, which is the version to prefer inside a pipeline."],
  ["code","update(launch_moment, year = 2027, month = 12, mday = 1)"],
  ["code","[1] \"2027-12-01 09:05:00 UTC\""],
  ["p","Values that overflow their component roll forward instead of erroring. Asking for the forty-fifth day of March gives the fourteenth of April, which is genuinely useful for arithmetic and a trap when the number came from somewhere you did not check."],
  ["code","update(ymd(\"2026-03-14\"), mday = 45)"],
  ["code","[1] \"2026-04-14\""],
  ["note","year(x) <- 2027 changes x in place, and update() returns a new value while leaving x alone. Writing update(x, year = 2027) on a line by itself therefore looks like it worked — the answer prints — and x is unchanged on the next line. Assign the result of update() to something, or use the accessor form, and be clear about which one you chose."]
]},
{ t: "Durations, periods, and intervals",
  body: [
  ["p","Subtracting one date from another gives a difftime, which is a number with a unit attached. R picks the unit, and which unit it picks depends on how far apart the two dates are, so a difftime is awkward to compute with."],
  ["code","gap <- ymd(\"2026-04-19\") - ymd(\"2026-03-06\")\n\ngap\nclass(gap)\nas.numeric(gap)"],
  ["code","Time difference of 44 days\n[1] \"difftime\"\n[1] 44"],
  ["p","lubridate replaces it with three classes that each answer a different question. A duration is an exact number of seconds. It always prints the seconds first, then a human-scale approximation in brackets."],
  ["code","as.duration(gap)\nddays(1)\ndyears(1)"],
  ["code","[1] \"3801600s (~6.29 weeks)\"\n[1] \"86400s (~1 days)\"\n[1] \"31557600s (~1 years)\""],
  ["p","Every duration constructor starts with d. ddays(1) is exactly 86400 seconds by definition, and dyears(1) is 31557600 seconds, which is 365.25 days — an average year, not any particular one. Adding a duration adds that many seconds."],
  ["code","launch_moment + ddays(30)"],
  ["code","[1] \"2026-04-13 09:05:00 UTC\""],
  ["p","A period is the other answer: a length measured in human units, which stay attached to their names instead of collapsing into seconds. The constructors are the plain nouns."],
  ["code","days(1)\nmonths(3)\nlaunch_day + months(1)\nlaunch_day + years(1)"],
  ["code","[1] \"1d 0H 0M 0S\"\n[1] \"3m 0d 0H 0M 0S\"\n[1] \"2026-04-14\"\n[1] \"2027-03-14\""],
  ["p","A month added as a period means the same date next month, whatever that costs in days. That works until the same date next month does not exist, and then the answer is NA — the thirty-first of February is not a date, and lubridate refuses to guess which nearby day you meant."],
  ["code","ymd(\"2026-01-31\") + months(1)\nymd(\"2026-01-31\") %m+% months(1)"],
  ["code","[1] NA\n[1] \"2026-02-28\""],
  ["p","The %m+% operator is the version that rolls back to the last valid day of the target month. Use it for anything monthly — billing dates, renewal dates — where an NA once a year is a bug and the end of the month is the intended answer."],
  ["p","The difference between the two classes only becomes visible when a day is not twenty-four hours long. Clocks in New York go forward in the small hours of the eighth of March 2026, so that day is twenty-three hours."],
  ["code","dst_eve <- ymd_hms(\"2026-03-07 22:00:00\", tz = \"America/New_York\")\n\ndst_eve\ndst_eve + ddays(1)\ndst_eve + days(1)"],
  ["code","[1] \"2026-03-07 22:00:00 EST\"\n[1] \"2026-03-08 23:00:00 EDT\"\n[1] \"2026-03-08 22:00:00 EDT\""],
  ["p","Same start, same phrase in English, two different answers. The duration added exactly 86400 seconds and landed at eleven at night, because an hour of that day did not happen. The period kept the clock reading and landed at ten, one hour of real time earlier. Neither is wrong. A duration answers how much time passed, a period answers what the clock will say."],
  ["p","An interval is the third class: a specific span with a start and an end, built with %--%. Because it knows its endpoints it can report an exact length, and it can be asked whether an instant falls inside it."],
  ["code","window <- ymd(\"2026-03-01\") %--% ymd(\"2026-03-31\")\n\nwindow\nint_length(window)\nymd(\"2026-03-14\") %within% window\nymd(\"2026-04-19\") %within% window"],
  ["code","[1] 2026-03-01 UTC--2026-03-31 UTC\n[1] 2592000\n[1] TRUE\n[1] FALSE"],
  ["p","Dividing an interval by a period converts it into that unit, and because the interval knows exactly which months it covers, the answer is exact rather than an average."],
  ["code","(ymd(\"2026-01-01\") %--% ymd(\"2026-03-01\")) / months(1)\n(ymd(\"2026-01-01\") %--% ymd(\"2026-03-01\")) / ddays(1)"],
  ["code","[1] 2\n[1] 59"],
  ["note","The naming is the part people get wrong, and it is worth learning as a rule rather than a feeling: constructors beginning with d build durations of exact seconds, the plain nouns build periods of calendar units, and %--% builds an interval between two known points. Reach for a period when a human would say tomorrow or next month, a duration when you mean elapsed time, and an interval when you have both ends and want to test membership."]
]},
{ t: "Time zones",
  body: [
  ["p","A zone name is a region, not an offset. \"Europe/Lisbon\" is a place whose rules about offsets and daylight saving are recorded in a database that R ships with, and it is those rules, not a fixed number of hours, that get applied. The abbreviation printed after an instant is the offset in force at that moment, which is why the same zone prints WET in winter and something else in summer."],
  ["code","\"Europe/Lisbon\" %in% OlsonNames()"],
  ["code","[1] TRUE"],
  ["p","OlsonNames() is the list of every zone R recognises, and checking membership before trusting a zone string is cheap insurance against a typo. Two functions change the zone of an existing instant, and they do opposite things."],
  ["code","lisbon <- ymd_hms(\"2026-03-14 09:05:00\", tz = \"Europe/Lisbon\")\n\nlisbon\nwith_tz(lisbon, \"Asia/Tokyo\")\nforce_tz(lisbon, \"Asia/Tokyo\")"],
  ["code","[1] \"2026-03-14 09:05:00 WET\"\n[1] \"2026-03-14 18:05:00 JST\"\n[1] \"2026-03-14 09:05:00 JST\""],
  ["p","with_tz keeps the instant and changes the display: the same moment, described by a Tokyo clock, is six in the evening. force_tz keeps the display and changes the instant: it declares that the clock reading nine-oh-five was a Tokyo clock all along, which is a different moment entirely. Comparison settles which is which."],
  ["code","lisbon == with_tz(lisbon, \"Asia/Tokyo\")\nlisbon == force_tz(lisbon, \"Asia/Tokyo\")\nas.numeric(force_tz(lisbon, \"Asia/Tokyo\")) - as.numeric(lisbon)"],
  ["code","[1] TRUE\n[1] FALSE\n[1] -32400"],
  ["p","The forced version is 32400 seconds — nine hours — earlier as an instant, because nine in the morning in Tokyo happens before nine in the morning in Lisbon. Use with_tz to report a known moment in someone else's local time, and force_tz only to repair data whose zone was recorded wrongly or not at all."],
  ["p","Every date-time carries its zone as an attribute, which tz() reads back. A Date has no time and therefore no real zone, and reports UTC."],
  ["code","tz(lisbon)\ntz(launch_moment)\ntz(launch_day)"],
  ["code","[1] \"Europe/Lisbon\"\n[1] \"UTC\"\n[1] \"UTC\""],
  ["p","Three functions in this chapter depend on when you run them rather than on what you wrote, so this app cannot print their results: Sys.timezone() reports the zone of the machine, and now() and today() report the current instant and the current day. Run them and you get a single zone name, a date-time, and a date respectively, each different from what anyone else running the same line would see."],
  ["code","Sys.timezone()\nnow()\ntoday()"],
  ["note","Sys.timezone() is the reason a script can pass on your laptop and produce different numbers on a colleague's. Anything parsed without a tz argument, anything compared against now(), and any summary grouped by hour inherits whatever zone the machine happened to be set to. Pass tz explicitly wherever a zone is possible, and treat a date-time with no stated zone as a value you have not finished reading yet."]
]},
{ t: "Summary",
  body: [
  ["p","A Date is a calendar day counted in days from 1970, a date-time is an instant counted in seconds from the same point, and both print as quoted text that looks like a string and is not. Check with class() before trusting a column. lubridate parses text with functions named for the order of the parts — ymd, dmy, mdy, and the same names extended with hms or hm for a clock reading — and everything that fails to parse becomes NA with a count in the warning. as.Date without a format argument is the one to avoid: it returns a wrong date rather than an error."],
  ["p","make_date and make_datetime build one from separate components, as_datetime and as_date convert from numbers and between the two classes, and the accessors year, month, mday, yday, hour and minute read the components back out. month and wday take label = TRUE and return an ordered factor, so counts and sorts come out in calendar order. floor_date, round_date and ceiling_date move a date to a boundary, and the same accessors on the left of an assignment, or update() in one call, rewrite a component in place."],
  ["p","Three classes measure a span. Durations are exact seconds and their constructors begin with d; periods are calendar units and their constructors are the plain nouns; intervals are built with %--% between two known points, report an exact length through int_length, and test membership with %within%. Across a daylight saving change ddays(1) and days(1) give different answers, which is the clearest demonstration that the two are answering different questions. Adding months to a month-end date needs %m+% to avoid an NA."],
  ["p","Time zones are region names from OlsonNames(), not offsets. with_tz keeps the instant and changes the display, force_tz keeps the display and changes the instant, and tz() reports what a value is carrying. Parsers default to UTC without saying so, and Sys.timezone() makes the machine part of the result, so name the zone explicitly."],
  ["p","Answer the practice questions from memory before revealing the answers, then clear the graded exercises below. The next chapter is Missing values: the difference between a gap you can see and a row that was never written, how NA spreads through a calculation, and the tools that make an absent row explicit before you count anything."]
]}
],
questions: [
{ q:"What is the difference between a Date and a POSIXct, and what number is stored underneath each?",
  a:"A Date is a calendar day with no time attached; a POSIXct is an instant, meaning a day, a clock reading, and a zone. A Date holds the number of days since the start of 1970 — 20526 for the fourteenth of March 2026 — and a POSIXct holds the number of seconds since the same moment. Both print inside quotation marks, which is why class() is the only reliable way to tell either of them from a character string." },
{ q:"Which lubridate function parses \"14/03/2026\", and what does as.Date(\"14/03/2026\") return?",
  a:"dmy(), because the parts are in day, month, year order and the function name states that order. as.Date on the same string without a format argument returns \"0014-03-20\" — year 14 — with no warning. It is not an error, it is a wrong date, which makes it far more dangerous than a failure." },
{ q:"You call ymd_hms(\"2026-03-14 09:05:00\") without a tz argument. What zone do you get, and how would you know?",
  a:"UTC. Nothing warns you; the printed value simply ends in UTC, and tz() on the result returns \"UTC\". That default is correct only when the data really was recorded in UTC, so pass tz explicitly whenever the zone is known." },
{ q:"What does ymd() do with a vector containing \"2026-03-14\", \"2026-02-30\", and \"the fourteenth\"?",
  a:"It returns the first as a date and the other two as NA, and prints the warning \"2 failed to parse.\" The thirtieth of February counts as a failure for the same reason the sentence does — it is not a date that exists. The warning gives a count, not the positions, so is.na() on the result is how you find them." },
{ q:"month(x, label = TRUE) does not return a number. What does it return, and why does that matter for a count?",
  a:"An ordered factor whose levels run January through December. Because the calendar order lives in the levels rather than in the spelling, counting or sorting the result comes out in calendar order. The same column stored as character strings would sort alphabetically, which puts April first." },
{ q:"For an instant at 09:05, what do floor_date, round_date and ceiling_date give when the unit is \"hour\"?",
  a:"09:00, 09:00 and 10:00. floor_date always moves back to the boundary, ceiling_date always moves forward, and round_date goes to whichever is nearer — at five minutes past, that is the earlier one. Flooring to \"month\" is the usual way to collapse daily rows into monthly groups." },
{ q:"What is the difference between writing year(x) <- 2027 and writing update(x, year = 2027)?",
  a:"The accessor form modifies x in place. update() returns a new value and leaves x untouched, so its result has to be assigned to something. Both leave every component you did not name alone, and update() takes several at once. A component given a value too large rolls forward rather than erroring: mday = 45 in March gives the fourteenth of April." },
{ q:"An instant is 22:00 on the seventh of March 2026 in America/New_York, the night the clocks go forward. What do adding ddays(1) and adding days(1) each give?",
  a:"ddays(1) gives 23:00 on the eighth, and days(1) gives 22:00 on the eighth. A duration is exactly 86400 seconds, and that day only had 23 hours of clock time, so the extra hour pushes the reading forward. A period keeps the clock reading and accepts that less real time passed. A duration answers how much time elapsed, a period answers what the clock will say." },
{ q:"Why is ymd(\"2026-01-31\") + months(1) equal to NA, and what should you write instead?",
  a:"Adding a month as a period means the same day number in the next month, and the thirty-first of February does not exist, so the answer is NA rather than a guess. %m+% is the operator that rolls back to the last valid day, giving the twenty-eighth of February. Use it for anything monthly, where an NA at the end of a long month is a bug." },
{ q:"What is the difference between with_tz(x, \"Asia/Tokyo\") and force_tz(x, \"Asia/Tokyo\")?",
  a:"with_tz keeps the instant and changes how it is displayed, so the result compares as equal to x. force_tz keeps the clock reading and declares it was always in the new zone, which makes it a different instant — nine hours earlier than a Lisbon nine o'clock, and comparison against x returns FALSE. Use with_tz to report a known moment elsewhere, and force_tz only to repair a zone that was recorded wrongly." }
],
exercises: [
{ c:"factors & dates", t:"One day, three spellings", book:"r17",
  b:"Attach lubridate with suppressMessages(library(lubridate)). The same day reached you written three ways: \"2026-05-09\", then \"09/05/2026\" in day/month/year order, then \"May 9, 2026\". Parse each with the lubridate function whose name matches that order, combine the three results into a vector named opened with c(), then print opened and its class on two lines.",
  o:"[1] \"2026-05-09\" \"2026-05-09\" \"2026-05-09\"\n[1] \"Date\"",
  h:["Three different parsing functions, one per string, chosen by the order the parts appear in.",
     "The function names are the order of the parts. Year first, day first, and month first are three different names from the same family, and none of them needs a format string.",
     "Wrap the three parsing calls in a single c(), assign that to opened, then write two lines: the variable on its own, and class() of it."]},
{ c:"factors & dates", t:"Which weekdays the drops land on", book:"r17",
  b:"Attach lubridate with suppressMessages(library(lubridate)), tibble with library(tibble), and dplyr with suppressMessages(library(dplyr)). Build a tibble named deliveries with one column, dropped, holding the date-times \"2026-06-01 08:30:00\", \"2026-06-03 14:00:00\", \"2026-06-06 09:15:00\", \"2026-06-08 17:45:00\" and \"2026-06-13 11:20:00\", all parsed in UTC. Add a column named weekday holding each row's full unabbreviated weekday name, then count the rows per weekday and print the result.",
  o:"# A tibble: 3 × 2\n  weekday       n\n  <ord>     <int>\n1 Monday        2\n2 Wednesday     1\n3 Saturday      2",
  h:["One parsing call handles the whole column, because these functions work on a vector.",
     "The weekday accessor takes two arguments beyond the date: one asks for a label instead of a number, the other switches the abbreviation off. What comes back is an ordered factor, which is why the count arrives in week order rather than alphabetical order.",
     "Parse the five strings inside one ymd_hms() with tz = \"UTC\", then pipe the tibble through mutate() with wday() and its two extra arguments, then through count() on the new column."]},
{ c:"factors & dates", t:"A month after the thirty-first", book:"r17",
  b:"Attach lubridate with suppressMessages(library(lubridate)). Store the date the thirty-first of January 2026 in a variable named billed. Print four lines: billed plus one month added as a period, billed plus one month added with the operator that rolls back to a valid day, billed plus thirty days added as a duration, and the day of the year of billed.",
  o:"[1] NA\n[1] \"2026-02-28\"\n[1] \"2026-03-02\"\n[1] 31",
  h:["The first line is supposed to fail. The point of the exercise is that three plausible readings of a month later give three different answers.",
     "A period is built by the plain noun, a duration by the same noun with a d in front. The rolling operator is a two-character symbol wrapped in percent signs. The day of the year is not mday.",
     "After building billed with ymd(), write four single expressions: one using months(1), one using %m+% with months(1), one using ddays(30), and one using yday()."]},
{ c:"dplyr verbs", t:"Only the February readings", book:"r17",
  b:"Attach lubridate with suppressMessages(library(lubridate)), tibble with library(tibble), and dplyr with suppressMessages(library(dplyr)). Build a tibble named readings with a column taken holding the dates \"2026-01-18\", \"2026-02-02\", \"2026-02-27\", \"2026-03-05\" and \"2026-03-30\", and a column level holding 4.1, 3.8, 5.2, 4.9 and 6.0. Build an interval named feb running from the first of February 2026 to the twenty-eighth of February 2026. Keep only the rows whose taken falls inside feb, arrange them by taken, and print the result.",
  o:"# A tibble: 2 × 2\n  taken      level\n  <date>     <dbl>\n1 2026-02-02   3.8\n2 2026-02-27   5.2",
  h:["An interval is a span with a start and an end, and there is an operator that tests whether a date sits inside one.",
     "The interval is built between two dates with a four-character operator, and the membership test is a different operator whose name is a word. Both are used the way any infix operator is, with a value on each side.",
     "Parse the five dates in one ymd() call. Build feb as ymd(\"2026-02-01\") joined to ymd(\"2026-02-28\") with %--%. Then pipe readings through filter() using %within% and through arrange()."]}
]
};
