/* Practice Log book — R Chapter 18: Missing values.
   Original lesson text following the chapter-by-chapter curriculum of
   "R for Data Science" (2nd ed.) by Hadley Wickham, Mine Cetinkaya-Rundel,
   and Garrett Grolemund. Read the original chapter free at the src link below.
   Every shown output was captured by executing the code in WebR, not written from memory. */
window.BOOK_R = window.BOOK_R || { chapters: {} };
window.BOOK_R.chapters.r18 = {
n: 18,
title: "Missing values",
src: "https://r4ds.hadley.nz/missing-values.html",
blurb: "Telling a value that is present but unknown from a row that was never written down, and the tools that turn the second kind into the first before you count anything.",
pkgs: ["tibble", "dplyr", "tidyr"],
sections: [
{ t: "Two kinds of missing",
  body: [
  ["p","A missing value is not always a hole you can see. There are two kinds, and only one of them is visible in the data. An explicit missing value is an NA sitting in a cell: the row exists, the column exists, and the value is recorded as unknown. An implicit missing value is a row that was never written at all — nothing marks its absence, and every function you run agrees with the data that it does not exist."],
  ["p","The distinction matters because the second kind survives every check you make on the first. Counting NA values finds nothing wrong, because there is nothing there to find."],
  ["code","library(tibble)\nlibrary(tidyr)\nsuppressMessages(library(dplyr))"],
  ["p","The table below records soil moisture for three plots across three weeks. Two readings are explicitly missing, and one plot-week is missing in the other way."],
  ["code","moisture <- tibble(\n  plot = c(\"A\", \"A\", \"A\", \"B\", \"B\", \"C\", \"C\", \"C\"),\n  week = c(1, 2, 3, 1, 3, 1, 2, 3),\n  reading = c(31.2, NA, 28.7, 26.5, 25.1, NA, 33.4, 30.9)\n)\n\nmoisture"],
  ["code","# A tibble: 8 × 3\n  plot   week reading\n  <chr> <dbl>   <dbl>\n1 A         1    31.2\n2 A         2    NA  \n3 A         3    28.7\n4 B         1    26.5\n5 B         3    25.1\n6 C         1    NA  \n7 C         2    33.4\n8 C         3    30.9"],
  ["p","The two NA values are easy to see. The third gap is harder: three plots across three weeks should be nine rows, and there are eight. Counting the rows per plot says which one is short."],
  ["code","nrow(moisture)\nsum(is.na(moisture$reading))\ncount(moisture, plot)"],
  ["code","[1] 8\n[1] 2\n# A tibble: 3 × 2\n  plot      n\n  <chr> <int>\n1 A         3\n2 B         2\n3 C         3"],
  ["p","Plot B has two rows where the others have three, and week 2 is the one that never got written down. Nothing in the table says so. The count says so, and only because you knew to expect three."],
  ["note","An average over this column is the place the difference bites. Both kinds of missing lower the count you are dividing by, but only the explicit ones can be found with is.na(). A mean per plot computed straight off this table gives plot B an answer over two weeks and calls it comparable to the others. The habit worth building is to check the shape — rows against the number you expect — before you compute anything, not after a number looks odd."]
]},
{ t: "What NA does to a calculation",
  body: [
  ["p","NA means unknown, and R takes that literally. Any operation with an unknown input has an unknown result, so NA spreads through arithmetic and comparison rather than being skipped."],
  ["code","NA + 1\nNA > 5\nNA == NA\nsum(c(31.2, NA, 28.7))"],
  ["code","[1] NA\n[1] NA\n[1] NA\n[1] NA"],
  ["p","The third line is the one that catches people. Two unknown values might or might not be equal, so the honest answer to NA == NA is that it is unknown. That means the obvious way of finding missing values does not work, and does not fail either — it hands back a column of NA, which then quietly selects no rows."],
  ["code","moisture$reading == NA"],
  ["code","[1] NA NA NA NA NA NA NA NA"],
  ["p","Every summary function has an na.rm argument for dropping the missing values before it computes. It is off by default, which is deliberate: an NA in the result is R telling you the data has holes in it, and turning na.rm on is you saying you already knew."],
  ["code","mean(c(31.2, NA, 28.7))\nmean(c(31.2, NA, 28.7), na.rm = TRUE)\nsum(c(31.2, NA, 28.7), na.rm = TRUE)"],
  ["code","[1] NA\n[1] 29.95\n[1] 59.9"],
  ["p","is.na() is the function that actually tests for missingness, and it answers TRUE or FALSE rather than NA. Summing it counts the holes, because TRUE counts as one; which() turns the same answer into positions."],
  ["code","is.na(c(31.2, NA, 28.7))\nsum(is.na(moisture$reading))\nwhich(is.na(moisture$reading))"],
  ["code","[1] FALSE  TRUE FALSE\n[1] 2\n[1] 2 6"],
  ["p","NA on its own is a logical value, and there is a typed version for every other kind of vector. You rarely write them by hand, but the reason they exist is that a vector holds one type, so an NA inside a character vector has to be a character NA."],
  ["code","class(NA)\nclass(NA_character_)\nclass(NA_real_)\nc(NA, \"clay\")"],
  ["code","[1] \"logical\"\n[1] \"character\"\n[1] \"numeric\"\n[1] NA     \"clay\""],
  ["p","In a data frame, filter() keeps only rows where the condition is TRUE, so rows where it is NA are dropped along with the FALSE ones. Use is.na() inside filter() to go and find them, and drop_na() from tidyr to remove them."],
  ["code","filter(moisture, is.na(reading))\ndrop_na(moisture, reading)"],
  ["code","# A tibble: 2 × 3\n  plot   week reading\n  <chr> <dbl>   <dbl>\n1 A         2      NA\n2 C         1      NA\n# A tibble: 6 × 3\n  plot   week reading\n  <chr> <dbl>   <dbl>\n1 A         1    31.2\n2 A         3    28.7\n3 B         1    26.5\n4 B         3    25.1\n5 C         2    33.4\n6 C         3    30.9"],
  ["p","Sorting treats missing values differently depending on which function you use, which is worth knowing before it surprises you in a report."],
  ["code","sort(c(3, NA, 1))\narrange(tibble(x = c(3, NA, 1)), x)"],
  ["code","[1] 1 3\n# A tibble: 3 × 1\n      x\n  <dbl>\n1     1\n2     3\n3    NA"],
  ["note","sort() silently threw a value away and arrange() kept it, parked at the end. Neither is a bug and the inconsistency is real: base R's sort() drops missing values unless you pass na.last, and dplyr's arrange() always puts them last regardless of direction. If a vector goes into sort() and comes back shorter, that is where the rows went."]
]},
{ t: "Carrying the last observation forward",
  body: [
  ["p","Some missing values are missing on purpose. Data entered by hand often records a value only when it changes, leaving the repeats blank, because a human reading down the column supplies them without noticing. The table below records which inspector covered which bay."],
  ["code","inspections <- tibble(\n  inspector = c(\"Nadia\", NA, NA, \"Omar\", NA, \"Priya\"),\n  bay = c(1, 2, 3, 4, 5, 6),\n  faults = c(0, 2, 1, 3, 0, 4)\n)\n\ninspections"],
  ["code","# A tibble: 6 × 3\n  inspector   bay faults\n  <chr>     <dbl>  <dbl>\n1 Nadia         1      0\n2 <NA>          2      2\n3 <NA>          3      1\n4 Omar          4      3\n5 <NA>          5      0\n6 Priya         6      4"],
  ["p","A tibble prints a missing character value as <NA> in angle brackets, which distinguishes it from the four-letter string \"NA\" that a column of country codes would legitimately contain. fill() from tidyr replaces each missing value with the last non-missing one above it — the operation usually called last observation carried forward."],
  ["code","fill(inspections, inspector)"],
  ["code","# A tibble: 6 × 3\n  inspector   bay faults\n  <chr>     <dbl>  <dbl>\n1 Nadia         1      0\n2 Nadia         2      2\n3 Nadia         3      1\n4 Omar          4      3\n5 Omar          5      0\n6 Priya         6      4"],
  ["p","Nadia now covers bays 1 to 3 and Omar covers 4 and 5, which is what the person entering the data meant. The direction is an argument, and the other one fills upward from the next value below."],
  ["code","fill(inspections, inspector, .direction = \"up\")"],
  ["code","# A tibble: 6 × 3\n  inspector   bay faults\n  <chr>     <dbl>  <dbl>\n1 Nadia         1      0\n2 Omar          2      2\n3 Omar          3      1\n4 Omar          4      3\n5 Priya         5      0\n6 Priya         6      4"],
  ["note","Filling upward gives a completely different and equally plausible-looking table, and only one of them is what happened. fill() is an assumption about how the data was entered, not a repair — it is right when blanks mean same as above and wrong when they mean not recorded. It also depends entirely on the row order, so a fill() after an arrange() on some other column produces confident nonsense."]
]},
{ t: "Sentinels, defaults, and NaN",
  body: [
  ["p","Data collected outside R often marks missing values with a number instead of a blank: -99, -999, 0, or 9999. These are called sentinels, and they are dangerous precisely because they are valid numbers — every mean, sum and plot will happily include them. na_if() converts a sentinel into a real NA."],
  ["code","scores <- c(12, -99, 8, -99, 15)\n\nna_if(scores, -99)\nmean(na_if(scores, -99), na.rm = TRUE)"],
  ["code","[1] 12 NA  8 NA 15\n[1] 11.66667"],
  ["p","The mean of the raw vector would have been well below zero, and nothing about it would have looked like an error. Convert sentinels at the moment you read the data, before anything else touches it."],
  ["p","coalesce() goes the other way: given several vectors, it takes the first non-missing value at each position. It is how you supply a fallback from a second source, or a constant."],
  ["code","coalesce(c(NA, 4, NA), c(1, 2, 3))\ncoalesce(c(NA, 4, NA), 0)"],
  ["code","[1] 1 4 3\n[1] 0 4 0"],
  ["p","replace_na() from tidyr does the same job inside a data frame, taking a list that names the column and the value to put in it."],
  ["code","mutate(moisture, reading = replace_na(reading, 0))"],
  ["code","# A tibble: 8 × 3\n  plot   week reading\n  <chr> <dbl>   <dbl>\n1 A         1    31.2\n2 A         2     0  \n3 A         3    28.7\n4 B         1    26.5\n5 B         3    25.1\n6 C         1     0  \n7 C         2    33.4\n8 C         3    30.9"],
  ["p","NaN is a separate thing that behaves almost identically. It means not a number and it comes from an arithmetic operation with no defined answer rather than from an absent measurement. is.na() counts it as missing, which is usually what you want, but the two are not interchangeable."],
  ["code","0 / 0\nis.na(NaN)\nis.nan(NA)\nclass(NaN)"],
  ["code","[1] NaN\n[1] TRUE\n[1] FALSE\n[1] \"numeric\""],
  ["p","One more corner worth seeing, because it produces a number that looks like data. Removing the missing values from a vector that is entirely missing leaves nothing to work with, and the two summary functions disagree about what to do with nothing."],
  ["code","sum(c(NA, NA), na.rm = TRUE)\nmean(c(NA_real_, NA_real_), na.rm = TRUE)"],
  ["code","[1] 0\n[1] NaN"],
  ["note","That zero is the one to watch. A grouped sum with na.rm = TRUE reports 0 for a group whose every value was missing, and 0 is a perfectly ordinary total that no reader will question. The mean at least reports NaN. If na.rm = TRUE is on anywhere, carry a count of non-missing values alongside the summary so that a group with no data is visible as one."]
]},
{ t: "Implicit missing values",
  body: [
  ["p","Back to the row that was never written. The trick for finding one is to reshape the data so that the gap has somewhere to appear: pivoting to a wider form builds a cell for every combination, and any combination with no row becomes an explicit NA."],
  ["code","pivot_wider(moisture, names_from = week, values_from = reading)"],
  ["code","# A tibble: 3 × 4\n  plot    `1`   `2`   `3`\n  <chr> <dbl> <dbl> <dbl>\n1 A      31.2  NA    28.7\n2 B      26.5  NA    25.1\n3 C      NA    33.4  30.9"],
  ["p","Three NA values in the wide table against two in the long one. The extra one is plot B in week 2 — the row that did not exist. Nothing was added to the data; the shape simply forced the absence into a cell where it could be seen. Column names made from numbers arrive wrapped in backticks, because 1 is not a name R would otherwise accept."],
  ["p","Pivoting back returns nine rows rather than the eight you started with, because the gap is now a real row carrying a real NA."],
  ["code","moisture |>\n  pivot_wider(names_from = week, values_from = reading) |>\n  pivot_longer(cols = c(\"1\", \"2\", \"3\"), names_to = \"week\", values_to = \"reading\")"],
  ["code","# A tibble: 9 × 3\n  plot  week  reading\n  <chr> <chr>   <dbl>\n1 A     1        31.2\n2 A     2        NA  \n3 A     3        28.7\n4 B     1        26.5\n5 B     2        NA  \n6 B     3        25.1\n7 C     1        NA  \n8 C     2        33.4\n9 C     3        30.9"],
  ["p","Note that week came back as a character column, because it spent the round trip as a column name. The reverse switch, values_drop_na, throws the missing rows away instead, which turns every explicit gap back into an implicit one."],
  ["code","moisture |>\n  pivot_wider(names_from = week, values_from = reading) |>\n  pivot_longer(cols = c(\"1\", \"2\", \"3\"), names_to = \"week\", values_to = \"reading\",\n               values_drop_na = TRUE)"],
  ["code","# A tibble: 6 × 3\n  plot  week  reading\n  <chr> <chr>   <dbl>\n1 A     1        31.2\n2 A     3        28.7\n3 B     1        26.5\n4 B     3        25.1\n5 C     2        33.4\n6 C     3        30.9"],
  ["note","Six rows now, down from the original eight, and the two explicitly missing readings are gone as thoroughly as the row that never existed. values_drop_na is convenient for making a table narrow enough to read and destructive if you save the result — the information that a measurement was attempted and failed cannot be recovered from what is left."]
]},
{ t: "Completing the grid",
  body: [
  ["p","Reshaping twice to expose one gap is a lot of work for the answer. complete() from tidyr does it directly: name the columns whose combinations should all exist, and it adds a row for every combination that does not, filling the rest with NA."],
  ["code","complete(moisture, plot, week)"],
  ["code","# A tibble: 9 × 3\n  plot   week reading\n  <chr> <dbl>   <dbl>\n1 A         1    31.2\n2 A         2    NA  \n3 A         3    28.7\n4 B         1    26.5\n5 B         2    NA  \n6 B         3    25.1\n7 C         1    NA  \n8 C         2    33.4\n9 C         3    30.9"],
  ["p","Nine rows, sorted, with plot B week 2 now present and explicitly missing. The two kinds of gap are now the same kind, which is the point: from here a single is.na() finds all three. week stayed numeric this time, because the column was never turned into a name."],
  ["p","A fill argument supplies a value instead of NA, taking a list that names the column. Use it only where zero is genuinely the right reading for an absent row — for counts of events it usually is, and for measurements it usually is not."],
  ["code","complete(moisture, plot, week, fill = list(reading = 0))"],
  ["code","# A tibble: 9 × 3\n  plot   week reading\n  <chr> <dbl>   <dbl>\n1 A         1    31.2\n2 A         2     0  \n3 A         3    28.7\n4 B         1    26.5\n5 B         2     0  \n6 B         3    25.1\n7 C         1     0  \n8 C         2    33.4\n9 C         3    30.9"],
  ["p","complete() only knows about values that appear somewhere in the data. If week 4 is missing for every plot, no combination containing it exists and nothing will be added. full_seq() builds the run of values that should be there, and passing it to complete() covers the case."],
  ["code","full_seq(c(1, 3), 1)\ncomplete(moisture, plot, week = full_seq(week, 1))"],
  ["code","[1] 1 2 3\n# A tibble: 9 × 3\n  plot   week reading\n  <chr> <dbl>   <dbl>\n1 A         1    31.2\n2 A         2    NA  \n3 A         3    28.7\n4 B         1    26.5\n5 B         2    NA  \n6 B         3    25.1\n7 C         1    NA  \n8 C         2    33.4\n9 C         3    30.9"],
  ["note","complete() generates every combination of the columns you name, so the row count is their product. Two columns with 40 and 500 distinct values give 20000 rows, most of them empty, from a table that had a few hundred. Check what the product will be before running it on real data, and complete only the columns whose full grid you actually want."]
]},
{ t: "Missing rows in joins, and empty groups",
  body: [
  ["p","The third way a value goes missing is that it is absent from a table you expected to match against. That is a question about two tables rather than one, and the tools for it are joins. Here is a lookup of who owns each plot."],
  ["code","plot_owner <- tibble(\n  plot = c(\"A\", \"B\", \"D\"),\n  owner = c(\"Reza\", \"Suki\", \"Tomas\")\n)\n\nanti_join(distinct(moisture, plot), plot_owner, by = \"plot\")\nanti_join(plot_owner, distinct(moisture, plot), by = \"plot\")"],
  ["code","# A tibble: 1 × 1\n  plot \n  <chr>\n1 C    \n# A tibble: 1 × 2\n  plot  owner\n  <chr> <chr>\n1 D     Tomas"],
  ["p","anti_join() keeps the rows of the first table with no match in the second, so running it both ways round answers two different questions. Plot C has readings and no owner; plot D has an owner and no readings. Both are worth knowing about and neither shows up as an NA anywhere until you join."],
  ["p","A left join keeps every row of the first table and fills the unmatched ones with NA, which converts the mismatch into the explicit kind of missing."],
  ["code","moisture |>\n  distinct(plot) |>\n  left_join(plot_owner, by = \"plot\")"],
  ["code","# A tibble: 3 × 2\n  plot  owner\n  <chr> <chr>\n1 A     Reza \n2 B     Suki \n3 C     <NA> "],
  ["p","The last case is a group with no rows in it. A factor carries its full vocabulary in its levels, so a level with nothing behind it is a known category with a count of zero rather than a category that does not exist. table() reports it."],
  ["code","soil <- factor(c(\"clay\", \"loam\", \"clay\"), levels = c(\"clay\", \"loam\", \"peat\"))\n\ntable(soil)"],
  ["code","soil\nclay loam peat \n   2    1    0 "],
  ["p","dplyr drops empty groups by default, which loses that zero. Both count() and group_by() take a .drop argument to keep it."],
  ["code","beds <- tibble(soil = soil)\n\ncount(beds, soil)\ncount(beds, soil, .drop = FALSE)"],
  ["code","# A tibble: 2 × 2\n  soil      n\n  <fct> <int>\n1 clay      2\n2 loam      1\n# A tibble: 3 × 2\n  soil      n\n  <fct> <int>\n1 clay      2\n2 loam      1\n3 peat      0"],
  ["p","The first table says nothing about peat, and a reader will take that as peat not being a category. The second says there are no peat beds, which is a fact. group_by() takes the same argument and behaves the same way."],
  ["code","beds |>\n  group_by(soil, .drop = FALSE) |>\n  summarise(n = n(), .groups = \"drop\")"],
  ["code","# A tibble: 3 × 2\n  soil      n\n  <fct> <int>\n1 clay      2\n2 loam      1\n3 peat      0"],
  ["note","A count of zero and an absent row read identically in a chart, because both draw nothing. The difference is what the reader concludes: an absent bar looks like a category nobody thought to measure, and a zero-height bar states that it was measured and found empty. If the column is a factor, .drop = FALSE costs one argument and makes the claim explicit."]
]},
{ t: "Summary",
  body: [
  ["p","Missing values come in two kinds. An explicit one is an NA in a cell that exists, and an implicit one is a row that was never written — invisible to is.na(), to any count of missing values, and to every check that looks at the data as it stands. Most of this chapter is about turning the second kind into the first so that one test finds both."],
  ["p","NA means unknown, so it propagates: NA + 1, NA > 5 and NA == NA are all NA, which is why comparing a column against NA selects nothing instead of failing. is.na() is the real test, sum() over it counts the holes, and which() gives their positions. Summary functions take na.rm = TRUE to drop missing values first, off by default so that a hole in the data shows up in the answer. filter() keeps only TRUE rows, so NA rows are dropped alongside FALSE ones, sort() discards missing values while arrange() parks them last, and sum(x, na.rm = TRUE) over an all-missing vector returns a plausible-looking 0."],
  ["p","fill() carries the last observation forward for data entered only when it changed, with .direction to reverse it — an assumption about data entry that depends on row order, not a repair. na_if() converts a sentinel such as -99 into a real NA, coalesce() takes the first non-missing value across several vectors, and replace_na() substitutes a value inside a data frame. NaN is a separate value from undefined arithmetic that is.na() nonetheless counts as missing."],
  ["p","pivot_wider() exposes an implicit gap by building a cell for every combination, and complete() does it directly by adding a row for every combination that has none, with full_seq() to cover values absent from the data entirely and a fill argument to supply something other than NA. Across two tables, anti_join() run in both directions finds the rows on each side with no match, and left_join() turns a mismatch into an explicit NA. For a factor, count() and group_by() take .drop = FALSE so that a category with no rows is reported as a zero rather than disappearing."],
  ["p","Answer the practice questions from memory before revealing the answers, then clear the graded exercises below. The next chapter is Joins: matching rows between two tables on a key, the difference between the mutating and filtering joins, and what happens when a key matches more rows than you expected."]
]}
],
questions: [
{ q:"What is the difference between an explicit and an implicit missing value?",
  a:"An explicit missing value is an NA in a cell: the row exists and the value is recorded as unknown. An implicit missing value is a row that was never written, so nothing marks its absence. is.na() and any count of missing values find the first kind and are blind to the second, which is why the second is usually caught by checking the row count against the number of combinations you expect." },
{ q:"Why does moisture$reading == NA return a column of NA rather than TRUE where the value is missing?",
  a:"NA means unknown, so any comparison involving it is also unknown — two unknown values might or might not be equal. The result is a column of NA, and because filter() keeps only rows where the condition is TRUE, using it selects no rows at all. It never errors, which is what makes it worth learning once. is.na() is the test that returns TRUE and FALSE." },
{ q:"Why is na.rm off by default in mean() and sum()?",
  a:"Because an NA in the result is R reporting that the data has holes in it. Getting NA back is information; silently computing a mean over whatever happened to be present is not. Passing na.rm = TRUE is a statement that you already know about the missing values and have decided to ignore them." },
{ q:"What does sum(c(NA, NA), na.rm = TRUE) return, and why is that a problem?",
  a:"It returns 0. Removing every value leaves nothing, and the sum of nothing is zero. In a grouped summary that means a group whose every value was missing reports a total of 0, which reads as a real total and will not be questioned. mean() on the same input at least returns NaN. Carry a count of non-missing values next to any summary that uses na.rm." },
{ q:"What does fill() do, and what has to be true for it to be correct?",
  a:"It replaces each missing value with the last non-missing value above it, or below it with .direction = \"up\". It is correct only when the blanks mean the same as the row above — the way people enter data when they record a value only as it changes. It is an assumption, not a repair, and because it works down the rows it gives a different answer after any arrange()." },
{ q:"What is a sentinel value, and which function converts one into a missing value?",
  a:"A number used to mark a missing measurement, such as -99, -999 or 9999. It is dangerous because it is a valid number that every calculation will include, dragging means and totals wherever it points. na_if(x, -99) turns it into a real NA. Convert sentinels when the data is read, before anything else touches the column." },
{ q:"How does pivoting a table wider reveal a missing value that was not visible before?",
  a:"Pivoting wider builds a cell for every combination of the identifiers, so a combination with no row in the long table gets a cell with nothing to put in it and becomes an explicit NA. On the moisture table that takes the count of NA values from two to three: the extra one is plot B in week 2, the row that was never recorded." },
{ q:"What does complete(moisture, plot, week) do, and what is the risk of complete() on real data?",
  a:"It adds a row for every combination of plot and week that does not already exist, filling the other columns with NA, so all three plots have all three weeks and both kinds of missing become the explicit kind. The risk is size: the result has one row per combination, so completing two columns with 40 and 500 distinct values produces 20000 rows. Work out the product before running it." },
{ q:"You have readings for plots A, B and C and an owner table listing A, B and D. Which join answers which rows are unmatched?",
  a:"anti_join(), run in both directions. anti_join(readings, owners) returns plot C, which has readings and no owner; anti_join(owners, readings) returns plot D, which has an owner and no readings. Those are two different questions and one call answers only one of them. A left join instead keeps every row and turns the mismatch into an explicit NA." },
{ q:"A factor has a level with no rows behind it. What do count() and table() each report, and how do you change it?",
  a:"table() reports the level with a count of 0, because a factor carries its full vocabulary in its levels. count() drops it, so the category vanishes from the result entirely. Passing .drop = FALSE to count() or to group_by() keeps it and reports the zero. The distinction matters in a chart, where an absent bar reads as a category nobody measured and a zero bar states that it was measured and found empty." }
],
exercises: [
{ c:"data types", t:"What NA does to arithmetic", book:"r18",
  b:"No packages are needed. Store the values 18, NA, 24, NA and 30, in that order, in a vector named depths. Print five lines: the sum of depths, the sum with missing values removed, the number of missing values it contains, the result of testing whether each value is greater than 20, and the result of testing whether each value is missing.",
  o:"[1] NA\n[1] 72\n[1] 2\n[1] FALSE    NA  TRUE    NA  TRUE\n[1] FALSE  TRUE FALSE  TRUE FALSE",
  h:["Four of the five lines are one function call each. Two of them are the same function with and without one argument.",
     "The argument that drops missing values before summarising is na.rm. Counting missing values is a sum over the test for missingness, because TRUE counts as one. Note that comparing an unknown value against 20 gives an unknown answer, not FALSE.",
     "After building depths with c(), write sum() twice — the second time with na.rm = TRUE — then sum() wrapped around the missingness test, then the comparison against 20 on its own, then the missingness test on its own."]},
{ c:"tidy data", t:"Carry the crew forward", book:"r18",
  b:"Attach tibble with library(tibble) and tidyr with library(tidyr). Build a tibble named shifts with a character column crew holding \"Ada\", NA, NA, \"Bo\", NA and a numeric column bay holding 1, 2, 3, 4, 5, in that order. The blanks mean the same crew as the row above. Replace each missing crew name with the last recorded one above it and print the result.",
  o:"# A tibble: 5 × 2\n  crew    bay\n  <chr> <dbl>\n1 Ada       1\n2 Ada       2\n3 Ada       3\n4 Bo        4\n5 Bo        5",
  h:["One tidyr function does this in a single call, and it takes the column to work on as an ordinary argument.",
     "The operation is last observation carried forward. The function fills downward by default, which is the direction this brief asks for, so no extra argument is needed.",
     "Build the tibble with NA written unquoted among the strings, then call the tidyr function with the tibble first and the bare column name second."]},
{ c:"tidy data", t:"Every hive, every week", book:"r18",
  b:"Attach tibble with library(tibble), tidyr with library(tidyr), and dplyr with suppressMessages(library(dplyr)). Build a tibble named counts with a character column hive holding \"north\", \"north\", \"south\", a numeric column week holding 1, 2, 2, and a numeric column bees holding 120, 135, 98. One hive-week combination has no row at all. Add the missing row so that every hive has one row per week, arrange the result by hive and then week, and print it.",
  o:"# A tibble: 4 × 3\n  hive   week  bees\n  <chr> <dbl> <dbl>\n1 north     1   120\n2 north     2   135\n3 south     1    NA\n4 south     2    98",
  h:["The gap here is a row that was never written, so no amount of testing for missing values will find it. Something has to create the row first.",
     "One tidyr function takes the columns whose combinations should all exist and adds a row for each combination that has none, leaving the remaining columns missing. Do not pass a fill argument — the new reading is genuinely unknown, not zero.",
     "Pipe counts through that function with hive and week named as bare arguments, then through arrange() with both columns."]},
{ c:"data types", t:"Sentinel to missing", book:"r18",
  b:"Attach dplyr with suppressMessages(library(dplyr)). Store the values 7.5, -999, 6.2, -999 and 8.1, in that order, in a vector named rainfall, where -999 is the code the logger writes when a reading failed. Convert every -999 into a genuine missing value and store the result in a variable named clean. Print three lines: clean, the number of missing values in clean, and the mean of clean with missing values removed.",
  o:"[1] 7.5  NA 6.2  NA 8.1\n[1] 2\n[1] 7.266667",
  h:["Taking the mean of rainfall as it stands would give a large negative number, and nothing about it would look wrong. The sentinel has to become a missing value first.",
     "One dplyr function takes a vector and the value to treat as missing, and returns a new vector. Counting the missing values afterwards is a sum over the test for missingness.",
     "Assign the conversion to clean, then write three lines: clean on its own, sum() around the missingness test, and mean() with na.rm = TRUE."]}
]
};
