/* Practice Log book — R Chapter 19: Joins.
   Original lesson text following the chapter-by-chapter curriculum of
   "R for Data Science" (2nd ed.) by Hadley Wickham, Mine Cetinkaya-Rundel,
   and Garrett Grolemund. Read the original chapter free at the src link below.
   Every shown output was captured by executing the code in WebR, not written from memory. */
window.BOOK_R = window.BOOK_R || { chapters: {} };
window.BOOK_R.chapters.r19 = {
n: 19,
title: "Joins",
src: "https://r4ds.hadley.nz/joins.html",
blurb: "Combining two tables through a shared key: the four mutating joins, the two filtering joins, and what happens when a key repeats.",
pkgs: ["dplyr"],
sections: [
{ t: "Two tables and a shared column",
  body: [
  ["p","Real data almost never arrives as one table. It arrives as several, each describing one kind of thing, connected by columns that hold the same values. A table of customers and a table of purchases. A table of stations and a table of readings. Splitting the data this way avoids repeating the same description on every row, and it means a correction has to be made in exactly one place."],
  ["p","The price of that split is that most questions need more than one table at a time. A join is the operation that puts them back together for the length of a single question. dplyr has six, and they divide cleanly into two groups: the four that add columns, and the two that only remove rows."],
  ["p","dplyr is where all six live, so it has to be attached first. The attach notice below is normal and is covered in chapter 3."],
  ["code",'library(dplyr)'],
  ["code","\nAttaching package: ‘dplyr’\n\nThe following objects are masked from ‘package:stats’:\n\n    filter, lag\n\nThe following objects are masked from ‘package:base’:\n\n    intersect, setdiff, setequal, union"],
  ["p","Every example in this chapter uses one pair of tables from a covered market. The first describes the stalls: an identifying number, a name, and the aisle the stall sits in. One row per stall, and nothing about what anyone bought."],
  ["code",'stalls <- tibble(\n  stall_id = c(1L, 2L, 3L, 4L, 5L),\n  stall    = c("Bramble", "Coppice", "Dovecote", "Elm Row", "Fernway"),\n  aisle    = c("A", "A", "B", "B", "C")\n)\n\nstalls'],
  ["code","# A tibble: 5 × 3\n  stall_id stall    aisle\n     <int> <chr>    <chr>\n1        1 Bramble  A    \n2        2 Coppice  A    \n3        3 Dovecote B    \n4        4 Elm Row  B    \n5        5 Fernway  C    "],
  ["p","The second describes wholesale orders: an order number, the stall that placed it, what was ordered, and how many boxes. The stall is recorded as a number, not a name, and that number is the thread connecting the two tables."],
  ["code",'orders <- tibble(\n  order_id = c(101L, 102L, 103L, 104L, 105L, 106L),\n  stall_id = c(2L, 1L, 2L, 4L, 9L, 3L),\n  item     = c("quince", "walnuts", "medlar", "damsons", "sorrel", "chard"),\n  boxes    = c(3L, 1L, 2L, 5L, 4L, 2L)\n)\n\norders'],
  ["code","# A tibble: 6 × 4\n  order_id stall_id item    boxes\n     <int>    <int> <chr>   <int>\n1      101        2 quince      3\n2      102        1 walnuts     1\n3      103        2 medlar      2\n4      104        4 damsons     5\n5      105        9 sorrel      4\n6      106        3 chard       2"],
  ["p","Two things about these six rows are worth noticing before any join happens. Stall 2 placed two orders, so the number 2 appears twice in the orders table. And order 105 was placed by stall 9, which does not appear in the stalls table at all. Both facts will change what a join returns, and both are the kind of thing you find out by joining rather than by reading."],
  ["note","Joins do not promise an order. Every result in this chapter is piped through arrange() before it is printed, and yours should be too — otherwise a result that is correct today can come back in a different order after a dplyr update, and you will spend an afternoon looking for a bug in your own code."]
]},
{ t: "Keys",
  body: [
  ["p","A key is a column, or a set of columns, that identifies a row. There are two kinds and the difference is about which table you are standing in. A primary key identifies a row in its own table: stall_id is the primary key of stalls, order_id is the primary key of orders. A foreign key is a column that points at another table's primary key: stall_id in orders is a foreign key pointing at stalls."],
  ["p","So the same column name can be a primary key in one table and a foreign key in another. That is the normal case, and it is what makes the pair joinable."],
  ["p","A primary key has to be unique, and believing it is unique without checking is one of the reliable ways to get a wrong answer. Count the rows per value and keep only the counts above one. An empty result means the column really does identify a row."],
  ["code",'stalls |> count(stall_id) |> filter(n > 1)\norders |> count(order_id) |> filter(n > 1)'],
  ["code","# A tibble: 0 × 2\n# ℹ 2 variables: stall_id <int>, n <int>\n# A tibble: 0 × 2\n# ℹ 2 variables: order_id <int>, n <int>"],
  ["p","Zero rows twice, so both columns are genuine primary keys. A tibble with no rows still prints its column names, on the ℹ line, because there is no room for them above a table with nothing in it."],
  ["p","Run the same check on a column that is not a key and the difference is obvious. Aisle looks like a label of the stall, and it is, but several stalls share an aisle."],
  ["code",'stalls |> count(aisle)'],
  ["code","# A tibble: 3 × 2\n  aisle     n\n  <chr> <int>\n1 A         2\n2 B         2\n3 C         1"],
  ["p","The other check worth doing early is on the foreign key: does every value in it exist in the other table. setdiff() answers that in one line, by asking which stall numbers appear in orders and nowhere in stalls."],
  ["code",'setdiff(orders$stall_id, stalls$stall_id)'],
  ["code","[1] 9"],
  ["p","Stall 9 is a dangling reference. Either the stalls table is missing a row or the orders table has a typo in it, and no join can tell you which. What a join can do is make the consequence visible instead of silent, which is what the rest of this chapter is about."],
  ["p","When a table has no column that identifies a row, you invent one. A column of row numbers added purely to serve as a key is called a surrogate key, and it is a perfectly respectable thing to do — order_id here is almost certainly one, since nothing about an order is naturally called 101. Note that mutate(row_number()) has to be added before any filtering, because renumbering a table you have already cut leaves the numbers pointing at the wrong rows."],
  ["note","The mistake to expect is treating a name as a key. Stall names look unique here, and two stalls in a market can be called Fernway. Numbers are used as keys precisely because nobody is tempted to reuse them, edit their spelling, or write them with a different capital letter."]
]},
{ t: "Mutating joins",
  body: [
  ["p","A mutating join adds columns. It takes two tables, matches rows by key, and returns the first table with the second table's columns attached. The four of them differ in one respect only: which unmatched rows survive."],
  ["p","left_join() is the one to reach for by default. Every row of the left table comes back, whether or not it found a match, and the added columns are NA where nothing matched. Called with no key at all, dplyr guesses: it uses every column name the two tables share, and tells you what it decided."],
  ["code",'orders |> left_join(stalls) |> arrange(order_id)'],
  ["code","Joining with `by = join_by(stall_id)`\n# A tibble: 6 × 6\n  order_id stall_id item    boxes stall    aisle\n     <int>    <int> <chr>   <int> <chr>    <chr>\n1      101        2 quince      3 Coppice  A    \n2      102        1 walnuts     1 Bramble  A    \n3      103        2 medlar      2 Coppice  A    \n4      104        4 damsons     5 Elm Row  B    \n5      105        9 sorrel      4 <NA>     <NA> \n6      106        3 chard       2 Dovecote B    "],
  ["p","That first line is a message, not a warning and not an error. dplyr found one shared column name, joined on it, and printed the join_by() call it worked out so that you can check it. Order 105 came back with NA in both added columns, because stall 9 has no row to attach."],
  ["p","Write the key out yourself and the message goes away, because there is nothing left to guess."],
  ["code",'orders |> left_join(stalls, join_by(stall_id)) |> arrange(order_id)'],
  ["code","# A tibble: 6 × 6\n  order_id stall_id item    boxes stall    aisle\n     <int>    <int> <chr>   <int> <chr>    <chr>\n1      101        2 quince      3 Coppice  A    \n2      102        1 walnuts     1 Bramble  A    \n3      103        2 medlar      2 Coppice  A    \n4      104        4 damsons     5 Elm Row  B    \n5      105        9 sorrel      4 <NA>     <NA> \n6      106        3 chard       2 Dovecote B    "],
  ["p","Identical result, no message. Every join from here on names its key, and the reason is worth stating plainly: the guess is made from column names, which change. Add a column called date to both tables next month and the guessed join silently becomes a join on stall and date together, returning fewer rows, with nothing marking the day it changed. An explicit join_by() cannot drift like that."],
  ["p","inner_join() keeps only the rows that matched on both sides. Order 105 is gone, and so is the evidence that it existed."],
  ["code",'orders |> inner_join(stalls, join_by(stall_id)) |> arrange(order_id)'],
  ["code","# A tibble: 5 × 6\n  order_id stall_id item    boxes stall    aisle\n     <int>    <int> <chr>   <int> <chr>    <chr>\n1      101        2 quince      3 Coppice  A    \n2      102        1 walnuts     1 Bramble  A    \n3      103        2 medlar      2 Coppice  A    \n4      104        4 damsons     5 Elm Row  B    \n5      106        3 chard       2 Dovecote B    "],
  ["p","right_join() keeps every row of the right table instead. Fernway placed no orders, so it appears with NA in every column that came from orders — including order_id, which is why the last row sorts to the bottom."],
  ["code",'orders |> right_join(stalls, join_by(stall_id)) |> arrange(order_id)'],
  ["code","# A tibble: 6 × 6\n  order_id stall_id item    boxes stall    aisle\n     <int>    <int> <chr>   <int> <chr>    <chr>\n1      101        2 quince      3 Coppice  A    \n2      102        1 walnuts     1 Bramble  A    \n3      103        2 medlar      2 Coppice  A    \n4      104        4 damsons     5 Elm Row  B    \n5      106        3 chard       2 Dovecote B    \n6       NA        5 <NA>       NA Fernway  C    "],
  ["p","full_join() keeps everything from both sides. Seven rows: five that matched, the orphan order, and the stall with no orders."],
  ["code",'orders |> full_join(stalls, join_by(stall_id)) |> arrange(order_id)'],
  ["code","# A tibble: 7 × 6\n  order_id stall_id item    boxes stall    aisle\n     <int>    <int> <chr>   <int> <chr>    <chr>\n1      101        2 quince      3 Coppice  A    \n2      102        1 walnuts     1 Bramble  A    \n3      103        2 medlar      2 Coppice  A    \n4      104        4 damsons     5 Elm Row  B    \n5      105        9 sorrel      4 <NA>     <NA> \n6      106        3 chard       2 Dovecote B    \n7       NA        5 <NA>       NA Fernway  C    "],
  ["p","Lined up, the row counts are the whole lesson. The left table has six rows; the inner join has five; the full join has seven."],
  ["code",'nrow(orders)\nnrow(inner_join(orders, stalls, join_by(stall_id)))\nnrow(full_join(orders, stalls, join_by(stall_id)))'],
  ["code","[1] 6\n[1] 5\n[1] 7"],
  ["note","inner_join() dropping a row is the quietest bug in this chapter. Nothing is printed, no NA appears, and the total at the bottom of your report is simply too small. If a join returns fewer rows than the table you started with, that is a finding about your data and it deserves a look before you carry on. left_join() turns the same problem into visible NA values, which is why it is the safer default."]
]},
{ t: "Filtering joins",
  body: [
  ["p","A filtering join never adds a column. It uses the second table only as a test, and returns rows of the first table unchanged. There are two, and between them they answer every question of the form which of these have a match."],
  ["p","semi_join() keeps the rows of the left table that do have a match. Note the column count: four in, four out."],
  ["code",'orders |> semi_join(stalls, join_by(stall_id)) |> arrange(order_id)'],
  ["code","# A tibble: 5 × 4\n  order_id stall_id item    boxes\n     <int>    <int> <chr>   <int>\n1      101        2 quince      3\n2      102        1 walnuts     1\n3      103        2 medlar      2\n4      104        4 damsons     5\n5      106        3 chard       2"],
  ["p","anti_join() keeps the rows that have no match, which makes it the fastest data-quality check in dplyr. Run it in the direction that names the problem: orders with no stall."],
  ["code",'orders |> anti_join(stalls, join_by(stall_id)) |> arrange(order_id)'],
  ["code","# A tibble: 1 × 4\n  order_id stall_id item   boxes\n     <int>    <int> <chr>  <int>\n1      105        9 sorrel     4"],
  ["p","There is the dangling reference from section 2, this time with the whole row attached rather than just the number 9. Turn the two tables around and the same function answers the opposite question: stalls that placed no orders."],
  ["code",'stalls |> anti_join(orders, join_by(stall_id)) |> arrange(stall_id)'],
  ["code","# A tibble: 1 × 3\n  stall_id stall   aisle\n     <int> <chr>   <chr>\n1        5 Fernway C    "],
  ["p","Both directions are worth running on any new pair of tables, before any analysis. They take one line each and they tell you whether the join you are about to write is going to lose anything."],
  ["note","The two filtering joins are not symmetric, and swapping the arguments is not the same as swapping the function. anti_join(orders, stalls, ...) finds orphan orders; anti_join(stalls, orders, ...) finds unused stalls. Both returned exactly one row here, and they are entirely different findings. Read the first argument as the table you are keeping rows from."]
]},
{ t: "Naming the join columns",
  body: [
  ["p","join_by() is a small language for describing how rows correspond. A bare column name means that column has to be equal in both tables, which is why join_by(stall_id) has done all the work so far."],
  ["p","When the two tables call the key different things, write the equality out. The left table's column goes on the left of the ==."],
  ["code",'leases <- tibble(\n  stall_no = c(1L, 2L, 3L, 4L, 5L),\n  rent     = c(120, 95, 140, 110, 80)\n)\n\nstalls |> left_join(leases, join_by(stall_id == stall_no)) |> arrange(stall_id)'],
  ["code","# A tibble: 5 × 4\n  stall_id stall    aisle  rent\n     <int> <chr>    <chr> <dbl>\n1        1 Bramble  A       120\n2        2 Coppice  A        95\n3        3 Dovecote B       140\n4        4 Elm Row  B       110\n5        5 Fernway  C        80"],
  ["p","Only stall_id survives into the result. The right table's key column is dropped once it has been used, because it holds the same values under a different name."],
  ["p","The awkward case is a column the two tables share that is not part of the key. Here is a clipboard record of which aisle each stall was noted in, covering three stalls, with one of them recorded wrongly."],
  ["code",'checks <- tibble(\n  stall_id = c(1L, 3L, 5L),\n  aisle    = c("A", "B", "D")\n)\n\nstalls |> left_join(checks, join_by(stall_id)) |> arrange(stall_id)'],
  ["code","# A tibble: 5 × 4\n  stall_id stall    aisle.x aisle.y\n     <int> <chr>    <chr>   <chr>  \n1        1 Bramble  A       A      \n2        2 Coppice  A       <NA>   \n3        3 Dovecote B       B      \n4        4 Elm Row  B       <NA>   \n5        5 Fernway  C       D      "],
  ["p","Both aisle columns came through, renamed. dplyr cannot keep two columns with one name, so it appends .x to the left one and .y to the right one. The result is correct and unreadable, and three lines later you will have forgotten which was which. Fernway is the disagreement: aisle C on the plan, aisle D on the clipboard."],
  ["p","suffix takes a pair of strings and replaces the defaults with something you can read."],
  ["code",'stalls |> left_join(checks, join_by(stall_id), suffix = c("_plan", "_noted")) |> arrange(stall_id)'],
  ["code","# A tibble: 5 × 4\n  stall_id stall    aisle_plan aisle_noted\n     <int> <chr>    <chr>      <chr>      \n1        1 Bramble  A          A          \n2        2 Coppice  A          <NA>       \n3        3 Dovecote B          B          \n4        4 Elm Row  B          <NA>       \n5        5 Fernway  C          D          "],
  ["p","A key can also be more than one column: join_by(stall_id, week) matches rows only where both agree. Older dplyr code writes the key as a string or a named vector — by = \"stall_id\", or by = c(\"stall_id\" = \"stall_no\") — and that form still runs. join_by() replaced it because it can express far more than equality, which is section 7."],
  ["note","Seeing .x and .y in a result means two columns collided, and it is worth stopping to ask whether you meant to join on that column as well. A join on stall_id alone, where both tables also carry a week column, quietly produces week.x and week.y and a row for every combination of weeks. The suffixes are the symptom; the missing key is the disease."]
]},
{ t: "How rows are matched",
  body: [
  ["p","A join compares every row of the left table with every row of the right, keeps the pairs where the key condition holds, and returns one output row per surviving pair. That sentence explains every row count in this chapter, including the ones that surprise people."],
  ["p","So far every key value appeared at most once in stalls, and the arithmetic was dull. Here is a table where it does not: monthly satisfaction scores, with stall 2 scored in two different months."],
  ["code",'ratings <- tibble(\n  stall_id = c(1L, 2L, 2L, 3L),\n  month    = c("may", "may", "june", "june"),\n  score    = c(4.5, 3.8, 4.1, 4.9)\n)\n\nratings'],
  ["code","# A tibble: 4 × 3\n  stall_id month score\n     <int> <chr> <dbl>\n1        1 may     4.5\n2        2 may     3.8\n3        2 june    4.1\n4        3 june    4.9"],
  ["p","Join the orders to it and six rows become eight. Stall 2 placed two orders and has two ratings, so each of those orders matches twice."],
  ["code",'orders |> left_join(ratings, join_by(stall_id)) |> arrange(order_id, month)'],
  ["code","Warning in left_join(orders, ratings, join_by(stall_id)) :\n  Detected an unexpected many-to-many relationship between `x` and `y`.\nℹ Row 1 of `x` matches multiple rows in `y`.\nℹ Row 2 of `y` matches multiple rows in `x`.\nℹ If a many-to-many relationship is expected, set `relationship =\n  \"many-to-many\"` to silence this warning.\n# A tibble: 8 × 6\n  order_id stall_id item    boxes month score\n     <int>    <int> <chr>   <int> <chr> <dbl>\n1      101        2 quince      3 june    4.1\n2      101        2 quince      3 may     3.8\n3      102        1 walnuts     1 may     4.5\n4      103        2 medlar      2 june    4.1\n5      103        2 medlar      2 may     3.8\n6      104        4 damsons     5 <NA>   NA  \n7      105        9 sorrel      4 <NA>   NA  \n8      106        3 chard       2 june    4.9"],
  ["p","Order 101 appears twice, once against each of stall 2's ratings, and so does order 103. dplyr noticed and warned, because a key repeating on both sides is more often an accident than a plan. The row count now depends on the ratings table, which means summing boxes over this result would double-count every order stall 2 placed."],
  ["p","The relationship argument turns that assumption into something the code states. Set it to what you expect, and dplyr checks rather than guesses. Claim each order matches at most one rating and the join stops."],
  ["code",'orders |> left_join(ratings, join_by(stall_id), relationship = "many-to-one")'],
  ["code","Error: Each row in `x` must match at most 1 row in `y`."],
  ["p","That error is the useful outcome. It arrives at the join instead of three steps later in a total that is too large, and it names the side of the join that broke the promise. When the multiplication genuinely is what you want, say so and the warning goes."],
  ["code",'orders |> left_join(ratings, join_by(stall_id), relationship = "many-to-many") |> arrange(order_id, month)'],
  ["code","# A tibble: 8 × 6\n  order_id stall_id item    boxes month score\n     <int>    <int> <chr>   <int> <chr> <dbl>\n1      101        2 quince      3 june    4.1\n2      101        2 quince      3 may     3.8\n3      102        1 walnuts     1 may     4.5\n4      103        2 medlar      2 june    4.1\n5      103        2 medlar      2 may     3.8\n6      104        4 damsons     5 <NA>   NA  \n7      105        9 sorrel      4 <NA>   NA  \n8      106        3 chard       2 june    4.9"],
  ["p","Same eight rows, no warning, and now the code records that the multiplication was intended. The other accepted values are \"one-to-one\" and \"one-to-many\", and adding one to a join you rely on is cheap insurance."],
  ["note","The warning is easy to lose, because the table prints anyway and looks perfectly reasonable. Nothing about eight rows of orders and scores says the total is wrong. Treat an unexpected many-to-many warning as a stop sign: either the key is incomplete — joining on stall_id and month together would give one rating per order — or you are about to sum a column that has been duplicated."]
]},
{ t: "Non-equi joins",
  body: [
  ["p","Everything so far matched rows by equality. join_by() also understands comparisons, and that opens up questions equality cannot ask — which band a value falls into, which event came most recently before another. These are non-equi joins, and they are the reason join_by() exists as a function rather than a string."],
  ["p","between() matches when a value from the left table lies inside a pair of bounds in the right table. Here the bands are order sizes."],
  ["code",'tiers <- tibble(\n  tier = c("small", "medium", "large"),\n  lo   = c(1L, 3L, 5L),\n  hi   = c(2L, 4L, 9L)\n)\n\norders |> inner_join(tiers, join_by(between(boxes, lo, hi))) |> arrange(order_id)'],
  ["code","# A tibble: 6 × 7\n  order_id stall_id item    boxes tier      lo    hi\n     <int>    <int> <chr>   <int> <chr>  <int> <int>\n1      101        2 quince      3 medium     3     4\n2      102        1 walnuts     1 small      1     2\n3      103        2 medlar      2 small      1     2\n4      104        4 damsons     5 large      5     9\n5      105        9 sorrel      4 medium     3     4\n6      106        3 chard       2 small      1     2"],
  ["p","Six rows in, six rows out, because the bands do not overlap and every order falls in exactly one. Bands that overlap would multiply rows the same way a repeated key does, and bands with a gap would drop rows — an inner join keeps nothing that failed to match, so an order of 12 boxes would vanish here without comment."],
  ["p","cross_join() matches every row with every row, no condition at all. It is how you build the full set of combinations, and the result is as large as the two inputs multiplied."],
  ["code",'days <- tibble(day = c("fri", "sat"))\n\nstalls |> distinct(aisle) |> cross_join(days) |> arrange(aisle, day)'],
  ["code","# A tibble: 6 × 2\n  aisle day  \n  <chr> <chr>\n1 A     fri  \n2 A     sat  \n3 B     fri  \n4 B     sat  \n5 C     fri  \n6 C     sat  "],
  ["p","Three aisles and two days give six rows. That growth is the thing to respect: a cross join of two thousand-row tables is a million rows, and nothing warns you first."],
  ["p","An inequality on its own matches every row that satisfies it, which is usually more rows than you wanted. Below, each pick is matched to every restock that happened on or before its day."],
  ["code",'picks <- tibble(\n  order_id = c(101L, 103L, 104L),\n  day      = c(4L, 9L, 15L)\n)\n\nrestocks <- tibble(\n  day   = c(1L, 7L, 12L),\n  crate = c("K1", "K2", "K3")\n)\n\npicks |> left_join(restocks, join_by(day >= day)) |> arrange(order_id, day.y)'],
  ["code","# A tibble: 6 × 4\n  order_id day.x day.y crate\n     <int> <int> <int> <chr>\n1      101     4     1 K1   \n2      103     9     1 K1   \n3      103     9     7 K2   \n4      104    15     1 K1   \n5      104    15     7 K2   \n6      104    15    12 K3   "],
  ["p","Three picks became six rows, and both tables have a column called day, so the suffixes from section 5 appear. Usually the question is not every earlier restock but the most recent one. closest() wraps the inequality and keeps only the nearest match."],
  ["code",'picks |> left_join(restocks, join_by(closest(day >= day))) |> arrange(order_id)'],
  ["code","# A tibble: 3 × 4\n  order_id day.x day.y crate\n     <int> <int> <int> <chr>\n1      101     4     1 K1   \n2      103     9     7 K2   \n3      104    15    12 K3   "],
  ["p","Three picks, three rows, each carrying the crate that was last put out before it. That pattern — join to the most recent earlier event — is called a rolling join, and it comes up constantly with anything timestamped: the price in force when an order was placed, the rate in force when a payment cleared."],
  ["note","In join_by(day >= day) the left name and the right name are positional, not literal: the first is the left table's column and the second is the right table's, even though they are spelled the same. Reading it as a comparison of one column with itself is the mistake, and the result looks plausible enough to survive review. When both tables use the same column name, rename one before joining and the code stops needing that explanation."]
]},
{ t: "Summary",
  body: [
  ["p","A join combines two tables through a key. A primary key identifies a row in its own table, a foreign key points at another table's primary key, and both are worth checking before you rely on them: count() the values and keep the counts above one to confirm uniqueness, and setdiff() the foreign key against the primary key to find references that lead nowhere."],
  ["p","Four mutating joins add the right table's columns to the left table's rows, differing only in which unmatched rows survive. left_join() keeps every left row and fills NA, inner_join() keeps only matched pairs, right_join() keeps every right row, and full_join() keeps everything. Two filtering joins add nothing and only remove rows: semi_join() keeps the left rows that matched, anti_join() keeps the ones that did not, and running anti_join() in both directions is the quickest health check on any new pair of tables."],
  ["p","Name the key with join_by() rather than letting dplyr guess from shared column names, because guesses drift when columns are added. join_by(a == b) handles keys named differently, suffix renames non-key columns that collide, and join_by() also accepts comparisons: between() for banding, a bare inequality for every earlier match, closest() for the most recent one, and cross_join() for every combination. Matching is pair by pair, so a key repeating on both sides multiplies rows; state what you expect with relationship and let dplyr enforce it. Sort with arrange() before you print, because no join guarantees an order."],
  ["p","Answer the practice questions from memory before revealing the answers, then clear the graded exercises below. The next chapter is spreadsheets: reading data out of Excel workbooks and Google Sheets, where the rectangle you get is rarely the rectangle you wanted."]
]}
],
questions: [
{ q:"What is the difference between a primary key and a foreign key, and can one column be both?",
  a:"A primary key identifies a row in its own table; a foreign key is a column that points at another table's primary key. stall_id is the primary key of stalls and a foreign key in orders, so the same column name is both — which is exactly what makes the two tables joinable." },
{ q:"How do you check that stall_id really is a primary key of stalls?",
  a:"Count the rows per value and keep the counts above one: stalls |> count(stall_id) |> filter(n > 1). An empty result confirms uniqueness. Running the same check on aisle returns three rows with counts 2, 2 and 1, so aisle is not a key." },
{ q:"orders |> left_join(stalls) prints a line before the table. What is that line, and why should you make it stop appearing?",
  a:"Joining with `by = join_by(stall_id)` — a message telling you which columns dplyr guessed, because none were named. Write join_by(stall_id) yourself instead: the guess is made from shared column names, so adding a column to both tables later would silently change the join without changing your code." },
{ q:"orders has 6 rows and stalls has 5. How many rows come back from an inner join, and how many from a full join?",
  a:"Five and seven. The inner join drops order 105, whose stall_id of 9 has no matching stall. The full join keeps that orphan order and also keeps Fernway, the stall that placed no orders, giving five matched rows plus one on each side." },
{ q:"Which join would you use to attach stall names to orders without losing any orders, and what appears where a stall is missing?",
  a:"left_join(), with orders on the left. Every order comes back, and the added columns are NA for order 105 because stall 9 does not exist in stalls. inner_join() would answer the same question by quietly deleting that row." },
{ q:"What does semi_join() return that anti_join() does not, and how many columns does either add?",
  a:"semi_join() returns the left rows that have a match; anti_join() returns the left rows that have none. Neither adds a column — orders goes in with four columns and comes out with four, because a filtering join uses the second table only as a test." },
{ q:"You want to find stalls that placed no orders. Which call does it, and what would swapping the arguments find instead?",
  a:"stalls |> anti_join(orders, join_by(stall_id)), which returns Fernway. Swapped, orders |> anti_join(stalls, join_by(stall_id)) returns order 105 — the orphan order. Same function, opposite question; the first argument is the table you keep rows from." },
{ q:"A join result contains columns called aisle.x and aisle.y. What happened, and what are the two ways to respond?",
  a:"Both tables had a column named aisle that was not part of the key, so dplyr renamed them rather than lose one. Either set suffix = c(\"_plan\", \"_noted\") to make the names readable, or ask whether aisle should have been part of the key — colliding names often mean a key column was left out." },
{ q:"Joining orders to ratings turns 6 rows into 8 and produces a warning. Explain the arithmetic, and say what relationship = \"many-to-one\" would do.",
  a:"A join returns one row per matching pair. Stall 2 placed two orders and has two ratings, so each of those orders matches twice, adding two rows. relationship = \"many-to-one\" would stop the join with Error: Each row in `x` must match at most 1 row in `y`, catching the multiplication at the join instead of in a later total." },
{ q:"What does closest() do inside join_by(), and why is a bare inequality usually the wrong tool?",
  a:"closest(day >= day) keeps only the nearest matching row rather than all of them, so three picks return three rows instead of six. A bare inequality matches every row that satisfies it — every earlier restock, not just the last one — which is rarely the question and grows quickly with the size of the tables." }
],
exercises: [
{ c:"joins", t:"Attach the depot to each van", book:"r19",
  b:"Attach dplyr inside suppressPackageStartupMessages() so the attach notice stays out of your output. Build a tibble named depots with an integer column depot_id holding 1, 2, 3 and a character column city holding \"Lund\", \"Malmo\", \"Ystad\". Build a tibble named vans with an integer column van_id holding 7, 8, 9, 10, an integer column depot_id holding 2, 1, 3, 2, and an integer column seats holding 3, 2, 3, 5. Add each van's city by joining so that every van survives, name the key explicitly so no Joining message appears, then sort by van_id and print.",
  o:"# A tibble: 4 × 4\n  van_id depot_id seats city \n   <int>    <int> <int> <chr>\n1      7        2     3 Malmo\n2      8        1     2 Lund \n3      9        3     3 Ystad\n4     10        2     5 Malmo",
  h:["Keeping every row of the first table is what one particular mutating join promises. Four vans go in, four come out.",
     "Name the key with join_by() as the argument after the second table, or dplyr will guess and print a message. Whole numbers need the L suffix — 1L, not 1 — so the printed types read <int>.",
     "Build both tibbles, pipe vans into the join with depots and a join_by() naming the shared key, then pipe that into arrange() on the van column. Depot 2 is used twice, which is fine: repetition on the right side is what would multiply rows, not repetition on the left."]},
{ c:"joins", t:"Members who have not paid", book:"r19",
  b:"Attach dplyr inside suppressPackageStartupMessages(). Build a tibble named members with an integer column member_id holding 11, 12, 13, 14 and a character column name holding \"Ada\", \"Bo\", \"Cleo\", \"Dov\". Build a tibble named payments with a character column ref holding \"P1\", \"P2\", \"P3\" and an integer column member_id holding 12, 14, 12. Return the members with no payment at all, keeping the members columns unchanged, sorted by member_id.",
  o:"# A tibble: 2 × 2\n  member_id name \n      <int> <chr>\n1        11 Ada  \n2        13 Cleo ",
  h:["This is a filtering join: the payments table is only being used as a test, and no column from it should appear in the answer.",
     "One of the two filtering joins keeps rows that matched and the other keeps rows that did not. You want the second. The table you keep rows from goes first.",
     "Pipe members into that join with payments and join_by(member_id), then arrange by member_id. Member 12 appears twice in payments and that changes nothing here, because a filtering join asks only whether a match exists."]},
{ c:"joins", t:"Cost of every pick that matched", book:"r19",
  b:"Attach dplyr inside suppressPackageStartupMessages(). Build a tibble named parts with a character column part_id holding \"A1\", \"A2\", \"A3\" and a double column price holding 2.5, 4, 1.25. Build a tibble named picks with an integer column pick_id holding 1, 2, 3, 4, a character column part_id holding \"A2\", \"A1\", \"A9\", \"A2\", and an integer column qty holding 3, 2, 1, 5. Keep only the picks whose part exists in parts, add a column cost holding price times qty, then keep just pick_id, part_id and cost, sorted by pick_id.",
  o:"# A tibble: 3 × 3\n  pick_id part_id  cost\n    <int> <chr>   <dbl>\n1       1 A2         12\n2       2 A1          5\n3       4 A2         20",
  h:["Dropping the unmatched pick is the join's job, not a filter's. One of the four mutating joins keeps only rows that matched on both sides.",
     "You need price in the table before you can multiply by it, so the join has to come first, then mutate(), then select(). Part A9 exists in no row of parts, so pick 3 disappears at the join.",
     "The order is join, then mutate a new column from the two you now have side by side, then select the three columns asked for, then arrange. Name the key with join_by() rather than leaving it to be guessed."]},
{ c:"grouping & summaries", t:"Kilos per zone", book:"r19",
  b:"Attach dplyr inside suppressPackageStartupMessages(). Build a tibble named plots with an integer column plot_id holding 1, 2, 3 and a character column zone holding \"north\", \"north\", \"south\". Build a tibble named hauls with an integer column haul_id holding 1, 2, 3, 4, 5, an integer column plot_id holding 1, 1, 2, 3, 3, and a double column kg holding 4, 6, 2, 5, 3. Attach each haul's zone, then report the total kg per zone in a column named total_kg, sorted by zone.",
  o:"# A tibble: 2 × 2\n  zone  total_kg\n  <chr>    <dbl>\n1 north       12\n2 south        8",
  h:["The zone lives in the other table, so it has to be joined on before anything can be grouped by it.",
     "Join hauls to plots on plot_id keeping every haul, then group_by() the zone column and summarise() the sum. Grouping by a single column leaves an ungrouped result, so no regroup message appears.",
     "Four steps piped together: the join with join_by(plot_id), group_by on zone, summarise with total_kg = sum(...), then arrange. Plot 1 supplies two hauls and plot 3 supplies two, which is why north totals more than the two rows it looks like."]}
]
};
