/* Practice Log book — R Chapter 20: Spreadsheets.
   Original lesson text following the chapter-by-chapter curriculum of
   "R for Data Science" (2nd ed.) by Hadley Wickham, Mine Cetinkaya-Rundel,
   and Garrett Grolemund. Read the original chapter free at the src link below.
   Every shown output was captured by executing the code in WebR, not written from memory. */
window.BOOK_R = window.BOOK_R || { chapters: {} };
window.BOOK_R.chapters.r20 = {
n: 20,
title: "Spreadsheets",
src: "https://r4ds.hadley.nz/spreadsheets.html",
blurb: "Reading .xlsx files into tibbles with readxl and writing them back with writexl — sheets, ranges, and the column types a spreadsheet quietly gets wrong.",
pkgs: ["readxl", "writexl", "tibble", "dplyr"],
sections: [
{ t: "Spreadsheets, and the packages that read them",
  body: [
  ["p","Most data that reaches you from someone else's desk arrives as a spreadsheet. An .xlsx file is not a rectangle of values the way a CSV is; it is a small archive holding one or more sheets, and inside each sheet every single cell carries its own type, its own formatting, and possibly a formula. A CSV has none of that, which is why reading one is a matter of splitting on commas and reading a spreadsheet is a matter of asking a library."],
  ["p","Two packages do the work here. readxl reads .xlsx and .xls files into tibbles, and it has no outside dependencies — no Excel, no Java, no system libraries. writexl goes the other way, turning a data frame into an .xlsx file. Both are deliberately small: they move values, and they leave the decoration alone."],
  ["p","Everything in the first six sections of this chapter runs in this app for real. The outputs below were captured from actual runs, files and all, in the browser's in-memory filesystem. Section 7 is the exception, and it says so where it starts."],
  ["code","library(readxl)\nlibrary(writexl)\nlibrary(tibble)\nsuppressMessages(library(dplyr))"],
  ["note","Attaching dplyr prints a banner about masked functions. It is information, not a problem, but it lands in the transcript this app grades, so every block here wraps that one call in suppressMessages(). The other three packages attach silently."]
]},
{ t: "Making a workbook, then reading it back",
  body: [
  ["p","A chapter about reading spreadsheets has an awkward first step: there is no spreadsheet to read. On a desktop you would point readxl at a file someone sent you. Here the file has to exist before it can be read, so the chapter writes one first — which has the side benefit of showing writexl before you need it."],
  ["p","The running example is a fruit packhouse. Five crates, each with a count of apples and the grower who supplied them. write_xlsx() takes a data frame and a filename, writes the file, and returns nothing visible, so file.exists() is how you confirm it landed."],
  ["code","orders <- tibble(\n  crate = c(\"A-11\", \"A-12\", \"B-04\", \"B-07\", \"C-01\"),\n  apples = c(120, 84, 96, 150, 62),\n  grower = c(\"Halloran\", \"Iyer\", \"Halloran\", \"Nkemdi\", \"Iyer\")\n)\n\nwrite_xlsx(orders, \"packhouse.xlsx\")\nfile.exists(\"packhouse.xlsx\")"],
  ["code","[1] TRUE"],
  ["p","Before reading a workbook, find out what is in it. excel_sheets() takes a path and returns the sheet names as a character vector, in the order the tabs appear. writexl named this one Sheet1, because it was handed a bare data frame with no name attached."],
  ["code","excel_sheets(\"packhouse.xlsx\")"],
  ["code","[1] \"Sheet1\""],
  ["p","read_excel() is the function that does the reading. Given only a path it takes the first sheet, treats the first row as column names, and guesses a type for each column from the cells it finds."],
  ["code","read_excel(\"packhouse.xlsx\")"],
  ["code","# A tibble: 5 × 3\n  crate apples grower  \n  <chr>  <dbl> <chr>   \n1 A-11     120 Halloran\n2 A-12      84 Iyer    \n3 B-04      96 Halloran\n4 B-07     150 Nkemdi  \n5 C-01      62 Iyer    "],
  ["p","What comes back is an ordinary tibble. That is the whole point of readxl: the spreadsheet stops being a spreadsheet at the moment it is read, and everything you learned about dplyr and ggplot2 applies to it unchanged. The type row under the column names is the first thing to check, because it is the first thing that goes wrong."],
  ["code","back <- read_excel(\"packhouse.xlsx\")\n\nclass(back)\nclass(back$apples)"],
  ["code","[1] \"tbl_df\"     \"tbl\"        \"data.frame\"\n[1] \"numeric\""],
  ["p","A path that does not exist stops the read immediately, and the message names the path it looked for. That is worth reading rather than skimming, because the usual cause is a working directory you were not thinking about rather than a filename you typed wrong."],
  ["code","read_excel(\"nosuch.xlsx\")"],
  ["code","Error: `path` does not exist: ‘nosuch.xlsx’"],
  ["note","In this app the file is written into the browser's own in-memory filesystem, not into a folder on your device. file.exists() finds it, read_excel() reads it, and it is gone the moment the page reloads. On a desktop the same two calls write into and read from your working directory, which is where getwd() points."]
]},
{ t: "More than one sheet",
  body: [
  ["p","A real workbook usually has several tabs. To write one, hand write_xlsx() a named list of data frames instead of a single data frame: each element becomes a sheet, and the name on the element becomes the name on the tab."],
  ["code","write_xlsx(\n  list(\n    Orders = orders,\n    Growers = tibble(\n      grower = c(\"Halloran\", \"Iyer\", \"Nkemdi\"),\n      county = c(\"Kerry\", \"Clare\", \"Mayo\")\n    )\n  ),\n  \"season.xlsx\"\n)\n\nexcel_sheets(\"season.xlsx\")"],
  ["code","[1] \"Orders\"  \"Growers\""],
  ["p","read_excel() reads one sheet per call, and the sheet argument picks which. The readable form is the tab's name as a string."],
  ["code","read_excel(\"season.xlsx\", sheet = \"Growers\")"],
  ["code","# A tibble: 3 × 2\n  grower   county\n  <chr>    <chr> \n1 Halloran Kerry \n2 Iyer     Clare \n3 Nkemdi   Mayo  "],
  ["p","A number works too, counting tabs from the left. It is shorter, and it is the form to reach for when a loop is choosing the sheet. It is also the form that breaks silently when somebody reorders the tabs, so prefer the name whenever a person wrote the code."],
  ["code","read_excel(\"season.xlsx\", sheet = 2)"],
  ["code","# A tibble: 3 × 2\n  grower   county\n  <chr>    <chr> \n1 Halloran Kerry \n2 Iyer     Clare \n3 Nkemdi   Mayo  "],
  ["p","Naming a sheet that is not there is an error, and the message quotes the name you asked for. Compare it against excel_sheets() rather than against your memory of the workbook."],
  ["code","read_excel(\"season.xlsx\", sheet = \"Suppliers\")"],
  ["code","Error: Sheet 'Suppliers' not found"],
  ["note","Sheet names are matched exactly, including case and any trailing space. A tab that reads Growers in the Excel window can be stored as \"Growers \" if somebody once typed a space after it, and the error then names a sheet you can see on your screen. excel_sheets() is the only account of the names that is not a guess, which is why it is worth calling before every unfamiliar file."]
]},
{ t: "Reading part of a sheet",
  body: [
  ["p","Sheets made for people to look at rarely start with a clean header in A1. There may be a title across the top, a blank row, a block of notes down the side, or a totals row at the bottom that is not data at all. readxl gives you four arguments for cutting the part you want out of the part you do not."],
  ["p","range takes a spreadsheet range string, exactly as you would type it in Excel, and reads only that rectangle. The first row of the rectangle is still treated as the header."],
  ["code","read_excel(\"packhouse.xlsx\", range = \"A1:B3\")"],
  ["code","# A tibble: 2 × 2\n  crate apples\n  <chr>  <dbl>\n1 A-11     120\n2 A-12      84"],
  ["p","n_max caps how many data rows are read, without you having to work out the last cell reference. It counts data rows, so the header is not included in the number."],
  ["code","read_excel(\"packhouse.xlsx\", n_max = 2)"],
  ["code","# A tibble: 2 × 3\n  crate apples grower  \n  <chr>  <dbl> <chr>   \n1 A-11     120 Halloran\n2 A-12      84 Iyer    "],
  ["p","col_names = FALSE says the sheet has no header row. readxl then invents names — ...1, ...2, ...3 — and treats what was the header as ordinary data. Watch what that does to the types: with the word apples sitting in the column, the whole column reads as text."],
  ["code","read_excel(\"packhouse.xlsx\", col_names = FALSE)"],
  ["code","New names:\n• `` -> `...1`\n• `` -> `...2`\n• `` -> `...3`\n# A tibble: 6 × 3\n  ...1  ...2   ...3    \n  <chr> <chr>  <chr>   \n1 crate apples grower  \n2 A-11  120    Halloran\n3 A-12  84     Iyer    \n4 B-04  96     Halloran\n5 B-07  150    Nkemdi  \n6 C-01  62     Iyer    "],
  ["p","Handing col_names a character vector supplies your own names instead. That almost always wants skip alongside it, to step over the header row the file does have, or the old header comes through as a data row."],
  ["code","read_excel(\"packhouse.xlsx\", col_names = c(\"id\", \"n\", \"who\"), skip = 1)"],
  ["code","# A tibble: 5 × 3\n  id        n who     \n  <chr> <dbl> <chr>   \n1 A-11    120 Halloran\n2 A-12     84 Iyer    \n3 B-04     96 Halloran\n4 B-07    150 Nkemdi  \n5 C-01     62 Iyer    "],
  ["note","col_names = FALSE and skip solve different problems, and using the first where you needed the second is the standard mistake. col_names = FALSE keeps every row and names the columns for you; skip throws rows away before reading starts. A sheet with two lines of title above a real header needs skip = 2 and nothing else — reach for col_names = FALSE there and the title line becomes your data."]
]},
{ t: "Column types",
  body: [
  ["p","readxl decides each column's type by looking at the cells in it. When they agree, the guess is right and you never think about it. When one cell disagrees, the guess widens to whatever holds everything, and a column of numbers becomes a column of text."],
  ["p","Here is the situation that produces it. A market stall records apple counts, and on two crates nobody knew the number, so somebody typed a word. Because the column is an R character vector, every cell in it lands in the file as text — which is also what you get from a spreadsheet column that has been formatted as text, and from most exports out of older systems."],
  ["code","messy <- tibble(\n  crate = c(\"A-11\", \"A-12\", \"B-04\", \"B-07\"),\n  apples = c(\"120\", \"unknown\", \"96\", \"n/a\")\n)\n\nwrite_xlsx(messy, \"messy.xlsx\")\nread_excel(\"messy.xlsx\")"],
  ["code","# A tibble: 4 × 2\n  crate apples \n  <chr> <chr>  \n1 A-11  120    \n2 A-12  unknown\n3 B-04  96     \n4 B-07  n/a    "],
  ["p","The apples column reads as character, so 120 in that tibble is the three-character string and not the number. Arithmetic on it fails, and sorting it puts 96 after 120, because that is alphabetical order."],
  ["code","class(read_excel(\"messy.xlsx\")$apples)"],
  ["code","[1] \"character\""],
  ["p","The na argument names the strings that mean missing. Give it the two markers and those cells come back as NA instead of words. The type does not change, though — the remaining cells are still text in the file, so the column is still character."],
  ["code","read_excel(\"messy.xlsx\", na = c(\"unknown\", \"n/a\"))"],
  ["code","# A tibble: 4 × 2\n  crate apples\n  <chr> <chr> \n1 A-11  120   \n2 A-12  <NA>  \n3 B-04  96    \n4 B-07  <NA>  "],
  ["p","col_types is the argument that overrules the guess. It takes one string per column, from the set \"skip\", \"guess\", \"logical\", \"numeric\", \"date\", \"text\", and \"list\". Forcing the apples column to numeric works, and readxl reports every cell it had to touch on the way."],
  ["code","read_excel(\"messy.xlsx\", col_types = c(\"text\", \"numeric\"))"],
  ["code","Warning: Coercing text to numeric in B2 / R2C2: '120'\nWarning: Expecting numeric in B3 / R3C2: got 'unknown'\nWarning: Coercing text to numeric in B4 / R4C2: '96'\nWarning: Expecting numeric in B5 / R5C2: got 'n/a'\n# A tibble: 4 × 2\n  crate apples\n  <chr>  <dbl>\n1 A-11     120\n2 A-12      NA\n3 B-04      96\n4 B-07      NA"],
  ["p","There are two different warnings there, and the difference matters. Coercing text to numeric means the cell held a number written as text and readxl converted it — no data lost. Expecting numeric ... got 'unknown' means the cell could not be converted and became NA — data lost, on purpose, because you asked for a number. Read the cell references: they are in spreadsheet coordinates, so B3 is the cell you can go and look at."],
  ["p","Declaring the markers as NA up front removes the second kind of warning, because a cell that is already missing is not a failed conversion. The first kind stays, and it should: it is readxl telling you the file stores those numbers as text."],
  ["code","read_excel(\"messy.xlsx\", na = c(\"unknown\", \"n/a\"), col_types = c(\"text\", \"numeric\"))"],
  ["code","Warning: Coercing text to numeric in B2 / R2C2: '120'\nWarning: Coercing text to numeric in B4 / R4C2: '96'\n# A tibble: 4 × 2\n  crate apples\n  <chr>  <dbl>\n1 A-11     120\n2 A-12      NA\n3 B-04      96\n4 B-07      NA"],
  ["p","Now the column is numeric and the missing values are NA, which is the state every later step wants. It also means sum() returns NA unless you say what to do about the gaps — the same rule as everywhere else in R, arriving here through a spreadsheet."],
  ["code","clean <- read_excel(\"messy.xlsx\", na = c(\"unknown\", \"n/a\"), col_types = c(\"text\", \"numeric\"))\n\nsum(clean$apples)\nsum(clean$apples, na.rm = TRUE)"],
  ["code","Warning: Coercing text to numeric in B2 / R2C2: '120'\nWarning: Coercing text to numeric in B4 / R4C2: '96'\n[1] NA\n[1] 216"],
  ["p","The \"skip\" type drops a column entirely, which is how you ignore a wide sheet's unwanted columns without reading them at all. You still supply one entry per column in the file, including the ones being dropped."],
  ["code","read_excel(\"packhouse.xlsx\", col_types = c(\"text\", \"numeric\", \"skip\"))"],
  ["code","# A tibble: 5 × 2\n  crate apples\n  <chr>  <dbl>\n1 A-11     120\n2 A-12      84\n3 B-04      96\n4 B-07     150\n5 C-01      62"],
  ["p","Dates deserve their own warning. Write a genuine Date column into a workbook and read it back, and what returns is not a Date."],
  ["code","picks <- tibble(\n  crate = c(\"A-11\", \"A-12\", \"B-04\"),\n  picked = as.Date(c(\"2026-03-01\", \"2026-03-01\", \"2026-03-02\")),\n  apples = c(120, 84, 96)\n)\n\nwrite_xlsx(picks, \"picks.xlsx\")\nread_excel(\"picks.xlsx\")"],
  ["code","# A tibble: 3 × 3\n  crate picked              apples\n  <chr> <dttm>               <dbl>\n1 A-11  2026-03-01 00:00:00    120\n2 A-12  2026-03-01 00:00:00     84\n3 B-04  2026-03-02 00:00:00     96"],
  ["code","class(read_excel(\"picks.xlsx\")$picked)"],
  ["code","[1] \"POSIXct\" \"POSIXt\" "],
  ["note","The column went in as a Date and came back as a date-time at midnight, marked <dttm>. That is not readxl being careless: a spreadsheet has one date type and it carries a time, so there is no date-only value to return. Compare such a column against a Date with == and you are comparing two different classes; convert it with as.Date() as soon as it is read, and do that once at the top rather than in every later expression."]
]},
{ t: "Writing spreadsheets",
  body: [
  ["p","write_xlsx() is the whole of the writing side. It takes a data frame or a named list of data frames, a path, and writes the file. For the plain column types this chapter uses, the round trip is faithful: what comes back is the same tibble that went out."],
  ["code","write_xlsx(orders, \"scratch.xlsx\")\n\nback2 <- read_excel(\"scratch.xlsx\")\nidentical(orders, back2)"],
  ["code","[1] TRUE"],
  ["p","Writing to a path that already holds a file replaces it. There is no prompt and no backup, and the old contents are not recoverable."],
  ["code","write_xlsx(orders[1:2, ], \"scratch.xlsx\")\n\nnrow(read_excel(\"scratch.xlsx\"))"],
  ["code","[1] 2"],
  ["p","What writexl does not do is as important as what it does. It writes values. It does not write fonts, colours, column widths, merged cells, or frozen panes, and it does not write formulas — a string that begins with an equals sign is stored as that string, and comes back as text."],
  ["code","formulas <- tibble(a = c(2, 3), b = c(\"=A2*2\", \"=A3*2\"))\n\nwrite_xlsx(formulas, \"formulas.xlsx\")\nread_excel(\"formulas.xlsx\")"],
  ["code","# A tibble: 2 × 2\n      a b    \n  <dbl> <chr>\n1     2 =A2*2\n2     3 =A3*2"],
  ["p","That restraint is deliberate, and for a data pipeline it is the right default: the output is a rectangle of values, and nothing about it can be wrong in a way you cannot see. When a report genuinely has to arrive formatted, other packages exist for it — openxlsx is the usual answer — and they are a separate skill from reading data, not covered here."],
  ["note","Never write an output file over your input file. The habit that prevents a lost afternoon is to read from one name and write to another, so the source survives every bad run. write_xlsx() overwrites silently, and a script that reads season.xlsx and writes season.xlsx has destroyed its own input the first time the code between them is wrong."]
]},
{ t: "Google Sheets",
  body: [
  ["note","Nothing in this section was run, and none of it shows output. googlesheets4 talks to Google's servers over the network and, for anything other than a fully public sheet, needs you to sign in to a Google account in a browser window. This app has no network access from R and no way to complete that sign-in, so these blocks are here to be read, not executed. Run them in R on a desktop. Every output shown anywhere else in this chapter came from a real run; there are no outputs here because there was no run to capture."],
  ["p","googlesheets4 is the tidyverse package for Google Sheets, and it is built to feel like readxl. A sheet is identified either by its full URL or by the id — the long string of letters and digits in the middle of that URL. read_sheet() returns a tibble, and the arguments you already know carry over: sheet picks a tab, range takes a range string, n_max caps the rows, col_types constrains the types."],
  ["code","library(googlesheets4)\n\nplantings <- read_sheet(\"https://docs.google.com/spreadsheets/d/YOUR-SHEET-ID-HERE\")\n\nplantings"],
  ["p","Reading a tab and a rectangle works the same way it does for a local workbook."],
  ["code","read_sheet(\"YOUR-SHEET-ID-HERE\", sheet = \"Beds\")\n\nread_sheet(\"YOUR-SHEET-ID-HERE\", sheet = \"Beds\", range = \"A1:C20\")"],
  ["p","Writing has two functions. write_sheet() puts a data frame onto a tab of a sheet that already exists, replacing what is there. gs4_create() makes a new spreadsheet, taking the sheets as a named list, exactly like write_xlsx()."],
  ["code","write_sheet(orders, ss = \"YOUR-SHEET-ID-HERE\", sheet = \"Orders\")\n\ngs4_create(\"packhouse season\", sheets = list(Orders = orders))"],
  ["p","Authentication is where this differs from readxl, and it is the part worth understanding before you need it. The first call that touches a private sheet opens a browser so you can grant access, and the token is then cached on your machine for later sessions. A sheet that anyone with the link can view needs no account at all, and gs4_deauth() tells the package to stop asking — which is what you want in a script that runs unattended."],
  ["code","gs4_auth(email = \"you@example.com\")\n\ngs4_deauth()"],
  ["p","Two practical points, neither of which shows up until a script is scheduled. An interactive sign-in cannot happen on a server, so unattended jobs use a service account rather than your own login. And a Google Sheet is a live document: two reads a minute apart can return different data, which a local .xlsx will never do. When a result has to be reproducible, read once and save the result."]
]},
{ t: "Summary",
  body: [
  ["p","readxl turns a spreadsheet into a tibble and then gets out of the way. excel_sheets() lists the tabs, read_excel() reads one of them, and the arguments do the shaping: sheet picks the tab by name or number, range and n_max and skip cut out the part you want, col_names supplies or suppresses a header, na names the strings that mean missing, and col_types overrules the type readxl guessed. writexl goes the other way with a single function, write_xlsx(), which takes one data frame or a named list of them and overwrites the target path without asking."],
  ["p","The recurring problem is types, not files. A spreadsheet stores a type per cell rather than per column, so one typed word in a column of numbers makes the whole column character, and reading the sheet without looking at the <chr> and <dbl> row is how that reaches your analysis unnoticed. The fix is two arguments: na for the markers people write instead of leaving a cell blank, and col_types to state what the column actually is. Dates come back as date-times because a spreadsheet has no date-only type, so convert them once at the point of reading."],
  ["p","Google Sheets is the same shape of task through googlesheets4, with authentication and a network in the middle. That section was shown without output because this app cannot sign in to Google or reach the network — everything else in this chapter ran here, files and all, and you can rerun any of it yourself."],
  ["p","Answer the practice questions from memory before revealing the answers, then clear the graded exercises below. The next chapter is Databases: connecting to one from R with DBI, writing queries in SQL, and letting dbplyr turn dplyr verbs into SQL for you."]
]}
],
questions: [
{ q:"What does read_excel() return, and why does that matter for the rest of your work?",
  a:"A tibble. class() on the result gives \"tbl_df\", \"tbl\", \"data.frame\". Once the file is read it stops being a spreadsheet, so every dplyr verb and every ggplot2 call works on it unchanged — there is no separate spreadsheet dialect to learn." },
{ q:"You have been sent a workbook and do not know what is in it. Which function do you call first, and what does it give you?",
  a:"excel_sheets(path). It returns the tab names as a character vector in the order they appear, so you can pass one of them to read_excel(sheet = ). It is the only account of the names that is not a guess." },
{ q:"Give the two ways to choose a sheet with read_excel(), and say which is safer.",
  a:"sheet = \"Growers\" names the tab, and sheet = 2 counts tabs from the left. The name is safer for code a person wrote: reordering the tabs changes which sheet a number selects, and nothing errors — you silently read the wrong data." },
{ q:"What is the difference between col_names = FALSE and skip = 1?",
  a:"col_names = FALSE keeps every row and invents names ...1, ...2, ...3, so the file's header row becomes a data row. skip = 1 throws the first row away before reading begins. A sheet with two title lines above a real header needs skip = 2; col_names = FALSE there would turn the title into data." },
{ q:"A column of counts reads back as <chr>. What has happened in the file, and what are the two arguments that fix it?",
  a:"At least one cell in that column holds text rather than a number, so the guessed type widened to character to hold everything. na = c(\"unknown\", \"n/a\") declares the markers as missing, and col_types = c(\"text\", \"numeric\") states the type outright. Together they give a numeric column with NA in the gaps." },
{ q:"readxl printed both \"Coercing text to numeric in B2\" and \"Expecting numeric in B3 ... got 'unknown'\". What is the difference between those two warnings?",
  a:"Coercing means the cell held a number stored as text and readxl converted it — nothing was lost. Expecting numeric ... got means the cell could not be converted and is now NA — that value is gone. The first is a note about the file, the second is a note about your data." },
{ q:"Name the seven strings col_types accepts, and say what \"skip\" does.",
  a:"\"skip\", \"guess\", \"logical\", \"numeric\", \"date\", \"text\", and \"list\". \"skip\" drops that column so it is not read at all — but you still supply one entry per column in the file, including the dropped ones, because the entries are matched by position." },
{ q:"You wrote a Date column with write_xlsx() and read it back. What class comes back, and why?",
  a:"POSIXct — a date-time, shown as <dttm> and printed with 00:00:00 on the end. A spreadsheet has a single date type that carries a time, so there is no date-only value for readxl to return. Convert with as.Date() once, at the point of reading." },
{ q:"How do you write a workbook with more than one tab, and what happens if the file already exists?",
  a:"Hand write_xlsx() a named list of data frames — list(Orders = orders, Growers = growers) — and each name becomes a tab. If the path already holds a file it is replaced, with no prompt and no backup, which is why a script should never write to the file it read from." },
{ q:"Why is the Google Sheets section of this chapter shown without any output?",
  a:"googlesheets4 needs a network connection to Google's servers and, for a private sheet, a browser sign-in. This app has neither, so that code was never run and no output could honestly be captured. The rest of the chapter did run here, which is why it has output." }
],
exercises: [
{ c:"tibbles & pipes", t:"A workbook of seed packets", book:"r20",
  b:"Attach tibble, writexl, and readxl. Build a tibble named packets with a character column variety holding \"Cosmos\", \"Nigella\", \"Borage\" and a double column grams holding 4.5, 2, 6.5, in that order. Write it to \"packets.xlsx\", then read that file back and print what comes out.",
  o:"# A tibble: 3 × 2\n  variety grams\n  <chr>   <dbl>\n1 Cosmos    4.5\n2 Nigella   2  \n3 Borage    6.5",
  h:["The file has to exist before it can be read, so the writing call comes first and the reading call second.",
     "write_xlsx() takes the data frame and the path. read_excel() takes the path on its own and returns a tibble, which prints when it is the last thing on a line.",
     "Attach the three packages, build the tibble with tibble(variety = ..., grams = ...), call write_xlsx() on it with the filename, then put a read_excel() call for the same filename on a line of its own."]},
{ c:"data frames", t:"Two tabs in one file", book:"r20",
  b:"Attach tibble, writexl, and readxl. Write a workbook \"pottery.xlsx\" with two sheets: a sheet named Kilns holding columns kiln (\"K1\", \"K2\") and firings (14, 9), and a sheet named Glazes holding columns glaze (\"celadon\", \"tenmoku\", \"shino\") and cone (10, 10, 8). Then print the workbook's sheet names, and on the next line print the Glazes sheet read back.",
  o:"[1] \"Kilns\"  \"Glazes\"\n# A tibble: 3 × 2\n  glaze    cone\n  <chr>   <dbl>\n1 celadon    10\n2 tenmoku    10\n3 shino       8",
  h:["One call to write_xlsx() makes both tabs. What you hand it decides how many sheets you get.",
     "A named list of data frames becomes a workbook of tabs, and the list element names become the tab names. excel_sheets() lists them back.",
     "Pass list(Kilns = tibble(...), Glazes = tibble(...)) as the first argument to write_xlsx() and the filename as the second. Then call excel_sheets() on the file, and finally read_excel() on it with sheet set to the name of the second tab."]},
{ c:"tibbles & pipes", t:"A column that is not numbers", book:"r20",
  b:"Attach tibble, writexl, readxl, and dplyr with suppressMessages. Write \"market.xlsx\" from a tibble with a character column stall holding \"S1\", \"S2\", \"S3\", \"S4\" and a character column takings holding \"240\", \"closed\", \"185\", \"closed\". Read it back into takings so that the word closed becomes NA and the takings column is numeric, print that tibble arranged by stall, then on the next line print the total takings ignoring the missing values. readxl reports each text cell it converts to a number; those two warning lines are part of the expected output.",
  o:"Warning: Coercing text to numeric in B2 / R2C2: '240'\nWarning: Coercing text to numeric in B4 / R4C2: '185'\n# A tibble: 4 × 2\n  stall takings\n  <chr>   <dbl>\n1 S1        240\n2 S2         NA\n3 S3        185\n4 S4         NA\n[1] 425",
  h:["Two arguments to read_excel() are doing the work: one names the string that means missing, the other states what the column really is.",
     "na takes the marker string. col_types takes one entry per column, so two entries here, and the second is \"numeric\". Summing a column with NA in it needs na.rm.",
     "Read with read_excel(path, na = \"closed\", col_types = c(\"text\", \"numeric\")) and store it. Print arrange(takings, stall), then sum the takings column with na.rm set to TRUE on its own line."]},
{ c:"data frames", t:"Only part of the sheet", book:"r20",
  b:"Attach tibble, writexl, and readxl. Write \"wards.xlsx\" from a tibble with a character column ward holding \"north\", \"south\", \"east\", \"west\" and a double column beds holding 24, 18, 30, 12. Then print two reads of that file: first only the rectangle from A1 to B3, then the whole sheet with the header row stepped over and the columns named area and count instead.",
  o:"# A tibble: 2 × 2\n  ward   beds\n  <chr> <dbl>\n1 north    24\n2 south    18\n# A tibble: 4 × 2\n  area  count\n  <chr> <dbl>\n1 north    24\n2 south    18\n3 east     30\n4 west     12",
  h:["Two separate read_excel() calls on the same file, each with a different argument doing the shaping.",
     "The first read takes a range string written the way Excel writes one. The second supplies col_names as a character vector of your own names, and needs skip so the file's real header does not arrive as data.",
     "First call: read_excel(path, range = \"A1:B3\"). Second call: read_excel(path, col_names = c(\"area\", \"count\"), skip = ...) with the skip value that steps over exactly one row."]}
]
};
