/* Practice Log book — R Chapter 21: Databases.
   Original lesson text following the chapter-by-chapter curriculum of
   "R for Data Science" (2nd ed.) by Hadley Wickham, Mine Cetinkaya-Rundel,
   and Garrett Grolemund. Read the original chapter free at the src link below.
   Every shown output was captured by executing the code in WebR, not written from memory. */
window.BOOK_R = window.BOOK_R || { chapters: {} };
window.BOOK_R.chapters.r21 = {
n: 21,
title: "Databases",
src: "https://r4ds.hadley.nz/databases.html",
blurb: "Connecting to a database with DBI, asking for data in SQL, and letting dbplyr turn dplyr verbs into SQL that runs where the data already is.",
pkgs: ["DBI", "RSQLite", "dbplyr", "dplyr", "tibble"],
sections: [
{ t: "Tables that live outside R",
  body: [
  ["p","Everything so far has assumed the data is already in R: a tibble in memory, small enough that a copy of it costs nothing. A database breaks that assumption on purpose. The data sits in its own program, on your machine or on a server somewhere, and R asks for pieces of it. That arrangement is what lets many people read the same numbers at once, what keeps a table that will not fit in memory usable, and what makes it somebody else's job to back it up."],
  ["p","The vocabulary maps onto what you know. A database holds tables; a table has rows and columns; a column has one type for the whole column, which is stricter than a spreadsheet and the same as a tibble. The differences that matter are that rows in a database have no inherent order, and that a database column's type is declared up front rather than guessed."],
  ["p","Two layers of package stand between R and the data. DBI defines the interface — connect, list tables, run a query, disconnect — and every function you call is a DBI function. Underneath it sits a driver package for one particular database engine: RSQLite for SQLite, RPostgres for PostgreSQL, RMariaDB for MySQL and MariaDB, duckdb for DuckDB. Swap the driver and the DBI calls above it stay the same."],
  ["code","library(DBI)\nlibrary(RSQLite)\nlibrary(tibble)\nsuppressMessages(library(dplyr))\nsuppressMessages(library(dbplyr))"],
  ["note","dplyr and dbplyr both print a banner when attached — dbplyr's says it is masking dplyr's ident and sql, which is expected and harmless. Those banners land in the transcript this app grades, so both calls are wrapped in suppressMessages() here and in the exercises. DBI, RSQLite, and tibble attach silently."],
  ["p","This chapter uses SQLite, and it runs for real in this app. SQLite is a complete database engine that keeps its data in a single file, or, when you name it :memory:, in memory for as long as the connection lasts. It needs no server and no network, so everything below was executed here and the outputs were captured from those runs."],
  ["p","Connecting to a database on a server is the same dbConnect() call with a different driver and the details of where to find it. That cannot run in this app — there is no network from R here — so the block below is shown without output, and it was not run."],
  ["code","con <- dbConnect(\n  RPostgres::Postgres(),\n  dbname = \"orchard\",\n  host = \"db.example.org\",\n  port = 5432,\n  user = \"reader\",\n  password = Sys.getenv(\"PGPASSWORD\")\n)"],
  ["note","The password comes out of an environment variable rather than out of the script. A connection string typed into a file is a password in your history, in your backups, and in the repository the moment you share the code. Sys.getenv() reads it from the environment instead, which keeps the secret out of everything you commit."]
]},
{ t: "Connecting, and putting a table in",
  body: [
  ["p","dbConnect() takes a driver and returns a connection object. RSQLite::SQLite() is the driver, and the string :memory: asks SQLite for a private database that exists only while the connection is open. A fresh one holds no tables at all, which is why the third answer below is an empty character vector rather than an error."],
  ["code","con <- dbConnect(RSQLite::SQLite(), \":memory:\")\n\nclass(con)\ndbIsValid(con)\ndbListTables(con)"],
  ["code","[1] \"SQLiteConnection\"\nattr(,\"package\")\n[1] \"RSQLite\"\n[1] TRUE\ncharacter(0)"],
  ["p","Normally the tables are already there and somebody else put them there. To have something to query, this chapter puts them there itself with dbWriteTable(), which takes a connection, a table name, and a data frame. The example is an apiary's hive records: six hives across three apiaries, with a frame count and a honey yield."],
  ["code","hives <- tibble(\n  hive = c(\"H1\", \"H2\", \"H3\", \"H4\", \"H5\", \"H6\"),\n  apiary = c(\"Rowan\", \"Rowan\", \"Birch\", \"Birch\", \"Birch\", \"Alder\"),\n  frames = c(8L, 10L, 6L, 12L, 9L, 11L),\n  honey_kg = c(14.5, 21.0, 9.5, 26.5, 17.0, 23.5)\n)\n\ndbWriteTable(con, \"hives\", hives)\ndbListTables(con)\ndbListFields(con, \"hives\")"],
  ["code","[1] \"hives\"\n[1] \"hive\"     \"apiary\"   \"frames\"   \"honey_kg\""],
  ["p","dbListTables() and dbListFields() are how you find your way around a database nobody has described to you. They are the equivalent of excel_sheets() and names(): call them before you write a query, not after the query fails."],
  ["p","dbReadTable() pulls a whole table back into R. It is the simplest thing you can do with a connection and usually the wrong one, because it copies every row before you have said which rows you want."],
  ["code","dbReadTable(con, \"hives\")"],
  ["code","  hive apiary frames honey_kg\n1   H1  Rowan      8     14.5\n2   H2  Rowan     10     21.0\n3   H3  Birch      6      9.5\n4   H4  Birch     12     26.5\n5   H5  Birch      9     17.0\n6   H6  Alder     11     23.5"],
  ["note","What came back is a base data frame, not a tibble — no # A tibble header, no row of column types, and row numbers down the side. Every DBI function returns a plain data frame, because DBI predates tibble and refuses to depend on it. Wrap the result in as_tibble() when you want the printing you are used to, and remember that dbReadTable() on a table of ten million rows will try to bring all ten million into memory."]
]},
{ t: "Asking in SQL",
  body: [
  ["p","SQL is the language databases take their instructions in. A query is a single statement built from clauses in a fixed order, and the two that every query has are SELECT, naming the columns you want, and FROM, naming the table. An asterisk means every column. dbGetQuery() sends the statement and returns the answer as a data frame."],
  ["p","Databases do not promise any particular row order unless you ask for one, so ORDER BY is not decoration — it is the difference between a result you can rely on and one that happens to look right today."],
  ["code","dbGetQuery(con, \"SELECT * FROM hives ORDER BY hive\")"],
  ["code","  hive apiary frames honey_kg\n1   H1  Rowan      8     14.5\n2   H2  Rowan     10     21.0\n3   H3  Birch      6      9.5\n4   H4  Birch     12     26.5\n5   H5  Birch      9     17.0\n6   H6  Alder     11     23.5"],
  ["p","Naming columns instead of the asterisk is SQL's version of select(). It is worth doing for real: the columns you leave out are never sent, so a narrow query over a wide table moves far less data."],
  ["code","dbGetQuery(con, \"SELECT hive, honey_kg FROM hives ORDER BY hive\")"],
  ["code","  hive honey_kg\n1   H1     14.5\n2   H2     21.0\n3   H3      9.5\n4   H4     26.5\n5   H5     17.0\n6   H6     23.5"],
  ["p","WHERE keeps only the rows a condition is true for, which is filter(). The comparison operators are the ones you expect, and they go after the column name."],
  ["code","dbGetQuery(con, \"SELECT hive, honey_kg FROM hives WHERE honey_kg > 15 ORDER BY hive\")"],
  ["code","  hive honey_kg\n1   H2     21.0\n2   H4     26.5\n3   H5     17.0\n4   H6     23.5"],
  ["p","Conditions combine with AND and OR. Note two spellings that catch R programmers out: equality in SQL is a single = rather than ==, and a text value goes in single quotes. Since the whole statement is already inside an R double-quoted string, single quotes sit in it without any escaping."],
  ["code","dbGetQuery(con, \"SELECT hive, frames FROM hives WHERE apiary = 'Birch' AND frames >= 9 ORDER BY hive\")"],
  ["code","  hive frames\n1   H4     12\n2   H5      9"],
  ["p","Whatever the query, what returns is a plain data frame in R's memory. At that point the database is finished with the question and everything you know about data frames applies again."],
  ["code","class(dbGetQuery(con, \"SELECT * FROM hives\"))"],
  ["code","[1] \"data.frame\""],
  ["p","A name the database does not recognise stops the query, and the message comes from the database rather than from R. Read it as such: it is reporting on the tables that exist, not on your spelling."],
  ["code","dbGetQuery(con, \"SELECT hive FROM beehives\")"],
  ["code","Error: no such table: beehives"],
  ["note","SQL is not R, and the two places that bite are equality and quotes. SQLite is unusually forgiving about both: it takes == as a synonym for =, and when a double-quoted name matches no column it falls back to reading it as text, so both of the wrong spellings appear to work here. The SQL standard is a single = with text in single quotes, and stricter engines enforce it, so a query that runs in SQLite can fail the moment it moves to another database. The lenient spelling is also the dangerous one: if a column of that name does exist, apiary = \"Birch\" compares two columns instead of comparing a column to text, and returns the wrong rows without any error."]
]},
{ t: "GROUP BY, and the clauses in order",
  body: [
  ["p","GROUP BY collapses rows that share a value into one row each, and the SELECT list then describes what to compute for each group. It is group_by() and summarise() fused into a single statement. COUNT(*) counts the rows in the group; SUM, AVG, MIN, and MAX do what their names say. AS renames a computed column, which matters because otherwise the column comes back named after the expression."],
  ["code","dbGetQuery(con, \"SELECT apiary, COUNT(*) AS n, SUM(honey_kg) AS total FROM hives GROUP BY apiary ORDER BY apiary\")"],
  ["code","  apiary n total\n1  Alder 1  23.5\n2  Birch 3  53.0\n3  Rowan 2  35.5"],
  ["p","A query's clauses have to appear in one fixed order: SELECT, then FROM, then WHERE, then GROUP BY, then ORDER BY. That order is not the order the database works in — it filters with WHERE before it groups, and it groups before it evaluates the SELECT list — but it is the order you must write. Getting it wrong is a syntax error rather than a wrong answer, which is the kinder of the two outcomes."],
  ["p","A value that comes from a variable should never be pasted into the statement text. Write a question mark where the value goes and pass the value through params, and the database keeps the value and the code apart. This is also the habit that stops a stray apostrophe in somebody's name from breaking a query."],
  ["code","dbGetQuery(con, \"SELECT hive FROM hives WHERE apiary = ? ORDER BY hive\", params = list(\"Birch\"))"],
  ["code","  hive\n1   H3\n2   H4\n3   H5"],
  ["note","Building a query with paste0() and a variable is the mistake to never make. Beyond the ordinary bugs — a missing quote, a number formatted with a comma — a value that arrives from outside your program can close the quote and add a clause of its own, and the database will run it because it cannot tell your text from the value's. The question mark and params exist so that this cannot happen."]
]},
{ t: "dbplyr: dplyr verbs that become SQL",
  body: [
  ["p","Writing SQL by hand is fine for one query and tedious for twenty. dbplyr lets you write dplyr instead: tbl() gives you an object that stands for a database table, the verbs pile up on it as usual, and dbplyr generates the SQL. You do not need to attach dbplyr to use it — dplyr finds it — but attaching it gives you show_query(), which is the whole reason to learn this rather than treat it as magic."],
  ["code","bees <- tbl(con, \"hives\")\n\nclass(bees)"],
  ["code","[1] \"tbl_SQLiteConnection\" \"tbl_dbi\"              \"tbl_sql\"             \n[4] \"tbl_lazy\"             \"tbl\"                 "],
  ["p","That object is a tbl_lazy. It holds a connection and a description of a query, and it contains no data. Printing one runs enough of the query to fill the screen and no more, which is why the header says [?? x 4] — the row count is unknown, because counting the rows would mean running the whole thing."],
  ["code","bees"],
  ["code","# Source:   table<`hives`> [?? x 4]\n# Database: sqlite 3.53.1 [:memory:]\n  hive  apiary frames honey_kg\n  <chr> <chr>   <int>    <dbl>\n1 H1    Rowan       8     14.5\n2 H2    Rowan      10     21  \n3 H3    Birch       6      9.5\n4 H4    Birch      12     26.5\n5 H5    Birch       9     17  \n6 H6    Alder      11     23.5"],
  ["p","Now stack verbs on it. filter(), select(), and arrange() work exactly as they do on a tibble, and nothing is computed while you do it. show_query() prints the SQL dbplyr would send."],
  ["code","q <- bees |>\n  filter(honey_kg > 15) |>\n  select(hive, apiary, honey_kg) |>\n  arrange(hive)\n\nshow_query(q)"],
  ["code","<SQL>\nSELECT `hive`, `apiary`, `honey_kg`\nFROM `hives`\nWHERE (`honey_kg` > 15.0)\nORDER BY `hive`"],
  ["p","Read that against the pipeline and the mapping is plain: select() became the SELECT list, filter() became WHERE, arrange() became ORDER BY, and the three verbs collapsed into one statement rather than three round trips. Backticks around names are dbplyr being careful, not something you would have to write."],
  ["p","collect() is what actually runs the query and brings the answer back. It returns a tibble, and from that point the data is in R."],
  ["code","collect(q)"],
  ["code","# A tibble: 4 × 3\n  hive  apiary honey_kg\n  <chr> <chr>     <dbl>\n1 H2    Rowan      21  \n2 H4    Birch      26.5\n3 H5    Birch      17  \n4 H6    Alder      23.5"],
  ["p","group_by() and summarise() translate the way you would hope, into GROUP BY and aggregate functions. n() becomes COUNT(*), sum() becomes SUM, mean() becomes AVG."],
  ["code","g <- bees |>\n  group_by(apiary) |>\n  summarise(n = n(), total = sum(honey_kg, na.rm = TRUE)) |>\n  arrange(apiary)\n\nshow_query(g)"],
  ["code","<SQL>\nSELECT `apiary`, COUNT(*) AS `n`, SUM(`honey_kg`) AS `total`\nFROM `hives`\nGROUP BY `apiary`\nORDER BY `apiary`"],
  ["code","collect(g)"],
  ["code","# A tibble: 3 × 3\n  apiary     n total\n  <chr>  <int> <dbl>\n1 Alder      1  23.5\n2 Birch      3  53  \n3 Rowan      2  35.5"],
  ["p","mutate() becomes a computed column in the SELECT list. The AS naming that you would write by hand in SQL is generated from the argument name you used."],
  ["code","m <- bees |>\n  mutate(per_frame = honey_kg / frames) |>\n  select(hive, per_frame) |>\n  arrange(hive)\n\nshow_query(m)"],
  ["code","<SQL>\nSELECT `hive`, `honey_kg` / `frames` AS `per_frame`\nFROM `hives`\nORDER BY `hive`"],
  ["note","Run show_query() on anything you are about to trust. dbplyr is a translator, and a translator can produce a statement that is valid, runs quickly, and answers a slightly different question than the one you asked — most often around grouping and around what counts as missing. The SQL is the thing the database will actually do, so it is the thing to read."]
]},
{ t: "When the query actually runs",
  body: [
  ["p","The point that catches everyone is that a dbplyr pipeline does nothing until something forces it. Printing forces a few rows; collect() forces all of them; show_query() forces none at all. Anything else that expects real data gets a shrug, and nrow() is the clearest demonstration — the lazy table cannot say how many rows it has without running the query, so it answers NA."],
  ["code","nrow(bees)\nnrow(collect(bees))"],
  ["code","[1] NA\n[1] 6"],
  ["p","That laziness is the feature, not a limitation. Because the verbs are collected before anything is sent, dbplyr can fold them into one statement that the database runs where the data already lives, and only the result travels. head() becoming LIMIT is the clearest case: the database returns three rows, not the whole table."],
  ["code","h <- bees |>\n  arrange(desc(honey_kg)) |>\n  head(3)\n\nshow_query(h)"],
  ["code","<SQL>\nSELECT `hives`.*\nFROM `hives`\nORDER BY `honey_kg` DESC\nLIMIT 3"],
  ["code","collect(h)"],
  ["code","# A tibble: 3 × 4\n  hive  apiary frames honey_kg\n  <chr> <chr>   <int>    <dbl>\n1 H4    Birch      12     26.5\n2 H6    Alder      11     23.5\n3 H2    Rowan      10     21  "],
  ["p","Inside a verb, dbplyr translates R functions into the database's own functions where it knows an equivalent. It knows a good number of them, and the translation is textual rather than an execution of your R code."],
  ["code","bad <- bees |>\n  mutate(tag = toupper(hive))\n\nshow_query(bad)"],
  ["code","<SQL>\nSELECT `hives`.*, UPPER(`hive`) AS `tag`\nFROM `hives`"],
  ["p","When it does not know an equivalent, it passes the name through unchanged and lets the database refuse it. Your own function is the obvious case: it exists in R, and the database has never heard of it. Nothing complains while the pipeline is being built, because nothing has been sent yet — the failure waits for collect()."],
  ["code","collect(bees |> mutate(z = my_own_fn(frames)) |> arrange(hive))"],
  ["code","Error: Failed to collect lazy table."],
  ["note","A pipeline that builds without error has not been checked, because building sends nothing. The habit that saves you is show_query() while you write and collect() before you believe the result. Note also which functions can appear at all: a dbplyr pipeline runs in the database, so a function of yours, or any package function the database does not have, cannot be part of it. Bring the data back with collect() first, then use R on it."]
]},
{ t: "Joins, changes, and closing up",
  body: [
  ["p","Joins are where databases earn their keep, and they work on the same idea as chapter 19: matching rows across two tables by a shared column. Here is a second table naming the county each apiary sits in."],
  ["code","apiaries <- tibble(\n  apiary = c(\"Rowan\", \"Birch\", \"Alder\"),\n  county = c(\"Kerry\", \"Clare\", \"Mayo\")\n)\n\ndbWriteTable(con, \"apiaries\", apiaries)\ndbListTables(con)"],
  ["code","[1] \"apiaries\" \"hives\"   "],
  ["p","In SQL, JOIN names the second table and ON gives the condition that matches a row of one to a row of the other. Table aliases — h and a below — keep the column references short and unambiguous."],
  ["code","dbGetQuery(con, \"SELECT h.hive, a.county FROM hives AS h JOIN apiaries AS a ON h.apiary = a.apiary ORDER BY h.hive\")"],
  ["code","  hive county\n1   H1  Kerry\n2   H2  Kerry\n3   H3  Clare\n4   H4  Clare\n5   H5  Clare\n6   H6   Mayo"],
  ["p","In dbplyr it is left_join(), with both sides being tbl() objects on the same connection. The generated SQL wraps the join in a subquery, which is dbplyr composing rather than optimising — the database will flatten it."],
  ["code","j <- bees |>\n  left_join(tbl(con, \"apiaries\"), by = \"apiary\") |>\n  select(hive, county) |>\n  arrange(hive)\n\nshow_query(j)"],
  ["code","<SQL>\nSELECT `q01`.*\nFROM (\n  SELECT `hive`, `county`\n  FROM `hives`\n  LEFT JOIN `apiaries`\n    ON (`hives`.`apiary` = `apiaries`.`apiary`)\n) AS `q01`\nORDER BY `hive`"],
  ["code","collect(j)"],
  ["code","# A tibble: 6 × 2\n  hive  county\n  <chr> <chr> \n1 H1    Kerry \n2 H2    Kerry \n3 H3    Clare \n4 H4    Clare \n5 H5    Clare \n6 H6    Mayo  "],
  ["p","Statements that change the database rather than ask it something go through dbExecute(), which returns the number of rows affected instead of a data frame. DELETE, UPDATE, INSERT, and CREATE TABLE all go this way."],
  ["code","dbExecute(con, \"DELETE FROM hives WHERE frames < 7\")\ndbGetQuery(con, \"SELECT COUNT(*) AS n FROM hives\")"],
  ["code","[1] 1\n  n\n1 5"],
  ["p","When you are finished, close the connection. dbDisconnect() releases it, and for an in-memory SQLite database it also discards everything in it, since the database only existed for the life of the connection."],
  ["code","dbDisconnect(con)\ndbIsValid(con)"],
  ["code","[1] FALSE"],
  ["note","Leaving a connection open has a delayed cost you will not connect to its cause. R eventually garbage-collects the forgotten object and prints a warning about calling dbDisconnect(), and it prints it in the middle of whatever you happen to be running at the time. Every exercise in this chapter ends with dbDisconnect(con) for that reason: without it, a later exercise inherits a warning line it did nothing to earn."]
]},
{ t: "Summary",
  body: [
  ["p","DBI is the interface and a driver package is the engine underneath it. dbConnect() opens a connection, dbListTables() and dbListFields() describe what is there, dbGetQuery() sends a query and returns a plain data frame, dbExecute() sends a statement that changes data and returns a row count, and dbDisconnect() closes up. dbWriteTable() and dbReadTable() move a whole table in and out, which is convenient and, on anything large, the thing to avoid."],
  ["p","SQL is the query language, and its shape is fixed: SELECT the columns, FROM a table, WHERE a condition holds, GROUP BY a column with aggregates in the SELECT list, ORDER BY something so the order is yours rather than the database's. Equality is a single =, text goes in single quotes, and any value coming from a variable goes in through a question mark and params rather than through paste0()."],
  ["p","dbplyr writes that SQL for you from dplyr verbs. tbl() names a table, the verbs accumulate without sending anything, show_query() shows what will be sent, and collect() runs it and returns a tibble. The laziness is the point — the work happens in the database and only the result travels — and it is also the trap: nrow() on a lazy table is NA, an untranslatable function survives until collect() and fails there, and a pipeline that built cleanly has not been checked. Read the SQL, then collect it."],
  ["p","Answer the practice questions from memory before revealing the answers, then clear the graded exercises below. Every one of them opens an in-memory SQLite database, so they run here for real, and every one closes its connection at the end. The next chapter is Arrow: reading data that is far too large for memory, stored in files rather than in a database."]
]}
],
questions: [
{ q:"What is the division of labour between DBI and a package like RSQLite?",
  a:"DBI defines the interface — dbConnect(), dbListTables(), dbGetQuery(), dbExecute(), dbDisconnect() — and those are the functions you call. The driver package implements that interface for one engine. Swapping RSQLite for RPostgres changes the dbConnect() call and nothing above it." },
{ q:"What does dbConnect(RSQLite::SQLite(), \":memory:\") give you, and what happens to it when you disconnect?",
  a:"A connection to a complete SQLite database that exists only in memory and only for the life of the connection. It starts with no tables, so dbListTables() returns character(0). dbDisconnect() closes it and the data is gone with it." },
{ q:"dbGetQuery() returned something that printed with row numbers down the side and no type row. What did you get, and why?",
  a:"A base data frame. Every DBI function returns a plain data frame rather than a tibble, because DBI does not depend on tibble. Wrap it in as_tibble() if you want tibble printing." },
{ q:"Name the five SQL clauses this chapter uses and the order they must be written in.",
  a:"SELECT, FROM, WHERE, GROUP BY, ORDER BY, in that order. It is not the order the database evaluates them — WHERE filters before GROUP BY groups, and the SELECT list is computed after grouping — but writing them out of order is a syntax error." },
{ q:"Which dplyr verb does each of SELECT, WHERE, GROUP BY, and ORDER BY correspond to?",
  a:"SELECT is select() and, when it computes something, mutate(). WHERE is filter(). GROUP BY with aggregates in the SELECT list is group_by() plus summarise(). ORDER BY is arrange()." },
{ q:"SQLite accepted both WHERE apiary == \"Birch\" and WHERE apiary = 'Birch'. Why is only the second one worth writing?",
  a:"SQLite is forgiving: it takes == as a synonym for =, and a double-quoted name that matches no column falls back to being read as text. The standard is a single = with text in single quotes, and stricter engines enforce it, so the lenient spelling breaks when the query moves. It is also unsafe — if a column of that name does exist, apiary = \"Birch\" compares two columns and returns the wrong rows with no error at all." },
{ q:"Why should a value from an R variable go into a query through a question mark and params rather than through paste0()?",
  a:"Because pasted text becomes part of the statement. A value containing a quote can end the string and add a clause of its own, and the database runs it, having no way to tell your SQL from the value's. params keeps the code and the value in separate channels, and it also handles quoting and formatting for you." },
{ q:"What does tbl(con, \"hives\") return, and how much data does it contain?",
  a:"A tbl_lazy — an object holding a connection and a description of a query. It contains no data at all. Printing it runs just enough of the query to show a screenful, which is why its header reads [?? x 4] with the row count unknown." },
{ q:"What do show_query() and collect() each do to a dbplyr pipeline?",
  a:"show_query() prints the SQL that would be sent and runs nothing. collect() runs the query and returns the result as a tibble in R's memory. Until one of them, or a print, forces it, the pipeline has sent nothing to the database." },
{ q:"nrow() on a lazy table returned NA, and a pipeline using a function of your own built fine but failed at collect(). What single fact explains both?",
  a:"A dbplyr pipeline is a description of SQL, not an execution of R. The row count is unknown because counting would mean running the query, and your function is passed through into the SQL as a name the database has never heard of — which nothing can object to until the statement is actually sent, at collect()." }
],
exercises: [
{ c:"dplyr verbs", t:"A first query", book:"r21",
  b:"Attach DBI, RSQLite, and tibble. Open an in-memory SQLite connection called con, and write into it a table named boats from a tibble with columns boat (\"Aoife\", \"Brendan\", \"Ciara\", \"Donal\", \"Eimear\"), port (\"Dingle\", \"Howth\", \"Dingle\", \"Kinsale\", \"Howth\") and catch_kg (310, 145, 260, 480, 95). Then run one SQL query that returns the boat and catch_kg columns for the boats whose catch is over 150, ordered by boat, and print the result. Close the connection at the end.",
  o:"   boat catch_kg\n1 Aoife      310\n2 Ciara      260\n3 Donal      480",
  h:["The whole thing is three steps: connect, load a table, ask one question. dbGetQuery() sends the query and prints its answer.",
     "dbConnect() takes the driver RSQLite::SQLite() and the string \":memory:\". dbWriteTable() takes the connection, the table name as a string, and the data frame. Rows are chosen with WHERE and ordered with ORDER BY.",
     "The query string has the shape SELECT two columns FROM boats WHERE the catch column is greater than 150 ORDER BY boat. Finish with dbDisconnect(con) so no warning leaks into a later run."]},
{ c:"grouping & summaries", t:"One row per port", book:"r21",
  b:"Set up the same boats table as the previous exercise: attach DBI, RSQLite and tibble, open an in-memory SQLite connection called con, and write the table with columns boat, port and catch_kg holding the same five rows. Then run one SQL query that returns, for each port, the port name, a column named boats counting the rows, and a column named total holding the summed catch_kg, ordered by port. Print it, then close the connection.",
  o:"     port boats total\n1  Dingle     2   570\n2   Howth     2   240\n3 Kinsale     1   480",
  h:["One statement does the whole summary. The clause that collapses rows sharing a value goes after the table name.",
     "GROUP BY port makes one row per port. COUNT(*) counts a group's rows and SUM() adds a column up, and AS gives each computed column the name the output needs.",
     "The shape is SELECT port, then the count expression AS boats, then the sum expression AS total, FROM boats, GROUP BY port, ORDER BY port. Disconnect at the end."]},
{ c:"dplyr verbs", t:"Verbs that become SQL", book:"r21",
  b:"Attach DBI, RSQLite and tibble plainly, and dplyr and dbplyr with suppressMessages. Open an in-memory SQLite connection called con and write the same boats table (boat, port, catch_kg) into it. Build a lazy query on that table that keeps rows where catch_kg is over 150, keeps the boat and port columns, and orders by boat. Store it in q. Print the SQL it would send, then on the next line print the collected result.",
  o:"<SQL>\nSELECT `boat`, `port`\nFROM `boats`\nWHERE (`catch_kg` > 150.0)\nORDER BY `boat`\n# A tibble: 3 × 2\n  boat  port   \n  <chr> <chr>  \n1 Aoife Dingle \n2 Ciara Dingle \n3 Donal Kinsale",
  h:["No SQL is written by hand here. tbl() names the table and the ordinary dplyr verbs stack onto it.",
     "tbl(con, \"boats\") is the lazy table. filter(), select() and arrange() do the three steps. show_query() prints the SQL without running it, and collect() runs it and returns a tibble.",
     "Pipe the lazy table through the three verbs and assign it to q. Then call show_query(q) on one line and collect(q) on the next. Disconnect after that."]},
{ c:"joins", t:"Two tables, one answer", book:"r21",
  b:"Attach DBI, RSQLite and tibble plainly, and dplyr and dbplyr with suppressMessages. Open an in-memory SQLite connection called con. Write a table boats with columns boat (\"Aoife\", \"Brendan\", \"Ciara\", \"Donal\") and port (\"Dingle\", \"Howth\", \"Dingle\", \"Kinsale\"), and a table ports with columns port (\"Dingle\", \"Howth\", \"Kinsale\") and county (\"Kerry\", \"Dublin\", \"Cork\"). Using dbplyr rather than hand-written SQL, left join the two on port, keep the boat and county columns, order by boat, and print the collected result. Close the connection.",
  o:"# A tibble: 4 × 2\n  boat    county\n  <chr>   <chr> \n1 Aoife   Kerry \n2 Brendan Dublin\n3 Ciara   Kerry \n4 Donal   Cork  ",
  h:["Both sides of the join are database tables, so both need to be named with tbl() on the same connection.",
     "left_join() takes the second lazy table as its second argument and by = \"port\" as the matching column. Nothing runs until collect().",
     "Pipe tbl(con, \"boats\") into left_join(tbl(con, \"ports\"), by = \"port\"), then select(boat, county), then arrange(boat). Wrap the whole pipeline in collect() to print it, and disconnect afterwards."]}
]
};
