/* Practice Log book — R Chapter 22: Arrow.
   Original lesson text following the chapter-by-chapter curriculum of
   "R for Data Science" (2nd ed.) by Hadley Wickham, Mine Cetinkaya-Rundel,
   and Garrett Grolemund. Read the original chapter free at the src link below.
   Every shown output was captured by executing the code in WebR, not written from memory. */
window.BOOK_R = window.BOOK_R || { chapters: {} };
window.BOOK_R.chapters.r22 = {
n: 22,
title: "Arrow",
src: "https://r4ds.hadley.nz/arrow.html",
blurb: "Parquet files, why they beat csv once a table stops being small, datasets spread over many files, and dplyr running against data you have not loaded.",
pkgs: ["nanoparquet", "dplyr"],
sections: [
{ t: "Where csv gives out",
  body: [
  ["p","A csv is a text file. Every number is spelled out in digits, every value is separated by a comma, and every row is a line. That plainness is the format's entire case: any program written in the last forty years can read one, and you can open it in a text editor and see your data. For a few thousand rows nothing else matters."],
  ["p","Three costs arrive together once the table stops being small. The first is size. Nothing in a csv is compressed, and the column that repeats the same twelve station names for a million rows writes those names out a million times. The second is types. A csv has none: every value is characters, so whatever reads the file has to guess whether 2026-03-01 is a date or a string, and the guess is not always the same twice. The third is the one that costs the most time. To read one column out of a csv you have to read the whole file, because the values of that column are scattered one per line across every byte in it."],
  ["p","Parquet is the answer to all three at once. It is a binary format that stores a table column by column rather than row by row, records the type of each column in the file itself, compresses each column separately, and splits long tables into chunks called row groups. Reading one column means reading the stretch of the file where that column lives and skipping the rest. Because a column holds one kind of value, compression works far better on it than on a line of mixed text."],
  ["p","The arrow package is the R interface to that world. It reads and writes parquet, and it goes further: a directory of parquet files can be treated as one table, and dplyr verbs can be written against that table and executed without ever loading it into memory. This chapter covers the file format, the directory-as-a-table idea, and the dplyr backend."],
  ["note","The arrow package cannot be installed in this app's R, which runs inside your browser. Every arrow block below is therefore shown with no output — nothing was run to produce one, and none is invented. To run them you need R on a desktop, where install.packages(\"arrow\") works. The file format is not the obstacle: nanoparquet is a small package that reads and writes the same parquet files, it does install here, and every output you see in this chapter came from running its code in this app's runtime."]
]},
{ t: "Writing and reading a parquet file",
  body: [
  ["p","Two packages get attached. nanoparquet supplies write_parquet() and read_parquet(); dplyr supplies the verbs used from section 6 onwards, and attaching it now rather than later keeps the printing in this chapter consistent, for a reason the note below explains."],
  ["code","library(nanoparquet)\nsuppressMessages(library(dplyr))"],
  ["p","Writing takes a data frame and a filename. There is no options ceremony: the types come from the columns, and the compression is chosen for you."],
  ["code","gauges <- data.frame(\n  station = c(\"Alder\", \"Birk\", \"Cotton\", \"Dunlin\"),\n  river = c(\"Ouse\", \"Wye\", \"Ouse\", \"Wye\"),\n  level_m = c(1.24, 0.87, 2.05, 1.61)\n)\n\nwrite_parquet(gauges, \"gauges.parquet\")\nfile.exists(\"gauges.parquet\")"],
  ["code","[1] TRUE"],
  ["p","Reading it back gives a data frame with the same columns and the same values. Nothing had to be told about types, quoting, or which line the header is on, because the file carries all of that."],
  ["code","back <- read_parquet(\"gauges.parquet\")\nback"],
  ["code","# A data frame: 4 × 3\n  station river level_m\n  <chr>   <chr>   <dbl>\n1 Alder   Ouse     1.24\n2 Birk    Wye      0.87\n3 Cotton  Ouse     2.05\n4 Dunlin  Wye      1.61"],
  ["p","That header says data frame rather than tibble, and the object explains why: read_parquet() hands back an ordinary data frame carrying one extra class."],
  ["code","class(back)"],
  ["code","[1] \"tbl\"        \"data.frame\""],
  ["note","The tbl class is what produces the compact header and the row of column types. Printing therefore depends on what else is loaded in your session: with dplyr attached you get the block above, and with nothing but nanoparquet attached the same object prints in the plain data frame style, with row numbers and no type row. That is why this chapter attaches dplyr in the first code block and why every exercise below does the same. An answer that prints a parquet frame will not match the expected output if the printing style has changed underneath it."],
  ["p","The file also knows about itself. read_parquet_info() reports the shape and the layout without reading a single row of data, which is how you check a file you have been handed before deciding what to do with it."],
  ["code","read_parquet_info(\"gauges.parquet\")"],
  ["code","# A data frame: 1 × 7\n  file_name      num_cols num_rows num_row_groups file_size parquet_version\n  <chr>             <int>    <dbl>          <int>     <dbl>           <int>\n1 gauges.parquet        3        4              1       751               1\n# ℹ 1 more variable: created_by <chr>"],
  ["p","Four rows, three columns, one row group, 751 bytes. Note the size: four rows of tiny data in 751 bytes, where the equivalent csv would be under a hundred. A parquet file carries a schema and a block of metadata whether it holds four rows or forty million, so on toy data the format loses. Section 4 is where it starts winning."]
]},
{ t: "Types that survive the trip",
  body: [
  ["p","The type problem is the one that bites quietly. A csv writes a date as characters and a factor as characters, and reading it back gives you characters, because characters are all that was ever in the file. Every script that reads that csv has to redo the conversion, and any script that forgets gets wrong answers rather than an error. Parquet writes the type down."],
  ["code","mixed <- data.frame(\n  day = as.Date(c(\"2026-03-01\", \"2026-03-02\", \"2026-03-03\")),\n  depot = factor(c(\"north\", \"south\", \"north\")),\n  crates = c(12L, 8L, 15L)\n)\n\nwrite_parquet(mixed, \"mixed.parquet\")\nwrite.csv(mixed, \"mixed.csv\", row.names = FALSE)\n\nsapply(read_parquet(\"mixed.parquet\"), class)"],
  ["code","      day     depot    crates \n   \"Date\"  \"factor\" \"integer\" "],
  ["p","A Date came back a Date and a factor came back a factor. The same three columns through the csv arrive flattened."],
  ["code","sapply(read.csv(\"mixed.csv\"), class)"],
  ["code","        day       depot      crates \n\"character\" \"character\"   \"integer\" "],
  ["p","Two of the three lost their type. The integer survived only because read.csv() guessed it correctly from the digits, and that guess is exactly the fragility being described: one row containing a stray letter and the whole column becomes character."],
  ["p","The types live in the file's schema, which you can read directly. r_type is what the column becomes in R; type is how the value is laid out on disk."],
  ["code","read_parquet_schema(\"mixed.parquet\")[, c(\"name\", \"r_type\", \"type\")]"],
  ["code","# A data frame: 4 × 3\n  name   r_type    type      \n  <chr>  <chr>     <chr>     \n1 schema <NA>      <NA>      \n2 day    Date      INT32     \n3 depot  character BYTE_ARRAY\n4 crates integer   INT32     "],
  ["p","A date is stored as a 32-bit integer counting days, which is what R holds underneath anyway, and the schema records that it should come back as a Date. The first row named schema is the root of the tree rather than a column, which is why its types are NA — parquet describes a nested structure and a flat table is the simple case of one."],
  ["note","The schema is why a parquet file is safe to hand to someone else and a csv is not quite. It is also why a script that reads parquet needs no col_types argument and no post-read conversion step. If you find yourself writing as.Date() on every read, the file format is the thing to change, not the script."]
]},
{ t: "Size, and reading only the columns you need",
  body: [
  ["p","Sixty thousand rows is enough for the format's advantages to show. The table below has two columns that repeat a handful of values over and over and one column of numbers — the ordinary shape of logged data."],
  ["code","set.seed(4)\nn <- 60000\nreadings <- data.frame(\n  station = rep(c(\"Alder\", \"Birk\", \"Cotton\", \"Dunlin\", \"Elder\"), length.out = n),\n  river = rep(c(\"Ouse\", \"Wye\"), length.out = n),\n  level_m = round(runif(n, 0.2, 3.4), 2)\n)\n\nwrite.csv(readings, \"readings.csv\", row.names = FALSE)\nwrite_parquet(readings, \"readings.parquet\")\n\nfile.size(\"readings.csv\")\nfile.size(\"readings.parquet\")\nfile.size(\"readings.csv\") > 10 * file.size(\"readings.parquet\")"],
  ["code","[1] 1174787\n[1] 71090\n[1] TRUE"],
  ["p","About 1.17 MB against about 71 KB, more than ten times smaller. The station column is where most of it goes: five distinct names repeated twelve thousand times each, which parquet stores once with a compact code per row, and which the csv spells out in full sixty thousand times. That trick has a name, dictionary encoding, and it is why the repetitive columns you would expect to be expensive are the cheapest ones in a parquet file."],
  ["note","Those two byte counts came from running the block above in this app, so they are real measurements rather than remembered figures. They are not laws. A different version of the writer, a different compression setting, or different data changes them, and your own numbers may not match to the byte. What holds is the shape of the result: repetitive columns compress hard, and the gap widens as the table grows."],
  ["p","The second advantage costs nothing to use. col_select names the columns you want, and the reader skips the rest of the file instead of reading it and throwing it away."],
  ["code","narrow <- read_parquet(\"readings.parquet\", col_select = c(\"station\", \"level_m\"))\n\nnames(narrow)\nnrow(narrow)"],
  ["code","[1] \"station\" \"level_m\"\n[1] 60000"],
  ["p","All sixty thousand rows, two columns instead of three. On three columns this saves little; on a file with two hundred columns where an analysis needs four, it is the difference between a query that runs and a query that fills your memory. There is no csv equivalent, because a csv has no way to find a column without reading every line."]
]},
{ t: "One dataset, many files",
  body: [
  ["p","Large tables are rarely one file. They are written a chunk at a time — a file per day, per region, per run — into a directory, and the whole directory is the table. Parquet has a convention for this: each subdirectory is named column=value, and the value is not stored inside the files at all, because the folder name already says it."],
  ["code","dir.create(\"levels\", showWarnings = FALSE)\ndir.create(\"levels/river=Ouse\", showWarnings = FALSE)\ndir.create(\"levels/river=Wye\", showWarnings = FALSE)\n\nwrite_parquet(gauges[gauges$river == \"Ouse\", c(\"station\", \"level_m\")],\n              \"levels/river=Ouse/part-0.parquet\")\nwrite_parquet(gauges[gauges$river == \"Wye\", c(\"station\", \"level_m\")],\n              \"levels/river=Wye/part-0.parquet\")\n\nlist.files(\"levels\", recursive = TRUE)"],
  ["code","[1] \"river=Ouse/part-0.parquet\" \"river=Wye/part-0.parquet\" "],
  ["p","Reading one file gives one river's rows. This is the layout doing its job: a question about the Ouse touches one file and never opens the other."],
  ["code","parts <- list.files(\"levels\", recursive = TRUE, full.names = TRUE)\n\nread_parquet(parts[1])"],
  ["code","# A data frame: 2 × 2\n  station level_m\n  <chr>     <dbl>\n1 Alder      1.24\n2 Cotton     2.05"],
  ["p","Look at what came back: two columns, not three. The river column is gone, because it was never written — its value is in the directory name."],
  ["code","nrow(read_parquet(\"levels/river=Ouse/part-0.parquet\"))\nnames(read_parquet(\"levels/river=Ouse/part-0.parquet\"))"],
  ["code","[1] 2\n[1] \"station\" \"level_m\""],
  ["p","That is the whole partitioning idea, and it is also its cost: the column has to be put back by whatever reads the directory. Doing it by hand means listing the files, reading each one, parsing its folder name, adding the column, and stacking the results. arrow does all of it. open_dataset() points at the directory, works out the schema from the files, recovers river from the folder names, and returns a Dataset object that has read none of the rows."],
  ["code","library(arrow)\n\nwrite_dataset(readings, \"levels_arrow\", format = \"parquet\", partitioning = \"river\")\n\nlevels_ds <- open_dataset(\"levels_arrow\", format = \"parquet\")"],
  ["note","The block above is arrow, so it is shown without output — it cannot run in this app. Note the pattern it teaches even so: partition on a column you filter by often and that has few distinct values. A partition per river is useful. A partition per reading timestamp gives you one file per row, thousands of tiny files, and a directory that is slower to open than the single file you started with."]
]},
{ t: "dplyr over data you have not loaded",
  body: [
  ["p","The part of arrow worth the install is the dplyr backend. Verbs written against a Dataset are not executed — they are recorded, translated, and held. Nothing happens until collect() asks for the answer, and then arrow runs the whole recorded query at once, reading only the partitions and columns the query actually needs and handing back an ordinary data frame."],
  ["code","levels_ds |>\n  filter(river == \"Ouse\", level_m > 3) |>\n  group_by(station) |>\n  summarise(sightings = n(), mean_level = mean(level_m)) |>\n  collect()"],
  ["p","Two things in that pipeline are doing invisible work. The filter on river is a partition the reader can skip files by, so the Wye files are never opened. The columns named are the only ones read. A query over a hundred gigabytes that touches two columns of one partition reads a few hundred megabytes, which is why this works on data that does not fit in memory."],
  ["p","The verbs are the ones from chapters 3 and 4, and the same pipeline runs unchanged over a data frame you have loaded. Here it is against the sixty thousand rows from section 4, which are in memory, so the answer comes back directly."],
  ["code","readings |>\n  filter(level_m > 3.3) |>\n  group_by(station) |>\n  summarise(sightings = n(), mean_level = round(mean(level_m), 3)) |>\n  arrange(station)"],
  ["code","# A tibble: 5 × 3\n  station sightings mean_level\n  <chr>       <int>      <dbl>\n1 Alder         337       3.35\n2 Birk          322       3.35\n3 Cotton        350       3.35\n4 Dunlin        342       3.35\n5 Elder         359       3.35"],
  ["p","Reading from the file with col_select and then summarising is the same idea at a smaller scale: name the columns, let the reader skip the others, group and summarise what comes back."],
  ["code","read_parquet(\"readings.parquet\", col_select = c(\"river\", \"level_m\")) |>\n  group_by(river) |>\n  summarise(rows = n(), highest = max(level_m)) |>\n  arrange(river)"],
  ["code","# A tibble: 2 × 3\n  river  rows highest\n  <chr> <int>   <dbl>\n1 Ouse  30000     3.4\n2 Wye   30000     3.4"],
  ["p","Thirty thousand rows each, and both rivers reach the top of the generated range. The difference between this and the arrow version is when the reading happens: here the whole column pair comes into memory first and dplyr works on it afterwards, where arrow pushes the filtering down into the reading and never materialises the rows it does not want."]
]},
{ t: "What goes wrong",
  body: [
  ["p","The errors are short and they say what they mean, which is a change from csv reading. A missing file stops at the open."],
  ["code","read_parquet(\"missing.parquet\")"],
  ["code","Error: Can't open Parquet file at 'missing.parquet' @ lib/ParquetReader.cpp:62"],
  ["p","A column name that is not in the file stops at the schema, before any data is read. Compare that with a csv, where asking for a column that is not there gives you NULL and a script that carries on computing with nothing."],
  ["code","read_parquet(\"gauges.parquet\", col_select = c(\"statoin\"))"],
  ["code","Error: Column statoin does not exist in Parquet file"],
  ["p","The third mistake belongs to arrow and has no error attached to it. A pipeline without collect() returns the recorded query rather than the answer, and the query object prints as a description of the work to be done. Nothing failed, so nothing complains, and the result you pass on to the next step is a plan rather than data."],
  ["code","levels_ds |>\n  filter(level_m > 3) |>\n  summarise(n = n())"],
  ["note","That block is arrow again, so it carries no output. The habit to build is that a pipeline against a Dataset ends in collect(), every time, and that anything surprising downstream should send you back to check whether it did. The related trap is names: arrow and nanoparquet both export read_parquet() and write_parquet(), so attaching both means whichever came last wins and the other is masked. Attach one, or write nanoparquet::read_parquet() to say which you mean."]
]},
{ t: "Summary",
  body: [
  ["p","A parquet file stores a table column by column, in binary, with the type of each column recorded in the file and each column compressed on its own. That buys three things a csv cannot offer: files many times smaller on repetitive data, types that survive the round trip so a Date comes back a Date, and the ability to read a few columns without reading the whole file. write_parquet() and read_parquet() are the two calls, read_parquet_info() and read_parquet_schema() describe a file without reading it, and col_select limits what comes back."],
  ["p","A directory of parquet files with subdirectories named column=value is one table split into pieces. The partition column lives in the folder names rather than in the files, so anything reading the directory has to put it back — and a filter on that column becomes a decision about which files to open at all. Partition on columns you filter by often and that have few distinct values, or you end up with thousands of tiny files and a slower table than you began with."],
  ["p","arrow is the package that turns a directory into something you can write dplyr against. Verbs on a Dataset are recorded rather than run, collect() executes the whole query, and only the needed columns and partitions are read, which is what makes the approach work on data larger than memory. arrow cannot install in this app, so its blocks were shown without output; nanoparquet handled the file-level work you saw run, and the two share function names, so attach one at a time."],
  ["p","Answer the practice questions from memory before revealing the answers, then clear the graded exercises below. The next chapter is hierarchical data: what to do when the thing you have been handed is not a rectangle at all but lists nested inside lists, and how to unnest it into one."]
]}
],
questions: [
{ q:"Name the three costs of csv that parquet is designed to remove.",
  a:"Size, because a csv compresses nothing and spells every repeated value out in full. Types, because a csv holds only characters and whatever reads it has to guess. Reading cost, because the values of one column are scattered across every line, so getting one column means reading the whole file." },
{ q:"What does it mean to say parquet is columnar, and what does that buy you at read time?",
  a:"The values of one column are stored together in a stretch of the file rather than interleaved with the other columns row by row. Reading one column then means reading its stretch and skipping the rest, which is what col_select exploits, and it also means compression works on a run of similar values instead of a line of mixed ones." },
{ q:"back <- read_parquet(\"gauges.parquet\"). What does class(back) report, and why does that matter for what you see printed?",
  a:"\"tbl\" and \"data.frame\". The extra tbl class is what produces the compact header and the row of column types, but only when a package supplying that printing is loaded — with dplyr attached you get the tibble-style block, and without it the same object prints in the plain data frame style with row numbers." },
{ q:"A file of four rows came out at 751 bytes, larger than the same data as csv. Is that a fault in the format?",
  a:"No. A parquet file carries a schema and a block of metadata whose size barely depends on the number of rows, so on toy data that overhead is most of the file. The format is built for tables where the overhead is a rounding error, and the advantage grows with the row count." },
{ q:"Write a data frame with a Date column and a factor column to both csv and parquet, then read both back. What differs?",
  a:"Through parquet both come back as they went in, a Date and a factor, because the types are recorded in the file's schema. Through csv both come back as character, because a csv stores only characters and read.csv() has nothing but the digits and letters to guess from." },
{ q:"What does read_parquet_info() tell you, and what makes it cheap?",
  a:"The file name, the number of columns and rows, the number of row groups, the file size, the parquet version, and who wrote it. It is cheap because all of that lives in the file's metadata block, so it answers without reading any of the data." },
{ q:"A directory holds levels/river=Ouse/part-0.parquet and levels/river=Wye/part-0.parquet. Read one of those files directly and the river column is missing. Why?",
  a:"Because it was never written into the file. The partition value is carried by the directory name in the column=value convention, which is what makes it free to store and what lets a reader skip whole files when you filter on it. Anything reading the directory has to put the column back, which is one of the jobs open_dataset() does for you." },
{ q:"What is the rule for choosing a column to partition on, and what happens if you get it wrong?",
  a:"Partition on a column you filter by often and that has few distinct values. Partition on something close to unique, like a timestamp, and you get one file per row — thousands of tiny files, each with its own metadata block, which is slower to open than the single file you started with." },
{ q:"You wrote a dplyr pipeline against a Dataset from open_dataset() and left off collect(). What do you get back, and does anything complain?",
  a:"The recorded query rather than the answer, and nothing complains — the verbs against a Dataset are translated and held, not executed. It prints as a description of the work to be done, and the trouble arrives further downstream where a plan is being used as if it were data." },
{ q:"Both arrow and nanoparquet export read_parquet(). What happens if you attach both, and how do you avoid the problem?",
  a:"Whichever package was attached second wins and the other version is masked, so calls silently go to a function you did not mean. Attach one of the two, or qualify the call with the package name, as in nanoparquet::read_parquet(), which never depends on attach order." }
],
exercises: [
{ c:"data frames", t:"Types out and back", book:"r22",
  b:"Attach nanoparquet and dplyr (suppress dplyr's attach messages). Build a data frame named kilns with a Date column fired_on holding 2026-05-16, 2026-05-02 and 2026-05-09 in that order, a factor column glaze holding \"matte\", \"gloss\", \"matte\", and an integer column pots holding 19, 24, 31. Write it to \"kilns.parquet\", read it back into back, then print the class of each column of back and, below that, back arranged by fired_on.",
  o:" fired_on     glaze      pots \n   \"Date\"  \"factor\" \"integer\" \n# A data frame: 3 × 3\n  fired_on   glaze  pots\n  <date>     <fct> <int>\n1 2026-05-02 gloss    24\n2 2026-05-09 matte    31\n3 2026-05-16 matte    19",
  h:["Dates are made with as.Date() over a character vector, a factor with factor(), and integers by writing the L suffix on the numbers.",
     "sapply() over a data frame applies a function to every column, so sapply(back, class) gives one class per column. The arranging is a dplyr verb.",
     "Write the frame, read it back, then two expressions on two lines: sapply() with class over back, then arrange() with back and the column to order by. Attach both packages first or neither the writing nor the printing will match."]},
{ c:"tibbles & pipes", t:"Only the columns you asked for", book:"r22",
  b:"Attach nanoparquet and dplyr (suppressing dplyr's messages). Build a data frame named hives with apiary holding \"Ridge\", \"Marsh\", \"Ridge\", \"Fen\", \"Marsh\", \"Fen\"; hive holding \"h1\" through \"h6\" in order; and honey_kg holding 14.2, 9.8, 17.5, 11.1, 12.4, 8.3. Write it to \"hives.parquet\". Then read the file back taking only the apiary and honey_kg columns, and in one pipeline sort the result from heaviest to lightest and keep the top three.",
  o:"# A data frame: 3 × 2\n  apiary honey_kg\n* <chr>     <dbl>\n1 Ridge      17.5\n2 Ridge      14.2\n3 Marsh      12.4",
  h:["read_parquet() takes a col_select argument naming the columns you want, so the hive column never has to be read at all.",
     "Descending order is arrange() wrapped around desc(), and keeping the first few rows is head() with a number. The native pipe |> carries the frame from one to the next.",
     "The shape is read_parquet(file, col_select = c(...)) piped into arrange(desc(column)) and then into head(3). Attach both packages first, or the printing will not match."]},
{ c:"grouping & summaries", t:"Crates by port", book:"r22",
  b:"Attach nanoparquet and dplyr (suppressing dplyr's messages). Build a data frame named hauls with port holding \"Rye\", \"Hoy\", \"Rye\", \"Fowey\", \"Hoy\", \"Rye\" and an integer column crates holding 12, 7, 15, 9, 11, 6. Write it to \"hauls.parquet\". Then read the file back and, in one pipeline, report for each port the number of rows in a column named trips and the sum of crates in a column named total, ordered by port name.",
  o:"# A tibble: 3 × 3\n  port  trips total\n  <chr> <int> <int>\n1 Fowey     1     9\n2 Hoy       2    18\n3 Rye       3    33",
  h:["Grouping and summarising are the dplyr verbs from chapter 3, and they work on whatever read_parquet() hands back.",
     "n() counts the rows in a group and takes no arguments; sum() adds a column up. Both go inside one summarise() call, each with the name you want given to it.",
     "Read the file, pipe into group_by() with the port column, then summarise() with trips = n() and total = sum(...), then arrange() by port. Write the crates with the L suffix so they stay integers."]},
{ c:"data frames", t:"Two files, one table", book:"r22",
  b:"Attach nanoparquet and dplyr (suppressing dplyr's messages). Build a data frame named north with plot holding \"n1\", \"n2\" and yield_t holding 3.4, 2.9, and a data frame named south with plot holding \"s1\", \"s2\" and yield_t holding 4.1, 3.7. Write them to \"north.parquet\" and \"south.parquet\". Read both files back, stack them into one data frame named both, then print the number of rows in both and, below that, both arranged by plot.",
  o:"[1] 4\n# A data frame: 4 × 2\n  plot  yield_t\n  <chr>   <dbl>\n1 n1        3.4\n2 n2        2.9\n3 s1        4.1\n4 s2        3.7",
  h:["Stacking two frames with the same columns on top of each other is one base R function, and it takes the frames as its arguments.",
     "rbind() is that function. It can take the two read_parquet() calls directly, without storing each result in its own variable first.",
     "Assign rbind() over the two read_parquet() calls to both, then two expressions on two lines: nrow() of both, then arrange() of both by the plot column."]}
]
};
