/* Practice Log book — R Chapter 23: Hierarchical data.
   Original lesson text following the chapter-by-chapter curriculum of
   "R for Data Science" (2nd ed.) by Hadley Wickham, Mine Cetinkaya-Rundel,
   and Garrett Grolemund. Read the original chapter free at the src link below.
   Every shown output was captured by executing the code in WebR, not written from memory. */
window.BOOK_R = window.BOOK_R || { chapters: {} };
window.BOOK_R.chapters.r23 = {
n: 23,
title: "Hierarchical data",
src: "https://r4ds.hadley.nz/rectangling.html",
blurb: "Lists nested inside a data frame, and the tidyr functions that flatten them back into columns and rows.",
pkgs: ["tidyr", "dplyr", "tibble", "jsonlite"],
sections: [
{ t: "Lists, and why they turn up in tables",
  body: [
  ["p","A vector holds many values of one type. A list holds many values of any types, including other lists, and that second property is what makes it the shape data arrives in when it comes from anywhere other than a spreadsheet. An API response, a configuration file, a survey where one respondent answered three questions and the next answered nine — none of those are rectangles, and all of them are lists."],
  ["p","Rectangling is the name for turning that shape into a data frame you can use. It is not one function; it is a small set of moves applied repeatedly until nothing nested is left. This chapter is those moves."],
  ["p","Three packages are needed. tidyr supplies the rectangling functions, dplyr supplies the verbs used on the results, and jsonlite parses JSON in the last section. Attaching dplyr prints the notice covered in chapter 3; tidyr and jsonlite are silent."],
  ["code",'library(tidyr)\nlibrary(dplyr)\nlibrary(jsonlite)'],
  ["code","\nAttaching package: ‘dplyr’\n\nThe following objects are masked from ‘package:stats’:\n\n    filter, lag\n\nThe following objects are masked from ‘package:base’:\n\n    intersect, setdiff, setequal, union"],
  ["p","str() is the tool for looking at a list. It prints the structure rather than the contents, which is what you need when the contents are large. An unnamed list of three different types looks like this."],
  ["code",'x <- list(1, "wren", TRUE)\n\nstr(x)'],
  ["code","List of 3\n $ : num 1\n $ : chr \"wren\"\n $ : logi TRUE"],
  ["p","Each element gets a line, with its type and its value. Give the elements names and the names appear where the blank was, which is the difference between a list you can address by position and one you can address by name."],
  ["code",'one <- list(species = "wren", eggs = 5, rings = c("AX1", "AX2"))\n\nstr(one)'],
  ["code","List of 3\n $ species: chr \"wren\"\n $ eggs   : num 5\n $ rings  : chr [1:2] \"AX1\" \"AX2\""],
  ["p","Two of those elements hold one value and the third holds two, shown as chr [1:2]. That is the hierarchy in miniature: a named list whose elements are not all the same length. Written into a table it would be one row and three columns, except that one of the cells contains two things."],
  ["note","Read str() output as a tree, not as a table. The indentation is the depth, and the depth is what determines how many rectangling steps you will need. A list of lists of lists takes three passes, and trying to do it in one call is how people end up with a column of unusable rubbish."]
]},
{ t: "List-columns",
  body: [
  ["p","A data frame column is usually a vector, and a vector cannot hold a list. But a column can be a list, and then each cell of that column is one element of the list — which can be anything at all. That is a list-column, and it is how hierarchical data sits inside a tibble until you flatten it."],
  ["p","Below, a nature reserve records three nest boxes. The box column is ordinary text. The record column is a list, and each of its three elements is itself a named list holding a species and an egg count."],
  ["code",'boxes <- tibble(\n  box    = c("B1", "B2", "B3"),\n  record = list(\n    list(species = "wren", eggs = 5),\n    list(species = "tit", eggs = 8),\n    list(species = "robin", eggs = 4)\n  )\n)\n\nboxes'],
  ["code","# A tibble: 3 × 2\n  box   record          \n  <chr> <list>          \n1 B1    <named list [2]>\n2 B2    <named list [2]>\n3 B3    <named list [2]>"],
  ["p","The type line reads <list>, and the cells describe their contents instead of showing them: a named list of length 2 in each row. That description is all a tibble will ever print for a list-column, however small the contents are, because there is no sensible way to fit an arbitrary object into a cell."],
  ["p","To see inside one cell, index into the list twice — once to reach the column, once to reach the element. A single bracket would hand back a one-element list; the double bracket hands back the thing itself."],
  ["code",'boxes$record[[1]]'],
  ["code","$species\n[1] \"wren\"\n\n$eggs\n[1] 5"],
  ["p","Two functions answer most questions about a list-column without printing any of it. lengths() gives the length of every element, and names() gives the names inside one of them."],
  ["code",'lengths(boxes$record)\nnames(boxes$record[[1]])'],
  ["code","[1] 2 2 2\n[1] \"species\" \"eggs\"   "],
  ["p","All three elements have two components, and those components are called species and eggs. Equal lengths and shared names are exactly the conditions under which the next section's function does something useful, so this pair of checks is the right thing to run before rectangling anything."],
  ["note","boxes$record[1] and boxes$record[[1]] look almost the same and differ in kind. The single bracket returns a list containing one element, so it prints with an extra layer of wrapping and every function you pass it to sees a list. The double bracket returns the element. When a rectangling call complains about a type you are sure you got right, count the brackets first."]
]},
{ t: "unnest_wider(): elements become columns",
  body: [
  ["p","When every element of a list-column is a named list with the same names, those names are columns waiting to happen. unnest_wider() makes them columns: one new column per name, one value per row."],
  ["code",'unnest_wider(boxes, record)'],
  ["code","# A tibble: 3 × 3\n  box   species  eggs\n  <chr> <chr>   <dbl>\n1 B1    wren        5\n2 B2    tit         8\n3 B3    robin       4"],
  ["p","Three rows in, three rows out. Wider means the table gains columns and keeps its height, which is the way to remember which of the two unnesting functions you want. The record column is gone, replaced by the two columns that were inside it."],
  ["p","A named vector works the same way, because the names are what matter rather than whether the element is a list. Here each cell holds two counts labelled by month."],
  ["code",'counts <- tibble(\n  box   = c("B1", "B2"),\n  tally = list(c(may = 3L, june = 5L), c(may = 1L, june = 2L))\n)\n\nunnest_wider(counts, tally)'],
  ["code","# A tibble: 2 × 3\n  box     may  june\n  <chr> <int> <int>\n1 B1        3     5\n2 B2        1     2"],
  ["p","Without names there is nothing to call the new columns, and the function refuses rather than inventing something."],
  ["code",'plain <- tibble(\n  box     = c("B1", "B2"),\n  reading = list(c(3L, 5L), c(1L, 2L))\n)\n\nunnest_wider(plain, reading)'],
  ["code","Error: In column: `reading`."],
  ["p","That error is unhelpfully short in this app's console, and the fix is to supply the naming scheme yourself. names_sep glues the column name to the position of each element."],
  ["code",'unnest_wider(plain, reading, names_sep = "_")'],
  ["code","# A tibble: 2 × 3\n  box   reading_1 reading_2\n  <chr>     <int>     <int>\n1 B1            3         5\n2 B2            1         2"],
  ["note","names_sep is worth using even when the names exist. Unnesting a record column that contains box produces a bare column called box beside the one you already had, and the collision is resolved in ways you will not enjoy tracing. names_sep = \"_\" would have made it record_box, which is both unambiguous and a record of where the value came from."]
]},
{ t: "unnest_longer(): elements become rows",
  body: [
  ["p","The other move is for cells that hold several observations rather than several fields. A box visited on three days does not want three columns; it wants three rows. unnest_longer() gives one row per element, repeating the other columns to fill them."],
  ["code",'visits <- tibble(\n  box  = c("B1", "B2", "B3"),\n  days = list(c(2L, 9L), c(4L), c(1L, 6L, 11L))\n)\n\nvisits'],
  ["code","# A tibble: 3 × 2\n  box   days     \n  <chr> <list>   \n1 B1    <int [2]>\n2 B2    <int [1]>\n3 B3    <int [3]>"],
  ["p","The cells describe themselves as integer vectors of length 2, 1 and 3. Six values in total sit in that column, so the unnested table has six rows."],
  ["code",'unnest_longer(visits, days)'],
  ["code","# A tibble: 6 × 2\n  box    days\n  <chr> <int>\n1 B1        2\n2 B1        9\n3 B2        4\n4 B3        1\n5 B3        6\n6 B3       11"],
  ["p","B1 appears twice, B3 three times, and the days column is now a plain integer column. Longer means the table gains rows and keeps its columns, and the row count is the sum of the lengths you saw with lengths()."],
  ["p","When the elements are named, those names are information too, and unnest_longer() keeps them in a second column rather than throwing them away. Recall counts from the previous section, whose cells hold values labelled may and june."],
  ["code",'unnest_longer(counts, tally)'],
  ["code","# A tibble: 4 × 3\n  box   tally_id tally\n  <chr> <chr>    <int>\n1 B1    may          3\n2 B1    june         5\n3 B2    may          1\n4 B2    june         2"],
  ["p","One column of values, one column of the names those values had, called tally_id after the column it came from. That is the same data as the wide version from the previous section, in tidy form: one row per box per month. Which of the two you want depends on whether month is a variable you will group by, in which case this shape, or a fixed pair of fields, in which case the other."],
  ["note","The two functions are not interchangeable and choosing wrongly is not obviously wrong. unnest_wider() on the tally column gives a two-row table with columns may and june; unnest_longer() gives a four-row table with a month column. Both run, both look fine, and only one of them lets you write group_by(tally_id). Decide by asking whether the names are field names or values of a variable."]
]},
{ t: "When the pieces do not match",
  body: [
  ["p","Everything so far assumed the elements were the same shape. Data from the wild is not, and both functions have an answer for each way it goes wrong."],
  ["p","Missing and extra names are handled by taking the union: every name that appears anywhere becomes a column, and rows that lacked it get NA."],
  ["code",'mixed <- tibble(\n  box    = c("B1", "B2", "B3"),\n  record = list(\n    list(species = "wren", eggs = 5),\n    list(species = "tit"),\n    list(eggs = 4, ringed = TRUE)\n  )\n)\n\nunnest_wider(mixed, record)'],
  ["code","# A tibble: 3 × 4\n  box   species  eggs ringed\n  <chr> <chr>   <dbl> <lgl> \n1 B1    wren        5 NA    \n2 B2    tit        NA NA    \n3 B3    <NA>        4 TRUE  "],
  ["p","Three different record shapes became four columns with NA in the gaps. Note that the ringed column is logical and only one row ever had a value for it — a column that is almost entirely NA is a signal that the field is rare, not that the unnesting went wrong."],
  ["p","Empty elements are the other case, and unnest_longer() drops them by default. A box that was never visited has NULL where its days should be, and NULL has length zero, so it contributes no rows."],
  ["code",'gaps <- tibble(\n  box  = c("B1", "B2", "B3"),\n  days = list(c(2L, 9L), NULL, c(1L))\n)\n\nunnest_longer(gaps, days)'],
  ["code","# A tibble: 3 × 2\n  box    days\n  <chr> <int>\n1 B1        2\n2 B1        9\n3 B3        1"],
  ["p","B2 has vanished. That is often correct and occasionally a disaster, so there is an argument for it. keep_empty gives the empty elements one row each with NA in the unnested column."],
  ["code",'unnest_longer(gaps, days, keep_empty = TRUE)'],
  ["code","# A tibble: 4 × 2\n  box    days\n  <chr> <int>\n1 B1        2\n2 B1        9\n3 B2       NA\n4 B3        1"],
  ["p","Four rows, and every box still accounted for. Use keep_empty whenever the rows of the outer table are the things you are counting — boxes, customers, patients — because losing one silently changes a denominator."],
  ["note","This is the mistake that survives review. unnest_longer() on a list-column with a few NULL elements returns a table that is entirely correct, entirely plausible, and missing rows nobody asked it to remove. Compare nrow() before and after, or count the distinct values of the outer key, every time. The default is a reasonable default and it is still a data loss."]
]},
{ t: "hoist(), and going deeper",
  body: [
  ["p","Unnesting takes one layer at a time, and deeply nested data needs several calls. When you want two fields out of a five-field structure that is three levels deep, unnesting the whole thing to reach them is wasteful and produces columns you immediately drop."],
  ["p","hoist() pulls named components out to the top level and leaves the rest where it is. Each argument is the new column name, and its value is the path: a string for one level, a list of strings for several."],
  ["code",'deep <- tibble(\n  box    = c("B1", "B2"),\n  record = list(\n    list(species = "wren", clutch = list(eggs = 5, hatched = 4), site = "copse"),\n    list(species = "tit",  clutch = list(eggs = 8, hatched = 8), site = "hedge")\n  )\n)\n\nhoist(deep, record, species = "species", eggs = list("clutch", "eggs"))'],
  ["code","# A tibble: 2 × 4\n  box   species  eggs record          \n  <chr> <chr>   <dbl> <list>          \n1 B1    wren        5 <named list [2]>\n2 B2    tit         8 <named list [2]>"],
  ["p","Two new columns, and record survives holding what was left: the site and the rest of the clutch. That is why the remaining lists are length 2 rather than 3 — hoisting removes what it takes."],
  ["p","The alternative is to unnest each layer in turn, which is the right move when you want everything. The clutch column produced by the first call is itself a list-column, so the second call goes to work on it."],
  ["code",'deep |> unnest_wider(record) |> unnest_wider(clutch)'],
  ["code","# A tibble: 2 × 5\n  box   species  eggs hatched site \n  <chr> <chr>   <dbl>   <dbl> <chr>\n1 B1    wren        5       4 copse\n2 B2    tit         8       8 hedge"],
  ["p","Five columns and nothing nested left. Two calls, one per level, and reading them in order tells you exactly how deep the original was."],
  ["p","There is a third case: a list-column whose elements are already data frames. unnest() handles that one, adding both the rows and the columns at once."],
  ["code",'frames <- tibble(\n  round = c("first", "second"),\n  table = list(\n    tibble(box = c("B1", "B2"), found = c(TRUE, FALSE)),\n    tibble(box = "B3", found = TRUE)\n  )\n)\n\nframes |> unnest(table)'],
  ["code","# A tibble: 3 × 3\n  round  box   found\n  <chr>  <chr> <lgl>\n1 first  B1    TRUE \n2 first  B2    FALSE\n3 second B3    TRUE "],
  ["note","hoist() is the one to reach for when the nested structure is large and you want three things out of it. Unnesting a wide record to get at two fields gives you thirty columns to select from, and every one of them is a name you now have to know. The path syntax is the cost: list(\"clutch\", \"eggs\") means go into clutch, then take eggs, and getting the nesting of that list wrong is the usual reason hoist() returns a column of NULL."]
]},
{ t: "Rectangling parsed JSON",
  body: [
  ["p","JSON is the format most hierarchical data arrives in, and its two container types map straight onto R's. A JSON object becomes a named list; a JSON array becomes an unnamed list. Once it is parsed, it is a list, and everything in this chapter applies unchanged."],
  ["p","jsonlite's fromJSON() does the parsing. Its default behaviour is to guess at rectangles and simplify them into vectors and data frames, which sounds helpful and makes the result depend on the data — the same call gives different shapes for different inputs. Setting simplifyVector to FALSE turns that off, so you always get plain lists and can do the rectangling deliberately."],
  ["code",'raw <- \'[\n  {"box": "B1", "species": "wren", "clutch": {"eggs": 5, "hatched": 4}},\n  {"box": "B2", "species": "tit",  "clutch": {"eggs": 8, "hatched": 8}}\n]\'\n\nparsed <- fromJSON(raw, simplifyVector = FALSE)\n\nstr(parsed, max.level = 2)'],
  ["code","List of 2\n $ :List of 3\n  ..$ box    : chr \"B1\"\n  ..$ species: chr \"wren\"\n  ..$ clutch :List of 2\n $ :List of 3\n  ..$ box    : chr \"B2\"\n  ..$ species: chr \"tit\"\n  ..$ clutch :List of 2"],
  ["p","The outer array is a list of 2, each element a named list of 3, and the clutch inside each is a list of 2 that max.level stopped short of printing. Limiting the depth is essential with real responses, which are otherwise thousands of lines."],
  ["p","Getting that into a tibble is one line: a list becomes a list-column by being handed to tibble() as a column."],
  ["code",'survey <- tibble(entry = parsed)\n\nsurvey'],
  ["code","# A tibble: 2 × 1\n  entry           \n  <list>          \n1 <named list [3]>\n2 <named list [3]>"],
  ["p","One column, two rows, each a named list of three. From here the moves are the ones already covered: widen the outer level, then widen the level below it."],
  ["code",'survey |>\n  unnest_wider(entry) |>\n  unnest_wider(clutch)'],
  ["code","# A tibble: 2 × 4\n  box   species  eggs hatched\n  <chr> <chr>   <int>   <int>\n1 B1    wren        5       4\n2 B2    tit         8       8"],
  ["p","A rectangle, from a string of JSON, in three calls. The last pattern worth knowing is the one-to-many case, where a field holds an array of records rather than a single record. Widening that field would be wrong, because its elements are observations. Lengthen first, then widen."],
  ["code",'rounds <- tibble(\n  plot  = c("P1", "P2"),\n  walks = list(\n    list(list(day = 3L, birds = 2L), list(day = 9L, birds = 5L)),\n    list(list(day = 4L, birds = 1L))\n  )\n)\n\nrounds |>\n  unnest_longer(walks) |>\n  unnest_wider(walks)'],
  ["code","# A tibble: 3 × 3\n  plot    day birds\n  <chr> <int> <int>\n1 P1        3     2\n2 P1        9     5\n3 P2        4     1"],
  ["p","unnest_longer() turned two plots into three walks, then unnest_wider() turned each walk's fields into columns. That pair — longer to make the rows, wider to make the columns — is the core rectangling idiom, and most nested API data comes apart under it repeated a few times."],
  ["note","Fetching the JSON is a separate problem from rectangling it. This app has no network access from R, so every example here parses a string that is written into the code. On a desktop you would read a file or call an endpoint and pass the result to fromJSON(); nothing after that line changes. Chapter 24 covers getting the data in the first place."]
]},
{ t: "Summary",
  body: [
  ["p","Hierarchical data is data whose pieces are not all the same shape, and in R it is held in lists. A list-column is a data frame column that is a list, so each cell can hold anything; a tibble prints such a column as <list> and describes each cell rather than showing it. str() reads the structure, lengths() reports how big each cell is, and names() reports what is inside one, and those three checks are what you run before touching anything."],
  ["p","Two functions do the flattening. unnest_wider() turns the names inside each element into columns, keeping the row count, and needs names — supply names_sep when there are none, and use it anyway to record where each column came from. unnest_longer() turns the elements into rows, keeping the columns, and puts element names into a companion _id column. Elements of different shapes are unioned, with NA in the gaps; empty elements are dropped unless keep_empty is TRUE, which is the quiet data loss to watch for."],
  ["p","Deeper structures need one call per level, or hoist() to pull specific components out by path and leave the rest nested. A list-column of data frames comes apart with unnest(). JSON is the common source: fromJSON() with simplifyVector = FALSE gives plain lists whose shape does not depend on the data, a list becomes a list-column simply by being made a column, and the idiom for nested arrays of records is unnest_longer() to make the rows and then unnest_wider() to make the columns."],
  ["p","Answer the practice questions from memory before revealing the answers, then clear the graded exercises below. The next chapter is web scraping: pulling data out of HTML pages that were built for people to read rather than for programs to parse, which produces exactly the kind of nested mess this chapter flattens."]
]}
],
questions: [
{ q:"What is a list-column, and what does a tibble print in its cells?",
  a:"A column whose values are a list, so each cell can hold any object, including another list. The tibble prints <list> as the column type and a description of each cell rather than its contents — <named list [2]> for a two-element named list, <int [3]> for a three-element integer vector." },
{ q:"boxes$record[1] and boxes$record[[1]] both look reasonable. What is the difference?",
  a:"The single bracket returns a list containing one element, so anything you pass it to sees a list with an extra layer of wrapping. The double bracket returns the element itself, which is what you want when inspecting a cell." },
{ q:"unnest_wider() and unnest_longer() both flatten a list-column. Which dimension does each one grow?",
  a:"unnest_wider() adds columns and keeps the row count: three rows of two-element records become three rows and two extra columns. unnest_longer() adds rows and keeps the columns: cells of length 2, 1 and 3 become six rows. Wider grows sideways, longer grows downwards." },
{ q:"Why does unnest_wider() fail on a list-column of unnamed vectors, and what fixes it?",
  a:"There is nothing to call the new columns, so it stops with an error rather than inventing names. names_sep = \"_\" fixes it by gluing the column name to each element's position, giving reading_1 and reading_2." },
{ q:"A list-column of named vectors is passed to unnest_longer(). What extra column appears and what is it called?",
  a:"A companion column holding the names, called the column name with _id appended — tally becomes tally_id beside tally. The names are data, so they are kept as a column rather than discarded." },
{ q:"Three elements of a list-column have different names: one has species and eggs, one has only species, one has eggs and ringed. What does unnest_wider() return?",
  a:"A table with the union of the names as columns — species, eggs and ringed — and NA wherever a row lacked that name. Three rows in, three rows out, with four columns counting the original box column." },
{ q:"A list-column holds NULL in one of its cells. What does unnest_longer() do with that row by default, and how do you change it?",
  a:"It drops the row, because NULL has length zero and so contributes no rows. keep_empty = TRUE gives it one row with NA in the unnested column. Compare nrow() before and after, since the default loses rows without saying so." },
{ q:"When would you use hoist() instead of unnest_wider(), and how is a nested path written?",
  a:"When the structure is large and you want a few named things out of it, rather than every field as its own column. Each argument names a new column and gives its path: a string for one level, a list of strings for deeper — eggs = list(\"clutch\", \"eggs\") means go into clutch, then take eggs. What is not hoisted stays nested in the original column." },
{ q:"Why pass simplifyVector = FALSE to fromJSON()?",
  a:"By default jsonlite guesses which parts of the JSON are rectangular and simplifies them into vectors and data frames, so the shape you get back depends on the data rather than on your code. FALSE returns plain lists every time, leaving the rectangling to be done deliberately with tidyr." },
{ q:"A parsed JSON field holds an array of records — several observations per row. Which two calls flatten it, and in what order?",
  a:"unnest_longer() first, to turn each record into its own row, then unnest_wider() on the same column, to turn each record's fields into columns. Widening first would be wrong, because the elements of the array are observations rather than fields." }
],
exercises: [
{ c:"tibbles & pipes", t:"Build a list-column", book:"r23",
  b:"Attach tidyr and dplyr inside suppressPackageStartupMessages() so no attach notice reaches your output. Build a tibble named kits with a character column kit holding \"K1\", \"K2\", \"K3\" and a list column parts whose three elements are the character vectors c(\"bolt\", \"nut\"), c(\"washer\"), and c(\"bolt\", \"clip\", \"nut\"), in that order. Print the tibble, then on the next line print the length of each element of the parts column.",
  o:"# A tibble: 3 × 2\n  kit   parts    \n  <chr> <list>   \n1 K1    <chr [2]>\n2 K2    <chr [1]>\n3 K3    <chr [3]>\n[1] 2 1 3",
  h:["A list-column is made the same way as any other column — the value you give tibble() just happens to be a list.",
     "list() takes the three vectors as its three arguments, so the column is list(c(...), c(...), c(...)) and not c(...) of three things. One function reports the length of every element of a list in one call.",
     "Two printed results are wanted, so end with two separate lines: the tibble on its own, then a call over the parts column reached with the dollar sign. The cells will print as <chr [n]> rather than showing the words."]},
{ c:"tidy data", t:"Readings into columns", book:"r23",
  b:"Attach tidyr and dplyr inside suppressPackageStartupMessages(). Build a tibble named logs with a character column site holding \"S1\", \"S2\", \"S3\" and a list column reading whose three elements are list(temp = 12, wind = 4), list(temp = 9, wind = 7), and list(temp = 15, wind = 2). Flatten the reading column so that temp and wind become columns of their own, then sort by site and print.",
  o:"# A tibble: 3 × 3\n  site   temp  wind\n  <chr> <dbl> <dbl>\n1 S1       12     4\n2 S2        9     7\n3 S3       15     2",
  h:["Every element is a named list with the same two names, and those names are what the new columns should be called.",
     "This is the widening move: the table should keep its three rows and gain two columns. The function takes the tibble and the name of the list-column to flatten.",
     "Build the tibble, pipe it into the unnesting function with reading as the column, then pipe into arrange(). Nothing needs names_sep here, because the elements already carry names."]},
{ c:"tidy data", t:"One row per stop", book:"r23",
  b:"Attach tidyr and dplyr inside suppressPackageStartupMessages(). Build a tibble named trips with a character column guide holding \"Ines\", \"Omar\", \"Yuki\" and a list column stops whose three elements are c(\"pier\", \"fort\"), NULL, and c(\"mill\"). Flatten stops so each stop gets its own row, keeping a row for the guide whose stops are empty, then sort by guide and then stops and print.",
  o:"# A tibble: 4 × 2\n  guide stops\n  <chr> <chr>\n1 Ines  fort \n2 Ines  pier \n3 Omar  <NA> \n4 Yuki  mill ",
  h:["Four rows are expected from three guides, and one of those rows exists only because you asked for it.",
     "This is the lengthening move, and its default would silently drop the guide whose element is NULL. One argument turns that off and gives the empty element a row with NA.",
     "Pipe trips into the unnesting function with stops as the column and the keep-empty argument set to TRUE, then arrange by both columns. NA sorts last within a guide, which does not matter here because Omar has only one row."]},
{ c:"tidy data", t:"Rectangle a JSON string", book:"r23",
  b:"Attach tidyr, dplyr and jsonlite inside suppressPackageStartupMessages(). Assign to raw the single-quoted string '[{\"id\": \"A\", \"meta\": {\"grade\": 3, \"tag\": \"ash\"}}, {\"id\": \"B\", \"meta\": {\"grade\": 5, \"tag\": \"oak\"}}]'. Parse it with fromJSON(), turning simplification off so the result is plain lists, and put the parsed list into a tibble named cores as a list column called entry. Then pull out two columns by path — id from the top level and grade from inside meta — keep only those two columns, sort by id and print.",
  o:"# A tibble: 2 × 2\n  id    grade\n  <chr> <int>\n1 A         3\n2 B         5",
  h:["A list becomes a list-column simply by being passed to tibble() as a column, so no conversion step is needed between parsing and the tibble.",
     "Pulling named components out by path, rather than flattening every level, is what hoist() is for. simplifyVector = FALSE keeps fromJSON() from guessing at a rectangle.",
     "After hoisting, the entry column is still there holding the leftovers, so select() the two columns you want before arranging. A one-level path is a plain string; a two-level path is a list of two strings, outer name first."]}
]
};
