/* Practice Log book — R Chapter 24: Web scraping.
   Original lesson text following the chapter-by-chapter curriculum of
   "R for Data Science" (2nd ed.) by Hadley Wickham, Mine Cetinkaya-Rundel,
   and Garrett Grolemund. Read the original chapter free at the src link below.
   Every shown output was captured by executing the code in WebR, not written from memory. */
window.BOOK_R = window.BOOK_R || { chapters: {} };
window.BOOK_R.chapters.r24 = {
n: 24,
title: "Web scraping",
src: "https://r4ds.hadley.nz/webscraping.html",
blurb: "Taking data off a web page with rvest: what you are allowed to take, how HTML is built, and how to select elements, text, attributes, and tables.",
pkgs: ["rvest"],
sections: [
{ t: "Before you point a program at a site",
  body: [
  ["p","Scraping is asking someone else's server to do work for you and then keeping what comes back. That makes it a question about permission and cost before it is a question about code, so the constraints come first. None of what follows is legal advice; it is the set of checks that keeps ordinary scraping ordinary."],
  ["p","Terms of service. Many sites publish terms that say whether automated access is allowed. If you agreed to them by making an account then they bind you as a contract. For a page you can read without logging in the position is less settled and differs by country. Reading the terms takes a minute and tells you whether you have a problem to think about."],
  ["p","robots.txt. Most sites serve a file at /robots.txt listing the paths that automated clients are asked to stay out of. It is a request rather than a lock, and honouring it is the baseline of behaving well. A path named in it is also fair warning that traffic there gets noticed."],
  ["p","Personal data. Names, addresses, messages, anything that identifies a living person — collecting it puts you under data protection law, the GDPR in the UK and EU, and the page being public does not exempt you. The default is to not collect it. If a project genuinely needs it, work out what applies to you before you have a database rather than after."],
  ["p","Rate. A browser fetches a page when a person clicks. A loop fetches as fast as the network allows, and a few hundred requests a second is hard to tell apart from an attack. Sys.sleep() between requests and a cache so you never fetch the same page twice cost you nothing and keep you off the blocklist. Identify yourself in the user agent string if the library lets you, so an administrator who notices has someone to email."],
  ["p","Copyright. Facts are not copyrightable and the prose around them is, so extracting a table of numbers stands on much firmer ground than republishing an article. And before any of it: if the site publishes an API, use the API. It is stabler, it is faster, and it is the access the site chose to offer."],
  ["note","This app cannot make network requests, so nothing in this chapter fetches anything. Every block that names a URL is shown with no output — none was run and none is invented. That costs the chapter less than it sounds, because the fetching is one line and the whole skill is in what you do with the HTML afterwards. Parsing HTML held in a string needs no network at all, so every other block below did run here, and its output is what this app produced."]
]},
{ t: "What an HTML page is made of",
  body: [
  ["p","HTML is text with markup in it. A piece of content wrapped in an opening tag and a closing tag is an element: <h1>Kettle and Crow</h1> is an h1 element whose content is those three words. Elements sit inside other elements, and that nesting makes the page a tree — a body containing a list containing items containing text."],
  ["p","An opening tag can carry attributes, which are name=\"value\" pairs written inside the angle brackets. Three of them do most of the work in scraping. id names an element that is supposed to be unique on the page. class is a label that any number of elements can share, and an element can carry several class names separated by spaces. href holds the destination of a link."],
  ["code","<h1 id=\"shopname\">Kettle and Crow</h1>\n<a class=\"more\" href=\"https://example.com/hours\">Opening hours</a>"],
  ["p","Those two lines have everything the rest of the chapter needs: a tag name, an id, a class, an attribute holding a URL, and text inside the element. The way you find any of it in a real page is with the browser's developer tools — right-click the thing you want and choose Inspect, and the panel that opens shows that element's place in the tree with its attributes visible. That is where the id or class you will aim at comes from."],
  ["note","Real HTML is worse than any example. Tags go unclosed, attributes appear in single quotes or double quotes or none at all, whitespace lands wherever the template put it, and the same page can come back slightly different tomorrow. That is the argument against parsing HTML with find-and-substring string surgery and for handing it to a parser that has already met all of it."]
]},
{ t: "Reading a page into R",
  body: [
  ["p","rvest is the tidyverse package for this job. It sits on xml2, which does the actual parsing, and adds functions shaped for the way you want to think about a page. The example page below is an ordinary shop listing, held in an R string so that everything in this chapter can run without touching the network."],
  ["p","Note the quoting. The string is written with single quotes, so the double quotes inside the HTML need no escaping. Wrapping HTML in double quotes and then backslashing every attribute is the usual way this gets unreadable."],
  ["code","library(rvest)\n\nshop <- '<html>\n<head><title>Kettle and Crow</title></head>\n<body>\n<h1 id=\"shopname\">Kettle and Crow</h1>\n<p class=\"blurb\">   Roasted   in\n   Norwich.   </p>\n<ul id=\"beans\">\n<li class=\"bean\"><span class=\"name\">Kenya Nyeri</span> <span class=\"price\">18</span></li>\n<li class=\"bean sale\"><span class=\"name\">Brazil Cerrado</span> <span class=\"price\">11</span></li>\n<li class=\"bean\"><span class=\"name\">Sumatra Lintong</span> <span class=\"price\">15</span></li>\n<li class=\"bean\"><span class=\"name\">Ethiopia Guji</span></li>\n</ul>\n<a class=\"more\" href=\"https://example.com/orders\">Order page</a>\n<a class=\"more\" href=\"https://example.com/hours\">Opening hours</a>\n<a class=\"more\">Closed for stocktaking</a>\n</body>\n</html>'\n\nnchar(shop)"],
  ["code","[1] 705"],
  ["p","Seven hundred characters of markup, held in an ordinary character vector of length one. read_html() turns that text into the tree, and what comes back is not a string any more."],
  ["code","page <- read_html(shop)\nclass(page)"],
  ["code","[1] \"xml_document\" \"xml_node\"    "],
  ["p","read_html() takes either a string of HTML like this one or a URL. When the argument contains angle brackets it is parsed as markup; otherwise it is treated as a location to fetch or open. That is the only difference between the examples here and a scraper pointed at a live site."],
  ["p","A node prints as the tag it stands for rather than as its text, which is worth seeing once so that it is never mistaken for a string later."],
  ["code","html_element(page, \"h1\")"],
  ["code","{html_node}\n<h1 id=\"shopname\">"]
]},
{ t: "Finding elements",
  body: [
  ["p","Two functions find things, and the difference between them decides most of what your code has to handle afterwards. html_elements() with the plural returns every match; html_element() with the singular returns one. Both take a CSS selector: a tag name matches by tag, .name matches every element whose class list includes name, and #name matches the element with that id."],
  ["code","html_elements(page, \".more\")"],
  ["code","{xml_nodeset (3)}\n[1] <a class=\"more\" href=\"https://example.com/orders\">Order page</a>\n[2] <a class=\"more\" href=\"https://example.com/hours\">Opening hours</a>\n[3] <a class=\"more\">Closed for stocktaking</a>"],
  ["p","A nodeset is a list of nodes, and it prints with its length in the header. length() gets that count, which is the first thing to check when a selector is not doing what you expected."],
  ["code","length(html_elements(page, \".bean\"))"],
  ["code","[1] 4"],
  ["p","The singular takes only the first match, and it returns a node rather than a nodeset of one. Use it when you know there is exactly one of the thing — a page title, an id — or in the row-by-row pattern of the next section."],
  ["code","html_element(page, \".bean\")"],
  ["code","{html_node}\n<li class=\"bean\">\n[1] <span class=\"name\">Kenya Nyeri</span>\n[2] <span class=\"price\">18</span>"],
  ["p","When nothing matches, neither function raises an error. The plural gives you an empty nodeset."],
  ["code","html_elements(page, \".missing\")"],
  ["code","{xml_nodeset (0)}"],
  ["code","html_element(page, \".missing\")"],
  ["code","{xml_missing}\n<NA>"],
  ["note","A selector that matches nothing is the commonest scraping bug and it is silent. Nothing here throws, so an empty nodeset flows on into the next step and turns into a zero-row result or a column of NA somewhere further down. Check the length of a nodeset before you build anything on it, and treat a sudden empty result as the page having changed rather than as no data existing."]
]},
{ t: "Nesting, and keeping the rows lined up",
  body: [
  ["p","Selecting the four items gives you four nodes, and asking for their text gives you everything inside each one — including the text of the elements nested within."],
  ["code","beans <- html_elements(page, \".bean\")\nhtml_text2(beans)"],
  ["code","[1] \"Kenya Nyeri 18\"     \"Brazil Cerrado 11\"  \"Sumatra Lintong 15\"\n[4] \"Ethiopia Guji\"     "],
  ["p","Name and price ran together, because the price span sits inside the item. To get the parts separately, select the parts. A selector with a space in it means descendant: \".bean .price\" matches every price span anywhere inside a bean."],
  ["code","html_text2(html_elements(page, \".bean .price\"))"],
  ["code","[1] \"18\" \"11\" \"15\""],
  ["p","Three prices for four items, and nothing in the result says which item lost one. That is the trap. Four items and three prices cannot be put side by side in a data frame, and if you force them the values silently shift up by one from the missing row onwards."],
  ["p","The fix is the singular function applied to the nodeset. html_element() over a nodeset returns exactly one result per node, filling in a missing node where there is nothing to find, so the answer stays the same length as the thing you started from."],
  ["code","html_text2(html_element(beans, \".price\"))"],
  ["code","[1] \"18\" \"11\" \"15\" NA  "],
  ["p","Four values, with the gap marked. That is the pattern for every scraper that builds a table: select the repeating element once, then pull each column out of that nodeset with html_element(), never with html_elements()."],
  ["code","data.frame(\n  bean = html_text2(html_element(beans, \".name\")),\n  price = as.numeric(html_text2(html_element(beans, \".price\")))\n)"],
  ["code","             bean price\n1     Kenya Nyeri    18\n2  Brazil Cerrado    11\n3 Sumatra Lintong    15\n4   Ethiopia Guji    NA"],
  ["note","The two functions look interchangeable and are not. html_elements() answers what is on the page; html_element() answers what belongs to this row. Mixing them up produces a data frame that is the right shape, has no NA in it, and is wrong from the first missing value down — which is far harder to notice than a crash."]
]},
{ t: "Text and attributes",
  body: [
  ["p","There are two functions for text. html_text() gives you the characters exactly as they sit in the source, whitespace and all, which is what the file says and rarely what you want."],
  ["code","html_text(html_element(page, \".blurb\"))"],
  ["code","[1] \"   Roasted   in\\n   Norwich.   \""],
  ["p","html_text2() gives you the text as a browser would show it: runs of whitespace collapsed to single spaces, line breaks in the source treated as spaces, and the ends trimmed."],
  ["code","html_text2(html_element(page, \".blurb\"))"],
  ["code","[1] \"Roasted in Norwich.\""],
  ["p","Reach for html_text2() by default. It is slower, because working out what a browser would render is more work than copying characters, and on a page of a few thousand elements that difference does not matter. Reach for html_text() when whitespace inside the element is data, which happens with code listings and almost nowhere else."],
  ["p","Attributes come out with html_attr(), which takes the name of the attribute. It works across a nodeset and marks the elements that do not have it, the same way html_element() marks a missing node."],
  ["code","html_attr(html_elements(page, \".more\"), \"href\")"],
  ["code","[1] \"https://example.com/orders\" \"https://example.com/hours\" \n[3] NA                          "],
  ["p","Two links and one anchor without an href, reported as NA rather than dropped. An attribute the element does not carry is NA too, which is worth seeing next to one it does carry."],
  ["code","html_attr(html_element(page, \"h1\"), \"id\")\nhtml_attr(html_element(page, \"h1\"), \"href\")"],
  ["code","[1] \"shopname\"\n[1] NA"],
  ["p","Text and attributes are the two ends of the job. Once a nodeset is the right length and lined up with the rows you want, everything else is html_text2() for the words and html_attr() for the values hiding in the tags."],
  ["code","sort(html_text2(html_elements(page, \".name\")))"],
  ["code","[1] \"Brazil Cerrado\"  \"Ethiopia Guji\"   \"Kenya Nyeri\"     \"Sumatra Lintong\""]
]},
{ t: "Tables",
  body: [
  ["p","When the data is already in a table element, none of the row-by-row work is needed. html_table() takes a table node and returns a tibble: the th cells become column names, the td cells become the values, and columns that hold nothing but digits come back as numbers."],
  ["code","timetable <- read_html('<table>\n<tr><th>port</th><th>minutes</th></tr>\n<tr><td>Rye</td><td>40</td></tr>\n<tr><td>Hoy</td><td>25</td></tr>\n<tr><td>Fowey</td><td>65</td></tr>\n</table>')\n\ncrossings <- html_table(html_element(timetable, \"table\"))\ncrossings"],
  ["code","# A tibble: 3 × 2\n  port  minutes\n  <chr>   <int>\n1 Rye        40\n2 Hoy        25\n3 Fowey      65"],
  ["p","That is a tibble like any other, so the rest of what you know applies to it directly — ordering, filtering, joining, summarising."],
  ["code","crossings[order(crossings$minutes), ]"],
  ["code","# A tibble: 3 × 2\n  port  minutes\n  <chr>   <int>\n1 Hoy        25\n2 Rye        40\n3 Fowey      65"],
  ["note","html_table() works on tables that are tables. Plenty of pages lay data out in a grid using div elements and styling, and those have no table element to find, so the row-by-row approach from section 5 is the only route. Check for a real table first, since finding one saves you an hour."]
]},
{ t: "Fetching a real page, and what breaks",
  body: [
  ["p","Everything above worked on a string. Pointing the same code at a live site changes one line: read_html() takes the URL instead, fetches the page, and hands back the same kind of tree, so every selector you have written keeps working."],
  ["code","library(rvest)\n\nlive <- read_html(\"https://example.com/shop/beans\")\n\nhtml_text2(html_element(live, \"h1\"))"],
  ["p","Several pages means a loop, and a loop is where the rate constraint from section 1 becomes code. Sys.sleep() between fetches turns a burst into a trickle, and keeping the results in a list means you parse once rather than fetching again every time you change your mind about the selector."],
  ["code","urls <- c(\"https://example.com/shop/page1\", \"https://example.com/shop/page2\")\n\nfor (u in urls) {\n  doc <- read_html(u)\n  print(html_text2(html_elements(doc, \".price\")))\n  Sys.sleep(2)\n}"],
  ["p","The other thing that changes on a live site is that some pages have no data in them. A page assembled by JavaScript after it loads sends the browser a shell and fills it in afterwards, and read_html() gets the shell — the selectors match nothing at all. The way to tell is to compare what View Page Source shows against what the Inspect panel shows: the first is the file that arrived, the second is the page after the scripts ran. When they differ, no amount of selector work will help, and the answers are to find the underlying request the page makes for its data, or to drive a real browser from R with a package that can."],
  ["note","Both blocks above name URLs, so both are shown without output: this app cannot fetch anything, and no output has been invented for them. On a desktop R they run as written."],
  ["p","Two failures survive into the parsing, and neither announces itself. The first is the missing element, which becomes NA and travels on."],
  ["code","html_text2(html_element(page, \".missing\"))"],
  ["code","[1] NA"],
  ["p","The second is converting text that is not a number. Scraped values arrive as character strings, so as.numeric() is nearly always in the pipeline, and it turns anything it cannot read into NA with a warning rather than an error."],
  ["code","as.numeric(html_text2(html_element(page, \".bean\")))"],
  ["code","Warning in eval(ei, envir) : NAs introduced by coercion\n[1] NA"],
  ["p","There the selector picked the whole item rather than the price span, so the text was \"Kenya Nyeri 18\" and there was no number in it to find. The warning is the only sign, and warnings scroll past. When a scraped column comes out all NA, the two things to check in order are whether the selector matched and whether what it matched is really the value rather than the value plus its label."]
]},
{ t: "Summary",
  body: [
  ["p","Decide what you are allowed to take before you write anything: terms of service, robots.txt, whether the data identifies people, and how fast your loop will hit the server. Use the site's API if it has one. Sleep between requests, cache what you fetch, and remember that facts are not copyrightable but the writing around them is."],
  ["p","HTML is a tree of elements, and an element's tag, id, class, and other attributes are what selectors aim at. read_html() parses a string or fetches a URL into that tree. html_elements() returns every match as a nodeset, html_element() returns one node and quietly returns a missing node when there is nothing to match, and neither raises an error when a selector finds nothing."],
  ["p","That difference is the chapter's main mechanical lesson. To build a table, select the repeating element once with html_elements(), then take each column out of that nodeset with html_element(), so every column stays the same length as the rows and gaps arrive as NA instead of shifting the values. Pull words out with html_text2() rather than html_text(), pull attributes out with html_attr(), and when the page already holds a table element, hand it to html_table() and skip the whole business."],
  ["p","Answer the practice questions from memory before revealing the answers, then clear the graded exercises below. The next chapter is functions: how to take a piece of code you have now written three times with small changes and turn it into one thing you can call, which is exactly what a scraper turns into once it works on more than one page."]
]}
],
questions: [
{ q:"Name four things to check before pointing a scraper at a site.",
  a:"The terms of service, which bind you as a contract if you agreed to them by making an account. The /robots.txt file, which lists paths automated clients are asked to avoid. Whether the data identifies living people, which brings data protection law into it regardless of the page being public. The rate your loop will fetch at, which is what turns a scraper into something indistinguishable from an attack. And before all of them, whether the site publishes an API you could use instead." },
{ q:"In <a class=\"more\" href=\"https://example.com/hours\">Opening hours</a>, name the tag, the attributes, and the text.",
  a:"The tag is a. It carries two attributes: class, whose value is \"more\", and href, whose value is the URL. The text inside the element is \"Opening hours\" — what a reader sees and what html_text2() would return." },
{ q:"read_html() is given a string in one example and a URL in another. How does it tell them apart?",
  a:"By whether the argument looks like markup. A string containing angle brackets is parsed as HTML directly; anything else is treated as a location to fetch or open. That is why every example in this chapter can run without a network — the page is a string in the script." },
{ q:"What does html_elements(page, \".bean\") return, and what does the selector \".bean\" mean?",
  a:"A nodeset of every matching element, printing with its length in the header — four, on the example page. A leading dot means match by class, so it selects every element whose class list includes bean, including the one whose class attribute is \"bean sale\"." },
{ q:"A selector matches nothing. What do html_elements() and html_element() each give you, and what do they not do?",
  a:"html_elements() returns an empty nodeset, printed as {xml_nodeset (0)}; html_element() returns a missing node, printed as {xml_missing}. Neither raises an error, which is why a wrong selector shows up much later as an empty result or a column of NA rather than as a failure at the point of the mistake." },
{ q:"Four items on the page, only three of them carrying a price span. What does html_text2 over html_elements(page, \".bean .price\") give, and why is that a problem?",
  a:"Three values, with nothing recording which item is missing one. Three values cannot sit beside four names in a data frame, and pairing them anyway shifts every value up by one from the gap onwards — a table of the right shape with the wrong numbers in it." },
{ q:"What is the pattern for building a data frame out of repeating page elements?",
  a:"Select the repeating element once with html_elements() to get one node per row, then take each column out of that nodeset with html_element() and a selector for the part you want. html_element() returns exactly one result per node, so every column is the same length as the rows and a gap comes back as NA." },
{ q:"What is the difference between html_text() and html_text2(), and which should you reach for?",
  a:"html_text() returns the characters exactly as they appear in the source, keeping every run of spaces and every line break. html_text2() returns the text as a browser would render it: whitespace collapsed, source line breaks treated as spaces, ends trimmed. Reach for html_text2() by default and for html_text() only when the whitespace inside the element is itself the data." },
{ q:"html_attr(nodes, \"href\") is called on three anchors and one of them has no href. What comes back?",
  a:"Three values, with NA in the position of the anchor that has no href. The element is not dropped, so the result stays lined up with the nodeset it came from. An attribute an element simply does not carry gives NA in the same way." },
{ q:"A scraped numeric column has come out entirely NA and the only sign was a warning. What are the two things to check, in order?",
  a:"First, whether the selector matched anything at all — check the length of the nodeset, since an empty one produces NA silently. Second, whether what it matched is the value or the value plus its surrounding text: selecting the whole item rather than the price span gives as.numeric() a string like \"Kenya Nyeri 18\" to convert, which it cannot, so it returns NA with a coercion warning." }
],
exercises: [
{ c:"strings & regex", t:"Read the noticeboard", book:"r24",
  b:"Attach rvest. Assign to board this HTML, written as a single-quoted R string: <ul id=\"notices\"> then three list items each with class \"note\" holding the texts Bins out Tuesday, Hall closed Friday and Choir practice Wednesday in that order, then the closing </ul>. Parse it, select every element whose class is note, take the text of each, and print the results sorted alphabetically.",
  o:"[1] \"Bins out Tuesday\"         \"Choir practice Wednesday\"\n[3] \"Hall closed Friday\"      ",
  h:["Three steps chained into one line: parse the string, select the elements, take their text. The sorting is one more function wrapped around the result.",
     "read_html() parses, html_elements() with a class selector finds every match, and html_text2() takes the rendered text of each node in a nodeset.",
     "The class selector is a dot in front of the class name. The shape is sort(html_text2(html_elements(read_html(board), ...))). Write the HTML in single quotes so its double quotes need no escaping."]},
{ c:"strings & regex", t:"Collect the links", book:"r24",
  b:"Attach rvest. Assign to links this HTML as a single-quoted R string: a p element containing three anchors, each with class \"doc\", with hrefs https://example.com/rules, https://example.org/forms and https://example.net/map, and texts Rules, Forms and Map respectively. Parse it, select every element whose class is doc, pull out the href of each, and print those sorted alphabetically.",
  o:"[1] \"https://example.com/rules\" \"https://example.net/map\"  \n[3] \"https://example.org/forms\"",
  h:["The destination of a link is not its text, so the function that reads text is not the one you want here.",
     "html_attr() takes a nodeset and the name of an attribute, and returns one value per node. The attribute holding a link's destination is href.",
     "Select with html_elements() and the class selector, pass the result to html_attr() with \"href\", and wrap the whole thing in sort(). Sorting is on the URL strings, so the order follows the domain names."]},
{ c:"data frames", t:"A stall with no price", book:"r24",
  b:"Attach rvest. Assign to stalls a single-quoted R string holding a ul with three li elements of class \"stall\": the first contains only a span of class \"item\" holding Honey; the second a span of class \"item\" holding Bread followed by a space and a span of class \"cost\" holding 4; the third the same shape with Cheese and 7. Parse it and select the three stall elements into items. Build a data frame named market with a column stall holding each item's name text and a numeric column cost holding each item's cost, then print market ordered by the stall column.",
  o:"   stall cost\n2  Bread    4\n3 Cheese    7\n1  Honey   NA",
  h:["One of the three items has no cost, and the columns of a data frame have to be the same length, so the function that returns one result per node is the one to use for both columns.",
     "html_element() applied to a nodeset gives exactly one result per node and a missing node where there is nothing, which becomes NA after html_text2(). The cost column needs as.numeric() around the text.",
     "Build the frame with stall = html_text2(html_element(items, ...)) and cost = as.numeric(...) of the same shape with the other selector. Ordering a data frame by a column is market[order(market$stall), ]."]},
{ c:"tibbles & pipes", t:"Sort the tide table", book:"r24",
  b:"Attach rvest. Assign to tides a single-quoted R string holding a table whose first row has header cells beach and height_cm, followed by three rows: Cromer 310, Wells 275, Salthouse 402. Using the native pipe, parse it, select the table element, convert it to a tibble named heights, then print heights ordered by height_cm from lowest to highest.",
  o:"# A tibble: 3 × 2\n  beach     height_cm\n  <chr>         <int>\n1 Wells           275\n2 Cromer          310\n3 Salthouse       402",
  h:["A table element does not need the row-by-row treatment — one function turns the whole thing into a tibble.",
     "The chain is read_html(), then html_element() with the tag name of a table, then html_table(). The native pipe |> passes each result to the next.",
     "Store the result in heights, then order it with heights[order(heights$height_cm), ]. The header cells become the column names, and the column of digits comes back as integers on its own."]}
]
};
