/* Practice Log book — R Chapter 25: Functions.
   Original lesson text following the chapter-by-chapter curriculum of
   "R for Data Science" (2nd ed.) by Hadley Wickham, Mine Cetinkaya-Rundel,
   and Garrett Grolemund. Read the original chapter free at the src link below.
   Every shown output was captured by executing the code in WebR, not written from memory. */
window.BOOK_R = window.BOOK_R || { chapters: {} };
window.BOOK_R.chapters.r25 = {
n: 25,
title: "Functions",
src: "https://r4ds.hadley.nz/functions.html",
blurb: "Turning repeated code into a named thing with arguments: vector functions, defaults, early returns, and the embrace that lets a function take a column name.",
pkgs: ["dplyr", "tibble", "ggplot2"],
sections: [
{ t: "When a function earns its place",
  body: [
  ["p","Copying a line and editing the copy is the fastest way to write the second version of anything, and the slowest way to maintain the tenth. A function is what you reach for when the same shape of code turns up more than twice: it gives the shape a name, marks the parts that change as arguments, and leaves one place to fix when the shape turns out to be wrong."],
  ["p","Three packages appear in this chapter. dplyr and tibble supply the data frame work from section 4 onward, and ggplot2 supplies the plot functions in section 6. dplyr prints an attach banner, so it is wrapped to keep the console quiet."],
  ["code","suppressMessages(library(dplyr))\nlibrary(tibble)\nlibrary(ggplot2)"],
  ["p","Here are three counts of recycling bins collected on different kinds of day, each turned into a set of percentages that add up to a hundred. The three lines are the same idea written out three times."],
  ["code","weekday_bins <- c(18, 22, 15, 25, 30)\nweekend_bins <- c(31, 29)\nholiday_bins <- c(12, 9, 14, 11)\n\nround(100 * weekday_bins / sum(weekday_bins), 1)\nround(100 * weekend_bins / sum(weekend_bins), 1)\nround(100 * holiday_bins / sum(holiday_bins), 1)"],
  ["code","[1] 16.4 20.0 13.6 22.7 27.3\n[1] 51.7 48.3\n[1] 26.1 19.6 30.4 23.9"],
  ["p","Read the three lines side by side and ask what varies. One thing does: the name of the vector, and it appears twice on every line. Everything else — the multiplication by a hundred, the division by the sum, the rounding to one decimal — is fixed. A thing that varies is an argument, and a thing that is fixed belongs in the body."],
  ["note","The failure this prevents is not typing effort, it is a half-finished edit. When you decide later that one decimal is too coarse, you have to change three lines, and the line you miss keeps returning old numbers without complaining. Three copies of an idea are three chances to be inconsistent."]
]},
{ t: "Writing a vector function",
  body: [
  ["p","A function definition has three parts: a name to bind it to, the argument list in parentheses, and the body in braces. R evaluates the body when the function is called, and the value of the last expression in the body is what comes back — no keyword required."],
  ["code","pct_of_total <- function(x) {\n  round(100 * x / sum(x), 1)\n}\n\npct_of_total(weekday_bins)\npct_of_total(weekend_bins)\npct_of_total(holiday_bins)"],
  ["code","[1] 16.4 20.0 13.6 22.7 27.3\n[1] 51.7 48.3\n[1] 26.1 19.6 30.4 23.9"],
  ["p","Same three answers, one definition. This is a vector function: it takes a vector and gives back a vector of the same length, so it slots into a mutate() call or stands alone. The argument name x is a placeholder that only means anything inside the body, and formals() reports the argument list of any function you have."],
  ["code","names(formals(pct_of_total))\nis.function(pct_of_total)"],
  ["code","[1] \"x\"\n[1] TRUE"],
  ["p","Names created while the body runs live and die with the call. They do not leak into your workspace, which is the whole point: a function can use a working variable called total without wondering whether you already had one."],
  ["code","bump <- function(x) {\n  running <- sum(x)\n  running * 2\n}\n\nbump(c(1, 2, 3))\nexists(\"running\")"],
  ["code","[1] 12\n[1] FALSE"],
  ["note","The traffic runs one way only. A function cannot see names you made afterwards, but it can see names that already exist outside it, so a body that mentions a variable you forgot to make an argument will quietly use whatever is lying around in your workspace. It works while you test it and breaks in a fresh session. If a name in the body is not an argument and not created inside the body, it is a bug waiting."]
]},
{ t: "Arguments, defaults, and returning early",
  body: [
  ["p","An argument given a value in the definition becomes optional. The caller can ignore it and get the value you chose, or name it and get their own. Put the argument the function is really about first and the tuning arguments after it, because the first argument is the one people pass by position."],
  ["code","pct_of_total <- function(x, digits = 1) {\n  round(100 * x / sum(x), digits)\n}\n\npct_of_total(holiday_bins)\npct_of_total(holiday_bins, digits = 3)\npct_of_total(holiday_bins, 0)"],
  ["code","[1] 26.1 19.6 30.4 23.9\n[1] 26.087 19.565 30.435 23.913\n[1] 26 20 30 24"],
  ["p","The default is stored in the definition, not invented at call time, so you can read it back the same way you read the argument names."],
  ["code","names(formals(pct_of_total))\nformals(pct_of_total)$digits"],
  ["code","[1] \"x\"      \"digits\"\n[1] 1"],
  ["p","Missing values are the next thing that happens to a real column. sum() refuses to guess, so one NA anywhere in the input poisons the total and every percentage with it."],
  ["code","gapped <- c(12, NA, 14, 11)\n\npct_of_total(gapped)"],
  ["code","[1] NA NA NA NA"],
  ["p","The fix is an argument, not a decision. Hardcoding na.rm = TRUE inside the body would silently drop data on behalf of every future caller; passing it through leaves the choice where it belongs and keeps the cautious behaviour as the default."],
  ["code","pct_of_total <- function(x, digits = 1, na.rm = FALSE) {\n  round(100 * x / sum(x, na.rm = na.rm), digits)\n}\n\npct_of_total(gapped, na.rm = TRUE)"],
  ["code","[1] 32.4   NA 37.8 29.7"],
  ["p","The NA stays in its own slot, because dropping it from the total does not invent a value for it. Now consider a total of zero: the arithmetic divides by nothing and the answers are useless. return() ends the call on the spot, which is how you deal with a case that has no sensible arithmetic before the arithmetic runs."],
  ["code","pct_of_total <- function(x, digits = 1, na.rm = FALSE) {\n  total <- sum(x, na.rm = na.rm)\n  if (total == 0) {\n    return(rep(0, length(x)))\n  }\n  round(100 * x / total, digits)\n}\n\npct_of_total(c(0, 0, 0))\npct_of_total(holiday_bins)"],
  ["code","[1] 0 0 0\n[1] 26.1 19.6 30.4 23.9"],
  ["p","Note that the ordinary path still has no return() around it. Reserve the keyword for the exits that jump the queue, so a reader can find every early exit by searching for one word. Not every function gives back a vector as long as its input, either — a summary function reduces the whole vector to one number."],
  ["code","spread_ratio <- function(x, digits = 3) {\n  round(diff(range(x)) / mean(x), digits)\n}\n\nspread_ratio(weekday_bins)\nspread_ratio(holiday_bins)"],
  ["code","[1] 0.682\n[1] 0.435"],
  ["note","R matches argument names by prefix, so a call that names an argument dig instead of digits works, and so does anything else that picks out exactly one name. It looks like a typo that got away with it, and it is: add another argument starting with dig later and every one of those calls becomes an error about an ambiguous name."],
  ["code","pct_of_total(holiday_bins, dig = 3)"],
  ["code","[1] 26.087 19.565 30.435 23.913"]
]},
{ t: "Data frame functions and the indirection problem",
  body: [
  ["p","A function that wraps dplyr verbs hits a problem a vector function never sees. dplyr uses data masking: inside summarise() or group_by(), a bare word is looked up as a column of the data frame first. That is what lets you write sum(parcels) instead of sum(df$parcels), and it is exactly what goes wrong when the column name arrives as an argument."],
  ["p","Here is a table of delivery runs — nine runs across three depots, with a driver, a parcel count, and a distance."],
  ["code","deliveries <- tibble(\n  depot = c(\"north\", \"north\", \"north\", \"south\", \"south\", \"east\", \"east\", \"east\", \"east\"),\n  driver = c(\"Ines\", \"Dara\", \"Ines\", \"Omar\", \"Lena\", \"Yuki\", \"Yuki\", \"Omar\", \"Lena\"),\n  parcels = c(31, 24, 28, 19, 22, 35, 30, 27, 25),\n  km = c(48.5, 33.0, 41.2, 52.8, 47.1, 29.4, 31.7, 44.0, 38.6)\n)\n\ndeliveries"],
  ["code","# A tibble: 9 × 4\n  depot driver parcels    km\n  <chr> <chr>    <dbl> <dbl>\n1 north Ines        31  48.5\n2 north Dara        24  33  \n3 north Ines        28  41.2\n4 south Omar        19  52.8\n5 south Lena        22  47.1\n6 east  Yuki        35  29.4\n7 east  Yuki        30  31.7\n8 east  Omar        27  44  \n9 east  Lena        25  38.6"],
  ["p","Now the obvious attempt: a function that groups by whatever column you hand it and totals the parcels."],
  ["code","total_by <- function(df, group_var) {\n  df |>\n    group_by(group_var) |>\n    summarise(parcels = sum(parcels), .groups = \"drop\")\n}\n\ntotal_by(deliveries, depot)"],
  ["code","Error: Must group by variables found in `.data`."],
  ["p","This app's R console shows only the first line of a dplyr error, and the line that identifies the culprit is the second one. Catching the condition and printing its message gets you the rest."],
  ["code","msg <- tryCatch(total_by(deliveries, depot), error = function(e) conditionMessage(e))\n\ncat(msg)"],
  ["code","Must group by variables found in `.data`.\n✖ Column `group_var` is not found."],
  ["p","Read that literally. group_by() went looking in the data for a column named group_var, because inside a data-masking verb that is what a bare word means. It never occurred to it to ask what group_var holds. The argument name got taken at face value, and the value you passed was never used."],
  ["p","The fix is to wrap the argument in two braces. This is called embracing, and it tells the verb to substitute the value of the argument — the column name the caller wrote — before doing the lookup."],
  ["code","total_by <- function(df, group_var) {\n  df |>\n    group_by({{ group_var }}) |>\n    summarise(parcels = sum(parcels), .groups = \"drop\") |>\n    arrange({{ group_var }})\n}\n\ntotal_by(deliveries, depot)\ntotal_by(deliveries, driver)"],
  ["code","# A tibble: 3 × 2\n  depot parcels\n  <chr>   <dbl>\n1 east      117\n2 north      83\n3 south      41\n# A tibble: 5 × 2\n  driver parcels\n  <chr>    <dbl>\n1 Dara        24\n2 Ines        59\n3 Lena        47\n4 Omar        46\n5 Yuki        65"],
  ["p","One definition, two questions answered, and the grouping column keeps its own name in the result because the caller's word is what got substituted. The arrange() is embraced for the same reason — it is a dplyr verb, so it masks data too."],
  ["note","The full message names the argument, not the column, and that is the tell. Any complaint about a variable called group_var, var, col, or whatever you named the parameter means the braces are missing. It never means the column is missing, which is where most people go looking first — and since the console here truncates the message to its first line, that second line is worth catching before you start editing the data."]
]},
{ t: "Embracing more than one argument",
  body: [
  ["p","Every argument that names a column needs its own embrace. Arguments that carry ordinary values — a number, a string, a logical — need none, because nothing about them is looked up in the data."],
  ["code","mean_by <- function(df, group_var, value_var, digits = 1) {\n  df |>\n    group_by({{ group_var }}) |>\n    summarise(mean = round(mean({{ value_var }}), digits), .groups = \"drop\") |>\n    arrange({{ group_var }})\n}\n\nmean_by(deliveries, depot, km)\nmean_by(deliveries, driver, parcels)"],
  ["code","# A tibble: 3 × 2\n  depot  mean\n  <chr> <dbl>\n1 east   35.9\n2 north  40.9\n3 south  50  \n# A tibble: 5 × 2\n  driver  mean\n  <chr>  <dbl>\n1 Dara    24  \n2 Ines    29.5\n3 Lena    23.5\n4 Omar    23  \n5 Yuki    32.5"],
  ["p","Two column arguments, both embraced, and digits left plain. There is a second flavour of column reference in the tidyverse: tidy selection, the language of select() and across(), where you can write ranges, helpers like starts_with(), and where(is.numeric). The same braces carry a whole selection through into a function."],
  ["code","col_means <- function(df, cols) {\n  df |> summarise(across({{ cols }}, mean))\n}\n\ncol_means(deliveries, c(parcels, km))\ncol_means(deliveries, where(is.numeric))"],
  ["code","# A tibble: 1 × 2\n  parcels    km\n    <dbl> <dbl>\n1    26.8  40.7\n# A tibble: 1 × 2\n  parcels    km\n    <dbl> <dbl>\n1    26.8  40.7"],
  ["p","Both calls select the same two columns by different routes. Embracing is for arguments the caller wrote as bare column names. When the caller has strings instead — a character vector built somewhere else, or read from a config — the tool is all_of(), which turns strings into a selection."],
  ["code","col_means_str <- function(df, cols) {\n  df |> summarise(across(all_of(cols), mean))\n}\n\ncol_means_str(deliveries, c(\"parcels\", \"km\"))"],
  ["code","# A tibble: 1 × 2\n  parcels    km\n    <dbl> <dbl>\n1    26.8  40.7"],
  ["p","And plenty of useful data frame functions need no embracing at all, because the columns are fixed and only the numbers vary. A threshold is just a number."],
  ["code","busy_runs <- function(df, min_parcels = 25) {\n  df |>\n    filter(parcels >= min_parcels) |>\n    arrange(driver, parcels)\n}\n\nbusy_runs(deliveries, 30)"],
  ["code","# A tibble: 3 × 4\n  depot driver parcels    km\n  <chr> <chr>    <dbl> <dbl>\n1 north Ines        31  48.5\n2 east  Yuki        30  31.7\n3 east  Yuki        35  29.4"],
  ["p","Strings are where this gets dangerous, because the two worlds fail differently. A tidy selection accepts an embraced string quietly and does the sensible thing, so col_means(deliveries, \"parcels\") returns the mean of that column. A data-masking verb does not: give the embraced argument a string and it groups by the text itself."],
  ["code","total_by(deliveries, \"depot\")"],
  ["code","# A tibble: 1 × 2\n  `\"depot\"` parcels\n  <chr>       <dbl>\n1 depot         241"],
  ["note","No error, no warning, one row, and every parcel in the table added together. The column is named with the quotes still visible and holds the word depot nine times over, because grouping by a constant makes one group. This is the worst kind of mistake — a plausible-looking answer to a question you did not ask — so when a grouped result comes back with one row, check what you passed before you check the data."]
]},
{ t: "Plot functions",
  body: [
  ["p","A plot is a value, so a function can build one and hand it back. Column arguments are embraced inside aes() for exactly the reason they are embraced inside summarise(), and everything else — a bin width, a title — travels as an ordinary argument."],
  ["code","km_hist <- function(df, var, binwidth = 10) {\n  ggplot(df, aes(x = {{ var }})) +\n    geom_histogram(binwidth = binwidth)\n}\n\np <- km_hist(deliveries, km)\n\nlength(p$layers)\nclass(p$layers[[1]]$geom)[1]\np$layers[[1]]$stat_params$binwidth\nnrow(p$data)\nget_labs(p)$x"],
  ["code","[1] 1\n[1] \"GeomBar\"\n[1] 10\n[1] 9\n[1] \"km\""],
  ["p","One layer, drawn with the bar geom that every histogram uses, a bin width of ten because the default was taken, all nine rows aboard, and an x label of km because the embrace passed the caller's word straight through to the label machinery."],
  ["note","This app grades text, and printing a plot object in its R console emits none. The block below runs and produces nothing at all, so an answer that ends on a bare plot object submits an empty transcript. Inspect the object instead — the five lines above are the pattern — and run the same code in desktop R when you want to see the picture."],
  ["code","p"],
  ["p","A title is a string argument, so it stays plain. get_labs() reports the labels a plot will actually use, including the ones ggplot2 works out for itself, and ggplot_build() runs the layer's statistics without drawing anything."],
  ["code","depot_bars <- function(df, var, title) {\n  ggplot(df, aes(x = {{ var }})) +\n    geom_bar() +\n    labs(title = title)\n}\n\nq <- depot_bars(deliveries, depot, \"Runs per depot\")\n\nget_labs(q)$title\nget_labs(q)$x\nggplot_build(q)$data[[1]]$count"],
  ["code","[1] \"Runs per depot\"\n[1] \"depot\"\n[1] 4 3 2"],
  ["p","Four runs from the east depot, three from the north, two from the south, counted by the layer rather than by you. Note what happens when an argument has no default and the caller leaves it out: the complaint arrives when the body first needs the value, not when the call is made."],
  ["code","depot_bars(deliveries, depot)"],
  ["code","Error: argument \"title\" is missing, with no default"],
  ["note","Give an argument a default only when there is a sensible one. A title has no sensible default, so leaving it required is right, and the error above is the function doing its job. Reaching for title = \"\" to make the message go away buys you an untitled plot that nobody notices is untitled."]
]},
{ t: "Style and naming",
  body: [
  ["p","A function name is the interface. Make it a verb or a verb phrase, because a function does something, and keep it in snake_case so it reads the same as the rest of your script. Arguments describe the pieces, so they are usually nouns. Prefer a longer name that says what happens over a short one that needs a comment: total_by beats tb, and mean_by beats calc."],
  ["p","Keep related functions on a shared prefix rather than a shared suffix. A family called plot_hist, plot_bars, plot_box is discoverable by typing the prefix and pausing; hist_plot, bars_plot, box_plot is not. Never take a name that base R already uses — writing your own mean() or filter() shadows the real one for everything else in the session."],
  ["code","names(formals(km_hist))\nformals(km_hist)$binwidth\nis.function(km_hist)"],
  ["code","[1] \"df\"       \"var\"      \"binwidth\"\n[1] 10\n[1] TRUE"],
  ["p","Layout has a few settled conventions. The opening brace ends the line that starts the block, the body is indented two spaces, and the closing brace sits alone on a line at the indentation of the line that opened it. When the body is a pipeline, break after every pipe so each verb has a line to itself and lines can be commented out one at a time while debugging."],
  ["code","km_per_parcel <- function(df, digits = 2) {\n  df |>\n    mutate(km_each = round(km / parcels, digits)) |>\n    arrange(depot, driver)\n}"],
  ["p","That definition prints nothing, because a definition is an assignment. Call it to see the work."],
  ["code","km_per_parcel(deliveries)"],
  ["code","# A tibble: 9 × 5\n  depot driver parcels    km km_each\n  <chr> <chr>    <dbl> <dbl>   <dbl>\n1 east  Lena        25  38.6    1.54\n2 east  Omar        27  44      1.63\n3 east  Yuki        35  29.4    0.84\n4 east  Yuki        30  31.7    1.06\n5 north Dara        24  33      1.38\n6 north Ines        31  48.5    1.56\n7 north Ines        28  41.2    1.47\n8 south Lena        22  47.1    2.14\n9 south Omar        19  52.8    2.78"],
  ["note","Comments in a function body should say why, not what. The code already states what it does, and a comment that restates it becomes a lie the moment somebody edits the code and not the comment. Write down the thing that is not in the code: the reason for the threshold, the source of the constant, the case you decided to ignore."]
]},
{ t: "Summary",
  body: [
  ["p","Write a function when the same shape of code appears a third time. The parts that change become arguments, the parts that stay become the body, and the value of the last expression in the body is what comes back. Variables created inside a body are private to the call, so a function is a box you can reason about on its own — as long as every name in the body is either an argument or created there."],
  ["p","An argument with a value in the definition is optional, and formals() reads both the names and the defaults back. Pass choices like na.rm through as arguments rather than deciding them inside the body. Use return() only for early exits, so every jump out of a function is findable by searching for one word."],
  ["p","A function wrapping dplyr verbs needs help, because those verbs look bare words up as columns. Embrace a column argument with double braces to substitute the caller's word, embrace tidy selections the same way, and use all_of() when the caller supplies strings instead of bare names. Arguments carrying plain values need nothing. A plot function follows the same rule: embrace inside aes(), leave titles and bin widths alone, and check the returned object with length(p$layers), get_labs(p) and ggplot_build(p), because printing a plot in this app produces no text."],
  ["p","Answer the practice questions from memory before revealing the answers, then clear the graded exercises below. The next chapter is Iteration: doing the same thing to many columns with across(), to many list elements with the map family, and to many files at once."]
]}
],
questions: [
{ q:"What is the signal that a piece of code should become a function, and what becomes the argument?",
  a:"The same shape of code appearing a third time. Compare the copies and see what varies: in the recycling example only the vector name changed, and it changed twice per line, so the vector becomes the argument and the multiplication, division and rounding become the body. The reason is maintenance, not typing — three copies are three chances for an edit to be applied to two of them." },
{ q:"Name the three parts of a function definition and say what the call gives back.",
  a:"A name it is assigned to, an argument list in parentheses, and a body in braces. The value of the last expression evaluated in the body is returned, with no keyword needed. Name functions as verbs in snake_case, and give families a shared prefix so typing the prefix finds them all." },
{ q:"bump() creates a variable called running in its body. Why does exists(\"running\") report FALSE afterwards?",
  a:"Names created while a body runs belong to that call and vanish when it ends, so the function cannot litter your workspace. The traffic is one-way though: the body can still see names that already exist outside it, so a body mentioning a name that is neither an argument nor created inside will silently pick up whatever is lying around." },
{ q:"What does digits = 1 in the argument list do, and how do you read it back later?",
  a:"It makes digits optional and supplies the value used when the caller says nothing. It is stored in the definition, so names(formals(f)) lists the argument names and formals(f)$digits returns the default — 1 in this case." },
{ q:"One NA in the input made every percentage NA. Why add na.rm as an argument instead of hardcoding sum(x, na.rm = TRUE) in the body?",
  a:"Hardcoding it drops data on behalf of every future caller without telling them, and silently changes the meaning of the total. Passing it through keeps the cautious behaviour as the default and puts the choice with the person who knows why the value is missing. Note that removing an NA from the total still leaves that slot as NA in the result." },
{ q:"What is return() for, and why does the ordinary path in pct_of_total not use it?",
  a:"To leave a function before the end, which is how you handle a case with no sensible arithmetic — a total of zero, for instance — before the arithmetic runs. The normal path needs no return() because the last expression is already the value, and reserving the keyword for early exits means every jump out of the function can be found by searching for one word." },
{ q:"Why does group_by(group_var) fail inside a data frame function, and what does the error say?",
  a:"dplyr verbs use data masking: a bare word is looked up as a column of the data first. So group_by() searched for a column literally named group_var and never asked what the argument held. The message is Error: Must group by variables found in `.data`. The tell is that it names the parameter rather than the column." },
{ q:"What do the double braces do, and which arguments do not need them?",
  a:"They substitute the value of the argument — the column name the caller typed — before the masking lookup happens, so group_by({{ group_var }}) groups by the caller's column. Every argument naming a column needs its own pair, including inside arrange() and inside aes(). Arguments carrying ordinary values, such as digits or a numeric threshold or a title string, need nothing." },
{ q:"A caller wants to pass column names as strings, like c(\"parcels\", \"km\"). What do you use, and what happens if a string reaches an embraced argument instead?",
  a:"all_of(cols) inside the tidy selection. The two worlds fail differently: a tidy selection accepts an embraced string quietly and works, but a data-masking verb groups by the text itself — total_by(deliveries, \"depot\") returns one row, a column printed as `\"depot\"`, and every parcel summed, with no error at all. all_of() given a bare name is the opposite mistake and does error." },
{ q:"A function returns a ggplot object. Why can printing it not be the last line of an answer here, and what do you check instead?",
  a:"Printing a plot object emits no text in this app's R console, so the transcript would be empty and nothing could be graded. Inspect the object: length(p$layers) for the layer count, class(p$layers[[1]]$geom)[1] for the geom, the stat_params for a bin width, nrow(p$data) for the rows carried, get_labs(p) for the labels, and ggplot_build(p) for the numbers a stat computed." }
],
exercises: [
{ c:"functions", t:"A share above a cutoff", book:"r25",
  b:"Write a function named pct_above taking a numeric vector x and an argument cutoff with a default of 10, returning the percentage of values in x that are strictly greater than cutoff, rounded to one decimal place. Build a vector named readings holding 4, 12, 8, 15, 3, 21, 9 in that order. Then print pct_above applied to readings with the default, and again with cutoff set to 5.",
  o:"[1] 42.9\n[1] 71.4",
  h:["The body is one expression, and the value of that expression is what the call gives back. No keyword is needed to return it.",
     "A comparison over a vector gives a logical vector, and mean() of a logical vector is the proportion that are TRUE. Multiply by 100 before rounding. A default is written into the argument list as cutoff = 10.",
     "The argument list holds x and then cutoff with its default. The body is a single rounded expression: 100 times the mean of x compared against cutoff, to one decimal. Then two calls on separate lines, the second naming cutoff."]},
{ c:"functions", t:"Three bands, two early exits", book:"r25",
  b:"Write a function named band taking a single score plus arguments top defaulting to 90 and mid defaulting to 70. Using early returns, it gives back \"top\" when score is at least top, \"mid\" when score is at least mid, and otherwise \"low\". Print, on four lines, band applied to 94, to 71, to 40, and to 71 with mid set to 75.",
  o:"[1] \"top\"\n[1] \"mid\"\n[1] \"low\"\n[1] \"low\"",
  h:["Two of the three answers leave the function before the end. The third is just the last expression in the body.",
     "return() takes the value to hand back and stops there, so the checks can be written as two separate if blocks with no else between them. Order matters: test the highest band first.",
     "The shape is an if block testing score against top with a return inside, then an if block testing score against mid with a return inside, then the remaining value on its own line. The last call needs mid named, since it is not the first optional argument."]},
{ c:"functions", t:"Grouping by whichever column", book:"r25",
  b:"Attach dplyr with suppressMessages and attach tibble. Build a tibble named stalls with a character column market holding \"quay\", \"quay\", \"hill\", \"hill\", \"hill\", \"gate\"; a character column trader holding \"Ada\", \"Bo\", \"Ada\", \"Cyd\", \"Bo\", \"Cyd\"; and a numeric column crates holding 6, 4, 9, 5, 7, 3. Write a function named crate_totals taking a data frame and a grouping column, which groups by that column, sums crates into a column named crates with .groups set to \"drop\", and arranges by the grouping column. Print it applied to stalls grouped by market, then grouped by trader.",
  o:"# A tibble: 3 × 2\n  market crates\n  <chr>   <dbl>\n1 gate        3\n2 hill       21\n3 quay       10\n# A tibble: 3 × 2\n  trader crates\n  <chr>   <dbl>\n1 Ada        15\n2 Bo         11\n3 Cyd         8",
  h:["Writing group_by(group_var) makes dplyr look for a column with that literal name, which is not what you want.",
     "Every argument that names a column has to be embraced so the caller's word is substituted before the lookup. arrange() is a dplyr verb too, so the same argument needs embracing there as well.",
     "The body is df piped into group_by with the grouping argument in double braces, then summarise(crates = sum(crates), .groups = \"drop\"), then arrange with the same argument in double braces. Then two calls, one per line."]},
{ c:"ggplot2 basics", t:"A histogram function you can inspect", book:"r25",
  b:"Attach ggplot2 and tibble. Build a tibble named hauls with a character column boat holding \"Ren\", \"Sol\", \"Vim\", \"Kip\", \"Ash\", \"Nim\" and a numeric column kg holding 12, 18, 9, 24, 15, 21. Write a function named kg_hist taking a data frame, a column, and a binwidth argument defaulting to 5, which returns a ggplot mapping that column to x with a histogram layer using that bin width. Store kg_hist applied to hauls and kg in p, then print the number of layers, the class of the first layer's geom (first element only), the layer's stored bin width, and the x label the plot will use.",
  o:"[1] 1\n[1] \"GeomBar\"\n[1] 5\n[1] \"kg\"",
  h:["The column argument is used inside aes(), which masks data exactly like a dplyr verb does. The bin width is an ordinary number and needs no special treatment.",
     "A histogram stores its bin width on the layer's stat, not its geom, and the geom a histogram draws with is the same one a bar chart uses. Printing the plot itself would produce no text, so ask the object questions instead.",
     "Four single expressions after the assignment: length() over p$layers, class() of p$layers[[1]]$geom subset with [1], p$layers[[1]]$stat_params$binwidth, and get_labs(p)$x."]}
]
};
