/* Practice Log book — R Chapter 26: Iteration.
   Original lesson text following the chapter-by-chapter curriculum of
   "R for Data Science" (2nd ed.) by Hadley Wickham, Mine Cetinkaya-Rundel,
   and Garrett Grolemund. Read the original chapter free at the src link below.
   Every shown output was captured by executing the code in WebR, not written from memory. */
window.BOOK_R = window.BOOK_R || { chapters: {} };
window.BOOK_R.chapters.r26 = {
n: 26,
title: "Iteration",
src: "https://r4ds.hadley.nz/iteration.html",
blurb: "Doing one thing many times: across() over columns, the map family over lists, walk() for side effects, and reading a folder of files into one table.",
pkgs: ["dplyr", "tibble", "purrr"],
sections: [
{ t: "Three shapes of repetition",
  body: [
  ["p","Chapter 25 removed duplication by naming the code that repeated. This chapter removes the other kind: the same code applied to many things. Three tools cover almost all of it. across() runs one job over many columns inside a dplyr verb. The map family runs one job over every element of a list. walk() does the same when the point is a side effect rather than an answer."],
  ["p","dplyr and tibble supply the data frames, purrr supplies the map family. purrr attaches quietly; dplyr prints a banner, so it is wrapped."],
  ["code","suppressMessages(library(dplyr))\nlibrary(tibble)\nlibrary(purrr)"],
  ["p","Four weather stations, each with a morning and an afternoon reading of temperature in degrees and rainfall in inches."],
  ["code","sensors <- tibble(\n  station = c(\"alpha\", \"bravo\", \"charlie\", \"delta\"),\n  temp_am = c(11.2, 9.8, 13.4, 10.5),\n  temp_pm = c(18.6, 16.1, 21.0, 17.3),\n  rain_am = c(0.0, 2.4, 1.1, 0.6),\n  rain_pm = c(3.2, 0.0, 4.5, 1.8)\n)\n\nsensors"],
  ["code","# A tibble: 4 × 5\n  station temp_am temp_pm rain_am rain_pm\n  <chr>     <dbl>   <dbl>   <dbl>   <dbl>\n1 alpha      11.2    18.6     0       3.2\n2 bravo       9.8    16.1     2.4     0  \n3 charlie    13.4    21       1.1     4.5\n4 delta      10.5    17.3     0.6     1.8"],
  ["p","Averaging every numeric column the long way means writing the same call four times, with the column name appearing twice in each."],
  ["code","sensors |>\n  summarise(\n    temp_am = mean(temp_am),\n    temp_pm = mean(temp_pm),\n    rain_am = mean(rain_am),\n    rain_pm = mean(rain_pm)\n  )"],
  ["code","# A tibble: 1 × 4\n  temp_am temp_pm rain_am rain_pm\n    <dbl>   <dbl>   <dbl>   <dbl>\n1    11.2    18.2    1.02    2.38"],
  ["p","across() takes two things: a selection of columns and the function to run on each. The result is identical, and it stays identical when a fifth numeric column arrives next month."],
  ["code","sensors |>\n  summarise(across(where(is.numeric), mean))"],
  ["code","# A tibble: 1 × 4\n  temp_am temp_pm rain_am rain_pm\n    <dbl>   <dbl>   <dbl>   <dbl>\n1    11.2    18.2    1.02    2.38"],
  ["note","across() only means anything inside a dplyr verb. It is not a standalone function you can call on a data frame, and typing across(sensors, mean) does not work in either direction. Think of it as an instruction to summarise() or mutate() rather than as a thing that computes a result on its own."]
]},
{ t: "Choosing the columns for across()",
  body: [
  ["p","The first argument is a tidy selection, the same language select() speaks. where() takes a predicate and keeps the columns it says TRUE to. The name helpers — starts_with(), ends_with(), contains() — match on the column name instead."],
  ["code","sensors |>\n  summarise(across(starts_with(\"temp\"), median))"],
  ["code","# A tibble: 1 × 2\n  temp_am temp_pm\n    <dbl>   <dbl>\n1    10.8    18.0"],
  ["p","Inside mutate() the same selection rewrites the columns in place rather than collapsing them. Here the rainfall columns are converted from inches to millimetres, and everything else is left alone."],
  ["code","sensors |>\n  mutate(across(starts_with(\"rain\"), \\(x) round(x * 25.4, 1))) |>\n  arrange(station)"],
  ["code","# A tibble: 4 × 5\n  station temp_am temp_pm rain_am rain_pm\n  <chr>     <dbl>   <dbl>   <dbl>   <dbl>\n1 alpha      11.2    18.6     0      81.3\n2 bravo       9.8    16.1    61       0  \n3 charlie    13.4    21      27.9   114. \n4 delta      10.5    17.3    15.2    45.7"],
  ["p","The backslash is R's short form for an anonymous function, so \\(x) round(x * 25.4, 1) is a function of one argument written where it is used. That form matters: across() hands each column to the function as its single argument, so anything the function needs beyond the column has to be baked in."],
  ["p","Selections can cross the grain of the data too. Ends-with picks the afternoon columns whatever they measure."],
  ["code","sensors |>\n  summarise(across(ends_with(\"_pm\"), max))"],
  ["code","# A tibble: 1 × 2\n  temp_pm rain_pm\n    <dbl>   <dbl>\n1      21     4.5"],
  ["note","where(is.numeric) is a function being handed over, so it goes in without parentheses on the inner name — where(is.numeric), not where(is.numeric()). Adding the parentheses calls is.numeric with no argument at the moment you write the line, and the error that comes back talks about a missing argument rather than about column selection, which sends people looking in the wrong place."]
]},
{ t: "Several functions, and the names they make",
  body: [
  ["p","Passing a named list of functions runs every one of them on every selected column. The result gets one column per pair, named by gluing the column name to the function name."],
  ["code","sensors |>\n  summarise(across(starts_with(\"temp\"), list(low = min, high = max)))"],
  ["code","# A tibble: 1 × 4\n  temp_am_low temp_am_high temp_pm_low temp_pm_high\n        <dbl>        <dbl>       <dbl>        <dbl>\n1         9.8         13.4        16.1           21"],
  ["p","The default naming is column then function. .names takes a template in which {.col} stands for the column name and {.fn} for the function name, so the pieces can be reordered or joined differently."],
  ["code","sensors |>\n  summarise(across(starts_with(\"temp\"), list(low = min, high = max),\n                   .names = \"{.fn}_{.col}\"))"],
  ["code","# A tibble: 1 × 4\n  low_temp_am high_temp_am low_temp_pm high_temp_pm\n        <dbl>        <dbl>       <dbl>        <dbl>\n1         9.8         13.4        16.1           21"],
  ["p","Filtering is the one verb across() does not serve, because filter() needs a single logical vector and across() hands back several columns. if_any() keeps a row when at least one selected column says TRUE, and if_all() keeps it only when every one does."],
  ["code","sensors |>\n  filter(if_any(starts_with(\"rain\"), \\(x) x == 0)) |>\n  arrange(station)"],
  ["code","# A tibble: 2 × 5\n  station temp_am temp_pm rain_am rain_pm\n  <chr>     <dbl>   <dbl>   <dbl>   <dbl>\n1 alpha      11.2    18.6     0       3.2\n2 bravo       9.8    16.1     2.4     0  "],
  ["p","Two stations had a dry half-day. Now the stations that were above ten degrees both morning and afternoon."],
  ["code","sensors |>\n  filter(if_all(starts_with(\"temp\"), \\(x) x > 10)) |>\n  arrange(station)"],
  ["code","# A tibble: 3 × 5\n  station temp_am temp_pm rain_am rain_pm\n  <chr>     <dbl>   <dbl>   <dbl>   <dbl>\n1 alpha      11.2    18.6     0       3.2\n2 charlie    13.4    21       1.1     4.5\n3 delta      10.5    17.3     0.6     1.8"],
  ["p","A selection can be an argument, which is the chapter 25 lesson applied here: embrace it, because tidy selection masks the data exactly the way a verb does."],
  ["code","mean_cols <- function(df, cols) {\n  df |> summarise(across({{ cols }}, mean))\n}\n\nmean_cols(sensors, starts_with(\"rain\"))"],
  ["code","# A tibble: 1 × 2\n  rain_am rain_pm\n    <dbl>   <dbl>\n1    1.02    2.38"],
  ["note","if_any() and if_all() are for filter(), and reaching for across() there is the mistake almost everybody makes once. The error is not about filter wanting a logical vector in plain words, so if a filter over several columns complains about an argument, check which of the three you actually typed."]
]},
{ t: "Lists and the map family",
  body: [
  ["p","A data frame is a rectangle: every column the same length. A list has no such rule, so it is what you get when the pieces differ — three boats with different numbers of trips, for instance. Nothing about that fits in a column."],
  ["code","hauls <- list(\n  ren = c(12, 18, 9),\n  sol = c(24, 15),\n  vim = c(21, 30, 27, 19)\n)\n\nhauls"],
  ["code","$ren\n[1] 12 18  9\n\n$sol\n[1] 24 15\n\n$vim\n[1] 21 30 27 19"],
  ["p","Printing a list shows each element under its name with a dollar sign. length() counts the elements, not the values inside them, and lengths() with an s reports the size of each element."],
  ["code","length(hauls)\nnames(hauls)\nclass(hauls)\nlengths(hauls)"],
  ["code","[1] 3\n[1] \"ren\" \"sol\" \"vim\"\n[1] \"list\"\nren sol vim \n  3   2   4 "],
  ["p","map() applies a function to every element and returns a list of the results, always. Same length as the input, same names, one result per element."],
  ["code","map(hauls, mean)"],
  ["code","$ren\n[1] 13\n\n$sol\n[1] 19.5\n\n$vim\n[1] 24.25"],
  ["p","A list of single numbers is rarely what you wanted. The suffixed variants promise a plain vector of a stated type instead: map_dbl for doubles, map_int for integers, map_chr for character, map_lgl for logical. The names carry over."],
  ["code","map_dbl(hauls, mean)\nmap_int(hauls, length)\nmap_chr(hauls, \\(x) paste(x, collapse = \"-\"))\nmap_lgl(hauls, \\(x) mean(x) > 18)"],
  ["code","  ren   sol   vim \n13.00 19.50 24.25 \nren sol vim \n  3   2   4 \n          ren           sol           vim \n    \"12-18-9\"       \"24-15\" \"21-30-27-19\" \n  ren   sol   vim \nFALSE  TRUE  TRUE "],
  ["note","map() over a data frame iterates over its columns, not its rows, because a data frame is a list of columns. That is occasionally what you want and usually a surprise. If you find yourself writing map() over a data frame to do something per row, the answer is almost always a dplyr verb instead."]
]},
{ t: "One type in, one type out",
  body: [
  ["p","The suffix on map_dbl is a promise, and purrr checks it on every element. If the function hands back something that is not one double, the call stops rather than quietly returning a ragged answer. range() returns two numbers, so it breaks the promise on the first element."],
  ["code","map_dbl(hauls, range)"],
  ["code","Error: In index: 1."],
  ["p","This app's R console prints only the first line of a purrr error, and that line says where the trouble was without saying what it was. The detail sits on the error's parent condition, which you can pull out with tryCatch."],
  ["code","detail <- tryCatch(map_dbl(hauls, range), error = function(e) conditionMessage(e$parent))\n\ntrimws(detail)"],
  ["code","[1] \"Result must be length 1, not 2.\""],
  ["p","That is the whole complaint: one value was promised and two arrived. Nothing is wrong with the function, only with the container asked to hold the answers, so plain map() takes the same call without objection."],
  ["code","map(hauls, range)"],
  ["code","$ren\n[1]  9 18\n\n$sol\n[1] 15 24\n\n$vim\n[1] 19 30"],
  ["p","The other half of the promise is type, not length. map_chr over a function returning numbers gives one value per element and still refuses, because a double is not a string and purrr will not silently convert it."],
  ["code","trimws(tryCatch(map_chr(hauls, mean), error = function(e) conditionMessage(e$parent)))"],
  ["code","[1] \"Can't coerce from a number to a string.\""],
  ["p","So choose the suffix that matches what the function actually returns, and reach for an anonymous function when you need to adjust the result on the way out."],
  ["code","map_dbl(hauls, \\(x) round(mean(x), 1))"],
  ["code"," ren  sol  vim \n13.0 19.5 24.2 "],
  ["note","Reading 24.2 there and expecting 24.3 is the rounding rule, not a bug: R rounds a value ending in exactly half to the nearest even digit, so 24.25 goes to 24.2. Note also that the strictness is the feature. A map_dbl that quietly coerced would hand you a vector that looks right and is wrong somewhere in the middle, and you would find out three steps later."]
]},
{ t: "Reading many files",
  body: [
  ["p","The classic iteration job is a folder of files with the same shape. Build one first: three small comma-separated files, one per depot, written straight into the working directory. writeLines() overwrites, so this block can be run again without complaint."],
  ["code","dir.create(\"depot_logs\", showWarnings = FALSE)\n\nwriteLines(c(\"driver,parcels\", \"Ines,31\", \"Dara,24\"), \"depot_logs/north.csv\")\nwriteLines(c(\"driver,parcels\", \"Omar,19\", \"Lena,22\"), \"depot_logs/south.csv\")\nwriteLines(c(\"driver,parcels\", \"Yuki,35\", \"Omar,27\"), \"depot_logs/east.csv\")\n\nlist.files(\"depot_logs\")"],
  ["code","[1] \"east.csv\"  \"north.csv\" \"south.csv\""],
  ["note","In this app those files live in the browser's in-memory filesystem, not on your device, and they are gone when the page reloads. On a desktop the same calls write into your working directory. Everything else in this section behaves identically in both places."],
  ["p","list.files() with full.names gives paths you can hand straight to a reader, and pattern filters out anything that is not a csv. The result is sorted, which is worth knowing because the order of the files becomes the order of the rows."],
  ["code","paths <- list.files(\"depot_logs\", pattern = \"[.]csv$\", full.names = TRUE)\n\npaths"],
  ["code","[1] \"depot_logs/east.csv\"  \"depot_logs/north.csv\" \"depot_logs/south.csv\""],
  ["p","Now the iteration. map() over the paths with read.csv gives a list of three data frames, and because the pieces differ in nothing but content, they can be checked as a group."],
  ["code","frames <- map(paths, read.csv)\n\nlength(frames)\nmap_int(frames, nrow)\nframes[[2]]"],
  ["code","[1] 3\n[1] 2 2 2\n  driver parcels\n1   Ines      31\n2   Dara      24"],
  ["p","list_rbind() stacks a list of data frames into one. It is purrr's counterpart to map(): map produces the list, list_rbind collapses it."],
  ["code","list_rbind(frames)"],
  ["code","  driver parcels\n1   Yuki      35\n2   Omar      27\n3   Ines      31\n4   Dara      24\n5   Omar      19\n6   Lena      22"],
  ["p","Six rows, and no way to tell which depot any of them came from — the filename held that, and reading the file threw it away. set_names() attaches a name to each path, and list_rbind() will turn those names into a column if you ask."],
  ["code","named <- set_names(paths, \\(p) sub(\"[.]csv$\", \"\", basename(p)))\n\nnames(named)"],
  ["code","[1] \"east\"  \"north\" \"south\""],
  ["code","all_runs <- named |>\n  map(read.csv) |>\n  list_rbind(names_to = \"depot\")\n\nall_runs"],
  ["code","  depot driver parcels\n1  east   Yuki      35\n2  east   Omar      27\n3 north   Ines      31\n4 north   Dara      24\n5 south   Omar      19\n6 south   Lena      22"],
  ["p","Now it is one tidy table and the rest of the tidyverse applies."],
  ["code","all_runs |>\n  group_by(depot) |>\n  summarise(parcels = sum(parcels), .groups = \"drop\") |>\n  arrange(depot)"],
  ["code","# A tibble: 3 × 2\n  depot parcels\n  <chr>   <int>\n1 east       62\n2 north      55\n3 south      41"],
  ["note","Data in the path is the thing people lose. A file named by date, region or run number carries a variable, and reading the file discards it unless you capture it first. Name the paths before you map over them, and the column arrives with the data instead of being reconstructed later from a row count you half remember."]
]},
{ t: "walk() and saving many outputs",
  body: [
  ["p","Some jobs have no answer to collect: writing files, printing progress, drawing to a device. walk() runs the function over every element for its effect and returns the input unchanged, invisibly, so it can sit in the middle of a pipeline."],
  ["code","walk(names(named), \\(nm) cat(\"read\", nm, \"\\n\"))"],
  ["code","read east \nread north \nread south "],
  ["p","The return value is the input, which is what invisibly means here: the printing happened, and nothing new came back."],
  ["code","out <- walk(hauls, \\(x) cat(sum(x), \"\\n\"))\n\nidentical(out, hauls)"],
  ["code","39 \n39 \n97 \n[1] TRUE"],
  ["p","Using map() for the same job works and leaves litter. cat() returns NULL, so map() dutifully collects three NULLs into a list and prints them."],
  ["code","junk <- map(names(named), \\(nm) cat(\"read\", nm, \"\\n\"))\n\njunk"],
  ["code","read east \nread north \nread south \n[[1]]\nNULL\n\n[[2]]\nNULL\n\n[[3]]\nNULL"],
  ["p","iwalk() passes the name alongside the value, so the function takes two arguments: the element first, its name second."],
  ["code","iwalk(hauls, \\(x, nm) cat(nm, sum(x), \"\\n\"))"],
  ["code","ren 39 \nsol 39 \nvim 97 "],
  ["p","Saving many outputs is the same pattern with a file-writing function. split() cuts a data frame into a named list by the values of a column, and walk2() steps through two lists in parallel — here the pieces and their names."],
  ["code","dir.create(\"by_depot\", showWarnings = FALSE)\n\npieces <- split(all_runs, all_runs$depot)\n\nwalk2(pieces, names(pieces), \\(d, nm) write.csv(d, paste0(\"by_depot/\", nm, \".csv\"), row.names = FALSE))\n\nlist.files(\"by_depot\")"],
  ["code","[1] \"east.csv\"  \"north.csv\" \"south.csv\""],
  ["p","When the result is an R object rather than a table for someone else, saveRDS() writes one object to one file and readRDS() reads it back with its types intact."],
  ["code","saveRDS(all_runs, \"all_runs.rds\")\n\nfile.exists(\"all_runs.rds\")\nnrow(readRDS(\"all_runs.rds\"))"],
  ["code","[1] TRUE\n[1] 6"],
  ["note","walk2() needs its two lists in the same order, and split() sorts its output by the splitting value while your original data frame is in whatever order it arrived. Pairing a list of pieces against a vector of names you typed by hand is how files end up with the wrong contents under the right name. Take the names from the list itself, as above."]
]},
{ t: "The base R relatives",
  body: [
  ["p","The apply family predates purrr and is in every R installation, so you will read it in other people's code whether or not you write it. lapply() is map(): a function over every element, a list back."],
  ["code","lapply(hauls, mean)"],
  ["code","$ren\n[1] 13\n\n$sol\n[1] 19.5\n\n$vim\n[1] 24.25"],
  ["p","sapply() tries to simplify the list into a vector or a matrix, and vapply() does the same job with a stated result type. Given a function that returns one number, both give the same answer as map_dbl."],
  ["code","sapply(hauls, mean)\nvapply(hauls, mean, numeric(1))"],
  ["code","  ren   sol   vim \n13.00 19.50 24.25 \n  ren   sol   vim \n13.00 19.50 24.25 "],
  ["p","The difference shows up when the function returns something else. sapply() decides at runtime what shape to give you: two numbers per element and it silently becomes a matrix."],
  ["code","sapply(hauls, range)"],
  ["code","     ren sol vim\n[1,]   9  15  19\n[2,]  18  24  30"],
  ["p","vapply() was told to expect one double per element, so it refuses the same call and says exactly which element and what length it got — the base-R equivalent of the message purrr put on the parent condition."],
  ["code","vapply(hauls, range, numeric(1))"],
  ["code","Error: values must be length 1,\n but FUN(X[[1]]) result is length 2"],
  ["p","The sharpest edge is an empty input. sapply() has nothing to simplify, so it hands back a list whatever you were expecting, and any code downstream that assumed a numeric vector fails somewhere else entirely."],
  ["code","sapply(list(), mean)\nclass(sapply(list(), mean))\nclass(map(list(), mean))"],
  ["code","list()\n[1] \"list\"\n[1] \"list\""],
  ["note","sapply() in a script is the one to be wary of. It is convenient at the console, where you can see what came back, and unreliable inside a function, where the shape of the result depends on data you have not seen. Use vapply() or a suffixed map when something downstream depends on the type."]
]},
{ t: "Summary",
  body: [
  ["p","across() runs one or more functions over a tidy selection of columns inside a dplyr verb. Pick the columns with where(is.numeric) or a name helper, pass a list of functions to get several at once, and use .names with {.col} and {.fn} to control what the result columns are called. filter() takes if_any() or if_all() instead, and a column selection passed as an argument needs the double braces from chapter 25."],
  ["p","map() applies a function to every element of a list and always returns a list. The suffixed forms — map_dbl, map_int, map_chr, map_lgl — promise a plain vector of one type, and purrr enforces the promise: a result of the wrong length or the wrong type stops the call. This console shows only the first line of that error, so pull conditionMessage(e$parent) out with tryCatch when the first line is not enough."],
  ["p","A folder of same-shaped files becomes one table with list.files(), map() over a reader, and list_rbind(). Name the paths with set_names() first and pass names_to so that whatever the filename encoded arrives as a column. When the point is a side effect rather than a value, walk() replaces map(), walk2() steps through two lists together, and iwalk() supplies each element's name. lapply(), sapply() and vapply() are the base-R equivalents, and sapply() is the one to distrust in a script because it chooses the shape of its result at runtime."],
  ["p","Answer the practice questions from memory before revealing the answers, then clear the graded exercises below. The next chapter is A field guide to base R: the square brackets, the dollar sign and the other base idioms you have been reading around, explained in their own terms."]
]}
],
questions: [
{ q:"What two things does across() take, and where can it be used?",
  a:"A tidy selection of columns and the function or functions to run on each. It only works inside a dplyr verb such as summarise() or mutate() — it is an instruction to the verb, not a standalone function you can call on a data frame." },
{ q:"Give the two ways of choosing columns for across(), and say which one survives a new column being added.",
  a:"where() takes a predicate and keeps the columns it says TRUE to, as in where(is.numeric). The name helpers — starts_with(), ends_with(), contains() — match on the column name. Both survive new columns, which is the point: a fifth numeric column joins the selection without an edit. Note that where(is.numeric) passes the function itself, with no parentheses on is.numeric." },
{ q:"What happens when you pass a list of functions to across(), and how do you control the resulting column names?",
  a:"Every function runs on every selected column, giving one result column per pair, named column-then-function by default. .names takes a template where {.col} is the column name and {.fn} is the function name, so .names = \"{.fn}_{.col}\" reverses the order." },
{ q:"Why can filter() not use across(), and what does it use instead?",
  a:"filter() needs a single logical vector per row and across() hands back several columns. if_any() keeps a row when at least one selected column is TRUE, and if_all() keeps it only when every selected column is TRUE." },
{ q:"What does map() always return, and how do map_dbl, map_int, map_chr and map_lgl differ?",
  a:"map() returns a list, the same length as the input and carrying the same names, whatever the function gave back. The suffixed forms promise a plain atomic vector of a stated type instead, and purrr checks that promise on every element rather than coercing." },
{ q:"map_dbl(hauls, range) fails. What is the error here, what is actually wrong, and how do you see the detail?",
  a:"The console shows Error: In index: 1., which says where but not what. Nothing is wrong with range() — it returns two numbers and map_dbl promised one, so the container is the problem and plain map() takes the same call happily. The detail is on the error's parent condition: tryCatch(..., error = function(e) conditionMessage(e$parent)) reports Result must be length 1, not 2." },
{ q:"Describe the three steps that turn a folder of same-shaped csv files into one table.",
  a:"list.files() with full.names = TRUE and a pattern gives the paths in sorted order, map() over those paths with a reader gives a list of data frames, and list_rbind() stacks that list into one table." },
{ q:"A filename encodes the depot. How do you keep that information once the file is read?",
  a:"Name the paths before mapping over them — set_names() with a function that strips the directory and extension — and then pass names_to to list_rbind(), which turns those names into a column. Reading the file alone throws the path away, so the variable has to be captured before the read." },
{ q:"When do you use walk() instead of map(), and what does walk() return?",
  a:"When the function is run for its side effect — writing a file, printing progress — rather than for a value. walk() returns its input unchanged and invisibly, so it can sit in a pipeline. Using map() there works but collects the function's return values, so a loop of cat() calls leaves you a list of NULLs to print." },
{ q:"What are the base R equivalents of map() and map_dbl(), and why is sapply() risky inside a function?",
  a:"lapply() is map(): a list in, a list out. vapply() is the closest thing to map_dbl, because it is told the result type and refuses anything else. sapply() simplifies whatever it gets, so its result shape depends on the data — a function returning two values gives a matrix, and an empty input gives back a list. That makes it convenient at the console and unreliable in a script." }
],
exercises: [
{ c:"iteration", t:"Three summaries of one list", book:"r26",
  b:"Attach purrr. Build a named list called kilns with element east holding 940, 980, 1010; element north holding 900, 950, 1000, 970; and element west holding 1120, 1080, in that order. Print three lines: the mean of each element as a double vector, the number of values in each element as an integer vector, and for each element the smallest and largest joined by a hyphen as a character vector.",
  o:"     east     north      west \n 976.6667  955.0000 1100.0000 \n east north  west \n    3     4     2 \n       east       north        west \n \"940-1010\"  \"900-1000\" \"1080-1120\" ",
  h:["Three calls over the same list, differing only in the function applied and the type of vector you want back.",
     "The suffix on a map decides the type of the result: map_dbl for doubles, map_int for integers, map_chr for character. The third one needs a function of its own, written inline with the backslash shorthand.",
     "The first two hand a bare function name straight to the map. The third takes an anonymous function whose body pastes range(x) together with collapse set to a hyphen."]},
{ c:"iteration", t:"Print, do not collect", book:"r26",
  b:"Attach purrr. Build a named list called crates with element ash holding 4 and 6, element birch holding 9, and element cedar holding 2, 3 and 5. Using a function that iterates for its side effect rather than its value, print one line per element holding the element's name, a space, and the total of its values.",
  o:"ash 10 \nbirch 9 \ncedar 10 ",
  h:["The job here is printing, so the value the function returns is of no interest and should not end up on screen.",
     "walk() runs a function over every element and returns the input invisibly, so nothing extra is printed. cat() writes its arguments separated by spaces and adds no line break of its own.",
     "One call to walk over the names of the list, with an anonymous function that cats the name, the sum of the matching element, and a newline. Using map() here would print the same lines and then a list of NULLs."]},
{ c:"apply family", t:"The same job three base ways", book:"r26",
  b:"Build a named list called readings with element a holding 3, 7, 5; element b holding 10, 12; and element c holding 8, 8, 9, 11. Using base R only, print three lines: the largest value in each element simplified to a vector, the mean of each element with the result type stated as one double, and the number of values in each element as a plain named vector rather than a list.",
  o:" a  b  c \n 7 12 11 \n a  b  c \n 5 11  9 \na b c \n3 2 4 ",
  h:["Three different members of the apply family, one per line, and no package needs attaching for any of them.",
     "sapply() simplifies its result and guesses the shape. vapply() takes a template argument saying what each result should look like. lapply() always returns a list, so something has to flatten it.",
     "The second call needs numeric(1) as its third argument. The third call wraps lapply() in unlist() to turn the list of lengths into a named vector."]},
{ c:"dplyr verbs", t:"Every numeric column at once", book:"r26",
  b:"Attach dplyr with suppressMessages and attach tibble. Build a tibble named plots with a character column plot holding \"a\", \"b\", \"c\"; a numeric column beans_kg holding 3.5, 4.2, 2.8; a numeric column peas_kg holding 1.1, 0.9, 1.6; and a character column note holding \"dry\", \"wet\", \"dry\". Print two summaries: the mean of every numeric column, and then the smallest and largest of every column whose name ends in _kg, with the low named first and the high second.",
  o:"# A tibble: 1 × 2\n  beans_kg peas_kg\n     <dbl>   <dbl>\n1      3.5     1.2\n# A tibble: 1 × 4\n  beans_kg_low beans_kg_high peas_kg_low peas_kg_high\n         <dbl>         <dbl>       <dbl>        <dbl>\n1          2.8           4.2         0.9          1.6",
  h:["Neither summary should name a single column. Both describe the columns they want and let dplyr find them.",
     "across() takes a selection then a function. where() screens columns by a predicate, ends_with() screens them by name, and a named list of functions runs all of them and glues the names on.",
     "The first summarise uses where(is.numeric) with mean. The second uses ends_with(\"_kg\") with list(low = min, high = max), and the default naming already puts the column before the function."]}
]
};
