/* Practice Log book — R Chapter 27: A field guide to base R.
   Original lesson text following the chapter-by-chapter curriculum of
   "R for Data Science" (2nd ed.) by Hadley Wickham, Mine Cetinkaya-Rundel,
   and Garrett Grolemund. Read the original chapter free at the src link below.
   Every shown output was captured by executing the code in WebR, not written from memory. */
window.BOOK_R = window.BOOK_R || { chapters: {} };
window.BOOK_R.chapters.r27 = {
n: 27,
title: "A field guide to base R",
src: "https://r4ds.hadley.nz/base-R.html",
blurb: "The base R vocabulary a tidyverse user still meets daily: [ against [[, the $ shortcut, lists and str(), the apply family against purrr, for loops, and plots that print nothing.",
pkgs: ["tibble"],
sections: [
{ t: "Why base R is still in front of you",
  body: [
  ["p","The tidyverse gives you a verb for most things, and for a while it feels like the whole language. Then you read someone else's script, or an error message from inside a package, or a Stack Overflow answer from 2014, and the code is square brackets and dollar signs and a for loop. None of it is deprecated. The tidyverse sits on top of base R rather than replacing it, so the base vocabulary is what you fall back to whenever you leave a data frame behind — and lists, model objects, and the results of most non-tidyverse functions are not data frames."],
  ["p","This chapter is that vocabulary. Two subsetting operators do most of the work: a single bracket, which keeps the container and gives you a smaller one, and a double bracket, which reaches inside and hands you what was stored there. Nearly everything else in the chapter follows from telling those two apart."],
  ["p","Almost every line here is base R, so nothing needs attaching. The one exception is section 4, which compares a data frame against a tibble, and tibble is a package."],
  ["code","library(tibble)"],
  ["note","The two operators read almost identically and are easy to swap by accident, because on a vector of numbers they often give you the same-looking answer. The difference only bites once the container holds something interesting — a list, a data frame, a fitted model. By then the wrong operator has usually travelled a few lines from where you typed it."]
]},
{ t: "Selecting many elements with [",
  body: [
  ["p","A single bracket applied to a vector returns a vector. It can be shorter, longer, or reordered, but it is still the same kind of thing you started with. Here are seven high-tide readings in centimetres, one per day."],
  ["code","tide_cm <- c(412, 388, 455, 401, 470, 366, 428)\n\ntide_cm[3]\ntide_cm[c(1, 5, 7)]\ntide_cm[2:4]"],
  ["code","[1] 455\n[1] 412 470 428\n[1] 388 455 401"],
  ["p","Positive numbers say which positions to keep, and they may repeat or run in any order. Negative numbers say which positions to drop, and everything else comes back."],
  ["code","tide_cm[-1]\ntide_cm[-c(1, 6)]"],
  ["code","[1] 388 455 401 470 366 428\n[1] 388 455 401 470 428"],
  ["p","What you cannot do is combine the two ideas in one index. R has no way to read that as anything sensible, so it stops."],
  ["code","tide_cm[c(-1, 2)]"],
  ["code","Error: only 0's may be mixed with negative subscripts"],
  ["p","A logical vector is the third kind of index, and it is the one you will use most. A comparison produces one TRUE or FALSE per element, and indexing with it keeps the positions marked TRUE. The comparison and the subset are two separate steps, which is worth seeing written out."],
  ["code","tide_cm > 420\ntide_cm[tide_cm > 420]"],
  ["code","[1] FALSE FALSE  TRUE FALSE  TRUE FALSE  TRUE\n[1] 455 470 428"],
  ["p","If the vector has names, a character vector is the fourth kind of index. Names survive subsetting, so the answer arrives labelled."],
  ["code","names(tide_cm) <- c(\"mon\", \"tue\", \"wed\", \"thu\", \"fri\", \"sat\", \"sun\")\n\ntide_cm[c(\"wed\", \"sun\")]\ntide_cm[\"thu\"]"],
  ["code","wed sun \n455 428 \nthu \n401"],
  ["p","Asking for a position past the end is not an error. R returns NA with a missing name, which is how an off-by-one mistake travels quietly into the next calculation. Position zero is legal too and returns nothing at all — a vector of length 0, not an error and not NULL."],
  ["code","tide_cm[9]\ntide_cm[0]\nlength(tide_cm[0])"],
  ["code","<NA> \n  NA \nnamed numeric(0)\n[1] 0"],
  ["note","A logical index shorter than the vector is recycled to fit rather than rejected. c(TRUE, FALSE) against seven elements repeats to TRUE FALSE TRUE FALSE TRUE FALSE TRUE and takes every other reading, which is occasionally what you wanted and usually a sign that your condition was computed on the wrong vector. Check that the logical vector is the same length as the thing you are indexing."],
  ["code","tide_cm[c(TRUE, FALSE)]"],
  ["code","mon wed fri sun \n412 455 470 428"]
]},
{ t: "Data frames, and the comma",
  body: [
  ["p","A data frame is two-dimensional, so its single bracket takes two indexes separated by a comma: rows before it, columns after it. Each index can be any of the four kinds from section 2. This manifest lists five crates with a mass and the hold they are stowed in."],
  ["code","crates <- data.frame(\n  id = c(\"C1\", \"C2\", \"C3\", \"C4\", \"C5\"),\n  mass_kg = c(18.5, 42, 7.25, 31.75, 12),\n  hold = c(\"fore\", \"aft\", \"fore\", \"mid\", \"aft\")\n)\n\ncrates"],
  ["code","  id mass_kg hold\n1 C1   18.50 fore\n2 C2   42.00  aft\n3 C3    7.25 fore\n4 C4   31.75  mid\n5 C5   12.00  aft"],
  ["p","With no comma at all, the index is read as columns. So a single bracket and one number gives you a one-column data frame, not a column."],
  ["code","crates[1]\nclass(crates[1])"],
  ["code","  id\n1 C1\n2 C2\n3 C3\n4 C4\n5 C5\n[1] \"data.frame\""],
  ["p","Put the comma in with nothing after it and the index becomes rows. Same bracket, same number, different answer: one row of all three columns."],
  ["code","crates[1, ]\nclass(crates[1, ])"],
  ["code","  id mass_kg hold\n1 C1    18.5 fore\n[1] \"data.frame\""],
  ["p","Put the comma in with nothing before it and you ask for a whole column — and here the container quietly disappears. A one-column result from a data frame is simplified to a bare vector by default, which is the behaviour called dropping."],
  ["code","crates[, 1]\nclass(crates[, 1])"],
  ["code","[1] \"C1\" \"C2\" \"C3\" \"C4\" \"C5\"\n[1] \"character\""],
  ["p","Both halves at once is the usual case, and the row half is normally a condition."],
  ["code","crates[2:3, c(\"id\", \"mass_kg\")]\ncrates[crates$mass_kg > 15, ]"],
  ["code","  id mass_kg\n2 C2   42.00\n3 C3    7.25\n  id mass_kg hold\n1 C1   18.50 fore\n2 C2   42.00  aft\n4 C4   31.75  mid"],
  ["p","When you want the data frame kept even though only one column survives, say so. drop = FALSE is the third argument of the bracket, and it turns dropping off."],
  ["code","crates[, \"mass_kg\", drop = FALSE]"],
  ["code","  mass_kg\n1   18.50\n2   42.00\n3    7.25\n4   31.75\n5   12.00"],
  ["p","str() is the fastest way to see what you are actually holding: the class, the size, and one abbreviated line per column with its type. It is worth running on anything you did not build yourself."],
  ["code","str(crates)"],
  ["code","'data.frame':\t5 obs. of  3 variables:\n $ id     : chr  \"C1\" \"C2\" \"C3\" \"C4\" ...\n $ mass_kg: num  18.5 42 7.25 31.75 12\n $ hold   : chr  \"fore\" \"aft\" \"fore\" \"mid\" ..."],
  ["note","Every dplyr verb you already know is one of these subsets with a name. Rows by condition is filter(), rows by position is slice(), columns by name is select(), a single column pulled out as a vector is pull(), and reordering rows is arrange() where base R uses order() inside the row index. The dplyr version never drops to a vector by accident, which is most of why it exists."]
]},
{ t: "Selecting one element with $ and [[",
  body: [
  ["p","The double bracket reaches inside the container and returns what was stored at that position — for a data frame, the column itself. The dollar sign is shorthand for the same thing with a literal name, and it is the form you will read most often. All three of these give the same vector."],
  ["code","crates$mass_kg\ncrates[[\"mass_kg\"]]\ncrates[[2]]\nidentical(crates$mass_kg, crates[[\"mass_kg\"]])"],
  ["code","[1] 18.50 42.00  7.25 31.75 12.00\n[1] 18.50 42.00  7.25 31.75 12.00\n[1] 18.50 42.00  7.25 31.75 12.00\n[1] TRUE"],
  ["p","The convenience of $ comes with a trap. On a data frame it matches partially: an abbreviation that identifies exactly one column is accepted silently, as though you had spelled the column out. A name that matches nothing returns NULL, also silently. The double bracket does neither favour nor guesswork — it wants the whole name."],
  ["code","crates$mass\ncrates[[\"mass\"]]\ncrates$hatch"],
  ["code","[1] 18.50 42.00  7.25 31.75 12.00\nNULL\nNULL"],
  ["p","A tibble is a data frame with the guessing switched off. Partial matching warns and returns NULL instead of quietly working, so a typo surfaces at the line that made it."],
  ["code","tcrates <- as_tibble(crates)\n\ntcrates$mass\ntcrates[[\"mass_kg\"]]"],
  ["code","Warning: Unknown or uninitialised column: `mass`.\nNULL\n[1] 18.50 42.00  7.25 31.75 12.00"],
  ["p","The other tibble difference is dropping. A single bracket with a column index gives a bare vector from a data frame and a one-column tibble from a tibble, so a tibble stays a rectangle no matter how many columns are left."],
  ["code","crates[, \"mass_kg\"]\ntcrates[, \"mass_kg\"]"],
  ["code","[1] 18.50 42.00  7.25 31.75 12.00\n# A tibble: 5 × 1\n  mass_kg\n    <dbl>\n1   18.5 \n2   42   \n3    7.25\n4   31.8 \n5   12"],
  ["note","The silent partial match is the one to watch, because it works. Write crates$mass when you meant a column called mass that you never created, and R hands you mass_kg without a word. The bug is not that the code fails; it is that the code succeeds on the wrong column. Use [[ with the full name in anything you intend to keep, and prefer tibbles, which refuse the guess."]
]},
{ t: "Lists, str(), and NULL",
  body: [
  ["p","A list is the container that makes the bracket distinction impossible to ignore, because its elements can be anything — a string here, a vector there, another list below that. This one describes a single voyage."],
  ["code","voyage <- list(\n  ship = \"Alder\",\n  crew = 9L,\n  ports = c(\"Vigo\", \"Brest\", \"Cork\"),\n  cargo = list(tonnes = 240, insured = TRUE)\n)\n\nstr(voyage)"],
  ["code","List of 4\n $ ship : chr \"Alder\"\n $ crew : int 9\n $ ports: chr [1:3] \"Vigo\" \"Brest\" \"Cork\"\n $ cargo:List of 2\n  ..$ tonnes : num 240\n  ..$ insured: logi TRUE"],
  ["p","Read that as a map of the structure. Indentation and the leading dots show the nesting, chr and int and num and logi are the types, and [1:3] is a length. On a list you did not build, str() answers the only question that matters first: what shape is this thing."],
  ["p","Now the two operators. A single bracket returns a list — a shorter list, but still a list, printed with its element name above the value."],
  ["code","voyage[1]\nclass(voyage[1])"],
  ["code","$ship\n[1] \"Alder\"\n\n[1] \"list\""],
  ["p","A double bracket returns the element itself, with the list peeled away."],
  ["code","voyage[[1]]\nclass(voyage[[1]])"],
  ["code","[1] \"Alder\"\n[1] \"character\""],
  ["p","That is the whole distinction, and it explains why only the single bracket takes more than one index: several elements cannot be handed back except in a container."],
  ["code","voyage[c(\"ship\", \"ports\")]"],
  ["code","$ship\n[1] \"Alder\"\n\n$ports\n[1] \"Vigo\"  \"Brest\" \"Cork\""],
  ["p","Reaching into nested structure is repeated double brackets, or repeated dollar signs, or a mixture. Once you are down to a vector, the single bracket is back to meaning position."],
  ["code","voyage[[\"cargo\"]][[\"tonnes\"]]\nvoyage$cargo$insured\nvoyage[[\"ports\"]][2]"],
  ["code","[1] 240\n[1] TRUE\n[1] \"Brest\""],
  ["p","An element that was never there comes back as NULL, and assigning NULL is how you delete one. The list gets shorter, which is different from setting a value to NA — that would keep the element and mark it missing."],
  ["code","voyage$captain\nis.null(voyage$captain)\nlength(voyage)\nvoyage$crew <- NULL\nlength(voyage)\nnames(voyage)"],
  ["code","NULL\n[1] TRUE\n[1] 4\n[1] 3\n[1] \"ship\"  \"ports\" \"cargo\""],
  ["p","The same split shows up inside a vector. NULL is the absence of anything and vanishes when combined; NA is a value that happens to be unknown and occupies a slot, so it propagates through arithmetic until you tell a function to ignore it."],
  ["code","length(c(1, NULL, 3))\nlength(c(1, NA, 3))\nsum(c(1, NA, 3))\nsum(c(1, NA, 3), na.rm = TRUE)"],
  ["code","[1] 2\n[1] 3\n[1] NA\n[1] 4"],
  ["note","Getting NULL back from a lookup does not mean the element was empty. It usually means you spelled the name wrong, because a missing name and an element containing NULL look identical from the outside. Check names() before you believe a NULL."]
]},
{ t: "The apply family",
  body: [
  ["p","A list of numbers is not a number, so functions that expect a numeric vector do something unhelpful when handed a list. Three boats, each with its own run of catch weights in kilograms."],
  ["code","hauls <- list(\n  Alder = c(14, 22, 19),\n  Birch = c(31, 27, 40, 25),\n  Cedar = c(9, 12)\n)\n\nmean(hauls)"],
  ["code","Warning in mean.default(hauls) :\n  argument is not numeric or logical: returning NA\n[1] NA"],
  ["p","What you wanted was the function applied once per element. lapply() does exactly that and always returns a list of the same length, one result per input element, names carried over."],
  ["code","lapply(hauls, mean)"],
  ["code","$Alder\n[1] 18.33333\n\n$Birch\n[1] 30.75\n\n$Cedar\n[1] 10.5"],
  ["p","A list of single numbers is rarely what you want to look at, so sapply() runs lapply() and then tries to simplify the result. Here each answer is one number, so three numbers become a named vector."],
  ["code","sapply(hauls, mean)\nclass(sapply(hauls, mean))"],
  ["code","   Alder    Birch    Cedar \n18.33333 30.75000 10.50000 \n[1] \"numeric\""],
  ["p","The word tries is doing a lot of work in that sentence. Change the function so each answer is two numbers and the same call returns a matrix instead."],
  ["code","sapply(hauls, range)\nclass(sapply(hauls, range))"],
  ["code","     Alder Birch Cedar\n[1,]    14    25     9\n[2,]    22    40    12\n[1] \"matrix\" \"array\""],
  ["p","Change it again so the answers have different lengths and simplification gives up, handing back the list lapply() would have given you."],
  ["code","sapply(hauls, function(v) v[v > 20])\nclass(sapply(hauls, function(v) v[v > 20]))"],
  ["code","$Alder\n[1] 22\n\n$Birch\n[1] 31 27 40 25\n\n$Cedar\nnumeric(0)\n\n[1] \"list\""],
  ["p","And an empty input returns an empty list whatever the function was, because there was nothing to work out a type from."],
  ["code","sapply(list(), mean)\nclass(sapply(list(), mean))"],
  ["code","list()\n[1] \"list\""],
  ["p","So sapply() has returned a numeric vector, a matrix, and a list from the same three-line pattern. That is fine at the console, where you can see which one you got, and dangerous inside a function, where the next line assumes a vector and the code breaks on data you have not seen yet. vapply() takes a third argument that states the shape of each result in advance."],
  ["code","vapply(hauls, mean, numeric(1))"],
  ["code","   Alder    Birch    Cedar \n18.33333 30.75000 10.50000"],
  ["p","numeric(1) means one double per element. When that promise is broken, the call stops rather than silently changing shape — the same range() that quietly became a matrix under sapply() is now an error you can read."],
  ["code","vapply(hauls, range, numeric(1))"],
  ["code","Error: values must be length 1,\n but FUN(X[[1]]) result is length 2"],
  ["note","purrr's map() is lapply() with the arguments in tidyverse order, and map_dbl(), map_int(), map_chr() and map_lgl() are vapply() with the promise baked into the function name. purrr is not attached in this chapter, so no purrr code is shown here. The habit transfers either way: at the console reach for whichever is shortest, and inside a function name the return type, with vapply() or with a suffixed map_."]
]},
{ t: "for loops",
  body: [
  ["p","A for loop walks a variable over the elements of a vector or list and runs a block for each one. Nothing is returned; the loop exists for what it does on the way through. Note that a value computed inside a loop is not printed unless you print it, which is the first thing that surprises people arriving from the console."],
  ["code","for (hold in unique(crates$hold)) {\n  print(hold)\n}"],
  ["code","[1] \"fore\"\n[1] \"aft\"\n[1] \"mid\""],
  ["p","When the loop is building a result, make the container first at its final size and fill positions in. Growing a vector one element at a time works, but R copies the whole thing on every step, so it gets slower as it goes."],
  ["code","totals <- numeric(length(hauls))\nnames(totals) <- names(hauls)\n\nfor (i in seq_along(hauls)) {\n  totals[i] <- sum(hauls[[i]])\n}\n\ntotals"],
  ["code","Alder Birch Cedar \n   55   123    21"],
  ["p","seq_along() rather than 1:length() is not a style preference. The two agree on every non-empty input and disagree on the one input you did not test."],
  ["code","empty <- numeric(0)\n\nseq_along(empty)\n1:length(empty)"],
  ["code","integer(0)\n[1] 1 0"],
  ["p","The colon operator counts down when its second number is smaller than its first, so 1:0 is the two-element vector 1 0. A loop written that way over an empty vector does not skip — it runs twice, on positions 1 and 0, which give NA and nothing at all."],
  ["code","for (i in 1:length(empty)) {\n  print(empty[i])\n}"],
  ["code","[1] NA\nnumeric(0)"],
  ["p","seq_along() on an empty vector returns an empty integer vector, so the loop body never runs and there is no output to show."],
  ["code","for (i in seq_along(empty)) {\n  print(empty[i])\n}"],
  ["note","This is the bug that survives every test you write by hand, because a table you typed out yourself is never empty. It appears the first time a filter matches nothing upstream, and it appears as an NA in a result rather than as an error. Write seq_along() every time and the case never arises."]
]},
{ t: "Plots, and the errors you will hit",
  body: [
  ["p","Base R has its own plotting functions, entirely separate from ggplot2. plot() on a numeric vector gives a scatterplot against position, hist() bins a numeric vector, and boxplot() takes a formula of the form value against group. They draw immediately rather than building an object, which makes them quick for a look at your own data and awkward to build up in layers."],
  ["code","plot(crates$mass_kg)\nhist(tide_cm)\nboxplot(mass_kg ~ hold, data = crates)"],
  ["note","Those three lines are shown with no output because they produce none here. A base plot writes to a graphics device, and in this app there is no device to write to, so nothing comes back — not an error, not a warning, nothing. No output could honestly be shown, so none is. Run the same three lines in R on a desktop to see the pictures."],
  ["p","Three subsetting errors account for most of the time you will lose. The first is a comma in a bracket applied to something that has no rows and columns. The message names dimensions, which is a useful clue once you know that a plain vector has none."],
  ["code","tide_cm[1, 2]"],
  ["code","Error: incorrect number of dimensions"],
  ["p","The second is worse, because it is not an error. A data frame bracket accepts a third argument, and that argument is drop. Write a third index by mistake and R reads it as an instruction to simplify, so you get a number back where you expected a row."],
  ["code","crates[1, 2, 3]"],
  ["code","[1] 18.5"],
  ["p","The third is asking a double bracket for more than one element. It cannot comply, because it returns the element rather than a container, and it says so."],
  ["code","tide_cm[[1:3]]"],
  ["code","Error: attempt to select more than one element in vectorIndex"],
  ["p","Reading past the end of a data frame follows the vector rule from section 2 rather than raising anything. You get a row of NAs with a missing row name, and a bare NA from a column."],
  ["code","crates[6, ]\ncrates$mass_kg[6]"],
  ["code","     id mass_kg hold\nNA <NA>      NA <NA>\n[1] NA"],
  ["note","Two of those four are silent, and both give you a value of the right type to keep working with. That is the theme of the chapter: base R subsetting is permissive, and permissiveness turns typing mistakes into wrong answers rather than into stops. Check what you got with str() or class() whenever a subset was not trivial."]
]},
{ t: "Summary",
  body: [
  ["p","A single bracket keeps the container: on a vector it returns a vector, on a list a list, on a data frame a data frame. It accepts positions, negative positions, a logical vector, or names, and on a data frame it takes rows before the comma and columns after it. A double bracket, and its shorthand $, reaches inside and returns the element itself — one element only, which is why it takes a single index. crates[1] is a one-column data frame, crates[1, ] is a one-row data frame, and crates[, 1] is a bare vector, because a one-column result is dropped unless you pass drop = FALSE."],
  ["p","$ on a data frame matches names partially and returns NULL for a name it cannot find, both without complaint; a tibble warns instead, and a tibble never drops. NULL is absence and disappears when combined, so assigning it deletes a list element, while NA is an unknown value that keeps its slot and spreads through arithmetic until na.rm = TRUE stops it. str() prints the shape of anything, nested lists included, and it is the first thing to run on an object you did not build."],
  ["p","lapply() applies a function once per element and always returns a list. sapply() simplifies afterwards and may hand back a vector, a matrix, or a list depending on the data, which makes it fine at the console and unsafe inside a function; vapply() states the result shape up front and errors when the promise is broken. purrr's map() and map_dbl() are the same two ideas under tidyverse names. for loops walk a vector, print nothing on their own, and should be driven by seq_along() rather than 1:length(), which counts backwards to zero on an empty input and runs the body twice."],
  ["p","Base plotting draws straight to a device, so plot(), hist() and boxplot() return no text here and were shown output-free rather than described. The next chapter is Quarto: writing prose, code, and results into one document that regenerates itself, so the numbers in your report cannot drift away from the script that produced them."]
]}
],
questions: [
{ q:"For the list voyage, what do voyage[1] and voyage[[1]] return, and what does class() say about each?",
  a:"voyage[1] returns a list of length 1 — class \"list\" — printed with the element name above the value. voyage[[1]] returns the element itself, the character string \"Alder\", class \"character\". The single bracket keeps the container, the double bracket reaches inside." },
{ q:"What do negative indexes do, and what happens if you put a negative and a positive number in the same index?",
  a:"Negative positions are dropped and everything else is kept, so tide_cm[-1] returns six of the seven readings. Mixing signs is an error: Error: only 0's may be mixed with negative subscripts. Zero is the one value allowed alongside negatives, because it selects nothing." },
{ q:"You index a seven-element vector with c(TRUE, FALSE). How many elements come back, and why?",
  a:"Four. A logical index shorter than the vector is recycled to its length, so c(TRUE, FALSE) becomes TRUE FALSE TRUE FALSE TRUE FALSE TRUE and takes positions 1, 3, 5 and 7. R does not treat the length mismatch as a mistake, so a condition computed on the wrong vector silently returns something plausible." },
{ q:"Distinguish crates[1], crates[1, ] and crates[, 1].",
  a:"crates[1] has no comma, so the index means columns: a one-column data frame. crates[1, ] indexes rows: a one-row data frame, still class \"data.frame\". crates[, 1] indexes columns and drops, because a one-column result from a data frame is simplified to a bare vector — here a character vector. Pass drop = FALSE to keep the data frame." },
{ q:"crates has a column called mass_kg and no column called mass. What do crates$mass and crates[[\"mass\"]] return?",
  a:"crates$mass returns the mass_kg column, because $ on a data frame matches names partially and silently when exactly one column matches. crates[[\"mass\"]] returns NULL, because the double bracket wants the whole name. The dangerous one is $: it succeeds on a column you did not ask for." },
{ q:"Which two things does a tibble do differently from a data frame when you subset it?",
  a:"It refuses to guess a partial name — tcrates$mass emits Warning: Unknown or uninitialised column: `mass`. and returns NULL — and it never drops, so tcrates[, \"mass_kg\"] is a one-column tibble where crates[, \"mass_kg\"] is a bare vector." },
{ q:"What is the difference between NULL and NA, and how do you delete an element from a list?",
  a:"NULL is the absence of anything: it disappears when combined, so length(c(1, NULL, 3)) is 2 and length(NULL) is 0. NA is an unknown value that occupies a slot, so length(c(1, NA, 3)) is 3 and sum() of it is NA until na.rm = TRUE. Assigning NULL to a list element deletes it, and the list gets shorter." },
{ q:"Why can sapply() be unsafe inside a function, and what does vapply() add?",
  a:"sapply() simplifies whatever lapply() produced, so its return type depends on the data: one number per element gives a named vector, two give a matrix, ragged results give a list, and an empty input gives an empty list. vapply() takes a template such as numeric(1) that asserts the shape of each result, and stops with an error when the promise is broken instead of changing shape." },
{ q:"Why should a for loop be driven by seq_along(x) rather than 1:length(x)?",
  a:"They agree on every non-empty vector and disagree on an empty one. seq_along(numeric(0)) is integer(0), so the loop body never runs; 1:length(numeric(0)) is 1:0, which counts down to the two-element vector 1 0, so the body runs twice on positions 1 and 0 and produces NA and nothing. The result is a wrong answer rather than an error." },
{ q:"Why is no output shown for plot(), hist() and boxplot() here, and what does crates[1, 2, 3] return?",
  a:"Base plotting writes to a graphics device, and this app has none, so those calls produce no text at all — no error and no warning, which is why they are shown output-free rather than described. crates[1, 2, 3] returns 18.5: the third argument of a data frame bracket is drop, so an extra index is read as an instruction to simplify rather than rejected." }
],
exercises: [
{ c:"indexing", t:"Three ways to pick a depth", book:"r27",
  b:"Build a named numeric vector called depth_m holding quay 4.2, jetty 2.8, channel 7.5, slip 3.1, basin 5.9, in that order. Then print three things on three separate lines: the element named channel, the vector with the second element removed, and the elements greater than 4.",
  o:"channel \n    7.5 \n   quay channel    slip   basin \n    4.2     7.5     3.1     5.9 \n   quay channel   basin \n    4.2     7.5     5.9",
  h:["Names go into the vector when you build it, and all three answers are one bracket expression each.",
     "A name in quotes is one kind of index, a negative number is another, and a comparison produces the logical vector that is the third. Names survive subsetting, so every answer stays labelled.",
     "c() takes name = value pairs. Then one line indexing by a quoted name, one line indexing by a negative position, and one line indexing by a comparison of the vector against 4."]},
{ c:"indexing", t:"Rows by condition, columns by name", book:"r27",
  b:"Build a data frame called moorings with berth holding \"A1\", \"A2\", \"B1\", \"B2\", \"C1\"; fee holding 46, 22, 38, 61, 29; and depth_m holding 3.4, 2.1, 5.0, 2.9, 4.2. Keep only the rows whose depth_m is at least 3 and only the berth and fee columns, then print those rows ordered by fee from smallest to largest.",
  o:"  berth fee\n5    C1  29\n3    B1  38\n1    A1  46",
  h:["Rows and columns go in one pair of brackets, separated by a comma: rows before it, columns after it.",
     "The row half is a logical vector from a comparison on a column. The column half is a character vector of the two names you want. Sorting is a second subset, because order() returns row positions rather than sorted data.",
     "Subset once into a variable — the depth condition before the comma, c(\"berth\", \"fee\") after it — then subset that variable again with order() of its fee column before the comma and nothing after."]},
{ c:"apply family", t:"One number per boat, guaranteed", book:"r27",
  b:"Build a list called catches with Wren holding 12, 18, 9; Heron holding 41, 37; Snipe holding 8, 8, 8, 8; and Egret holding 25, 30, 22. Use vapply, asserting one double per element, to total each boat's catch, then print the totals sorted from smallest to largest.",
  o:"Snipe  Wren Egret Heron \n   32    39    77    78",
  h:["vapply() takes the list, the function, and a template value that states the shape of each result.",
     "The template for a single number is numeric(1). vapply() carries the names across, so the sorted result stays labelled with the boat names.",
     "Build the list, pass it to vapply() with the summing function and the length-1 numeric template, store that, then print it wrapped in sort()."]},
{ c:"iteration", t:"A loop that survives an empty element", book:"r27",
  b:"Build a list called readings with dawn holding 4, 9, 2; noon holding 11, 7; dusk holding 6, 6, 6, 3; and night holding numeric(0). Make a numeric vector called spans that is as long as readings and carries the same names, then use a for loop driven by seq_along to put the sum of each element into the matching position. Print spans.",
  o:" dawn  noon  dusk night \n   15    18    21     0",
  h:["Make the result container at its final size before the loop, then fill positions in rather than growing it.",
     "numeric(n) makes a vector of n zeros, and names() on the left of an assignment labels it. Inside the loop, i is a position, so the element you want is reached with a double bracket.",
     "Build spans with numeric() of the list's length, set its names from the list's names, then loop i over seq_along(readings) assigning sum() of the i-th element into spans[i], and print spans on its own line."]}
]
};
