/* Practice Log book — R Chapter 28: Quarto.
   Original lesson text following the chapter-by-chapter curriculum of
   "R for Data Science" (2nd ed.) by Hadley Wickham, Mine Cetinkaya-Rundel,
   and Garrett Grolemund. Read the original chapter free at the src link below.
   Every shown output was captured by executing the code in WebR, not written from memory. */
window.BOOK_R = window.BOOK_R || { chapters: {} };
window.BOOK_R.chapters.r28 = {
n: 28,
title: "Quarto",
src: "https://r4ds.hadley.nz/quarto.html",
blurb: "The .qmd source document — markdown prose, code chunks, chunk options, inline code — and how to read one back apart with R.",
pkgs: [],
sections: [
{ t: "What Quarto is",
  body: [
  ["p","Everything so far has ended at the console. You typed something, R answered, and the answer lived in a scrollback buffer that nobody else will ever see. Quarto is the step after that: one source document that holds your prose and your code together, and one command that turns it into a finished html page, a pdf, or a Word file with the results already computed and dropped into place."],
  ["p","The source file has the extension .qmd, and it is plain text. Rendering it runs three programs in sequence. Quarto reads the file and hands the code chunks to knitr, which runs each one in a fresh R session and writes the results back into the document as plain markdown. Pandoc then converts that markdown into whatever output format you asked for. Nothing about the chain is magic, and every stage of it operates on text."],
  ["note","Nothing on this page renders inside this app. Quarto is a separate command line program that you install on a desktop next to R, and rendering shells out to it; a browser tab has no terminal and no Quarto, so no .qmd here becomes an html file. Every block below that shows a .qmd document, a YAML header, or a quarto command is therefore printed with nothing under it — inventing a rendered result would be a lie. What does transfer is everything a .qmd is made of. It is a plain text file, and R is good at plain text, so the runnable parts of this chapter write a .qmd from R, read it back, split it into its three ingredients, count its chunks, pull out its options, and compute the exact numbers that inline code would drop into the prose. That is real practice for the format, and it all runs here."],
  ["p","On a desktop, the whole workflow is three commands. render produces the output file once. The --to flag overrides the format named in the document. preview renders and then watches the file, rebuilding and refreshing a browser every time you save, which is how you actually work on a report."],
  ["code","$ quarto render report.qmd\n$ quarto render report.qmd --to pdf\n$ quarto preview report.qmd"],
  ["p","RStudio and Positron put a Render button over the same commands, and both offer a visual editor that shows the document formatted while you type. The visual editor is a convenience over the source file, not a different file — it saves the same plain text either way, which is why everything in this chapter works on the text directly."]
]},
{ t: "What is inside a .qmd",
  body: [
  ["p","A .qmd holds exactly three kinds of content, and each one is marked. At the very top sits the YAML header, fenced above and below by a line of three hyphens, holding the document's settings as key and value pairs. Everything after it is markdown prose. Inside that prose sit code chunks, each opened by three backticks followed by the engine name in braces and closed by three backticks alone. Here is a small complete document."],
  ["code","---\ntitle: \"Allotment yields\"\nauthor: \"Practice Log\"\nformat: html\nexecute:\n  echo: false\n---\n\n## Beds\n\n```{r}\n#| label: setup\n#| include: false\nbeds <- c(3.5, 4.2, 2.8, 5.1)\n```\n\nThere are `r length(beds)` beds, averaging `r round(mean(beds), 2)` kg.\n\n## Yields\n\n```{r}\n#| label: fig-yield\n#| fig-cap: \"Yield per bed\"\n#| fig-width: 5\nbarplot(beds)\n```"],
  ["p","Read it top to bottom and the three parts are obvious: five lines of settings between the hyphen fences, two headings and one sentence of prose, and two chunks of R. That is the whole format. Since it is text, R can write it, and writeLines() takes a character vector of lines and puts one per line in a file."],
  ["code","qmd <- c(\n  \"---\",\n  'title: \"Allotment yields\"',\n  'author: \"Practice Log\"',\n  \"format: html\",\n  \"execute:\",\n  \"  echo: false\",\n  \"---\",\n  \"\",\n  \"## Beds\",\n  \"\",\n  \"```{r}\",\n  \"#| label: setup\",\n  \"#| include: false\",\n  \"beds <- c(3.5, 4.2, 2.8, 5.1)\",\n  \"```\",\n  \"\",\n  \"There are `r length(beds)` beds, averaging `r round(mean(beds), 2)` kg.\",\n  \"\",\n  \"## Yields\",\n  \"\",\n  \"```{r}\",\n  \"#| label: fig-yield\",\n  '#| fig-cap: \"Yield per bed\"',\n  \"#| fig-width: 5\",\n  \"barplot(beds)\",\n  \"```\"\n)\n\nwriteLines(qmd, \"report.qmd\")\n\nlength(qmd)\nfile.exists(\"report.qmd\")"],
  ["code","[1] 26\n[1] TRUE"],
  ["p","Note the two lines written with single quotes. Those are the lines whose contents include a double quote, and single quotes let them through without escaping. readLines() is the reverse trip, and identical() proves the round trip lost nothing."],
  ["code","lines <- readLines(\"report.qmd\")\n\nidentical(lines, qmd)\nwriteLines(lines[1:7])"],
  ["code","[1] TRUE\n---\ntitle: \"Allotment yields\"\nauthor: \"Practice Log\"\nformat: html\nexecute:\n  echo: false\n---"],
  ["note","The file lands in the browser's in-memory filesystem, not in a folder on your device, and it is gone when the page reloads. On a desktop the same two calls write and read a real report.qmd in your working directory. The lesson is the same either way: the document you will spend an afternoon editing is a vector of strings, and nothing stops you inspecting it as one."]
]},
{ t: "Markdown, the prose half",
  body: [
  ["p","Between the chunks, a .qmd is markdown: plain text with a handful of punctuation conventions that Pandoc turns into formatting. A line beginning with one to six hash marks and a space is a heading, and the number of hashes is the level. Text wrapped in single asterisks is italic and in double asterisks is bold. A line starting with a hyphen and a space is a bullet, a line starting with a number and a period is a numbered item, and square brackets followed by round brackets make a link. Backticks around a word mark it as code, and a leading angle bracket makes a block quote."],
  ["code","## Beds\n\nThe **north** bed is the oldest, and the *east* bed is new this year.\nSoil tests are in the [notes](notes.html).\n\n- north\n- south\n- east\n\n1. dig\n2. sow\n3. water\n\n> Yields are measured after drying.\n\nUse `mean()` for the average."],
  ["p","Two rules catch everyone. A blank line is what separates one block from the next, so a heading with text jammed against it on the following line is one paragraph rather than a heading and a paragraph. And two spaces at the end of a line force a line break inside a paragraph, which is invisible in your editor and therefore a common source of stray breaks."],
  ["p","Headings are worth extracting from R, because a document's outline is its headings and nothing else. The pattern below asks for one or more hashes followed by a space, which is why the chunk option lines that also begin with a hash are left alone — a hash followed by a vertical bar is not a heading."],
  ["code","heads <- grep(\"^#+ \", lines, value = TRUE)\n\nwriteLines(heads)\nnchar(sub(\"^(#+) .*$\", \"\\\\1\", heads))"],
  ["code","## Beds\n## Yields\n[1] 2 2"],
  ["p","Pulling out the prose itself takes one more idea. Fence lines alternate: the first opens a chunk, the second closes it, the third opens the next. So a running total of fence lines is odd inside a chunk and even outside one, and everything that is neither a fence nor inside a chunk is prose."],
  ["code","marks <- which(lines == \"---\")\nbody_lines <- lines[(marks[2] + 1):length(lines)]\nfence <- startsWith(body_lines, \"```\")\ninside <- (cumsum(fence) %% 2) == 1\nprose <- body_lines[(inside == FALSE) & (fence == FALSE) & (nchar(body_lines) > 0)]\n\nwriteLines(prose)"],
  ["code","## Beds\nThere are `r length(beds)` beds, averaging `r round(mean(beds), 2)` kg.\n## Yields"],
  ["note","That trick only works while the fences are balanced. One chunk left unclosed flips the parity for the rest of the file, and every heading and paragraph after it is silently classed as code. Quarto reacts the same way: an unclosed fence does not report a missing backtick, it reports something strange much further down. Section 4 has the check to run first."]
]},
{ t: "Code chunks",
  body: [
  ["p","A code chunk opens with three backticks and the engine in braces, and closes with three backticks on a line of their own. The engine name says which language runs the block, so an R chunk opens with a brace, the letter r, and a closing brace. The backticks have to start at the beginning of the line, with no indentation in front of them."],
  ["code","```{r}\n#| label: setup\nbeds <- c(3.5, 4.2, 2.8, 5.1)\n```"],
  ["p","Since the fences are just lines with a known prefix, finding every chunk in a document is a search. startsWith() takes a fixed string rather than a pattern, which suits the opening fence, and a closing fence is a line that equals three backticks exactly."],
  ["code","opens <- which(startsWith(lines, \"```{r\"))\ncloses <- which(lines == \"```\")\n\nopens\ncloses\nlength(opens)"],
  ["code","[1] 11 21\n[1] 15 26\n[1] 2"],
  ["p","The first line inside a chunk is usually its label, written as a chunk option. A label is a name for the chunk: it appears in the progress messages during a render, it names the image file a plot writes, and it is what a cross-reference points at. Labels must be unique within a document, and must avoid spaces and underscores — hyphens are the convention."],
  ["code","label_lines <- grep(\"^#\\\\| label: \", lines, value = TRUE)\nlabels <- sub(\"^#\\\\| label: \", \"\", label_lines)\n\nsort(labels)"],
  ["code","[1] \"fig-yield\" \"setup\""],
  ["p","Before you render anything, check the fences balance. The function below counts openings and closings and compares them; the second call feeds it the document with its last two lines removed, which is what a half-finished paste looks like."],
  ["code","balanced <- function(x) {\n  opens <- sum(startsWith(x, \"```{r\"))\n  closes <- sum(x == \"```\")\n  identical(opens, closes)\n}\n\nbalanced(lines)\nbalanced(lines[1:24])"],
  ["code","[1] TRUE\n[1] FALSE"],
  ["note","Two chunks sharing a label stops the render with a duplicate label error, and the usual way to get there is copying a chunk to make a variant and editing everything in it except the label line. The other reliable failure is a chunk that runs perfectly in your console and fails on render, because the console has objects in it that the document never creates. Rendering always starts from an empty session."]
]},
{ t: "Chunk options",
  body: [
  ["p","Options control what a chunk does and what of it appears in the output. They are written inside the chunk, one per line at the top, each line starting with a hash and a vertical bar and then a YAML key and value. That prefix is a comment in R, so the lines are invisible to the code itself."],
  ["code","```{r}\n#| label: fig-yield\n#| echo: false\n#| warning: false\n#| fig-cap: \"Yield per bed\"\nbarplot(beds)\n```"],
  ["p","The options you will use constantly are a short list. eval decides whether the code runs at all. echo decides whether the code is shown. output decides whether the results are shown. warning and message decide whether those go into the document or stay in the render log. include set to false runs the chunk and shows nothing at all, which is what you want for a setup chunk. Every value is YAML, so it is true or false in lower case, not R's TRUE and FALSE."],
  ["p","Collecting the option lines from a document is the same search as before, with the marker stripped off the front. The vertical bar is a special character in a pattern, so it needs a backslash in front of it, and a backslash inside an R string needs a backslash of its own."],
  ["code","option_lines <- grep(\"^#\\\\|\", lines, value = TRUE)\noptions_seen <- sub(\"^#\\\\| *\", \"\", option_lines)\n\nwriteLines(sort(options_seen))"],
  ["code","fig-cap: \"Yield per bed\"\nfig-width: 5\ninclude: false\nlabel: fig-yield\nlabel: setup"],
  ["p","Splitting each of those on its first colon gives the name and the value separately, which is the shape you want if you are auditing a folder of documents for a particular setting."],
  ["code","keys <- sub(\":.*$\", \"\", options_seen)\nvals <- sub(\"^[^:]+: *\", \"\", options_seen)\ntab <- data.frame(key = keys, value = vals)\n\ntab[order(tab$key, tab$value), ]"],
  ["code","        key           value\n4   fig-cap \"Yield per bed\"\n5 fig-width               5\n2   include           false\n3     label       fig-yield\n1     label           setup"],
  ["p","Setting the same option on twenty chunks by hand is how documents drift out of step. The execute key in the YAML header sets a default for every chunk in the file, and a chunk option overrides it for that one chunk. A report meant for readers who do not want to see code usually turns echo off globally and turns it back on in the two chunks worth showing."],
  ["code","execute:\n  echo: false\n  warning: false\n  message: false"],
  ["p","In the document written earlier, the header carries an execute block with one setting under it. Finding it means locating the key and then taking the indented lines that follow, stopping at the first line that is not indented."],
  ["code","start <- which(lines == \"execute:\")\ni <- start + 1\nwhile (i <= length(lines) && startsWith(lines[i], \"  \")) i <- i + 1\n\nwriteLines(lines[(start + 1):(i - 1)])"],
  ["code","  echo: false"],
  ["note","YAML is indentation sensitive and rejects tabs. An option line that looks correctly lined up but was indented with a tab produces a parse error pointing at a line number rather than at the invisible character, and editors that convert tabs to spaces on save will hide the problem from you until a colleague opens the file. Set your editor to insert spaces and the whole category disappears."]
]},
{ t: "Inline code",
  body: [
  ["p","Numbers quoted in prose go stale the moment the data changes, and a report that says twelve when the table says fourteen is worse than one that says nothing. Inline code fixes that by putting the expression in the sentence instead of the answer. The syntax is a backtick, the letter r, a space, an R expression, and a closing backtick, written in the middle of ordinary prose."],
  ["code","There are `r length(beds)` beds, averaging `r round(mean(beds), 2)` kg."],
  ["p","At render time each of those is evaluated and replaced by its value, so the sentence is rebuilt from the data every time. The expressions are just text in the file until then, which means R can find them the same way it found everything else. gregexpr() locates every match of a pattern in a string and regmatches() pulls the matched text out."],
  ["code","sentence_line <- lines[17]\ninline <- regmatches(sentence_line, gregexpr(\"`r [^`]+`\", sentence_line))[[1]]\n\nwriteLines(inline)"],
  ["code","`r length(beds)`\n`r round(mean(beds), 2)`"],
  ["p","Evaluating them by hand shows exactly what the rendered sentence would say. This is the honest substitute for a render: the numbers below are the numbers Quarto would splice in, computed here by the same R."],
  ["code","beds <- c(3.5, 4.2, 2.8, 5.1)\n\nlength(beds)\nround(mean(beds), 2)\nwriteLines(paste0(\"There are \", length(beds), \" beds, averaging \",\n                  round(mean(beds), 2), \" kg.\"))"],
  ["code","[1] 4\n[1] 3.9\nThere are 4 beds, averaging 3.9 kg."],
  ["p","Note what round() did and did not do. It cut the value to two decimal places, and then R printed it with one, because trailing zeros are not stored. If the report needs a fixed number of decimals, formatting is a separate job from rounding, and both format() and sprintf() will do it."],
  ["code","format(round(mean(beds), 2), nsmall = 2)\nsprintf(\"%.2f\", mean(beds))"],
  ["code","[1] \"3.90\"\n[1] \"3.90\""],
  ["note","Keep inline expressions short. A whole pipeline squeezed into a sentence is unreadable in the source, and when it fails the error message points at a paragraph rather than at a chunk. Compute the value in a chunk with include set to false, give it a name, and put the name in the sentence."]
]},
{ t: "Figures and tables",
  body: [
  ["p","A chunk that draws a plot produces an image in the output, and chunk options control it. fig-width and fig-height are in inches and set the size the plot is drawn at, fig-cap gives it a caption, and fig-alt gives it alternative text for screen readers. A label beginning with the four characters f, i, g, and a hyphen turns the figure into something you can point at from the prose with an at sign followed by the label, and Quarto numbers it for you."],
  ["code","See @fig-yield for the per-bed totals.\n\n```{r}\n#| label: fig-yield\n#| fig-cap: \"Yield per bed\"\n#| fig-width: 5\n#| fig-height: 3\nbarplot(beds)\n```"],
  ["p","That prefix rule is checkable from R, and worth checking, because a figure with a fig- label and no caption is a cross-reference that will not resolve. Count the fig- labels, count the captions, and compare."],
  ["code","fig_labels <- sort(sub(\"^#\\\\| label: \", \"\", grep(\"^#\\\\| label: fig-\", lines, value = TRUE)))\nfig_caps <- grep(\"^#\\\\| fig-cap: \", lines, value = TRUE)\n\nfig_labels\nlength(fig_caps)\nidentical(length(fig_labels), length(fig_caps))"],
  ["code","[1] \"fig-yield\"\n[1] 1\n[1] TRUE"],
  ["p","Tables work the same way with a different prefix. A label beginning with t, b, l, and a hyphen makes a table you can cross-reference, tbl-cap is its caption, and the usual way to turn a data frame into a formatted table is knitr::kable(), which is part of the same package that runs your chunks."],
  ["code","```{r}\n#| label: tbl-yield\n#| tbl-cap: \"Yield per bed\"\nknitr::kable(yields)\n```"],
  ["p","Under kable there is nothing but string assembly, and doing it by hand once makes the format concrete. A markdown table is a header row, a row of hyphens, and one row per record, all built from pipes and text."],
  ["code","yields <- data.frame(bed = c(\"north\", \"south\", \"east\", \"west\"),\n                     kg = c(3.5, 4.2, 2.8, 5.1))\nyields <- yields[order(yields$bed), ]\nmd <- c(\"| bed | kg |\",\n        \"| --- | --- |\",\n        paste0(\"| \", yields$bed, \" | \", yields$kg, \" |\"))\n\nwriteLines(md)"],
  ["code","| bed | kg |\n| --- | --- |\n| east | 2.8 |\n| north | 3.5 |\n| south | 4.2 |\n| west | 5.1 |"],
  ["note","The prefix is not a naming style, it is the mechanism. Label a plot yield instead of fig-yield and the cross-reference in your prose renders as the literal text you typed rather than as Figure 1, with no error anywhere. When a reference comes out looking like an at sign followed by a word, check the label prefix before you check anything else."]
]},
{ t: "Caching and the YAML header",
  body: [
  ["p","Some chunks are slow, and rendering runs every chunk every time. Setting cache to true on a chunk tells knitr to store the result on disk and reuse it on the next render, skipping the work. Set it in the header's execute block to cache everything, and it is usually better to set it on the two or three chunks that actually hurt."],
  ["code","```{r}\n#| label: slow-step\n#| cache: true\ntotals <- expensive_summary(readings)\n```"],
  ["p","The rule for when a cached result is thrown away is the important part: the cache is invalidated when the chunk's code changes, and only then. A tiny model of that is enough to see the consequence. Store a fingerprint of the code under the chunk's label, and reuse the stored result whenever the fingerprint still matches."],
  ["code","store <- list()\n\nfingerprint <- function(code) {\n  chars <- utf8ToInt(code)\n  sum(chars * seq_along(chars))\n}\n\nrun_chunk <- function(label, code) {\n  fp <- fingerprint(code)\n  if (label %in% names(store) && identical(store[[label]], fp)) {\n    \"cached\"\n  } else {\n    store[[label]] <<- fp\n    \"recomputed\"\n  }\n}\n\nrun_chunk(\"setup\", \"beds <- c(3.5, 4.2, 2.8, 5.1)\")\nrun_chunk(\"setup\", \"beds <- c(3.5, 4.2, 2.8, 5.1)\")\nrun_chunk(\"setup\", \"beds <- c(3.5, 4.2, 2.8, 6.0)\")"],
  ["code","[1] \"recomputed\"\n[1] \"cached\"\n[1] \"recomputed\""],
  ["p","The multiplication by position is doing real work there. A plain sum of character codes is a tempting fingerprint and a broken one, because rearranging characters leaves the total alone — the two numbers below differ, and their unweighted sums do not. knitr uses a proper hash function rather than arithmetic for exactly this reason, and the first version of the model on this page did use a plain sum, which reported the third call as a cache hit."],
  ["code","sum(utf8ToInt(\"5.1\"))\nsum(utf8ToInt(\"6.0\"))"],
  ["code","[1] 148\n[1] 148"],
  ["p","Now read the consequence off the model. Change the data file the chunk reads and the code is byte for byte the same, so the fingerprint matches and the stale result is served again. knitr offers dependson to name chunks a cached chunk depends on, and cache-extra to add anything else that should invalidate it, such as a file's modification time. When a cached document behaves impossibly, delete the cache folder that sits beside it and render again."],
  ["p","The YAML header is where a document's settings live. It sits at the very top, fenced by three hyphens above and below, and holds key and value pairs; a value can itself be a block of nested keys, indented under its parent. A fuller header than the one used so far looks like this."],
  ["code","---\ntitle: \"Allotment yields\"\nauthor: \"Practice Log\"\ndate: 2026-07-23\nformat:\n  html:\n    toc: true\n    number-sections: true\nexecute:\n  echo: false\n  warning: false\n---"],
  ["p","Splitting a document into header and body is a matter of finding the two fence lines. The first three-hyphen line opens the header and the second closes it, so the header is what lies between them and the body is everything after the second."],
  ["code","marks <- which(lines == \"---\")\nheader <- lines[(marks[1] + 1):(marks[2] - 1)]\n\nlength(header)\nlength(lines) - marks[2]\nwriteLines(header)"],
  ["code","[1] 5\n[1] 19\ntitle: \"Allotment yields\"\nauthor: \"Practice Log\"\nformat: html\nexecute:\n  echo: false"],
  ["p","When a render fails, the fastest diagnosis is to remember that Quarto renders in a fresh R session with your working directory set to the document's folder. So a document that works interactively and fails on render is almost always relying on an object you created in the console, a package you attached by hand, or a file path relative to somewhere else. Restart R, run the document's chunks in order from the top, and the failure reproduces. quarto check confirms the installation itself is sound."],
  ["code","$ quarto check\n$ quarto render report.qmd"]
]},
{ t: "Summary",
  body: [
  ["p","A .qmd is a plain text file with three kinds of content: a YAML header fenced by three-hyphen lines, markdown prose, and code chunks opened by three backticks and an engine name in braces. Rendering hands the chunks to knitr, which runs them in a fresh R session and writes the results into markdown, and then to Pandoc, which produces the output format. quarto render does it once, quarto preview does it on every save."],
  ["p","Chunk options are hash-and-bar lines at the top of a chunk: label names the chunk, echo shows or hides the code, output shows or hides the results, warning and message route those to the document or the log, include set to false runs the chunk silently, and eval decides whether it runs at all. The execute block in the header sets defaults for all of them. Inline code, written as a backtick, r, an expression, and a backtick, is evaluated at render time so quoted numbers cannot go stale. Figures take fig-width, fig-height, fig-cap, and a fig- label prefix for cross-references; tables take tbl-cap and a tbl- prefix. Caching skips slow chunks and invalidates only when their code changes."],
  ["p","None of that rendered here, and this chapter never pretended otherwise. What ran was the text half: writing a .qmd from R, reading it back, splitting header from body, counting fences, extracting labels and options, pulling the inline expressions out of a sentence, and computing the numbers a render would have spliced in. Those are the checks worth having whether or not Quarto is installed."],
  ["p","Answer the practice questions from memory before revealing the answers, then clear the graded exercises below. The next chapter is Quarto formats: what changes when the same document is asked for a pdf, a Word file, a slide deck, a dashboard, or a whole website, and how one document can produce a report per parameter."]
]}
],
questions: [
{ q:"Name the three kinds of content a .qmd file holds, and say what marks each one.",
  a:"A YAML header, fenced above and below by a line of three hyphens and holding key and value settings; markdown prose, which is everything else by default; and code chunks, opened by three backticks and an engine name in braces and closed by three backticks alone." },
{ q:"What does quarto render report.qmd actually do, and why can this app not do it?",
  a:"It hands each code chunk to knitr, which runs it in a fresh R session and writes the results back as markdown, then passes the whole document to Pandoc to produce html, pdf, or Word. Quarto is a separate command line program installed next to R on a desktop; a browser tab has no terminal and no Quarto, so nothing here renders." },
{ q:"In markdown, how do you write a level-two heading, bold text, a bullet list, and a link?",
  a:"Two hash marks and a space in front of the heading text; double asterisks around the bold text; a hyphen and a space at the start of each bullet line; and the link text in square brackets followed immediately by the address in round brackets. Blank lines separate one block from the next." },
{ q:"How does an R code chunk open and close, and what rules apply to its label?",
  a:"It opens with three backticks at the start of a line followed by the letter r in braces, and closes with three backticks alone on a line. The label is a chunk option; it has to be unique within the document and should avoid spaces and underscores, so hyphens are the convention. Duplicate labels stop the render." },
{ q:"Where do chunk options go, how are they written, and how do you set one for every chunk at once?",
  a:"Inside the chunk, one per line at the top, each beginning with a hash and a vertical bar followed by a YAML key and value. That prefix is an R comment, so the code ignores them. The execute block in the YAML header sets a default for the whole document, and a chunk option overrides it for that chunk." },
{ q:"What is the difference between echo: false, output: false, and include: false?",
  a:"echo: false runs the chunk and hides the code while keeping the results. output: false runs it and hides the results while keeping the code. include: false runs it and shows nothing at all, which is what a setup chunk wants. All three still run the code; eval: false is the one that does not." },
{ q:"What is inline code, how is it written, and when is it evaluated?",
  a:"An R expression placed inside a sentence rather than in a chunk, written as a backtick, the letter r, a space, the expression, and a closing backtick. It is evaluated at render time and replaced by its value, so a number quoted in prose is rebuilt from the data on every render instead of going stale." },
{ q:"round(mean(x), 2) gives 3.9 but the report needs two decimal places. What is the fix, and why is round not it?",
  a:"round() changes the value, not the way it prints, and a trailing zero is not stored. Formatting is a separate step: format(round(mean(x), 2), nsmall = 2) or sprintf(\"%.2f\", mean(x)) both give the string \"3.90\"." },
{ q:"A chunk labelled yield draws a plot, and the prose reference to it renders as literal text rather than as a figure number. What is wrong?",
  a:"The label lacks the fig- prefix. The prefix is the mechanism, not a naming convention: only a label starting with f, i, g, and a hyphen becomes a cross-referenceable figure. Rename it fig-yield and give it a fig-cap, since a figure without a caption has nothing to number." },
{ q:"What invalidates a cached chunk, and what does that fail to notice?",
  a:"A change to the chunk's own code, and nothing else. A chunk that reads a data file keeps serving the old result after the file changes, because the code is unchanged. dependson names other chunks it depends on and cache-extra adds anything else that should invalidate it; deleting the cache folder is the blunt fix." }
],
exercises: [
{ c:"strings & regex", t:"Counting the chunks", book:"r28",
  b:"A .qmd has been read into a character vector, one line per element. Build it with doc <- c(\"---\", 'title: \"Soil tests\"', \"---\", \"\", \"## Samples\", \"\", \"```{r}\", \"#| label: load\", \"ph <- c(6.1, 6.8, 5.9)\", \"```\", \"\", \"```{r}\", \"#| label: fig-ph\", \"plot(ph)\", \"```\") and then print two things on two lines: the number of R chunk opening fences, and the chunk labels in alphabetical order.",
  o:"[1] 2\n[1] \"fig-ph\" \"load\"",
  h:["An opening fence is a line that starts with three backticks followed by the engine in braces, and a label line starts with a hash and a vertical bar.",
     "startsWith() takes a fixed string, so it suits the fence; sum() over the logical vector counts the matches. For the labels, grep() with value = TRUE keeps the matching lines and sub() removes the marker from the front of each.",
     "First line: sum() of startsWith(doc, ...) with the opening fence as the fixed string. Second line: sort() around sub() applied to grep(doc, value = TRUE), with the same pattern used for both the search and the removal. The vertical bar is special in a pattern, so it needs a backslash, and a backslash in an R string needs another backslash."]},
{ c:"strings & regex", t:"Reading the options", book:"r28",
  b:"Build doc <- c(\"```{r}\", \"#| label: fig-ph\", \"#| echo: false\", \"#| fig-width: 6\", \"plot(ph)\", \"```\"). Print every chunk option with its hash-and-bar marker removed, one per line, in alphabetical order. Use writeLines so the lines appear without quotes or index numbers.",
  o:"echo: false\nfig-width: 6\nlabel: fig-ph",
  h:["An option line is any line beginning with a hash followed by a vertical bar; the code line and the fences are not.",
     "grep() with value = TRUE gives you the matching lines, sub() strips the marker off the front, sort() puts them in order, and writeLines() prints them plainly.",
     "The pattern for the search anchors a hash and an escaped vertical bar at the start of the line. For the removal, extend the same pattern to swallow the space after the bar, then wrap the result in sort() and hand it to writeLines()."]},
{ c:"functions", t:"The fence check", book:"r28",
  b:"Write a function named balanced that takes a character vector of document lines and returns TRUE when the number of lines opening an R chunk equals the number of lines that are exactly three backticks. Build good <- c(\"## Notes\", \"```{r}\", \"x <- 1\", \"```\", \"```{r}\", \"y <- 2\", \"```\") and cut <- good[1:6], then print balanced(good) and balanced(cut) on two lines.",
  o:"[1] TRUE\n[1] FALSE",
  h:["The function needs two counts and a comparison, and it returns whatever its last expression evaluates to.",
     "Count openings with sum() over startsWith() against the three-backtick-brace-r string, and closings with sum() over a comparison against three backticks alone. identical() compares the two counts.",
     "Define balanced <- function(x) with a body that assigns the two counts and ends on identical() of them. Then build the two vectors and call the function once on each, on separate lines, so both results print."]},
{ c:"vectors", t:"What inline code would print", book:"r28",
  b:"A report's prose reads: the sample count, the mean pH rounded to two decimal places, and the highest reading. With ph <- c(6.1, 6.8, 5.9, 6.4), print four things on four lines: the readings sorted from lowest to highest, the number of readings, the mean rounded to two decimal places, and the highest reading. Then print the finished sentence, built with paste0 and printed with writeLines, in exactly this shape: 4 samples, mean pH 6.3, highest 6.8.",
  o:"[1] 5.9 6.1 6.4 6.8\n[1] 4\n[1] 6.3\n[1] 6.8\n4 samples, mean pH 6.3, highest 6.8.",
  h:["Every value in the sentence is one short expression over the same vector, which is the whole point of inline code.",
     "sort(), length(), round() over mean(), and max() give you the four values. paste0() glues text and numbers together with no separator, so the literal words go in as their own arguments.",
     "Print the four expressions on four lines first. Then build the sentence as paste0 of the count, the words, the rounded mean, more words, the maximum, and a final period — and hand the whole thing to writeLines()."]}
]
};
